#!/bin/sh
# 
# Copyright (C) 2014 Neil McGill
#
# This game is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This game is distributed in the hope that it will be fun,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this game; if not, write to the Free
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ./VERSION
. ./scripts/common.sh

cat <<%%
${RED}
      @@@@@@@@  @@@@@@  @@@@@@@  @@@@@@@    @@@@@@   @@@@@@  @@@  @@@  
      @@@@@@@@ @@@@@@@@ @@@@@@@@ @@@@@@@@  @@@@@@@@ @@@@@@@  @@@  @@@  
           @@! @@!  @@@ @@!  @@@ @@!  @@@  @@!  @@@ !@@      @@!  @@@  
          !@!  !@!  @!@ !@!  @!@ !@   @!@  !@!  @!@ !@!      !@!  @!@  
         @!!   @!@  !@! @!@!!@!  @!@!@!@   @!@!@!@! !!@@!!   @!@!@!@!  
        !!!    !&!  !!! !!&!&!   !!!&!!!!  !!!&!!!!  !!&!!!  !!!&!!!!  
       !!&     !!&  !!! !!& &!!  !!&  !!!  !!&  !!!      !&! !!&  !!!  
      &!&      &!&  !&! &!&  !&! &!&  !&!  &!&  !&!     !&!  &!&  !&!  
      &&&&&&&& &&&&&&&& &&&  &&& &&& &&&&  &&&  &&& &&&&&&&  &&&  &&&  
      &&&&&&&&  &&&&&&  &&&  &&& &&&&&&&   &&&  &&& &&&&&&   &&&  &&& 
      :    :    :    :   :   :    : : ::   ::   : : :  : :    :   : : 
      : :  : :  :    :   :   :    : : ::    :   : : :  : :    :   : : 
      . .  . :  : .  :   .   : . .: . ::   .:   : . .. : :    .   : : 
${RESET}
%%

LOG=./build.log
MAINTAINER=goblinhack@gmail.com

tech_support()
{
    #
    # Record some useful to send back home on fail if we are permitted
    #
    (
        echo
        echo system install details
        echo ===================================================
        date
        (apt --installed list | grep -i SDL) 2>/dev/null
        (apt --installed list | grep gcc) 2>/dev/null
        (apt --installed list | grep clang) 2>/dev/null

        # msys2
        pacman -Q 2>/dev/null

        echo
        echo compilers
        echo ===================================================
        clang --version  2>/dev/null
        gcc --version  2>/dev/null
        # msys2
        /mingw64/bin/gcc.exe --version 2>/dev/null

        uname -a 
    ) >> $LOG 2>&1
}

run() {
    ARGS=$1
    STDOUT=$2

    EXIT_CODE=.exit_code
    ($1 2>&1; echo $? > $EXIT_CODE) | tee $STDOUT
    MY_RET=`cat $EXIT_CODE`
    /bin/rm $EXIT_CODE

    return $MY_RET
}


help()
{
    cat << %%
Build options:

usage $0 [options]

        [--dev]  Enable development warnings
        [--dev2] Enable stack checking
%%
}

OPT_DEV1=
OPT_DEV2=

read_opts()
{
    while [ "$#" -ne 0 ];
    do
        local option=$1

        case $option in
            -*dev2)
                OPT_DEV2="yes"
                export OPT_DEV2
                OPT_DEV1="yes"
                export OPT_DEV1
                shift
                ;;
            -*dev)
                OPT_DEV1="yes"
                export OPT_DEV1
                shift
                ;;
            *)
                help
                exit 1
                ;;
        esac
    done
}

read_opts $*

run scripts/build.sh $LOG

if [ $? -ne 0 ]; then
    log_err "Build failed."
    log_err "Could you send $LOG to $MAINTAINER?"
    log_err "Or file an issue at https://github.com/goblinhack/zorbash"
    exit 1
else
    log "Built successfully"
fi
