import my
import tp


def on_death(me, x, y):
    my.spawn_at_my_position(me, "crystal_explosion")


def tp_init(name, text_long_name):
    self = tp.Tp(name, text_long_name)
    # begin sort marker

    my.chance_d1000_appearing(self, 10)
    my.collision_check(self, True)
    my.collision_hit_priority(self, 100)
    my.gfx_ascii_animated(self, True)
    my.gfx_ascii_bg_color_spread_blue(self, 40)
    my.gfx_ascii_bg_color_spread_green(self, 40)
    my.gfx_ascii_color_is_animated(self, True)
    my.gfx_ascii_fade_with_dist(self, True)
    my.gfx_ascii_shown(self, True)
    my.gfx_ascii_shown_as_gray_in_shadow(self, True)
    my.gfx_ascii_shown_in_bg(self, True)
    my.gfx_pixelart_oversized_and_on_floor(self, True)
    my.gfx_pixelart_reflection(self, True)
    my.gfx_pixelart_shadow(self, True)
    my.gfx_pixelart_shadow_short(self, True)
    my.gfx_pixelart_show_highlighted(self, True)
    my.gfx_pixelart_shown_in_bg(self, True)
    my.gfx_pixelart_submergible(self, True)
    my.health_initial_dice(self, "40+1d20")
    my.is_able_to_fall(self, True)
    my.is_always_hit(self, True)
    my.is_attackable_by_monst(self, True)
    my.is_attackable_by_player(self, True)
    my.is_biome_chasms(self, True)
    my.is_biome_dungeon(self, True)
    my.is_biome_ice(self, True)
    my.is_biome_lava(self, True)
    my.is_block_of_crystal(self, True)
    my.is_brittle(self, True)
    my.is_cursor_can_hover_over(self, True)
    my.is_cursor_path_blocker(self, True)
    my.is_described_in_leftbar(self, True)
    my.is_described_when_hovering_over(self, True)
    my.is_hittable(self, True)
    my.is_immune_to_cold(self, True)
    my.is_immune_to_fire(self, True)
    my.is_interesting(self, True)  # so it can be shoved
    my.is_loggable(self, True)
    my.is_obs_ai(self, True)
    my.is_obs_jump_end(self, True)
    my.is_obs_jumping(self, True)
    my.is_obs_shooting(self, True)
    my.is_obs_shoving(self, True)
    my.is_obs_spawn_monst(self, True)
    my.is_obs_spell_casting(self, True)
    my.is_obs_throwing(self, True)
    my.is_one_per_tile(self, True)  # so staffs do not pile these up
    my.is_reflective(self, True)
    my.is_shootable(self, True)
    my.is_tickable(self, True)  # So it can interact with fire
    my.is_very_hard(self, True)
    my.is_very_heavy(self, True)
    my.light_color(self, "white")
    my.light_dist(self, 1)
    my.noise_blocker(self, True)
    my.normal_placement_rules(self, True)
    my.on_death_do(self, "me.on_death()")
    my.temperature(self, 10)
    my.temperature_max(self, 300)
    my.temperature_sensitive(self, True)
    my.text_a_or_an(self, "a")
    my.text_description_short(self, "A block of shining crystal.")
    my.thing_size(self, my.THING_SIZE_GIANT)
    my.z_depth(self, my.MAP_DEPTH_OBJ)
    my.z_prio(self, my.MAP_Z_PRIO_EFFECT)
    # end sort marker

    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.1")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.2")
    my.tile(self, ascii_fg_char="middle_dot", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.3")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.4")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.5")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.6")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.7")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.8")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.9")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.10")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.11")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.12")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.13")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.14")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.15")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.16")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.17")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.18")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.19")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.20")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.21")
    my.tile(self, ascii_fg_char="middle_dot", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.22")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.23")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.24")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.25")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.26")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.27")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.28")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.29")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.30")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.31")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.32")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.33")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.34")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.35")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.36")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.37")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.38")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.39")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.40")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.41")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.42")
    my.tile(self, ascii_fg_char="middle_dot", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.43")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.44")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.45")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.46")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.47")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.48")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.49")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.50")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.51")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.52")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.53")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.54")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.55")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.56")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.57")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.58")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.59")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.60")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.61")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.62")
    my.tile(self, ascii_fg_char="*", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.63")
    my.tile(self, ascii_fg_char="+", ascii_bg_char="block", ascii_bg_col_name="gray70", tile="block_of_crystal.64")

    my.tp_update(self)


def init():
    tp_init(name="block_of_crystal", text_long_name="block of crystal")


init()
