#!/bin/bash
#
# Adds default flags to all the templates and sorts them so it is easier to
# see what is missing or needs added.
#
# Use "do" as the first arg if the output looks sane.
#

PRE=$(mktemp) || exit 1
PAYLOAD=$(mktemp) || exit 1
POST=$(mktemp) || exit 1
OUT=$(mktemp) || exit 1

for IN in \
    armor/*py \
    buffs/*py \
    debuffs/*py \
    doors/*py \
    dungeon/*py \
    effects/*py \
    food/*py \
    internal/*py \
    items/*py \
    mobs/*py \
    monsts/*py \
    player/*py \
    potions/*py \
    rings/*py \
    skills/*py \
    treasure/*py \
    wands/*py \
    weapons/*py
do
    echo $IN

    sed '1,/mytp = tp.Tp(/!d' $IN > $PRE
    sed '/mytp = tp.Tp(/,/mytp.set_z_prio(/!d' $IN | tail -n +2 - | sort > $PAYLOAD
    sed '/mytp.set_z_prio(/,$!d' $IN | tail -n +2 - > $POST

    for arg in \
      set_aggression_level_pct \
      set_ai_detect_secret_doors \
      set_ai_obstacle \
      set_ai_resent_count \
      set_ai_wanderer \
      set_attack_eater \
      set_attack_humanoid \
      set_attack_living \
      set_attack_lunge \
      set_attack_meat \
      set_attack_undead \
      set_collateral_damage_pct \
      set_collision_check \
      set_collision_hit_priority \
      set_damage_received_doubled_from_acid \
      set_damage_received_doubled_from_fire \
      set_damage_received_doubled_from_necrosis \
      set_damage_received_doubled_from_poison \
      set_damage_received_doubled_from_water \
      set_distance_leader_max \
      set_distance_minion_vision_shared \
      set_enchant_level \
      set_enchant_max \
      set_environ_avoids_acid \
      set_environ_avoids_fire \
      set_environ_avoids_necrosis \
      set_environ_avoids_poison \
      set_environ_avoids_water \
      set_environ_prefers_acid \
      set_environ_prefers_fire \
      set_environ_prefers_necrosis \
      set_environ_prefers_poison \
      set_environ_prefers_spiderwebs \
      set_environ_prefers_water \
      set_gfx_an_animation_only \
      set_gfx_animated \
      set_gfx_animated_can_hflip \
      set_gfx_animated_can_vflip \
      set_gfx_animated_no_dir \
      set_gfx_attack_anim \
      set_gfx_bounce_always \
      set_gfx_bounce_on_move \
      set_gfx_dead_anim \
      set_gfx_equip_carry_anim \
      set_gfx_flickers \
      set_gfx_glows \
      set_gfx_health_bar_autohide \
      set_gfx_health_bar_shown \
      set_gfx_long_shadow_caster \
      set_gfx_on_fire_anim \
      set_gfx_oversized_and_on_floor \
      set_gfx_shown_in_bg \
      set_gfx_show_outlined \
      set_gfx_solid_shadow \
      set_gfx_very_short_shadow_caster \
      set_gfx_water \
      set_hunger_clock_tick_frequency \
      set_hunger_is_insatiable \
      set_is_able_to_attack_mobs \
      set_is_able_to_break_down_doors \
      set_is_able_to_break_out_of_webs \
      set_is_able_to_change_levels \
      set_is_able_to_collect_keys \
      set_is_able_to_enchant_items \
      set_is_able_to_fall \
      set_is_able_to_fire_at \
      set_is_able_to_follow \
      set_is_able_to_jump \
      set_is_able_to_jump_attack \
      set_is_able_to_jump_escape \
      set_is_able_to_jump_onto \
      set_is_able_to_jump_without_tiring \
      set_is_able_to_learn_skills \
      set_is_able_to_open_doors \
      set_is_able_to_see_in_the_dark \
      set_is_able_to_see_through_doors \
      set_is_able_to_shove \
      set_is_able_to_tire \
      set_is_able_to_use_armor \
      set_is_able_to_use_rings \
      set_is_able_to_use_wands \
      set_is_able_to_use_weapons \
      set_is_able_to_walk_through_walls \
      set_is_acid \
      set_is_alive_on_end_of_anim \
      set_is_always_hit \
      set_is_aquatic \
      set_is_armor \
      set_is_ascend_dungeon \
      set_is_ascend_sewer \
      set_is_attackable_by_monst \
      set_is_attackable_by_player \
      set_is_auto_collect_item \
      set_is_auto_equipped \
      set_is_auto_throw \
      set_is_auto_use \
      set_is_bag \
      set_is_bag_item \
      set_is_bag_item_container \
      set_is_bag_item_not_stackable \
      set_is_barrel \
      set_is_map_beast \
      set_is_bleeder \
      set_is_red_blood \
      set_is_red_blood_eater \
      set_is_red_splatter \
      set_is_bones \
      set_is_bony \
      set_is_brazier \
      set_is_bridge \
      set_is_buff \
      set_is_burnable \
      set_is_carrier_of_treasure_class_a \
      set_is_carrier_of_treasure_class_b \
      set_is_carrier_of_treasure_class_c \
      set_is_carrier_of_weapon_class_a \
      set_is_carrier_of_weapon_class_b \
      set_is_carrier_of_weapon_class_c \
      set_is_chasm \
      set_is_collectable \
      set_is_collect_as_keys \
      set_is_collected_as_gold \
      set_is_combustible \
      set_is_corpse_on_death \
      set_is_corridor \
      set_is_critical_to_level \
      set_is_crushable \
      set_is_cursor \
      set_is_cursor_can_hover_over \
      set_is_cursor_can_hover_over_x2_click \
      set_is_cursor_path \
      set_is_cursor_path_hazard_for_player \
      set_is_dead_on_end_of_anim \
      set_is_dead_on_shove \
      set_is_debuff \
      set_is_debug_path \
      set_is_debug_type \
      set_is_deep_water \
      set_is_descend_dungeon \
      set_is_descend_sewer \
      set_is_described_when_hovering_over \
      set_is_destroyed_on_hit_or_miss \
      set_is_destroyed_on_hitting \
      set_is_dirt \
      set_is_door \
      set_is_droppable \
      set_is_dry_grass \
      set_is_enchantable \
      set_is_enchantstone \
      set_is_engulfer \
      set_is_ethereal \
      set_is_ethereal_mob \
      set_is_exit_finder \
      set_is_explorer \
      set_is_explosion \
      set_is_fearless \
      set_is_fire \
      set_is_floating \
      set_is_floor \
      set_is_floor_deco \
      set_is_flying \
      set_is_foilage \
      set_is_food \
      set_is_food_eater \
      set_is_gfx_anim_synced_with_owner \
      set_is_glass \
      set_is_gold \
      set_is_green_blooded \
      set_is_green_splatter \
      set_is_hazard \
      set_is_health_booster \
      set_is_heavy \
      set_is_hittable \
      set_is_humanoid \
      set_is_toughness_very_tough \
      set_is_intelligent \
      set_is_interesting \
      set_is_item \
      set_is_item_carrier \
      set_is_item_collector \
      set_is_item_eater \
      set_is_item_magical \
      set_is_item_magical_eater \
      set_is_item_organic \
      set_is_jelly \
      set_is_jelly_baby \
      set_is_jelly_baby_eater \
      set_is_jelly_eater \
      set_is_jelly_parent \
      set_is_key \
      set_is_laser \
      set_is_lava \
      set_is_light_blocker \
      set_is_living \
      set_is_loggable \
      set_is_meat \
      set_is_meat_eater \
      set_is_metal \
      set_is_minion \
      set_is_mob \
      set_is_monst \
      set_is_moveable \
      set_is_msg \
      set_is_necrotic_danger_level \
      set_is_no_tile \
      set_is_obs_destructable \
      set_is_obs_wall_or_door \
      set_is_openable \
      set_is_organic \
      set_is_pink_blooded \
      set_is_pink_splatter \
      set_is_player \
      set_is_poisonous_danger_level \
      set_is_potion \
      set_is_potion_eater \
      set_is_projectile \
      set_is_red_blooded \
      set_is_removeable_if_out_of_slots \
      set_is_resurrectable \
      set_is_ring \
      set_is_ripple \
      set_is_rock \
      set_is_rusty \
      set_is_secret_door \
      set_is_sewer_wall \
      set_is_shallow_water \
      set_is_shovable \
      set_is_skill \
      set_is_skillstone \
      set_is_slippery \
      set_is_smoke \
      set_is_toughness_soft \
      set_is_spawner \
      set_is_spider \
      set_is_spiderweb \
      set_is_sticky \
      set_is_stone \
      set_is_sword \
      set_is_target_auto_select \
      set_is_the_grid \
      set_is_throwable \
      set_is_tickable \
      set_is_tmp_thing \
      set_is_torch \
      set_is_treasure_chest \
      set_is_treasure_class_a \
      set_is_treasure_class_b \
      set_is_treasure_class_c \
      set_is_treasure_eater \
      set_is_map_treasure \
      set_is_treasure_type \
      set_is_undead \
      set_is_usable \
      set_is_used_when_thrown \
      set_is_very_combustible \
      set_is_wall \
      set_is_wall_dungeon \
      set_is_wand \
      set_is_weapon \
      set_is_wooden \
      set_normal_placement_rules \
      set_on_death_drop_all_items \
      set_spawn_group_radius \
      set_unused_flag1 \
      set_unused_flag2 \
      set_unused_flag3 \
      set_unused_flag4 \
      set_unused_flag5 \
      set_unused_flag6 \
      set_unused_flag7 \
      set_unused_flag8 \
      set_unused_flag9 \
      set_unused_flag10 \
      set_unused_flag11 \
      set_unused_flag12 \
      set_unused_flag13 \
      set_unused_flag14 \
      set_unused_flag15 \
      set_unused_flag16 \
      set_unused_flag17 \
      set_unused_flag18 \
      set_unused_flag19 \
      set_unused_flag20 \
      set_unused_flag21 \
      set_unused_flag22 \
      set_unused_flag23 \
      set_unused_flag24 \
      set_unused_flag25 \
      set_unused_flag26 \
      set_unused_flag27 \
      set_unused_flag28 \
      set_unused_flag29 \
      set_unused_flag30 \
      set_unused_flag31 \
      set_unused_flag32 \
      set_unused_flag33 \
      set_unused_flag34 \
      set_unused_flag35 \
      set_unused_flag36 \
      set_unused_flag37 \
      set_unused_flag38 \
      set_unused_flag39 \
      set_unused_flag40 \
      set_unused_flag41 \
      set_unused_flag42 \
      set_unused_flag43 \
      set_unused_flag44 \
      set_unused_flag45 \
      set_unused_flag46 \
      set_unused_flag47 \
      set_unused_flag48 \
      set_unused_flag49 \
      set_unused_flag50 \
      set_unused_flag51 \
      set_unused_flag52 \
      set_unused_flag53 \
      set_unused_flag54 \
      set_unused_flag55 \
      set_unused_flag56 \
      set_unused_flag57 \
      set_unused_flag58 \
      set_unused_flag59 \
      set_unused_flag60 \
      set_unused_flag61 \
      set_unused_flag62 \
      set_unused_flag63 \
      set_unused_flag64 \
      set_unused_flag65 \
      set_unused_flag66 \
      set_unused_flag67 \
      set_unused_flag68 \
      set_unused_flag69 \
      set_unused_flag70 \
      set_unused_flag71 \
      set_unused_flag72 \
      set_unused_flag73 \
      set_unused_flag74 \
      set_unused_flag75 \
      set_unused_flag76 \
      set_unused_flag77 \
      set_unused_flag78 \
      set_unused_flag79 \
      set_unused_flag80 \
      set_unused_flag81 \
      set_unused_flag82 \
      set_unused_flag83 \
      set_unused_flag84 \
      set_unused_flag85 \
      set_unused_flag86 \
      set_unused_flag87 \
      set_unused_flag88 \
      set_unused_flag89 \
      set_unused_flag90 \
      set_unused_flag91 \
      set_unused_flag92 \
      set_unused_flag93 \
      set_unused_flag94 \
      set_unused_flag95 \
      set_unused_flag96 \
      set_unused_flag97 \
      set_unused_flag98 \
      set_unused_flag99 \
      set_unused_flag100 \
      set_unused_flag101 \
      set_unused_flag102 \
      set_unused_flag103 \
      set_unused_flag104 \
      set_unused_flag105 \
      set_unused_flag106 \
      set_unused_flag107 \
      set_unused_flag108 \
      set_unused_flag109 \
      set_unused_flag110 \
      set_unused_flag111 \
      set_unused_flag112 \
      set_unused_flag113 \
      set_unused_flag114 \
      set_unused_flag115 \
      set_unused_flag116 \
      set_unused_flag117 \
      set_unused_flag118 \
      set_unused_flag119 \
      set_unused_flag120 \
      set_unused_flag121 \
      set_unused_flag122 \
      set_unused_flag123 \
      set_unused_flag124 \
      set_unused_flag125 \
      set_unused_flag126 \
      set_unused_flag127 \
      set_unused_flag128 \
      set_unused_flag129 \
      set_unused_flag130 \
      set_unused_flag131 \
      set_unused_flag132 \
      set_unused_flag133 \
      set_unused_flag134 \
      set_unused_flag135 \
      set_unused_flag136 \
      set_unused_flag137 \
      set_unused_flag138 \
      set_unused_flag139 \
      set_unused_flag140 \
      set_unused_flag141 \
      set_unused_flag142 \
      set_unused_flag143 \
      set_unused_flag144 \
      set_unused_flag145 \
      set_unused_flag146 \
      set_unused_flag147 \
      set_unused_flag148 \
      set_unused_flag149 \
      set_unused_flag150 \
      set_unused_flag151 \
      set_unused_flag152 \
      set_unused_flag153 \
      set_noise_level \
      set_is_asleep_initially \
      set_is_able_to_sleep \
      set_is_obstacle_when_dead \
      set_is_gas_blocker \
      set_is_light_blocker_for_monst \
      set_is_pink_blood_eater \
      set_is_green_blood \
      set_is_biome_swamp \
      set_is_biome_dungeon \
      set_is_treasure \
      set_is_monst_class_e \
      set_is_green_blood_eater \
      set_is_mob_challenge_class_b \
      set_is_mob_challenge_class_a \
      set_is_monst_class_d \
      set_is_monst_class_c \
      set_is_monst_class_b \
      set_is_monst_class_a \
      set_stat_att_penalty_when_in_deep_water \
      set_stat_att_penalty_when_in_shallow_water \
      set_stat_att_penalty_when_idle_max \
      set_stat_att_penalty_when_idle \
      set_stat_att_penalty_when_stuck \
      set_stat_att_penalty_when_stuck_max \
      set_stat_def_penalty_when_stuck_max \
      set_stat_def_penalty_when_idle_max \
      set_stat_def_penalty_when_in_deep_water \
      set_stat_def_penalty_when_in_shallow_water \
      set_stat_def_penalty_when_stuck \
      set_stat_def_penalty_when_idle \
      set_is_able_to_move_diagonally \
      set_is_meltable \
      set_is_amulet \
      set_is_able_to_use_amulet \
      set_is_able_to_use_helmet \
      set_is_able_to_use_boots \
      set_is_able_to_use_cloak \
      set_is_able_to_use_shield \
      set_is_able_to_use_gauntlet \
      set_is_able_to_use_helmet \
      set_is_helmet \
      set_is_boots \
      set_is_shield \
      set_is_cloak \
      set_is_gauntlet \
      set_is_toughness_hard \
      set_on_death_is_open
    do
        grep -q $arg $PAYLOAD
        # Too much noise
        #if [ $? -ne 0 ]; then
        #  echo "    mytp.$arg(False)" >> $PAYLOAD
        #fi
    done

    sort $PAYLOAD | uniq > $PAYLOAD.tmp
    mv $PAYLOAD.tmp $PAYLOAD

    cat $PRE $PAYLOAD $POST > $OUT

    diff $OUT $IN

    if [ "$1" = "do" ]; then
        mv $OUT $IN
    fi

done
