import zx
import tp


def floor_init(name, short_name, 
              tiles=[],
              left_tiles=[]):
    
    x = tp.Tp(name)
    x.set_short_name(short_name)
    x.set_is_floor(True)
    x.set_is_boring(True)
    x.set_z_depth(zx.MAP_DEPTH_FLOOR)
    for t in tiles:
        x.set_tile(t)

def init():
    floor_init(name="floor1", short_name="The floor", 
            tiles=[
                        "floor1.1",
                        "floor1.2",
                        "floor1.3",
                        "floor1.4",
                        "floor1.5",
                        "floor1.6",
                        "floor1.7",
                        "floor1.8",
                        "floor1.9",
                        "floor1.10",
                        "floor1.11",
                        "floor1.12",
                        "floor1.13",
                        "floor1.14",
                        "floor1.15",
                        "floor1.16",
                        "floor1.17",
                        "floor1.18",
                        "floor1.19",
                        "floor1.20",
                        "floor1.21",
                        "floor1.22",
                        "floor1.23",
                        "floor1.24",
                        "floor1.25",
                        "floor1.26",
                        "floor1.27",
                        "floor1.28",
                        "floor1.29",
                        "floor1.30",
                        "floor1.31",
                        "floor1.32",
                ])
    floor_init(name="floor2", short_name="The floor", 
            tiles=[
                        "floor2.1",
                        "floor2.2",
                        "floor2.3",
                        "floor2.4",
                        "floor2.5",
                        "floor2.6",
                        "floor2.7",
                        "floor2.8",
                        "floor2.9",
                        "floor2.10",
                        "floor2.11",
                        "floor2.12",
                        "floor2.13",
                        "floor2.14",
                        "floor2.15",
                        "floor2.16",
                        "floor2.17",
                        "floor2.18",
                        "floor2.19",
                        "floor2.20",
                        "floor2.21",
                        "floor2.22",
                        "floor2.23",
                        "floor2.24",
                        "floor2.25",
                        "floor2.26",
                        "floor2.27",
                        "floor2.28",
                        "floor2.29",
                        "floor2.30",
                        "floor2.31",
                        "floor2.32",
                ])
    floor_init(name="floor3", short_name="The floor", 
            tiles=[
                        "floor3.1",
                        "floor3.2",
                        "floor3.3",
                        "floor3.4",
                        "floor3.5",
                        "floor3.6",
                        "floor3.7",
                        "floor3.8",
                        "floor3.9",
                        "floor3.10",
                        "floor3.11",
                        "floor3.12",
                        "floor3.13",
                        "floor3.14",
                        "floor3.15",
                        "floor3.16",
                        "floor3.17",
                        "floor3.18",
                        "floor3.19",
                        "floor3.20",
                        "floor3.21",
                        "floor3.22",
                        "floor3.23",
                        "floor3.24",
                        "floor3.25",
                        "floor3.26",
                        "floor3.27",
                        "floor3.28",
                        "floor3.29",
                        "floor3.30",
                        "floor3.31",
                        "floor3.32",
                ])
init()
