import my
import tp


def on_idle(me, x, y):
    if not my.level_is_acid_at(me, x, y):
        my.level_spawn_at_thing(me, "acid1")


def on_death(me, x, y):
    my.level_spawn_at_thing(me, "green_splatter")


def tp_init(name, text_name, short_text_name):
    self = tp.Tp(name, text_name, short_text_name)
    my.tp_set_aggression_level_pct(self, 100)
    my.tp_set_ai_wanderer(self, True)
    my.tp_set_attack_eater(self, True)
    my.tp_set_attack_engulf_chance_d1000(self, 1000)
    my.tp_set_attack_lunge(self, True)
    my.tp_set_collision_check(self, True)
    my.tp_set_collision_hit_priority(self, 10)
    my.tp_set_collision_hit_priority(self, 6)
    my.tp_set_damage_digest_dice(self, "1d40")
    my.tp_set_damage_natural_attack_type(self, "burn")
    my.tp_set_damage_natural_dice(self, "1d20")
    my.tp_set_damage_received_doubled_from_cold(self, True)
    my.tp_set_damage_received_doubled_from_fire(self, True)
    my.tp_set_distance_vision(self, 3)
    my.tp_set_environ_avoids_fire(self, 100)
    my.tp_set_gfx_animated_can_hflip(self, True)
    my.tp_set_gfx_animated(self, True)
    my.tp_set_gfx_anim_use(self, "green_splatter")
    my.tp_set_gfx_bounce_on_move(self, True)
    my.tp_set_gfx_health_bar_shown(self, True)
    my.tp_set_gfx_oversized_and_on_floor(self, True)
    my.tp_set_gfx_short_shadow_caster(self, True)
    my.tp_set_gfx_show_outlined(self, True)
    my.tp_set_health_initial_dice(self, "8d10+40")
    my.tp_set_hunger_clock_tick_frequency(self, 50)
    my.tp_set_hunger_health_pct(self, 95)
    my.tp_set_hunger_is_insatiable(self, True)
    my.tp_set_is_able_to_fall(self, True)
    my.tp_set_is_able_to_see_in_the_dark(self, True)
    my.tp_set_is_attackable_by_monst(self, True)
    my.tp_set_is_attackable_by_player(self, True)
    my.tp_set_is_biome_dungeon(self, True)
    my.tp_set_is_biome_swamp(self, True)
    my.tp_set_is_bleeder(self, True)
    my.tp_set_is_carrier_of_treasure_class_a(self, True)
    my.tp_set_is_carrier_of_treasure_class_b(self, True)
    my.tp_set_is_carrier_of_treasure_class_c(self, True)
    my.tp_set_is_combustible(self, True)
    my.tp_set_is_crushable(self, True)
    my.tp_set_is_described_when_hovering_over(self, True)
    my.tp_set_is_engulfer(self, True)
    my.tp_set_is_green_blooded(self, True)
    my.tp_set_is_heavy(self, True)
    my.tp_set_is_hittable(self, True)
    my.tp_set_is_immune_to_acid(self, True)
    my.tp_set_is_item_collector(self, True)
    my.tp_set_is_item_eater(self, True)
    my.tp_set_is_jelly_baby_eater(self, True)
    my.tp_set_is_jelly_eater(self, True)
    my.tp_set_is_loggable(self, True)
    my.tp_set_is_meat_eater(self, True)
    my.tp_set_is_monst_class_b(self, True)
    my.tp_set_is_monst(self, True)
    my.tp_set_move_speed(self, 100)
    my.tp_set_is_moveable(self, True)
    my.tp_set_is_potion_eater(self, True)
    my.tp_set_is_red_blood_eater(self, True)
    my.tp_set_is_steal_item_chance_d1000(self, 200)
    my.tp_set_is_sticky(self, True)
    my.tp_set_is_tickable(self, True)
    my.tp_set_is_toughness_soft(self, True)
    my.tp_set_is_treasure_eater(self, True)
    my.tp_set_light_color(self, "green")
    my.tp_set_light_power(self, 2)
    my.tp_set_long_text_description(self, "Dungeon cleaners have evolved to scrub their domain of all messy organic matter. That means you. Cleaners leave a trail of corrosive slime in their wake. Avoid this. Cleaners also have a habit of eating your hard fought items.")
    my.tp_set_monst_size(self, my.MONST_SIZE_LARGE)
    my.tp_set_noise_decibels_hearing(self, 50)
    my.tp_set_normal_placement_rules(self, True)
    my.tp_set_nutrition_dice(self, "1d4")
    my.tp_set_on_death_do(self, "me.on_death()")
    my.tp_set_on_death_drop_all_items(self, True)
    my.tp_set_on_idle_tick_frequency_dice(self, "1d5:me.on_idle()")
    my.tp_set_rarity(self, my.RARITY_COMMON)
    my.tp_set_stat_con(self, 20)
    my.tp_set_stat_def(self, 6)
    my.tp_set_stat_dex(self, 3)
    my.tp_set_stat_luck(self, 10)
    my.tp_set_stat_str(self, 14)
    my.tp_set_text_a_or_an(self, "a")
    my.tp_set_text_description(self, "A dungeon auto cleaner jelly thingy.")
    my.tp_set_text_hits(self, "burns")
    my.tp_set_z_depth(self, my.MAP_DEPTH_OBJ)
    my.tp_set_z_prio(self, my.MAP_PRIO_IN_FRONT)  # so it appears over things when consuming

    delay = 200
    my.tp_set_tile(self, tile=name + ".1.100", is_hp_100_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".2.100", is_hp_100_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".1.75", is_hp_75_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".2.75", is_hp_75_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".1.50", is_hp_50_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".2.50", is_hp_50_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".1.25", is_hp_25_percent=True, delay_ms=delay)
    my.tp_set_tile(self, tile=name + ".1.25", is_hp_25_percent=True, delay_ms=delay)

    my.tp_update(self)


def init():
    tp_init(name="cleaner", text_name="dungeon cleaner", short_text_name="cleaner")


init()
