import my
import tp


def on_idle(me, x, y):
    if not my.level_is_acid_at(me, x, y):
        my.level_spawn_at_thing(me, "acid1")


def on_death(me, x, y):
    my.level_spawn_at_thing(me, "green_splatter")


def tp_init(name, text_name, short_text_name):
    mytp = tp.Tp(name, text_name, short_text_name)
    my.tp_set_aggression_level_pct(mytp, 100)
    my.tp_set_ai_wanderer(mytp, True)
    my.tp_set_attack_eater(mytp, True)
    my.tp_set_attack_engulf_chance_d1000(mytp, 1000)
    my.tp_set_attack_lunge(mytp, True)
    my.tp_set_collision_check(mytp, True)
    my.tp_set_collision_hit_priority(mytp, 10)
    my.tp_set_collision_hit_priority(mytp, 6)
    my.tp_set_damage_digest_dice(mytp, "1d40")
    my.tp_set_damage_natural_attack_type(mytp, "burn")
    my.tp_set_damage_natural_dice(mytp, "1d20")
    my.tp_set_damage_received_doubled_from_cold(mytp, True)
    my.tp_set_damage_received_doubled_from_fire(mytp, True)
    my.tp_set_distance_vision(mytp, 3)
    my.tp_set_environ_avoids_fire(mytp, 100)
    my.tp_set_gfx_animated_can_hflip(mytp, True)
    my.tp_set_gfx_animated(mytp, True)
    my.tp_set_gfx_anim_use(mytp, "green_splatter")
    my.tp_set_gfx_bounce_on_move(mytp, True)
    my.tp_set_gfx_health_bar_shown(mytp, True)
    my.tp_set_gfx_oversized_and_on_floor(mytp, True)
    my.tp_set_gfx_short_shadow_caster(mytp, True)
    my.tp_set_gfx_show_outlined(mytp, True)
    my.tp_set_health_initial_dice(mytp, "8d10+40")
    my.tp_set_hunger_clock_tick_frequency(mytp, 50)
    my.tp_set_hunger_health_pct(mytp, 95)
    my.tp_set_hunger_is_insatiable(mytp, True)
    my.tp_set_is_able_to_fall(mytp, True)
    my.tp_set_is_able_to_see_in_the_dark(mytp, True)
    my.tp_set_is_attackable_by_monst(mytp, True)
    my.tp_set_is_attackable_by_player(mytp, True)
    my.tp_set_is_biome_dungeon(mytp, True)
    my.tp_set_is_biome_swamp(mytp, True)
    my.tp_set_is_bleeder(mytp, True)
    my.tp_set_is_carrier_of_treasure_class_a(mytp, True)
    my.tp_set_is_carrier_of_treasure_class_b(mytp, True)
    my.tp_set_is_carrier_of_treasure_class_c(mytp, True)
    my.tp_set_is_combustible(mytp, True)
    my.tp_set_is_crushable(mytp, True)
    my.tp_set_is_described_when_hovering_over(mytp, True)
    my.tp_set_is_engulfer(mytp, True)
    my.tp_set_is_green_blooded(mytp, True)
    my.tp_set_is_heavy(mytp, True)
    my.tp_set_is_hittable(mytp, True)
    my.tp_set_is_immune_to_acid(mytp, True)
    my.tp_set_is_item_collector(mytp, True)
    my.tp_set_is_item_eater(mytp, True)
    my.tp_set_is_jelly_baby_eater(mytp, True)
    my.tp_set_is_jelly_eater(mytp, True)
    my.tp_set_is_loggable(mytp, True)
    my.tp_set_is_meat_eater(mytp, True)
    my.tp_set_is_monst_class_b(mytp, True)
    my.tp_set_is_monst(mytp, True)
    my.tp_set_is_moveable(mytp, True)
    my.tp_set_is_potion_eater(mytp, True)
    my.tp_set_is_red_blood_eater(mytp, True)
    my.tp_set_is_steal_item_chance_d1000(mytp, 200)
    my.tp_set_is_sticky(mytp, True)
    my.tp_set_is_tickable(mytp, True)
    my.tp_set_is_toughness_soft(mytp, True)
    my.tp_set_is_treasure_eater(mytp, True)
    my.tp_set_light_color(mytp, "green")
    my.tp_set_light_power(mytp, 2)
    my.tp_set_long_text_description(mytp, "Dungeon cleaners have evolved to scrub their domain of all messy organic matter. That means you. Cleaners leave a trail of corrosive slime in their wake. Avoid this. Cleaners also have a habit of eating your hard fought items.")
    my.tp_set_monst_size(mytp, my.MONST_SIZE_LARGE)
    my.tp_set_noise_decibels_hearing(mytp, 50)
    my.tp_set_normal_placement_rules(mytp, True)
    my.tp_set_nutrition_dice(mytp, "1d4")
    my.tp_set_on_death_do(mytp, "me.on_death()")
    my.tp_set_on_death_drop_all_items(mytp, True)
    my.tp_set_on_idle_tick_frequency_dice(mytp, "1d5:me.on_idle()")
    my.tp_set_rarity(mytp, my.RARITY_COMMON)
    my.tp_set_stat_con(mytp, 20)
    my.tp_set_stat_def(mytp, 6)
    my.tp_set_stat_dex(mytp, 3)
    my.tp_set_stat_luck(mytp, 10)
    my.tp_set_stat_str(mytp, 14)
    my.tp_set_text_a_or_an(mytp, "a")
    my.tp_set_text_description(mytp, "A dungeon auto cleaner jelly thingy.")
    my.tp_set_text_hits(mytp, "burns")
    my.tp_set_z_depth(mytp, my.MAP_DEPTH_OBJ)
    my.tp_set_z_prio(mytp, my.MAP_PRIO_IN_FRONT)  # so it appears over things when consuming

    delay = 200
    my.tp_set_tile(mytp, tile=name + ".1.100", is_hp_100_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".2.100", is_hp_100_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".1.75", is_hp_75_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".2.75", is_hp_75_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".1.50", is_hp_50_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".2.50", is_hp_50_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".1.25", is_hp_25_percent=True, delay_ms=delay)
    my.tp_set_tile(mytp, tile=name + ".1.25", is_hp_25_percent=True, delay_ms=delay)

    my.tp_update(mytp, )


def init():
    tp_init(name="cleaner", text_name="dungeon cleaner", short_text_name="cleaner")


init()
