import zx

def hello():
    zx.con(" ")
    zx.con("%fg=red$ @@@@@@@@  @@@@@@  @@@@@@@   @@@@@@@   @@@@@@   @@@@@@  @@@  @@@%fg=reset$")
    zx.con("%fg=red$ @@@@@@@@ @@@@@@@@ @@@@@@@@  @@@@@@@@ @@@@@@@@ @@@@@@@  @@@  @@@%fg=reset$")
    zx.con("%fg=red$      @@! @@!  @@@ @@!  @@@  @@!  @@@ @@!  @@@ !@@      @@!  @@@%fg=reset$")
    zx.con("%fg=red$     !@!  !@!  @!@ !@!  @!@  !@   @!@ !@!  @!@ !@!      !@!  @!@%fg=reset$")
    zx.con("%fg=red$    @!!   @!@  !@! @!@!!@!   @!@!@!@  @!@!@!@! !!@@!!   @!@!@!@!%fg=reset$")
    zx.con("%fg=red$   !!!    !@!  !!! !!@!@!    !!!@!!!! !!!@!!!!  !!@!!!  !!!@!!!!%fg=reset$")
    zx.con("%fg=red$  !!:     !!:  !!! !!: :!!   !!:  !!! !!:  !!!      !:! !!:  !!!%fg=reset$")
    zx.con("%fg=red$ :!:      :!:  !:! :!:  !:!  :!:  !:! :!:  !:!     !:!  :!:  !:!%fg=reset$")
    zx.con("%fg=red$ ::: :::: ::::: :: ::   :::   :: :::: ::   ::: :::: ::  ::   :::%fg=reset$")
    zx.con("%fg=red$ : :: : :  : :  :   :   : :   : : ::   :   : : :: :  :   :   : :%fg=reset$")
    zx.con("%fg=red$ : :  : :  :    :   :   :     : : ::   :   : : :  :  :   :   : :%fg=reset$")
    zx.con("%fg=red$ . .  . :  : .  :   .   : .   : . ::   :   : . .. :  :   .   : :%fg=reset$")
    zx.con(" ")
    zx.con("%fg=green$Version " + zx.VERSION + "%fg=reset$")
    zx.con(" ")
    zx.con("Press %fg=yellow$<tab>%fg=reset$ to complete commands.")
    zx.con("Press %fg=yellow$?%fg=reset$ to show command options.")
    zx.con("You can also enter raw python code here.")
