import zx

zx.map_load_level(level_data=[
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxx  xxxx xxx   xxx x xxxx                        xxxx",
"xxxxx   x               x                               xxxx",
"xxxx            |                                       xxxx",
"xxxx           xx           E  |                        xxxx",
"xxxx  S    |        | m    xxxxxx                       xxxx",
"xxxxxxxxxxxxx      xxxxxx  xxxxxxxxx                    xxxx",
"xxxxxxxxxxxXxwwwwwwxXxxxx  x        xxx                 xxxx",
"xxxx xxxxxxxxwwwwwxwxxxxx  x          xxx               xxxx",
"xxxx xxxxxxxxxwwwwxxxxxxx  x             xxx            xxxx",
"xxxx xxxxxxxxxwwwxxxxxxxx  x                xxx         xxxx",
"xxxx xxxxxxxxxWWWWWWWWWxx  x                            xxxx",
"xxxx xxxxxxxxxWWWWWWWWWxx  x                            xxxx",
"xxxx xxxxxxxxxWWWWWWWWWxx  x                            xxxx",
"xxxx xxxxxxxxxWxWWWWWWWxx  x                            xxxx",
"xxxx xxxxxxxxxWxWWWWWWWxx  x                            xxxx",
"xxxx   xxxxxxxxxxxxxxxxxx  x                            xxxx",
"xxxx         |        |    x                            xxxx",
"xxxx         xxxxxxxxxx xx x                            xxxx",
"xxxx                                                    xxxx",
"xxxx       |            |                               xxxx",
"xxxx   xxxxxxxxxxxxxxxxxxxxx                            xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxx                                                    xxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"])

