import zx


def map_data_init():

    zx.map_load_room(
        floor=[
                "......",
                "......",
                "......",
                "......",
                "......",
              ],
        walls=[
                "xxDxxx",
                "x    D",
                "D    x",
                "x    x",
                "xxxDxx",
              ],
        items=[
                "      ",
                "   $  ",
                "      ",
                "      ",
                "      ",
              ])
    zx.map_load_room(combo=[
                    "xxDxx",
                    "x...D",
                    "D...x",
                    "x...x",
                    "xxDxx" ])
    zx.map_load_room(combo=[
                    "xxxxDxx",
                    "x.....D",
                    "D.....x",
                    "x.....x",
                    "xxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxxxDxx",
                    "x.....D",
                    "D.....x",
                    "x.....x",
                    "x.....x",
                    "xxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxx  ",
                    "x...D  ",
                    "D...xxx",
                    "x.....x",
                    "xxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxxx",
                    "x......D",
                    "D......x",
                    "x......x",
                    "xxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxxxx",
                    "x.......D",
                    "D.......x",
                    "x.......x",
                    "xxxxxDxxx" ])
    zx.map_load_room(combo=[
                    " xDxxxxx",
                    "xx.....D",
                    "D......x",
                    "x......x",
                    "xxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxxxx",
                    "x.......D",
                    "D.......x",
                    "x.......x",
                    "x.......x",
                    "xxxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxx   ",
                    "x....D   ",
                    "D....xxxx",
                    "x.......D",
                    "x.......x",
                    "xxxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxxxxxDxxxxxx",
                    "x...........D",
                    "D...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxxxDxx    ",
                    "x.......x    ",
                    "D.......x    ",
                    "x.......xxxxx",
                    "x...........D",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxx   xxDxxx",
                    "x......x   x....x",
                    "D......xxxDx....x",
                    "x...............D",
                    "x...............x",
                    "x...............x",
                    "x...............x",
                    "xxxxxxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxx         ",
                    "x......x         ",
                    "D......xxxDxxxxxx",
                    "x...............D",
                    "x...............x",
                    "x...............x",
                    "x...............x",
                    "xxxxxxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxxxxxxxxxxxxxx",
                    "x...................x",
                    "D...................x",
                    "x...................x",
                    "x...................D",
                    "x...................x",
                    "xxxxxxxDxxxxxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxxxxx   xxxxxx",
                    "x..........x   x....x",
                    "D..........xxxxx....x",
                    "x...................x",
                    "x...................x",
                    "x...................x",
                    "x...................x",
                    "xxxxxxxDxxxxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxxxxxxxxxxxxxx",
                    "x...................x",
                    "x...................x",
                    "D...................x",
                    "x...............xxxxx",
                    "x........xxx....x    ",
                    "x........x x....xxxxx",
                    "x........x x........x",
                    "xxxxxxxDxx xxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxx   xxxxxxxxx",
                    "x.......x   x.......x",
                    "x.......x   x.......x",
                    "x.......xxxxx.......x",
                    "D...................x",
                    "x...................x",
                    "x...................D",
                    "x...................x",
                    "x...................x",
                    "x.x.x...........x.x.x",
                    "xxxxxxxDxxxxxxxxxxxxx" ])
    zx.map_load_room(combo=[
                "xxDxxxxxxx",
                "x..x.....D",
                "x..x...xxx",
                "x........x",
                "x........x",
                "D........x",
                "xxxxxDxxxx" ])
    zx.map_load_room(combo=[
                "   xxDxxxx",
                "   x.....D",
                "xxxx.....x",
                "D........x",
                "x.....xxxx",
                "x.....x   ",
                "xxxDxxx   " ])
    zx.map_load_room(combo=[
                "   xxDxxxx",
                "   x.....D",
                "xxxx.....x",
                "D..x..x..x",
                "x.....xxxx",
                "x.....x   ",
                "xxxDxxx   " ])
    zx.map_load_room(combo=[
                    "  xxDx  ",
                    " xx..xx ",
                    "xx....xx",
                    "D......D",
                    "xx.....x",
                    " xx....x",
                    "  xDxxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxx   ",
                    "x..x..xxxx",
                    "xx.......D",
                    " x.......x",
                    " x.......x",
                    "xx.......x",
                    "D.......xx",
                    "x.......x ",
                    "x.xDx...x ",
                    "xxx xxxDx " ])
    zx.map_load_room(combo=[
                    "xxDxxxx   ",
                    "x..x..xxxx",
                    "xx.......D",
                    "xx.......x",
                    "D.......xx",
                    "x.......x ",
                    "x.xDx...x ",
                    "xxx xxxDx " ])
    zx.map_load_room(combo=[
                    "xxxxDxxxxx",
                    "x........x",
                    "x........D",
                    "xxxx..xxxx",
                    "   D..D   ",
                    "   x..x   ",
                    "xxxx..xxxx",
                    "D........x",
                    "x........x",
                    "xxxxxDxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxDxxxxx",
                    "x........D",
                    "xxxx..xxxx",
                    "   D..D   ",
                    "xxxx..xxxx",
                    "D........x",
                    "xxxxxDxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxx    xxDx",
                    "D...x   x...D",
                    "x...x  xx...x",
                    "x...x xx...xx",
                    "x...xxx..xxx ",
                    "x........x   ",
                    "xxxx....xx   ",
                    "   D...xx    ",
                    "xxxx...x     ",
                    "x......x     ",
                    "x......x     ",
                    "xxxDxxxx     " ])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxDx",
                    "D...........D",
                    "x...xxxxx...x",
                    "x...x xx...xx",
                    "x...xxx..xxx ",
                    "x........x   ",
                    "x.......xx   ",
                    "xxxDxxxx     " ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...xxxxxxxxx",
                    "x...........D",
                    "xxxx...xxxxxx",
                    "   D...x     ",
                    "xxxx...x     ",
                    "x......x     ",
                    "xxxDxxxx     " ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...x        ",
                    "x...xxxxDxxxx",
                    "x...........D",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...xxxxxxxxx",
                    "x...........D",
                    "x..xxxxx....x",
                    "D...x  x....x",
                    "x...xxxxx...x",
                    "x...x.......x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "   xDxxxxxxxx",
                    "   x........x",
                    "xxxx......x.D",
                    "x..x......xxx",
                    "x..xx.....D  ",
                    "D........xxxx",
                    "x.xxx..xxxx.D",
                    "x.x...xx  x.x",
                    "x.x...xx xx.x",
                    "xDx....xxx..x",
                    "  x....x....x",
                    "  xx...x....x",
                    "   x......x.D",
                    "   xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "    xDxxxxxxxxxx",
                    "    x..........D",
                    "    x........xxx",
                    "    x.......xx  ",
                    "    x.......D   ",
                    "    x.......x   ",
                    "   xx.......xx  ",
                    "  xx....??...x  ",
                    " xx....????..D  ",
                    "xx....?????..x  ",
                    "D.....?????.xx  ",
                    "x..?...??..xx   ",
                    "x.........xx    ",
                    "xxx......xx     ",
                    "  xxxxxxDx      "])
    zx.map_load_room(combo=[
                    "    xxxxxDxxx ",
                    "    x.......D ",
                    "   xx.......xx",
                    "  xx....??...x",
                    " xx....????..D",
                    "x..?...??..xx ",
                    "x.........xx  ",
                    "xxx......xx   ",
                    "  xxxxxxDx    "])
    zx.map_load_room(combo=[
                    " xxDx     ",
                    " x..xx    ",
                    "xx...x    ",
                    "x....xx   ",
                    "D.....xx  ",
                    "x......xx ",
                    "xDxx....xx",
                    "   xx....x",
                    "    x....x",
                    "    xx...x",
                    "     xxxxx"])
    zx.map_load_room(combo=[
                    "            ",
                    "  xDxxxxxxxx",
                    "xxx........D",
                    "D..........x",
                    "x..........x",
                    "x.....xDx..x",
                    "x....xx xxDx",
                    "x....x      ",
                    "x....D      ",
                    "x....xx     ",
                    "D.....x     ",
                    "xxxxxDx     "])
    zx.map_load_room(combo=[
                    "xxxDx       ",
                    "x...xxxxx   ",
                    "x.......xx  ",
                    "x.xx.....xxx",
                    "D.x........D",
                    "xx.........x",
                    "x..........x",
                    "x.......xDxx",
                    "x.x....xx xx",
                    "x..x...x    ",
                    "x.xxx..x    ",
                    "xDx xDxx    "])
    zx.map_load_room(combo=[
                    "  xDxxxxxx ",
                    "  x.xx...x ",
                    " xx....xxx ",
                    " x.....D   ",
                    " x.....xx  ",
                    " x..x...xxx",
                    "xx..x.....x",
                    "D.........x",
                    "xx........x",
                    " xx...xxx.D",
                    "  xxxDx xxx"])
    zx.map_load_room(combo=[
                    "xxxxDx     ",
                    "x....D     ",
                    "x....x     ",
                    "xx...xx    ",
                    " D....xx   ",
                    "xx.....xxDx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xx........x",
                    " xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "xDxxDx  xxx",
                    "x.xx.xxxx.x",
                    "x.....xx..x",
                    "x.........x",
                    "D.........D",
                    "xx.......xx",
                    "xx....x..xx",
                    "x.........D",
                    "x.........x",
                    "D.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxDxxxxxxx",
                    "xx........D",
                    "D.........x",
                    "x.........x",
                    "x.........x",
                    "x........xx",
                    "xxx.......x",
                    "  xx......x",
                    "   xx.....x",
                    "    D.....x",
                    "   xx...xxx",
                    "xxxx...xx  ",
                    "D......D   ",
                    "xx.....xxxx",
                    " xxx......D",
                    "   xxxxxDxx"])
    zx.map_load_room(combo=[
                    "xxxxxDxxx",
                    "D...x...D",
                    "x...x...x",
                    "x.......x",
                    "xxx....xx",
                    "  xx..xx ",
                    "   xx.x  ",
                    "    x.x  ",
                    "    xDx  "])
    zx.map_load_room(combo=[
                    " xxDxx   xxDx",
                    " x...x  xx..x",
                    " xx.xx xx..xx",
                    " x...xxx....x",
                    " x...xx.....x",
                    " x...x......x",
                    " x..........x",
                    " D..........x",
                    "xx.....x....D",
                    "x.........xxx",
                    "x....xDx..x  ",
                    "x....x x..x  ",
                    "x.x..x x..x  ",
                    "x.xx.x x..x  ",
                    "x....x x..x  ",
                    "xxDxxx xxxx  "])
    zx.map_load_room(combo=[
                    "xxDx ",
                    "x..xx",
                    "x...D",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "D...x",
                    "x...x",
                    "xDxxx"])
    zx.map_load_room(combo=[
                    "xDxxxxxxxx",
                    "D........D",
                    "x........x",
                    "x....xx..x",
                    "x...xxxx.x",
                    "x...x  xDx",
                    "xx..x     ",
                    "x...D     ",
                    "x..xx     ",
                    "xxDx      "])
    zx.map_load_room(combo=[
                    "xxxDx   xDxxxxxx",
                    "x...xx xx......D",
                    "D....xxx......xx",
                    "xx............x ",
                    "x.............x ",
                    "x..xx.......xxx ",
                    "x..x.......xx   ",
                    "x......xDxxx    ",
                    "x.....xx        ",
                    "x.....xx        ",
                    "x......x        ",
                    "x......x        ",
                    "x.x...xx        ",
                    "x.x..xx         ",
                    "D....x          ",
                    "xxxxDx          "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "D.........x ",
                    "x.........x ",
                    "x.....x...x ",
                    "x.....xxx.x ",
                    "x......xx.x ",
                    "D.....xxx.D ",
                    "xxxxx.xxxxxx",
                    "   xx.xx...x",
                    " xxx.......x",
                    "xx.....x...x",
                    "x..........x",
                    "x..........x",
                    "x.....x...xx",
                    "x........xx ",
                    "xxxxxxxxDx  "])
    zx.map_load_room(combo=[
                    "xxxDx  ",
                    "x...D  ",
                    "x...xx ",
                    "x....xx",
                    "x.....x",
                    "x.....x",
                    "x....xx",
                    "x...xx ",
                    "xx...xx",
                    " x....x",
                    " x....x",
                    " x....x",
                    " x....x",
                    " D....x",
                    " xx...D",
                    "  xDxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxDx",
                    "x....x...x",
                    "x.......xx",
                    "x......xx ",
                    "x.....xx  ",
                    "xx...xx   ",
                    " x..xx    ",
                    " x..x     ",
                    " x.xx     ",
                    " xDx      "])
    zx.map_load_room(combo=[
                    "xDx    ",
                    "x.D    ",
                    "x.xx   ",
                    "x..xxx ",
                    "x....x ",
                    "x....x ",
                    "xDx..x ",
                    "  x..xx",
                    "  x...x",
                    "  xDxxx"])
    zx.map_load_room(combo=[
                    "xDx      ",
                    "x.D      ",
                    "x.xx     ",
                    "x..xxxxx ",
                    "x......D ",
                    "xx.....x ",
                    "xx.....x ",
                    "x...x..xx",
                    "D...x...D",
                    "xxxxxxxxx"])
    zx.map_load_room(combo=[
                    "       xDx",
                    "      xx.x",
                    "     xx..x",
                    " xxxxx...x",
                    "xx.x....xx",
                    "x...x..xx ",
                    "x......x  ",
                    "x......x  ",
                    "D......D  ",
                    "xDxxxxxx  "])
    zx.map_load_room(combo=[
                    "  xDx    ",
                    "  x.x    ",
                    " xx.xx   ",
                    "xx...xDx ",
                    "x......x ",
                    "x......xx",
                    "D.......x",
                    "xDxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxxxDx ",
                    "  x....x ",
                    "  x....xx",
                    " xx.....x",
                    "xx......x",
                    "D...xxxxx",
                    "xx.xx    ",
                    " x.x     ",
                    " xDx     "])
    zx.map_load_room(combo=[
                    " xDx ",
                    "xx.xx",
                    "x...D",
                    "x..xx",
                    "x..xx",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "    xDx",
                    "xxxxx.x",
                    "x.xx..x",
                    "x.....x",
                    "D..xx.x",
                    "xDxxxDx",
                    "       "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxx",
                    "D...x.......x",
                    "x..x...x....x",
                    "x......x....x",
                    "xx.........xx",
                    " xx.....x..x ",
                    " xx....xx..D ",
                    "xx....xxxxxx ",
                    "x.....xx     ",
                    "x......xx    ",
                    "x.......xxxxx",
                    "x..x.xx.....x",
                    "D.....x....xx",
                    "xxxx..x..x.x ",
                    "   xxxx..xxx ",
                    "      xxDx   "])
    zx.map_load_room(combo=[
                    "  xDx",
                    "  x.D",
                    "  x.x",
                    " xx.x",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "D..xx",
                    "xDxx "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxxxx",
                    "D...xx......x",
                    "x...x.......x",
                    "x...........x",
                    "xxx...xx....x",
                    "  x.........x",
                    "  x......x..x",
                    "  x.........x",
                    "  x.......x.x",
                    "  x.......x.x",
                    "  x.......x.x",
                    "  x.......x.D",
                    "  x...xxxxxDx",
                    "  D...D      ",
                    "  xxxxx      "])
    zx.map_load_room(combo=[
                    "   xxxDx",
                    "   x...D",
                    "   x..xx",
                    "   x..xx",
                    "   x...x",
                    "   xxx.x",
                    "   D.x.x",
                    " xxx...x",
                    " x.x...x",
                    " x.xx..x",
                    " x.x...x",
                    "xx.x...x",
                    "x......x",
                    "D......x",
                    "xx.xDx.x",
                    " xxx xxx"])
    zx.map_load_room(combo=[
                    "     xxxxxx ",
                    "    xx....D ",
                    "xxxDx.....x ",
                    "x.........x ",
                    "x.........x ",
                    "x.........x ",
                    "x..x......x ",
                    "x.x.......x ",
                    "xx.....x..x ",
                    "D.........x ",
                    "xxx.x.....x ",
                    "x.........x ",
                    "x.........xx",
                    "x..xx......x",
                    "D.xxxxxxxxDx",
                    "xxx         "])
    zx.map_load_room(combo=[
                    "xDxxxxx",
                    "D.....D",
                    "x....xx",
                    "x....x ",
                    "x....D ",
                    "x..xxx ",
                    "x.xx   ",
                    "x.xxxxx",
                    "x..xx.D",
                    "x.....x",
                    "x.....x",
                    "x.....x",
                    "D.....x",
                    "xx.xxxx",
                    " xDx   "])
    zx.map_load_room(combo=[
                    "xxxxxxxx xxxxxx",
                    "x......xDx....x",
                    "x...x.........x",
                    "x.........x..xx",
                    "x.......x.x..x ",
                    "x.x.......x..x ",
                    "x........xxxDx ",
                    "x...xxx..D     ",
                    "x....xx..x     ",
                    "x........x     ",
                    "x........x     ",
                    "D.xx.....x     ",
                    "xxxxx....D     ",
                    "    x.xxxx     ",
                    "    xDx        "])
    zx.map_load_room(combo=[
                    "xxxxxxxxDx ",
                    "D....x...xx",
                    "x.....x...D",
                    "x........xx",
                    "x......xxx ",
                    "x.....xx   ",
                    "x.....xx   ",
                    "xx.....x   ",
                    "x......x   ",
                    "x......xx  ",
                    "x.......xx ",
                    "xx..x....x ",
                    " x.......x ",
                    " xx......D ",
                    "  xDxxxxxx "])
    zx.map_load_room(combo=[
                    "        xDxx",
                    "      xxx..D",
                    "     xx....x",
                    "    xx.....x",
                    "    D.....xx",
                    "    x....xx ",
                    "   xx...xx  ",
                    "  xx....xx  ",
                    " xx......x  ",
                    "xx......xx  ",
                    "x......xx   ",
                    "xxxxxxDx    "])
    zx.map_load_room(combo=[
                    "   xxDx",
                    "xDxx..D",
                    "D.....x",
                    "x...x.x",
                    "x.....x",
                    "xx....x",
                    " xDxxxx"])
    zx.map_load_room(combo=[
                    "       xDx  ",
                    "   xxxxx.xxx",
                    "xxxx.......D",
                    "x..........x",
                    "x.....x...xx",
                    "x........xx ",
                    "x........x  ",
                    "x...x....x  ",
                    "D...x...xx  ",
                    "xx.....xx   ",
                    "D......x    ",
                    "xxxxxxDx    "])
    zx.map_load_room(combo=[
                    "  xxDxxxxxx ",
                    "xxx..x....D ",
                    "x....x....x ",
                    "x...xxx...xx",
                    "x...x xx...D",
                    "x...xxxx...x",
                    "x.....xx...x",
                    "x.....xxx..x",
                    "x......x...x",
                    "x..........x",
                    "D.......x..x",
                    "xxxxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "        xDx",
                    "  xxxxxxx.D",
                    " xx.......x",
                    " x........x",
                    "xx........x",
                    "D...x....xx",
                    "xx.xx...xxx",
                    " xxx.....xx",
                    " xx.......x",
                    " D.....x..x",
                    " xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "    xxxxxDx",
                    "   xx.....D",
                    "  xx......x",
                    "  x.......x",
                    " xx..xx...x",
                    "xx........x",
                    "D.......x.x",
                    "x.........x",
                    "x.........x",
                    "x.........D",
                    "xDxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xDx      ",
                    "xx.xxx    ",
                    "D....xx   ",
                    "x.....xxxx",
                    "x........D",
                    "x........x",
                    "x...xx...x",
                    "xx..xx...x",
                    "x...x....x",
                    "D..xx....x",
                    "xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    " xxxDx",
                    " x...D",
                    " x...x",
                    " x...x",
                    " xx..x",
                    " xx..x",
                    "xx...x",
                    "D....x",
                    "xDxxxx"])
    zx.map_load_room(combo=[
                    "xDxx ",
                    "x..xx",
                    "x...D",
                    "D...x",
                    "xxxDx"])
    zx.map_load_room(combo=[
                    "xxxxxxxDxxx",
                    "D.....x...x",
                    "x.........x",
                    "x.........x",
                    "xxx.......x",
                    "  xx...x..x",
                    "   xx.....x",
                    "    xx..x.x",
                    "     x....x",
                    "     xx...x",
                    "      xx..x",
                    "       x..D",
                    "       xDxx"])
    zx.map_load_room(combo=[
                    "       xDxxxx",
                    "       D....D",
                    "xDx    x....x",
                    "x.x   xx....x",
                    "x.xx xx.....x",
                    "x..xxx......x",
                    "x........x..x",
                    "xxx.........x",
                    "x....xx.....x",
                    "x...........x",
                    "x....x.....xx",
                    "x.........xx ",
                    "x.........x  ",
                    "D.....xxxDx  ",
                    "xx...xx      ",
                    " xxxDx       "])
    zx.map_load_room(combo=[
                    "xDxxxxx         ",
                    "D.....D         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....D         ",
                    "x.....xx     xDx",
                    "x......xxxx xx.D",
                    "x.........xxx..x",
                    "x.......x......x",
                    "x.............xx",
                    "x...xDx.....xxx ",
                    "x..xx x.....x   ",
                    "D..x  x.....x   ",
                    "xxDx  xxxxxDx   "])
    zx.map_load_room(combo=[
                    " xDxxxxxxxDx ",
                    " x.........xx",
                    "xxx.....x...D",
                    "D.xxx...x...x",
                    "x.xxxxx..x.xx",
                    "x..xx x....x ",
                    "x...xxxx..xx ",
                    "xx...xxx..D  ",
                    "xx...xx...xx ",
                    "x....x.....D ",
                    "x........x.x ",
                    "x........x.x ",
                    "x....xx..x.x ",
                    "x....x...x.x ",
                    "D.x........x ",
                    "xxxxxxxxxxDx "])
    zx.map_load_room(combo=[
                    " xDxxxxxxxxxxxx",
                    " D...x........x",
                    " x............x",
                    " x............x",
                    " xxxxx....x...x",
                    "     xx..xx...x",
                    "      xxxxx...x",
                    "         D...xx",
                    "        xx..xx ",
                    "        x...xx ",
                    "        x....x ",
                    " xxxx  xx....x ",
                    "xx..xxxx.....xx",
                    "D.........x...D",
                    "x............xx",
                    "xxxxxxxxxxxxDx "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxx ",
                    "x.........xx",
                    "x..........x",
                    "x..........x",
                    "x........xxx",
                    "xxx..xx...D ",
                    "  xx....x.xx",
                    "   x....x..x",
                    "   D....xx.x",
                    "   x....xx.x",
                    "   x....xx.x",
                    "  xx....xx.x",
                    "xxx........x",
                    "x..........x",
                    "x..........D",
                    "xDxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxDx",
                    "x..........D",
                    "x..x.......x",
                    "x..........x",
                    "x...xx.....x",
                    "x...xx.....x",
                    "x..........x",
                    "xx.........x",
                    " xxxx...x..x",
                    "    D..xx..x",
                    "    x......x",
                    "    x......x",
                    "    x......x",
                    "    x......D",
                    "    D....xxx",
                    "    xDxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxDx",
                    "D....D",
                    "x...xx",
                    "x...x ",
                    "x.xxx ",
                    "xDx   "])
    zx.map_load_room(combo=[
                    "   xxxxxDx ",
                    "  xx.....x ",
                    " xx......x ",
                    "xx.......x ",
                    "x........x ",
                    "x........D ",
                    "x........xx",
                    "x....x....x",
                    "x...xxx...x",
                    "x...x x...x",
                    "D...x xxxDx",
                    "xxxDx      "])
    zx.map_load_room(combo=[
                    "xDxxxx",
                    "D.xx.x",
                    "x....x",
                    "x....x",
                    "x.xx.D",
                    "xDxxDx"])
    zx.map_load_room(combo=[
                    "xDx   ",
                    "D.xx  ",
                    "x..xxx",
                    "x....D",
                    "x....x",
                    "xx..xx",
                    "D...D ",
                    "xxxDx "])
    zx.map_load_room(combo=[
                    "xDxxxxxxx  ",
                    "D.......xxx",
                    "x.........D",
                    "x.........x",
                    "x....xx...x",
                    "xxx..xx...x",
                    "  D.......x",
                    "  x.......x",
                    " xx.......x",
                    " x........x",
                    " x........x",
                    " x.....x..x",
                    " x........x",
                    " x........x",
                    " xx..xxx..D",
                    "  xDxx xxxx"])
    zx.map_load_room(combo=[
                    "            xDx",
                    "      xxxxxxx.x",
                    "xxx xxx...xx..x",
                    "D.xDx.........x",
                    "x.............x",
                    "x........??...x",
                    "x.......????..x",
                    "x..xx...x????.x",
                    "x...x....????.x",
                    "x...x..x..x?..x",
                    "xxxDx..xx.....x",
                    "    x..xxx....x",
                    "    x..x x....x",
                    "    xDxx xDxx.D",
                    "            xxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxDxxx",
                    "D............x",
                    "x..x.........x",
                    "x..xxx.......x",
                    "x..x x.......x",
                    "D.xx x......xx",
                    "xxx  x......x ",
                    "     x......x ",
                    "    xx......x ",
                    "  xxx.......D ",
                    "  x........xx ",
                    "  x........xx ",
                    "  D.........D ",
                    "  xx...xxxxxx ",
                    "   xDxxx      "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxxxx",
                    "x.....x.....x",
                    "x...........x",
                    "x...........x",
                    "x...xx......x",
                    "x..xxxx.....x",
                    "x.xx  xx....x",
                    "x.x    xxx.xx",
                    "x.x      xDx ",
                    "x.x          ",
                    "x.x          ",
                    "x.x          ",
                    "xDx          "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxx xDx",
                    "x........x x.x",
                    "x........x x.x",
                    "x.....x..xxx.x",
                    "xxx.......x..x",
                    "  xx...x....xx",
                    "  xx...x....x ",
                    "xxx....x....x ",
                    "x......x....x ",
                    "x......x....x ",
                    "x......x...xx ",
                    "x......x..xx  ",
                    "x...xxxx..x   ",
                    "xDxxx  x..x   ",
                    "       xDxx   "])
    zx.map_load_room(combo=[
                    " xxxx",
                    " x..D",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "x...x",
                    "x...x",
                    "D.xxx",
                    "xxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxDx",
                    "x..........x..x",
                    "x.............x",
                    "x.............x",
                    "x..x...x......x",
                    "xxx...x...x...x",
                    "x....x..xxxx..x",
                    "x......xx x...x",
                    "xx....xx  x...x",
                    " xx...x   x...x",
                    " xx...x   x.xxx",
                    "xx....x   xDx  ",
                    "x...xxx        ",
                    "D..xx          ",
                    "xxxx           "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxDx ",
                    "x.........x ",
                    "x.........x ",
                    "x.........x ",
                    "x.........xx",
                    "x.....x....x",
                    "xx...xxx...x",
                    "x.....x....x",
                    "x.........xx",
                    "D.........x ",
                    "xxxx.....xx ",
                    " xx.....xx  ",
                    "xx.....xx   ",
                    "D......x    ",
                    "xxx..xxx    ",
                    "  xDxx      "])
    zx.map_load_room(combo=[
                    "xxxxxDx",
                    "x.....D",
                    "x....xx",
                    "x.....x",
                    "D.....x",
                    "xx....x",
                    " x.xx.x",
                    " xDxxxx"])
    zx.map_load_room(combo=[
                    "  xDx  ",
                    " xx.xxx",
                    "xx....D",
                    "x.....x",
                    "x.xx..x",
                    "x.xx..x",
                    "x...xxx",
                    "x...D  ",
                    "xx..x  ",
                    " xxDx  "])
    zx.map_load_room(combo=[
                    "   xDx",
                    "  xx.D",
                    " xx..x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "D...xx",
                    "xxxDx "])
    zx.map_load_room(combo=[
                    "xDx   ",
                    "D.xx  ",
                    "x..xx ",
                    "x...x ",
                    "x...xx",
                    "xxx..x",
                    "  xDxx"])
    zx.map_load_room(combo=[
                    " xDxxx  ",
                    " D...xxx",
                    " x.....x",
                    " x.....x",
                    "xx..x..x",
                    "x......D",
                    "x...xxxx",
                    "xDxxx   "])
    zx.map_load_room(combo=[
                    "   xxx",
                    "  xx.D",
                    "xxx..x",
                    "x....x",
                    "D....x",
                    "xxxxDx"])
    zx.map_load_room(combo=[
                    "xDx         ",
                    "x.xxxxx     ",
                    "x.....xxxxDx",
                    "xx.....xx..D",
                    " xx........x",
                    " xxxxx.....x",
                    "xx..xxxxxx.x",
                    "x....x   xxx",
                    "x.x..xx  xxx",
                    "x.....xxxx.D",
                    "D..........x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxDx        ",
                    "x..xx     xx",
                    "x...xxxxxxxx",
                    "x..........D",
                    "x..........x",
                    "xDx........x",
                    "   x.....x.x",
                    "    xx.....x",
                    "      x....x",
                    "       xx..D",
                    "         xxx",
                    "          xx"])
    zx.map_load_room(combo=[
                    "     xDxx",
                    "     x..x",
                    "    xx..x",
                    "   xx...x",
                    "  xx...xx",
                    "  x....x ",
                    " xx...xx ",
                    " x...xx  ",
                    "xx..xx   ",
                    "x...D    ",
                    "xxxDx    "])
    zx.map_load_room(combo=[
                    " xDxxxx",
                    " x....x",
                    " xx...x",
                    "  x..xx",
                    " xx..x ",
                    "xx...x ",
                    "x...xx ",
                    "D..xx  ",
                    "xxxx   "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxx",
                    "D.........x",
                    "xx........x",
                    " xx......xx",
                    "  x.....xx ",
                    "  xx....x  ",
                    "  xx....xx ",
                    " xx......xx",
                    " x........x",
                    " x........D",
                    " xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "  xDx   ",
                    "xxx.xxx ",
                    "x.....xx",
                    "x......x",
                    "x...x..x",
                    "x......x",
                    "x......D",
                    "xxxxxxDx"])
    zx.map_load_room(combo=[
                    "   xxDx",
                    "  xx..D",
                    "  x...x",
                    " xx...x",
                    "xx....x",
                    "x.....D",
                    "xxxxxDx"])
    zx.map_load_room(combo=[
                    "xxxxxDx",
                    "x.xx..D",
                    "x.....x",
                    "x.....x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxxxDx   ",
                    " x......D   ",
                    "xx...x..xx  ",
                    "x...xxx..x  ",
                    "x........x  ",
                    "xx.......xx ",
                    " xx.......xx",
                    "  xx.......x",
                    "   xx......x",
                    "    xx...x.x",
                    "     x.....x",
                    "     x.....x",
                    "     x....xx",
                    "    xx.....x",
                    "    D......D",
                    "    xDxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxDx",
                    "x......D",
                    "D......x",
                    "xxxx...x",
                    "   xxxDx"])
    zx.map_load_room(combo=[
                    "  xxxxxDx   ",
                    " xx.....x   ",
                    "xx......xx  ",
                    "x........xxx",
                    "x..........D",
                    "x.......x..x",
                    "xx.........x",
                    "xx....xx...x",
                    "x....xxxxx.x",
                    "D...xx   xxx",
                    "xxxDx     xx",
                    "          xx"])
    zx.map_load_room(combo=[
                    "xDx          ",
                    "D.xxxxxxx    ",
                    "x...xx..xx   ",
                    "x........xx  ",
                    "x.........xx ",
                    "x.......x..xx",
                    "x.xx....xx..x",
                    "x..x....xxx.x",
                    "x...x..xxxx.x",
                    "x........xx.x",
                    "x........xx.x",
                    "x........xx.x",
                    "x....xxx....x",
                    "x...xx x....x",
                    "D...x  x....x",
                    "xxxxx  xDxxxx"])
    zx.map_load_room(combo=[
                    "xDxxxxx         ",
                    "D.....D         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....xx        ",
                    "xxx....xxxx xxDx",
                    "  x.......xxx..x",
                    "  x...x........x",
                    "  x..xx...x....x",
                    "  x...x...xxx..x",
                    "  x.x.x...xx...D",
                    "  x.x.x......xxx",
                    "  x..........x  ",
                    "  D.......x..D  ",
                    "  xxxxxxxxxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxDx ",
                    "x....x....xx",
                    "x..........D",
                    "x..........x",
                    "x..........x",
                    "x..........x",
                    "x....xx....x",
                    "x...xxx....x",
                    "x....xx....x",
                    "x...xxx....x",
                    "x...x xx..xx",
                    "x...xx xxDx ",
                    "x....xx     ",
                    "x.....xx    ",
                    "D......D    ",
                    "xxxxxxDx    "])
    zx.map_load_room(combo=[
                    "xDxxxxxx",
                    "D...xx.x",
                    "x..xxx.x",
                    "x...xx.x",
                    "x......x",
                    "x......x",
                    "x......x",
                    "x......D",
                    "x....xxx",
                    "x...xx  ",
                    "x..xx   ",
                    "x..x    ",
                    "x..x    ",
                    "x..x    ",
                    "D..x    ",
                    "xDxx    "])
    zx.map_load_room(combo=[
                    "   xxxDx  ",
                    "  xx...D  ",
                    " xx....x  ",
                    " x....xx  ",
                    " x....xxxx",
                    " x.....xxx",
                    "xx.......x",
                    "x...x....x",
                    "D........x",
                    "xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    " xxDx ",
                    "xx..x ",
                    "x...xx",
                    "x....D",
                    "D....x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "   xxx",
                    " xxx.D",
                    "xx...x",
                    "D....x",
                    "xx...x",
                    " xDxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxDx",
                    "D.......D",
                    "xx......x",
                    " xx..x..x",
                    "  x.....x",
                    "  x.....x",
                    "  xx....x",
                    "   xx..xx",
                    "    xxDx "])
    zx.map_load_room(combo=[
                    " xDx    ",
                    "xx.D    ",
                    "x..x    ",
                    "x..xx   ",
                    "x...x   ",
                    "x...xx  ",
                    "x.x..x  ",
                    "x....x  ",
                    "x....x  ",
                    "x....xx ",
                    "D.....xx",
                    "xx.....x",
                    " xx....x",
                    "  xx...x",
                    "   xxx.D",
                    "     xDx"])
    zx.map_load_room(combo=[
                    "  xDxxxxxx",
                    "  x..x...D",
                    " xx......x",
                    "xx...x.x.x",
                    "D........x",
                    "x........x",
                    "x....x...x",
                    "x......x.x",
                    "xxxxxx...x",
                    "     D...x",
                    "    xx...x",
                    "   xx..x.x",
                    " xxx.....x",
                    " x.......x",
                    " xDxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxDx ",
                    "D......xx",
                    "x.......D",
                    "x...xxxxx",
                    "x..xx    ",
                    "x..xx    ",
                    "x...xx   ",
                    "xx...xx  ",
                    "xxx...D  ",
                    "x....xx  ",
                    "x...xx   ",
                    "x...x    ",
                    "D.xDx    ",
                    "xDx      "])
    zx.map_load_room(combo=[
                    "   xDxxxxx",
                    "   x.....D",
                    "   x.....x",
                    "  xx.....x",
                    "xxx.....xx",
                    "x........x",
                    "x........x",
                    "x...xxxx.D",
                    "D..xx  xDx",
                    "xxxx      "])
    zx.map_load_room(combo=[
                    "xDxxxxxxx ",
                    "D.......xx",
                    "xxxxx....D",
                    "    xx...x",
                    "     xx..x",
                    "      D..x",
                    "      x..x",
                    "     xx..x",
                    "    xx...x",
                    "   xx....x",
                    " xxx.....x",
                    " D......xx",
                    " xxx...xx ",
                    "   xxxDx  "])
    zx.map_load_room(combo=[
                    "xxxDx ",
                    "x...xx",
                    "x....D",
                    "x....x",
                    "x....x",
                    "x..xxx",
                    "x.xx  ",
                    "D.x   ",
                    "xDx   "])
    zx.map_load_room(combo=[
                    "  xDxxxDx",
                    "  D.....D",
                    " xx....xx",
                    "xx......x",
                    "x....x..x",
                    "x...xx..x",
                    "xDxxxx..x",
                    "    D...x",
                    "    x...x",
                    "    x...x",
                    "    xx..x",
                    "    xx..x",
                    "   xx...x",
                    "   x....x",
                    "   D...xx",
                    "   xDxxx "])
    zx.map_load_room(combo=[
                    "xxxDx   ",
                    "D...D   ",
                    "x..xx   ",
                    "x..xx   ",
                    "x...xDx ",
                    "x.....D ",
                    "x.x...x ",
                    "x.....x ",
                    "x....xx ",
                    "x....xx ",
                    "x.....xx",
                    "x......x",
                    "x.....xx",
                    "D.....D ",
                    "xxxxxDx "])
    zx.map_load_room(combo=[
                    "xDxxxxxxDx",
                    "D........D",
                    "xx......xx",
                    " xx.....x ",
                    " xx.....x ",
                    " x......x ",
                    " x....xxx ",
                    " x...xx   ",
                    " x...x    ",
                    " x...D    ",
                    " x...x    ",
                    " xx..xx   ",
                    "  x...D   ",
                    "  x..xx   ",
                    "  D..x    ",
                    "  xDxx    "])
    zx.map_load_room(combo=[
                    " xDxxx     ",
                    " D...xx    ",
                    " xx...D    ",
                    " xx...x    ",
                    "xx....xx   ",
                    "D......xxx ",
                    "x........xx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x...xx....D",
                    "x....x...xx",
                    "D.....xx.D ",
                    "xDxxxxxxDx "])
    zx.map_load_room(combo=[
                    "         xDx",
                    "        xx.D",
                    "       xx..x",
                    "      xx...x",
                    "     xx....x",
                    "    xx.....x",
                    "    x......x",
                    "   xx......x",
                    "   x...xx..D",
                    "   D..xxxxxx",
                    "  xx..xx    ",
                    "xxx....xxxxx",
                    "D..........x",
                    "xxxxx...xxDx",
                    "    xxxDx   "])
    zx.map_load_room(combo=[
                    "xDxx  ",
                    "D..xx ",
                    "x...xx",
                    "x....D",
                    "x.xDxx",
                    "xDx   "])
    zx.map_load_room(combo=[
                    "    xDx",
                    "   xx.D",
                    "   x..x",
                    "   x..x",
                    "  xx..x",
                    "  x...x",
                    "  D...x",
                    " xx...D",
                    "xx...xx",
                    "x....D ",
                    "D.xxDx ",
                    "xDx    "])
    zx.map_load_room(combo=[
                    "   xDxx   ",
                    "  xx..xxx ",
                    " xx.....xx",
                    " x.......D",
                    "xx..x...xx",
                    "D...x...D ",
                    "xx......x ",
                    " xx.....x ",
                    "  xx...xx ",
                    "   xxxDx  "])
    zx.map_load_room(combo=[
                    "xDxxxx ",
                    "D....D ",
                    "x....xx",
                    "xx....D",
                    " xx...x",
                    "  xx..x",
                    "   xxDx"])
    zx.map_load_room(combo=[
                    " xxx   ",
                    " D.xxx ",
                    "xx...xx",
                    "D.....D",
                    "xx....x",
                    " x..xxx",
                    " xxDxxx"])
    zx.map_load_room(combo=[
                    "xxxxDx",
                    "D....x",
                    "x....D",
                    "x...xx",
                    "D.xxx ",
                    "xDx   "])
    zx.map_load_room(combo=[
                    "      xDxxx",
                    "    xxx...D",
                    "    D.....x",
                    "    x....xx",
                    "    xxx...x",
                    "   xx.....x",
                    "  xx......x",
                    "xxx.......x",
                    "x.........x",
                    "x.........x",
                    "D.........x",
                    "xDxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xDxx      xx",
                    "D..xx xxxxxx",
                    "x...xxx.xx.x",
                    "x..........x",
                    "D.x........x",
                    "xxx........x",
                    "xx.........x",
                    "x..........x",
                    "x......x...x",
                    "x......xx..D",
                    "D.xx....xxxx",
                    "xDxxxxxDx xx"])
    zx.map_load_room(combo=[
                    "   xDx  xDx ",
                    "xxxx.xxxx.D ",
                    "x.........xx",
                    "x....x.....D",
                    "x....x....xx",
                    "x......xxxx ",
                    "xx...xxx    ",
                    "x.....D     ",
                    "x....xxxxxxx",
                    "x.....x....D",
                    "x..........x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxDx",
                    "x....xx...D",
                    "x.........x",
                    "x.........x",
                    "xx.....xxxx",
                    "xx........D",
                    "x......xxxx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxDx xDx",
                    "D.....x x.D",
                    "x.....xxx.x",
                    "x......xx.x",
                    "xxxx....x.x",
                    "   xx...x.x",
                    "    D.....x",
                    "   xx.....x",
                    "  xx......x",
                    "  D..x....x",
                    "  xDxxxxxDx"])
    zx.map_load_room(combo=[
                    "xxxDx ",
                    "x...x ",
                    "x...xx",
                    "x....D",
                    "x...xx",
                    "x..xx ",
                    "x..x  ",
                    "x..x  ",
                    "x.xx  ",
                    "D.D   ",
                    "xDx   "])
    zx.map_load_room(combo=[
                    "xDxxxx   ",
                    "D....xxxx",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "xx...x..x",
                    " x......x",
                    " xx.....D",
                    "  xxxxxDx"])
    zx.map_load_room(combo=[
                    "xxDx",
                    "x..D",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x.xx",
                    "xxx "])
    zx.map_load_room(combo=[
                    "   xDx ",
                    " xxx.x ",
                    " D...xx",
                    "xx....x",
                    "D.....x",
                    "x.....x",
                    "xDxxxxx"])
    zx.map_load_room(combo=[
                    "  xDx ",
                    " xx.x ",
                    "xx..xx",
                    "x....x",
                    "x....D",
                    "D...xx",
                    "xxxDx "])
    zx.map_load_room(combo=[
                    "   xxxDx xDxxx",
                    "   x...xxx...D",
                    "   xx..xx....x",
                    "    D...xx...x",
                    "   xx..xxxx..x",
                    "  xx...x  x..x",
                    "  x....x  x..x",
                    "  x....xx x..x",
                    "  x.....xxx..x",
                    " xx......x...x",
                    " x..xx.....x.x",
                    "xx.........x.x",
                    "x..........xDx",
                    "x..........x  ",
                    "x........xxx  ",
                    "xxxxxxxxxx    "])
    zx.map_load_room(combo=[
                    "  xxxxxxxxxxxxxx",
                    " xx.......xx...x",
                    "xx....xDx.x...xx",
                    "D....xx x......x",
                    "x...xx  x......x",
                    "xx..x   x.xx...x",
                    "x...x   xxxxxxxx",
                    "x...x           ",
                    "x...x           ",
                    "xx..x           ",
                    "x..xx           ",
                    "x..D            ",
                    "x..xx           ",
                    "x...x           ",
                    "x..xx           ",
                    "xxDx            "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxxx",
                    "x..............x",
                    "x..............x",
                    "x.xDx..........x",
                    "xxx xxx........x",
                    "      xx.......x",
                    "       x...xxxxx",
                    "       x....xx  ",
                    "       x.....xx ",
                    "       x......xx",
                    "       xxx.....x",
                    "         xx....x",
                    "          D....x",
                    "         xx....x",
                    "         x....xx",
                    "         xDxxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx    ",
                    "D........x    ",
                    "x........x    ",
                    "xxx...x..x    ",
                    "  x......x    ",
                    "  x......x    ",
                    "  x......xxx  ",
                    "  x.....x..x  ",
                    "  xxx......x  ",
                    "xxx x......x  ",
                    "D.x x......xxx",
                    "x.xxx.....xx.x",
                    "x..xxxxx.....x",
                    "x.....xx.....x",
                    "x............D",
                    "xxxxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxxxxxxxx   ",
                    " D......x..x   ",
                    " xxx.......x   ",
                    "   xxxxx...x   ",
                    "xxxxxx xxx.x   ",
                    "x....xx xx.xxDx",
                    "x.....xxx..xx.x",
                    "x.xx.......xx.x",
                    "x..........xx.x",
                    "x..........xx.x",
                    "x..xx......xx.x",
                    "x.xxxx.....xx.x",
                    "x.x  x.x...xx.x",
                    "x.x xx.....xx.x",
                    "D.x x...x.....x",
                    "xDx xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "x....x",
                    "x....x",
                    "x.x..x",
                    "x....x",
                    "x..x.x",
                    "x..x.x",
                    "x..xDx",
                    "x..x  ",
                    "x..x  ",
                    "xx.D  ",
                    " xDx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx      ",
                    "x....xx..D      ",
                    "x........x      ",
                    "x.....xxxx      ",
                    "x....xx         ",
                    "x...xx          ",
                    "x...D           ",
                    "x...xx          ",
                    "x....xx         ",
                    "x.....xx        ",
                    "x......xxxxx    ",
                    "x.x........xxx  ",
                    "x.xx.........xx ",
                    "x.............xx",
                    "x.......xxx....x",
                    "xxxxxxxxx xxxxDx"])
    zx.map_load_room(combo=[
                    "   xDxxx  ",
                    "xxxx...xx ",
                    "x.......xx",
                    "x........D",
                    "D......x.x",
                    "xx.....x.x",
                    " xx......x",
                    "  x......x",
                    "  D.xxxxDx",
                    "  xDx     "])
    zx.map_load_room(combo=[
                    "xDx   ",
                    "D.xx  ",
                    "x..x  ",
                    "x..xx ",
                    "x...xx",
                    "xDx..x",
                    "  xx.D",
                    "   xxx"])
    zx.map_load_room(combo=[
                    " xxxDx",
                    " x...D",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x.x..x",
                    "x....x",
                    "x....x",
                    "xxx..x",
                    "  x..x",
                    "  x..x",
                    "  D..D",
                    "  xxDx"])
    zx.map_load_room(combo=[
                    "   xDxx",
                    " xxx..x",
                    "xx....x",
                    "x...x.x",
                    "x...x.D",
                    "D.xxx.x",
                    "xDx xxx"])
    zx.map_load_room(combo=[
                    " xDx       ",
                    "xx.xx xxxxx",
                    "D...xDx...x",
                    "x.........x",
                    "xx........x",
                    " x........x",
                    " x........x",
                    " x...x....x",
                    " x........x",
                    " x........x",
                    " xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xDx      ",
                    "xxx.D      ",
                    "D...xxxxxx ",
                    "xx...xx..xx",
                    " x........x",
                    " xxx......x",
                    "   xx.....x",
                    "    xx....x",
                    "     x....x",
                    "     xxxx.x",
                    "        xxx"])
    zx.map_load_room(combo=[
                    "xDx    ",
                    "D.D    ",
                    "x.xx   ",
                    "x..xxx ",
                    "x....xx",
                    "x.x...x",
                    "x.....x",
                    "x....xx",
                    "x..xxx ",
                    "xxxx   "])
    zx.map_load_room(combo=[
                    "xxDxxxxxxDx",
                    "D..xx...x.D",
                    "x..x......x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x......xxxx",
                    "x.....xx   ",
                    "x.....D    ",
                    "x.....xx   ",
                    "x......xx  ",
                    "x.......x  ",
                    "x.......x  ",
                    "xxxxxxx.D  ",
                    "      xDx  "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxx ",
                    "D....x....x ",
                    "xx...x....x ",
                    " x.xxxx...x ",
                    " x....xx..x ",
                    " xx.......x ",
                    " xx.......x ",
                    " x....x...x ",
                    " x........x ",
                    " x........x ",
                    " x..x.....x ",
                    "xx........xx",
                    "x..........x",
                    "x.........xx",
                    "xxxxxxxx.xx ",
                    "       xxx  "])
    zx.map_load_room(combo=[
                    "xxxDx",
                    "D...D",
                    "xx.xx",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x..xx",
                    "x.xx ",
                    "x..xx",
                    "x...x",
                    "x...x",
                    "xx..D",
                    " xxDx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x........D",
                    "x........x",
                    "x......xxx",
                    "x.....xx  ",
                    "D.....xx  ",
                    "xxx....x  ",
                    "  xx...D  ",
                    "   x.xxx  ",
                    "   xDx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx xxx",
                    "x...xx...xDx.D",
                    "x............x",
                    "x............x",
                    "x..xx...xx...x",
                    "x..xx......xxx",
                    "x..xx.....xxxx",
                    "x..xx...x.x xx",
                    "x..xx.....x xx",
                    "x..xx....xx xx",
                    "D.xxx....x    ",
                    "xxx x....x    ",
                    "    xx...D    ",
                    "     xxxDx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxx",
                    "x...xx........x",
                    "x....xx.......x",
                    "x........xx...x",
                    "x.......xxxx..x",
                    "xxx....xx  xx.D",
                    "xx....xx    xDx",
                    "x.....x        ",
                    "x.....xx       ",
                    "x......xx      ",
                    "x...x...xx     ",
                    "x........x     ",
                    "x........D     ",
                    "x.......xx     ",
                    "xxxxxxxDx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxx    ",
                    "x....x.....D    ",
                    "x....x.....xx   ",
                    "x.......x...D   ",
                    "x.....x.x...x   ",
                    "x.....x.x.xxx   ",
                    "x.......x..x    ",
                    "x....x..xx.x    ",
                    "x........x.x    ",
                    "x...xx.....x    ",
                    "D..........x    ",
                    "xxx....xx..x    ",
                    "  x...xxxxDx    ",
                    "  D...x         ",
                    "  xx..D         ",
                    "   xxDx         "])
    zx.map_load_room(combo=[
                    "xxxxDx",
                    "x....D",
                    "x..x.x",
                    "xx...x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x.xx.x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxDx  ",
                    "x.......D  ",
                    "x......xx  ",
                    "D.x...xx   ",
                    "xxx...xx   ",
                    "x......xx  ",
                    "x.......xx ",
                    "x........x ",
                    "x........xx",
                    "x....x.x..x",
                    "x.........x",
                    "x.........x",
                    "x.....xx..D",
                    "D....xxxxDx",
                    "xxxxDx     "])
    zx.map_load_room(combo=[
                    " xxx",
                    " x.x",
                    "xx.x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "xx.D",
                    " xDx"])
    zx.map_load_room(combo=[
                    "xxxxxDx",
                    "x.....D",
                    "x....xx",
                    "x...xx ",
                    "x...x  ",
                    "x...x  ",
                    "x...xx ",
                    "x....D ",
                    "D..xxx ",
                    "xxDx   "])
    zx.map_load_room(combo=[
                    "   xDx  ",
                    " xxx.D  ",
                    " x...x  ",
                    " x...x  ",
                    "xx..xxDx",
                    "x...xx.D",
                    "x...x..x",
                    "x......x",
                    "D......x",
                    "xxxx...x",
                    "   xxxDx"])
    zx.map_load_room(combo=[
                    " xDxx     ",
                    " x..xxxxxx",
                    "xx.......x",
                    "D........x",
                    "x........x",
                    "x........x",
                    "xxx...x..x",
                    "  xx.....x",
                    "   xx....D",
                    "    xxx.xx",
                    "      xDx "])
    zx.map_load_room(combo=[
                    "  xDx    ",
                    "xxx.xx   ",
                    "D....xxDx",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "x......xx",
                    "xxxxxxxx "])
    zx.map_load_room(combo=[
                    "  xDx",
                    " xx.D",
                    " x..x",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "D...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "  xDx   ",
                    "  x.xxxx",
                    " xx....D",
                    "xx.....x",
                    "x......x",
                    "D......x",
                    "xxx....x",
                    "  xxxxDx"])
    zx.map_load_room(combo=[
                    "xDxxDx",
                    "x.xx.x",
                    "x....x",
                    "x....x",
                    "xx...x",
                    " xxx.D",
                    "   xDx"])
    zx.map_load_room(combo=[
                    "       xDx  ",
                    "      xx.xx ",
                    "     xx...xx",
                    "    xx.....D",
                    "xxxxx......x",
                    "x..........x",
                    "x........xxx",
                    "x........xxx",
                    "D.x.......xx",
                    "x........xxx",
                    "x.......xx  ",
                    "xDxxxxxxx   "])
    zx.map_load_room(combo=[
                    "xDx  xxx    ",
                    "x.xDxx.xx   ",
                    "x.......xxxx",
                    "x........xxx",
                    "x.xx.......D",
                    "x.xx.......x",
                    "x..........x",
                    "x.....x....x",
                    "x....x.....D",
                    "xxx.......xx",
                    "  D........D",
                    "  xDxxxxxxDx"])
    zx.map_load_room(combo=[
                    " xxDxx",
                    "xx...D",
                    "D....x",
                    "xx..xx",
                    " xx.x ",
                    "  xDx "])
    zx.map_load_room(combo=[
                    "   xDxxx    ",
                    "  xx...xx xx",
                    "xxx.....xDxx",
                    "x..........D",
                    "x..........x",
                    "x...xx.....x",
                    "xxxxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "   xxxDx   ",
                    " xxx...D   ",
                    "xx....xx   ",
                    "x.....D    ",
                    "D..x..xx   ",
                    "x......xx  ",
                    "x.......xxx",
                    "x.........x",
                    "x.........D",
                    "x.........x",
                    "xxxxxxxxDxx"])
    zx.map_load_room(combo=[
                    "xDxxxxx    ",
                    "D.xx..x    ",
                    "x.....xx   ",
                    "x......xxxx",
                    "x.........x",
                    "x.........D",
                    "xx........x",
                    " xx....xxxx",
                    " xx...xx   ",
                    " D....x    ",
                    " xDxxxx    "])
    zx.map_load_room(combo=[
                    "     xxDxx ",
                    "    xx...xx",
                    "    x.....x",
                    "    xx....x",
                    "     x..x.D",
                    "xxx xx....x",
                    "x.xDx.....x",
                    "x........xx",
                    "D......xxx ",
                    "x.....xx   ",
                    "xxxDxxx    "])
    zx.map_load_room(combo=[
                    "xxxxDxxxxx  ",
                    "D........x  ",
                    "xx......xx  ",
                    " xxx....xx  ",
                    "   x.....xxx",
                    "  xx.......D",
                    " xx........x",
                    " x.........x",
                    " xx....xx..x",
                    "  xx...x...x",
                    "  xx......xx",
                    "  x........x",
                    "  x....x...x",
                    " xx....xx..x",
                    " D.........x",
                    " xxxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "xDxxxx",
                    "D....x",
                    "xx...x",
                    " xxx.D",
                    "   x.x",
                    "    xx"])
    zx.map_load_room(combo=[
                    "xxxxxxDx",
                    "x......D",
                    "xx.....x",
                    " x.....x",
                    " x.....D",
                    " xx....x",
                    " xx....x",
                    " x.....x",
                    " x.xxxDx",
                    " xDx    "])
    zx.map_load_room(combo=[
                    "      xDxxxxxxx ",
                    "      D.......xx",
                    "      x...x....D",
                    "      x........x",
                    "      xxx...xx.x",
                    "        x..xxxDx",
                    "  xxxx xx..xx   ",
                    " xx..xxx....x   ",
                    "xx.........xx   ",
                    "x..........x    ",
                    "D.x........x    ",
                    "x..........D    ",
                    "x..........x    ",
                    "x.........xx    ",
                    "x........xx     ",
                    "xDxxxxxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx xxxx",
                    "D........xDx..x",
                    "x.............x",
                    "x...........x.x",
                    "x.....x.....x.x",
                    "x..........x..x",
                    "x......xxxx...x",
                    "x..xx..xxx....x",
                    "x..xx..xx.....D",
                    "x..xxxxxx...xxx",
                    "x..x    x.xxx  ",
                    "x..x    x.x    ",
                    "x..x    x.x    ",
                    "D.xx    x.x    ",
                    "xDx     x.D    ",
                    "        xDx    "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxx",
                    "D.xx......x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xx...xxxx.D",
                    "x...xx  xxx",
                    "x...x    xx",
                    "x...x      ",
                    "D..xx      ",
                    "xDxx       "])
    zx.map_load_room(combo=[
                    "xDxxx",
                    "D...x",
                    "x...D",
                    "x..xx",
                    "xxxx "])
    zx.map_load_room(combo=[
                    " xDxxxxxDx ",
                    " x.......D ",
                    "xx..xx...x ",
                    "x........xx",
                    "x.........D",
                    "x....xx...x",
                    "x...xxxx..x",
                    "x...xxxx.xx",
                    "xx...xx..x ",
                    "x........x ",
                    "x........x ",
                    "x.x...x..x ",
                    "x....xx..x ",
                    "x........x ",
                    "D........D ",
                    "xDxxxxxxDx "])
    zx.map_load_room(combo=[
                    "       xxDx   ",
                    "      xx..xx  ",
                    "     xx....x  ",
                    " xDxxx.....xx ",
                    "xx.......x..xx",
                    "D........x...D",
                    "x............x",
                    "x............x",
                    "xx....x....xxx",
                    " xxx......xxxx",
                    "   xx.....xx  ",
                    "    x......xxx",
                    "    D.....xxxx",
                    "    xxxxxDx xx"])
    zx.map_load_room(combo=[
                    "   xDxx",
                    "   x..D",
                    "  xx..x",
                    "  x...x",
                    "  xx..x",
                    "   xx.x",
                    " xxxx.x",
                    "xx.x..x",
                    "x.....x",
                    "x.....x",
                    "x.x...D",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    "xDxxx      ",
                    "x...xx     ",
                    "x....x     ",
                    "x....xx    ",
                    "xx....xxxx ",
                    "x........xx",
                    "x.........x",
                    "x..x......x",
                    "x.........x",
                    "D....x....x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xDx ",
                    "  x.xx",
                    "  x..D",
                    " xx..x",
                    " x...x",
                    " xx..x",
                    "  x..x",
                    " xx..x",
                    "xx...x",
                    "D..x.x",
                    "xxxxDx"])
    zx.map_load_room(combo=[
                    " xxDx",
                    "xx..x",
                    "D...x",
                    "x...D",
                    "xxxDx"])
    zx.map_load_room(combo=[
                    "   xDxx",
                    "   x..x",
                    "  xx..x",
                    "xxx...D",
                    "D.....x",
                    "x.....x",
                    "xxxxDxx"])
    zx.map_load_room(combo=[
                    " xxDxx",
                    " D...x",
                    " x...x",
                    "xx...D",
                    "D....x",
                    "xDxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxDx",
                    "D..........x",
                    "xx.........x",
                    " D.........D",
                    " x.........x",
                    " x.........x",
                    " xx.xx.....x",
                    "  xxxxx....x",
                    "      xx...x",
                    "       x..xx",
                    "      xx..xx",
                    "    xxx....x",
                    "   xx......x",
                    "   D.......D",
                    "   x...xxxxx",
                    "   xDxxx    "])
    zx.map_load_room(combo=[
                    " xxxxxxxDx",
                    " D.......D",
                    " xx......x",
                    "xx.......x",
                    "D........x",
                    "x......xxx",
                    "x.....xx  ",
                    "x....xx   ",
                    "xx..xx    ",
                    " xDxx     "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxDx",
                    "x....x........D",
                    "x.............x",
                    "x...........x.x",
                    "x..xx.........x",
                    "x.xxxxxxx.....x",
                    "x.x     xx....x",
                    "x.x      xx..xx",
                    "x.x       x...x",
                    "x.x       x...x",
                    "x.x      xx...x",
                    "x.x     xx....x",
                    "D.x     x.....x",
                    "xDx     x....xx",
                    "        xxxxDx "])
    zx.map_load_room(combo=[
                    "xDx           ",
                    "D.D           ",
                    "x.x           ",
                    "x.x           ",
                    "x.xxxxx xxx   ",
                    "x.xx..xDx.xxxx",
                    "x............D",
                    "x............x",
                    "x......x..x..x",
                    "x........x...x",
                    "x............x",
                    "x..xx.......xx",
                    "x.......x...x ",
                    "D...........x ",
                    "xxxxDx......D ",
                    "     xxxxxxDx "])
    zx.map_load_room(combo=[
                    "  xDx",
                    "xDx.D",
                    "x...x",
                    "x...x",
                    "xxxDx"])
    zx.map_load_room(combo=[
                    "xDxxxxxxx   ",
                    "D.......D   ",
                    "x.......x   ",
                    "x.......xx  ",
                    "x........xx ",
                    "x.........xx",
                    "x..........x",
                    "x..........D",
                    "x..x.....xxx",
                    "x....x...x  ",
                    "x........D  ",
                    "xx.......x  ",
                    "xx......xx  ",
                    "D.....xxx   ",
                    "xx...xx     ",
                    " xxxDx      "])
    zx.map_load_room(combo=[
                    "xDxxxxxxxxxxxDx",
                    "D..xx.........D",
                    "x...x.........x",
                    "x.............x",
                    "x.....x...xxx.D",
                    "x.xx...xxxx xDx",
                    "x..x...x       ",
                    "x......D       ",
                    "x.....xx       ",
                    "x.x...D        ",
                    "x.....x        ",
                    "x..x..xx       ",
                    "x......xx      ",
                    "D.......x      ",
                    "xxxxxxDxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxDx",
                    "D.....x..x",
                    "x.xx.....x",
                    "xxxxx....x",
                    "    xx...x",
                    "     D...x",
                    "     x...D",
                    "    xx...x",
                    " xxxx....x",
                    "xx.......x",
                    "x........x",
                    "x.....xx.D",
                    "x....xxxDx",
                    "D....x    ",
                    "xxx..x    ",
                    "  xDxx    "])
    zx.map_load_room(combo=[
                    "xDxx",
                    "D..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "xx.D",
                    " xDx"])
    zx.map_load_room(combo=[
                    "   xDx       ",
                    "  xx.xxxxxxDx",
                    " xx...xx....x",
                    "xx..........x",
                    "x.........x.x",
                    "D.xx......xxx",
                    "x....x.....xx",
                    "x....xx.....x",
                    "x....x......x",
                    "x.x.........x",
                    "x...........D",
                    "x..........xx",
                    "xDxxxxxxxxxx "])
    zx.map_load_room(combo=[
                    "   xDx",
                    "  xx.D",
                    "  x..x",
                    " xx..x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "D....x",
                    "xxx..x",
                    "  xx.D",
                    "   xDx"])
    zx.map_load_room(combo=[
                    "          ",
                    "       xxx",
                    "      xx.x",
                    "  xxxDx..x",
                    " xx......x",
                    "xx.......x",
                    "x........x",
                    "D........x",
                    "xx.xxxxxxx",
                    " xDx      "])
    zx.map_load_room(combo=[
                    " xxxDx",
                    " x...x",
                    "xx..xx",
                    "D...x ",
                    "x..xx ",
                    "x..x  ",
                    "xxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "D.....x",
                    "x.....x",
                    "xx....x",
                    " xxx..x",
                    "   xx.x",
                    "    xDx"])
map_data_init()
