import zx

zx.map_load_level(level_data=[
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxx                                                   xx",
"xxx                                                   xx",
"xxx                                                   xx",
"xxx                       E  |                        xx",
"xxx S    m       |       xxxxxx                       xx",
"xxxxx   xxxxxxxxxxxxxxx  xxxxxxxxx                    xx",
"xxxxw   xxxwwwwwwwwxxxx  x        xxx                 xx",
"xxxxx   xxxwwwwwwwwxxxx  x          xxx               xx",
"xxxxx   xxxWWWWWWWWxxxx  x             xxx            xx",
"xxxxxxxxxxxWWWWWWWWxxxx  x                xxx         xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xxxxxxxxxxxxxxxxxxxxxxx  x                            xx",
"xx         |        |    x                            xx",
"xx         xxxxxxxxxx xx x                            xx",
"xx                                                    xx",
"xx       |            |                               xx",
"xx   xxxxxxxxxxxxxxxxxxxxx                            xx",
"xx                                                    xx",
"xx                                                    xx",
"xxxxxxxxxxx      xxxxxx  xxxxxxxxx                    xx",
"xxxxxxxxxXxwwwwwwxXxxxx  x        xxx                 xx",
"xx xxxxxxxxwwwwwwwxxxxx  x          xxx               xx",
"xx xxxxxxxxxwwwwxxxxxxx  x             xxx            xx",
"xx xxxxxxxwwwwwxxxwxxxx  x                xxx         xx",
"xx xxxxxxxxwWWWWWWWWWxx  x                            xx",
"xx xxxxxxxxxWWWWWWWWWxx  x                            xx",
"xx xxxxxxxxxWWWWWWWWWxx  x                            xx",
"xx xxxxxxxxxWxWWWWWWWxx  x                            xx",
"xx xxxxxxxxxWxWWWWWWWxx  x                            xx",
"xx   xxxxxxxxxxxxxxxxxx  x                            xx",
"xx         |        |    x                            xx",
"xx         xxxxxxxxxx xx x                            xx",
"xx                                                    xx",
"xx       |            |                               xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xx                                                    xx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"])

