import zx

zx.map_load_level(level_data=[
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"x                                                                                   x",
"x                             P                                                     x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                          xxx                                                      x",
"x                               xxx                                                 x",
"x                                                                                   x",
"x                            S           x                                          x",
"x                 x       xxxxx          x                                          x",
"x                 x                      x                                          x",
"x                 x                      x                                          x",
"x                 x                      x                                          x",
"x                 x                      x                                          x",
"x                 x                      x                                          x",
"x                 x                      x                                          x",
"x                 xxxxxxxxxxxxxx        xx                                          x",
"x                              x        x                                           x",
"x                              x        x                                           x",
"x                              x        x                                           x",
"x                              x        x                                           x",
"x                              xxxxxxxxxx                                           x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"x                                                                                   x",
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"])
