import zx


def map_data_init():

    zx.map_load_room(
        floor=[
                "......",
                "......",
                "......",
                "......",
                "......",
              ],
        walls=[
                "xxDxxx",
                "x    D",
                "D    x",
                "x    x",
                "xxxDxx",
              ],
        items=[
                "      ",
                "   $  ",
                "      ",
                "      ",
                "      ",
              ])
    zx.map_load_room(combo=[
                    "xxxxDxx",
                    "x.....D",
                    "D.....x",
                    "x.....x",
                    "xxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxxx",
                    "x......D",
                    "D......x",
                    "x......x",
                    "xxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxxxx",
                    "x.......D",
                    "D.......x",
                    "x.......x",
                    "x.......x",
                    "xxxxxDxxx" ])
    zx.map_load_room(combo=[
                    "xxxxxxDxxxxxx",
                    "x...........D",
                    "D...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxxxxxxxxxx",
                    "x...............x",
                    "D...............x",
                    "x...............D",
                    "x...............x",
                    "x...............x",
                    "x...............x",
                    "xxxxxxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxDxxxxxxxxxxxxxxxxx",
                    "x...................x",
                    "x...................x",
                    "x...................x",
                    "D...................x",
                    "x...................x",
                    "x...................D",
                    "x...................x",
                    "x...................x",
                    "x...................x",
                    "xxxxxxxDxxxxxxxxxxxx" ])
    zx.map_load_room(combo=[
                "xxDxxxxxxx",
                "x..x.....D",
                "x..x...xxx",
                "x........x",
                "x........x",
                "D........x",
                "xxxxxDxxxx" ])
    zx.map_load_room(combo=[
                "   xxDxxxx",
                "   x.....D",
                "xxxx.....x",
                "D........x",
                "x.....xxxx",
                "x.....x   ",
                "xxxDxxx   " ])
    zx.map_load_room(combo=[
                    "  xxDx  ",
                    " xx..xx ",
                    "xx....xx",
                    "D......D",
                    "xx.....x",
                    " xx....x",
                    "  xDxxxx" ])
    zx.map_load_room(combo=[
                    "xxDxxxx   ",
                    "x..x...xxx",
                    "xx.......D",
                    " x.......x",
                    " x.......x",
                    "xx.......x",
                    "D.......xx",
                    "x.......x ",
                    "x.xDx...x ",
                    "xxx xxxDx " ])
    zx.map_load_room(combo=[
                    "xxxxDxxxxx",
                    "x........x",
                    "x........D",
                    "xxxx..xxxx",
                    "   D..D   ",
                    "   x..x   ",
                    "xxxx..xxxx",
                    "D........x",
                    "x........x",
                    "xxxxxDxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxx    xxDx",
                    "D...x   x...D",
                    "x...x  xx...x",
                    "x...x xx...xx",
                    "x...xxx..xxx ",
                    "x........x   ",
                    "xxxx....xx   ",
                    "   D...xx    ",
                    "xxxx...x     ",
                    "x......x     ",
                    "x......x     ",
                    "xxxDxxxx     " ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...x        ",
                    "x...x        ",
                    "x...xxxxxxxxx",
                    "x...........D",
                    "xxxx...xxxxxx",
                    "   D...x     ",
                    "xxxx...x     ",
                    "x......x     ",
                    "x......x     ",
                    "xxxDxxxx     " ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...x        ",
                    "x...x        ",
                    "x...xxxxDxxxx",
                    "x...........D",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "xxxxx        ",
                    "D...D        ",
                    "x...x        ",
                    "x...x        ",
                    "x...xxxxxxxxx",
                    "x...........D",
                    "x...xxxx....x",
                    "D...x  x....x",
                    "x...xxxx....x",
                    "x...........x",
                    "x...........x",
                    "xxxDxxxxxxxxx" ])
    zx.map_load_room(combo=[
                    "   xDxxxxxxxx",
                    "   x........x",
                    "xxxx......x.D",
                    "x..x......xxx",
                    "x..xx.....D  ",
                    "D........xxxx",
                    "x.xxx..xxxx.D",
                    "x.x...xx  x.x",
                    "x.x...xx xx.x",
                    "xDx....xxx..x",
                    "  x.........x",
                    "  x.........x",
                    "  x....x....x",
                    "  xx...x....x",
                    "   x......x.D",
                    "   xxxxxxxxDx"])
    zx.map_load_room(combo=[
                    "    xDxxxxxxxxxx",
                    "    x..........D",
                    "    x........xxx",
                    "    x.......xx  ",
                    "    x.......D   ",
                    "    x.......x   ",
                    "    x.......x   ",
                    "   xx.......xx  ",
                    "  xx....??...x  ",
                    " xx....????..D  ",
                    "xx....?????..x  ",
                    "D.....?????.xx  ",
                    "x..?...??..xx   ",
                    "x.........xx    ",
                    "xxx......xx     ",
                    "  xxxxxxDx      "])
    zx.map_load_room(combo=[
                    " xxDx     ",
                    " x..xx    ",
                    "xx...x    ",
                    "x....xx   ",
                    "D.....xx  ",
                    "x......xx ",
                    "xDxx....xx",
                    "   xx....x",
                    "    x....x",
                    "    xx...x",
                    "     xxxxx"])
    zx.map_load_room(combo=[
                    "            ",
                    "  xxxxxxxxxx",
                    "xxx........x",
                    "x..........x",
                    "x..........x",
                    "x.....xxx..x",
                    "x....xx xxxx",
                    "x....x      ",
                    "x....x      ",
                    "x....xx     ",
                    "x.....x     ",
                    "xxxxxxx     "])
    zx.map_load_room(combo=[
                    "xxxxx       ",
                    "x...xxxxx   ",
                    "x.......xx  ",
                    "x.xx.....xxx",
                    "x.x........x",
                    "xx.........x",
                    "x..........x",
                    "x.......xxxx",
                    "x.x....xx xx",
                    "x..x...x    ",
                    "x.xxx..x    ",
                    "xxx xxxx    "])
    zx.map_load_room(combo=[
                    "  xxxxxxxx ",
                    "  x.xx...x ",
                    " xx.....xx ",
                    " x.....xx  ",
                    " x.....xxxx",
                    " x..x...xxx",
                    "xx..x.....x",
                    "x.........x",
                    "xx........x",
                    " xx...xxx.x",
                    "  xxxxx xxx"])
    zx.map_load_room(combo=[
                    "xxxxxx     ",
                    "x....x     ",
                    "x....x     ",
                    "xx...xx    ",
                    " x....xx   ",
                    "xx.....xxxx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xx........x",
                    " xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx  xxx",
                    "x.xx.xxxx.x",
                    "x.....xx..x",
                    "x.........x",
                    "x.........x",
                    "xx.......xx",
                    "xx....x..xx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxxxxxxx",
                    "xx........x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x........xx",
                    "xxx.......x",
                    "  xx......x",
                    "   xx.....x",
                    "    x.....x",
                    "   xx...xxx",
                    "xxxx...xx  ",
                    "x......xx  ",
                    "xx......xxx",
                    " xxx......x",
                    "   xxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxx",
                    "x...x...x",
                    "x...x...x",
                    "x.......x",
                    "xxx....xx",
                    "  xx..xx ",
                    "   xx.x  ",
                    "    x.x  ",
                    "    xxx  "])
    zx.map_load_room(combo=[
                    " xxxxx   xxxx",
                    " x...x  xx..x",
                    " x...x xx...x",
                    " x...xxx....x",
                    " x...xx.....x",
                    " x...x......x",
                    " x..........x",
                    " x..........x",
                    "xx.....x....x",
                    "x.........xxx",
                    "x....xx...x  ",
                    "x....xxx..x  ",
                    "x.x..x x..x  ",
                    "x.xx.x x..x  ",
                    "x....x x..x  ",
                    "xxxxxx xxxx  "])
    zx.map_load_room(combo=[
                    "xxxx ",
                    "x..xx",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x........x",
                    "x........x",
                    "x....xx..x",
                    "x...xxxx.x",
                    "x...x  xxx",
                    "xx..x     ",
                    "x...x     ",
                    "x..xx     ",
                    "xxxx      "])
    zx.map_load_room(combo=[
                    "xxxxx   xxxxxxxx",
                    "x...xx xx......x",
                    "x....xxx......xx",
                    "xx............x ",
                    "x.............x ",
                    "x..xx.......xxx ",
                    "x..x.......xx   ",
                    "x......xxxxx    ",
                    "x.....xx        ",
                    "x.....xx        ",
                    "x......x        ",
                    "x......x        ",
                    "x.x...xx        ",
                    "x.x..xx         ",
                    "x....x          ",
                    "xxxxxx          "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "x.........x ",
                    "x.........x ",
                    "x.....x...x ",
                    "x.....xxx.x ",
                    "x......xx.x ",
                    "x.....xxx.x ",
                    "xxxxx.xxx.xx",
                    "   xxxxx...x",
                    " xxx.......x",
                    "xx.....x...x",
                    "x..........x",
                    "x..........x",
                    "x.....x...xx",
                    "x........xx ",
                    "xxxxxxxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxx  ",
                    "x...x  ",
                    "x...xx ",
                    "x....xx",
                    "x.....x",
                    "x.....x",
                    "x....xx",
                    "x...xx ",
                    "xx...xx",
                    " x....x",
                    " x....x",
                    " x....x",
                    " x....x",
                    " x....x",
                    " xx...x",
                    "  xxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x....x...x",
                    "x.......xx",
                    "x......xx ",
                    "x.....xx  ",
                    "xx...xx   ",
                    " x..xx    ",
                    " x..x     ",
                    " x.xx     ",
                    " xxx      "])
    zx.map_load_room(combo=[
                    "xxx    ",
                    "x.x    ",
                    "x.xx   ",
                    "x..xxx ",
                    "x....x ",
                    "x....x ",
                    "xxx..x ",
                    "  x..xx",
                    "  x...x",
                    "  xxxxx"])
    zx.map_load_room(combo=[
                    "xxx      ",
                    "x.x      ",
                    "x.xx     ",
                    "x..xxxxx ",
                    "x......x ",
                    "xx.....x ",
                    "xx.....x ",
                    "x...x..xx",
                    "x...x...x",
                    "xxxxxxxxx"])
    zx.map_load_room(combo=[
                    "       xxx",
                    "      xx.x",
                    "     xx..x",
                    " xxxxx...x",
                    "xx.x....xx",
                    "x...x..xx ",
                    "x......x  ",
                    "x......x  ",
                    "x......x  ",
                    "xxxxxxxx  "])
    zx.map_load_room(combo=[
                    "  xxx    ",
                    "  x.x    ",
                    " xx.xx   ",
                    "xx...xxx ",
                    "x......x ",
                    "x......xx",
                    "x.......x",
                    "xxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxxxxx ",
                    "  x....x ",
                    "  x....xx",
                    " xx.....x",
                    "xx......x",
                    "x...xxxxx",
                    "xx.xx    ",
                    " x.x     ",
                    " xxx     "])
    zx.map_load_room(combo=[
                    " xxx ",
                    "xx.xx",
                    "x...x",
                    "x..xx",
                    "x..xx",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "    xxx",
                    "xxxxx.x",
                    "x.xx..x",
                    "x.....x",
                    "x..xx.x",
                    "xxxxxxx",
                    "       "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxx",
                    "x...x.......x",
                    "x..x...x....x",
                    "x......x....x",
                    "xx.........xx",
                    " xx.....x..x ",
                    " xx....xx..x ",
                    "xx....xxxxxx ",
                    "x.....xx     ",
                    "x......xx    ",
                    "x.......xxxxx",
                    "x..x.x......x",
                    "x..........xx",
                    "xxxx.......x ",
                    "   xxxx..xxx ",
                    "      xxxx   "])
    zx.map_load_room(combo=[
                    "  xxx",
                    "  x.x",
                    "  x.x",
                    " xx.x",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "x..xx",
                    "xxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxx",
                    "x...xx......x",
                    "x...x.......x",
                    "x...........x",
                    "xxx...xx....x",
                    "  x.........x",
                    "  x......x..x",
                    "  x.........x",
                    "  x.......x.x",
                    "  x.......x.x",
                    "  x.......x.x",
                    "  x.......x.x",
                    "  x...xxxxxxx",
                    "  x...x      ",
                    "  xxxxx      "])
    zx.map_load_room(combo=[
                    "   xxxxx",
                    "   x...x",
                    "   x..xx",
                    "   x..xx",
                    "   x...x",
                    "   xxx.x",
                    "   x.x.x",
                    " xxx...x",
                    " x.x...x",
                    " x.xx..x",
                    " x.x...x",
                    "xx.x...x",
                    "x......x",
                    "x......x",
                    "xx.xxx.x",
                    " xxx xxx"])
    zx.map_load_room(combo=[
                    "     xxxxxx ",
                    "    xx....x ",
                    "xxxxx.....x ",
                    "x.........x ",
                    "x.........x ",
                    "x.........x ",
                    "x..x......x ",
                    "x.x.......x ",
                    "xx.....x..x ",
                    "x.........x ",
                    "xxx.x.....x ",
                    "x.........x ",
                    "x.........xx",
                    "x..xx......x",
                    "x.xxxxxxxxxx",
                    "xxx         "])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "x.....x",
                    "x....xx",
                    "x....x ",
                    "x....x ",
                    "x..xxx ",
                    "x.xx   ",
                    "x.xxxxx",
                    "x..xx.x",
                    "x.....x",
                    "x.....x",
                    "x.....x",
                    "x.....x",
                    "xx.xxxx",
                    " xxx   "])
    zx.map_load_room(combo=[
                    "xxxxxxxx xxxxxx",
                    "x......xxx....x",
                    "x...x.........x",
                    "x.........x..xx",
                    "x.......x.x..x ",
                    "x.x.......x..x ",
                    "x........xxxxx ",
                    "x...xxx..x     ",
                    "x....xx..x     ",
                    "x........x     ",
                    "x........x     ",
                    "x.xx.....x     ",
                    "xxxxx....x     ",
                    "    x.xxxx     ",
                    "    xxx        "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx ",
                    "x....x...xx",
                    "x.....x...x",
                    "x........xx",
                    "x......xxx ",
                    "x.....xx   ",
                    "x.....xx   ",
                    "xx.....x   ",
                    "x......x   ",
                    "x......xx  ",
                    "x.......xx ",
                    "xx..x....x ",
                    " x.......x ",
                    " xx......x ",
                    "  xxxxxxxx "])
    zx.map_load_room(combo=[
                    "        xxxx",
                    "      xxx..x",
                    "     xx....x",
                    "    xx.....x",
                    "    x.....xx",
                    "    x....xx ",
                    "   xx...xx  ",
                    "  xx....xx  ",
                    " xx......x  ",
                    "xx......xx  ",
                    "x......xx   ",
                    "xxxxxxxx    "])
    zx.map_load_room(combo=[
                    "   xxxx",
                    "xxxx..x",
                    "x.....x",
                    "x...x.x",
                    "x.....x",
                    "xx....x",
                    " xxxxxx"])
    zx.map_load_room(combo=[
                    "       xxx  ",
                    "   xxxxx.xxx",
                    "xxxx.......x",
                    "x..........x",
                    "x.....x...xx",
                    "x........xx ",
                    "x........x  ",
                    "x...x....x  ",
                    "x...x...xx  ",
                    "xx.....xx   ",
                    "x......x    ",
                    "xxxxxxxx    "])
    zx.map_load_room(combo=[
                    "  xxxxxxxxx ",
                    "xxx..x....x ",
                    "x....x....x ",
                    "x...xxx...xx",
                    "x...x xx...x",
                    "x...xxxx...x",
                    "x.....xx...x",
                    "x.....xxx..x",
                    "x......x...x",
                    "x..........x",
                    "x.......x..x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "        xxx",
                    "  xxxxxxx.x",
                    " xx.......x",
                    " x........x",
                    "xx........x",
                    "x...x....xx",
                    "xx.xx...xxx",
                    " xxx.....xx",
                    " xx.......x",
                    " x.....x..x",
                    " xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "    xxxxxxx",
                    "   xx.....x",
                    "  xx......x",
                    "  x.......x",
                    " xx..xx...x",
                    "xx........x",
                    "x.......x.x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxx      ",
                    "xx.xxx    ",
                    "x....xx   ",
                    "x.....xxxx",
                    "x........x",
                    "x........x",
                    "x...xx...x",
                    "xx..xx...x",
                    "x...x....x",
                    "x..xx....x",
                    "xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxx",
                    " x...x",
                    " x...x",
                    " x...x",
                    " xx..x",
                    " xx..x",
                    "xx...x",
                    "x....x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxx ",
                    "x..xx",
                    "x...x",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx",
                    "x.....x...x",
                    "x.........x",
                    "x.........x",
                    "xxx.......x",
                    "  xx...x..x",
                    "   xx.....x",
                    "    xx..x.x",
                    "     x....x",
                    "     xx...x",
                    "      xx..x",
                    "       x..x",
                    "       xxxx"])
    zx.map_load_room(combo=[
                    "       xxxxxx",
                    "       x....x",
                    "xxx    x....x",
                    "x.x   xx....x",
                    "x.xx xx.....x",
                    "x..xxx......x",
                    "x........x..x",
                    "xxx.........x",
                    "x....xx.....x",
                    "x...........x",
                    "x....x.....xx",
                    "x.........xx ",
                    "x.........x  ",
                    "x.....xxxxx  ",
                    "xx...xx      ",
                    " xxxxx       "])
    zx.map_load_room(combo=[
                    "xxxxxxx         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....xx     xxx",
                    "x......xxxx xx.x",
                    "x.........xxx..x",
                    "x.......x......x",
                    "x.............xx",
                    "x...xxx.....xxx ",
                    "x..xx x.....x   ",
                    "x..x  x.....x   ",
                    "xxxx  xxxxxxx   "])
    zx.map_load_room(combo=[
                    " xxxxxxxxxxx ",
                    " x.........xx",
                    "xxx.....x...x",
                    "x.xxx...x...x",
                    "x.xxxxx..x.xx",
                    "x..xx x....x ",
                    "x...xxxx..xx ",
                    "xx...xxx..x  ",
                    "xx...xx...xx ",
                    "x....x.....x ",
                    "x........x.x ",
                    "x........x.x ",
                    "x....xx..x.x ",
                    "x....x...x.x ",
                    "x.x........x ",
                    "xxxxxxxxxxxx "])
    zx.map_load_room(combo=[
                    " xxxxxxxxxxxxxx",
                    " x...x........x",
                    " x............x",
                    " x............x",
                    " xxxxx....x...x",
                    "     xx..xx...x",
                    "      xxxxx...x",
                    "         x...xx",
                    "        xx..xx ",
                    "        x...xx ",
                    "        x....x ",
                    " xxxx  xx....x ",
                    "xx..xxxx.....xx",
                    "x.........x...x",
                    "x............xx",
                    "xxxxxxxxxxxxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "x.........xx",
                    "x..........x",
                    "x..........x",
                    "x........xxx",
                    "xxx..xx...x ",
                    "  xx....x.xx",
                    "   x....x..x",
                    "   x....xx.x",
                    "   x....xx.x",
                    "   x....xx.x",
                    "  xx....xx.x",
                    "xxx........x",
                    "x..........x",
                    "x..........x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxx",
                    "x..........x",
                    "x..x.......x",
                    "x..........x",
                    "x...xx.....x",
                    "x...xx.....x",
                    "x..........x",
                    "xx.........x",
                    " xxxx...x..x",
                    "    x..xx..x",
                    "    x......x",
                    "    x......x",
                    "    x......x",
                    "    x......x",
                    "    x....xxx",
                    "    xxxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "x...xx",
                    "x...x ",
                    "x.xxx ",
                    "xxx   "])
    zx.map_load_room(combo=[
                    "   xxxxxxx ",
                    "  xx.....x ",
                    " xx......x ",
                    "xx.......x ",
                    "x........x ",
                    "x........x ",
                    "x........xx",
                    "x....x....x",
                    "x...xxx...x",
                    "x...x x...x",
                    "x...x xxxxx",
                    "xxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x.xx.x",
                    "x....x",
                    "x....x",
                    "x.xx.x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxx   ",
                    "x.xx  ",
                    "x..xxx",
                    "x....x",
                    "x....x",
                    "xx..xx",
                    "x...x ",
                    "xxxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxx  ",
                    "x.......xxx",
                    "x.........x",
                    "x.........x",
                    "x....xx...x",
                    "xxx..xx...x",
                    "  x.......x",
                    "  x.......x",
                    " xx.......x",
                    " x........x",
                    " x........x",
                    " x.....x..x",
                    " x........x",
                    " x........x",
                    " xx..xxx..x",
                    "  xxxx xxxx"])
    zx.map_load_room(combo=[
                    "            xxx",
                    "      xxxxxxx.x",
                    "xxx xxx...xx..x",
                    "x.xxx.........x",
                    "x.............x",
                    "x........xx...x",
                    "x.......xxxx..x",
                    "x..xx...xx xx.x",
                    "x...x....xxxx.x",
                    "x...x..x..xx..x",
                    "xxxxx..xx.....x",
                    "    x..xxx....x",
                    "    x..x x....x",
                    "    xxxx xxxx.x",
                    "            xxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxx",
                    "x............x",
                    "x..x.........x",
                    "x..xxx.......x",
                    "x..x x.......x",
                    "x.xx x......xx",
                    "xxx  x......x ",
                    "     x......x ",
                    "    xx......x ",
                    "  xxx.......x ",
                    "  x........xx ",
                    "  x........xx ",
                    "  x.........x ",
                    "  xx...xxxxxx ",
                    "   xxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxx",
                    "x.....x.....x",
                    "x...........x",
                    "x...........x",
                    "x...xx......x",
                    "x..xxxx.....x",
                    "x.xx  xx....x",
                    "x.x    xxx.xx",
                    "x.x      xxx ",
                    "x.x          ",
                    "x.x          ",
                    "x.x          ",
                    "xxx          "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx xxx",
                    "x........x x.x",
                    "x........x x.x",
                    "x.....x..xxx.x",
                    "xxx.......x..x",
                    "  xx...x....xx",
                    "  xx...x....x ",
                    "xxx....x....x ",
                    "x......x....x ",
                    "x......x....x ",
                    "x......x...xx ",
                    "x......x..xx  ",
                    "x...xxxx..x   ",
                    "xxxxx  x..x   ",
                    "       xxxx   "])
    zx.map_load_room(combo=[
                    " xxxx",
                    " x..x",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "x...x",
                    "x...x",
                    "x.xxx",
                    "xxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxx",
                    "x..........x..x",
                    "x.............x",
                    "x.............x",
                    "x..x...x......x",
                    "xxx...x...x...x",
                    "x....x..xxxx..x",
                    "x......xx x...x",
                    "xx....xx  x...x",
                    " xx...x   x...x",
                    " xx...x   x.xxx",
                    "xx....x   xxx  ",
                    "x...xxx        ",
                    "x..xx          ",
                    "xxxx           "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "x.........x ",
                    "x.........x ",
                    "x.........x ",
                    "x.........xx",
                    "x.....x....x",
                    "xx...xxx...x",
                    "x.....x....x",
                    "x.........xx",
                    "x.........x ",
                    "xxxx.....xx ",
                    " xx.....xx  ",
                    "xx.....xx   ",
                    "x......x    ",
                    "xxx..xxx    ",
                    "  xxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "x.....x",
                    "x....xx",
                    "x.....x",
                    "x.....x",
                    "xx....x",
                    " x.xx.x",
                    " xxxxxx"])
    zx.map_load_room(combo=[
                    "  xxx  ",
                    " xx.xxx",
                    "xx....x",
                    "x.....x",
                    "x.xx..x",
                    "x.xx..x",
                    "x...xxx",
                    "x...x  ",
                    "xx..x  ",
                    " xxxx  "])
    zx.map_load_room(combo=[
                    "   xxx",
                    "  xx.x",
                    " xx..x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x...xx",
                    "xxxxx "])
    zx.map_load_room(combo=[
                    "xxx   ",
                    "x.xx  ",
                    "x..xx ",
                    "x...x ",
                    "x...xx",
                    "xxx..x",
                    "  xxxx"])
    zx.map_load_room(combo=[
                    " xxxxx  ",
                    " x...xxx",
                    " x.....x",
                    " x.....x",
                    "xx..x..x",
                    "x......x",
                    "x...xxxx",
                    "xxxxx   "])
    zx.map_load_room(combo=[
                    "   xxx",
                    "  xx.x",
                    "xxx..x",
                    "x....x",
                    "x....x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxx         ",
                    "x.xxxxx     ",
                    "x.....xxxxxx",
                    "xx.....xx..x",
                    " xx........x",
                    " xxxxx.....x",
                    "xx..xxxxxx.x",
                    "x....x   xxx",
                    "x.x..xx  xxx",
                    "x.....xxxx.x",
                    "x..........x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxx        ",
                    "x..xx     xx",
                    "x...xxxxxxxx",
                    "x..........x",
                    "x..........x",
                    "xxxx.......x",
                    "   xx....x.x",
                    "    xxx....x",
                    "      xx...x",
                    "       xxx.x",
                    "         xxx",
                    "          xx"])
    zx.map_load_room(combo=[
                    "     xxxx",
                    "     x..x",
                    "    xx..x",
                    "   xx...x",
                    "  xx...xx",
                    "  x....x ",
                    " xx...xx ",
                    " x...xx  ",
                    "xx..xx   ",
                    "x...x    ",
                    "xxxxx    "])
    zx.map_load_room(combo=[
                    " xxxxxx",
                    " x....x",
                    " xx...x",
                    "  x..xx",
                    " xx..x ",
                    "xx...x ",
                    "x...xx ",
                    "x..xx  ",
                    "xxxx   "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx",
                    "x.........x",
                    "xx........x",
                    " xx......xx",
                    "  x.....xx ",
                    "  xx....x  ",
                    "  xx....xx ",
                    " xx......xx",
                    " x........x",
                    " x........x",
                    " xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxx   ",
                    "xxx.xxx ",
                    "x.....xx",
                    "x......x",
                    "x...x..x",
                    "x......x",
                    "x......x",
                    "xxxxxxxx"])
    zx.map_load_room(combo=[
                    "   xxxx",
                    "  xx..x",
                    "  x...x",
                    " xx...x",
                    "xx....x",
                    "x.....x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "x.xx..x",
                    "x.....x",
                    "x.....x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxxxxx   ",
                    " x......x   ",
                    "xx...x..xx  ",
                    "x...xxx..x  ",
                    "x........x  ",
                    "xx.......xx ",
                    " xx.......xx",
                    "  xx.......x",
                    "   xx......x",
                    "    xx...x.x",
                    "     x.....x",
                    "     x.....x",
                    "     x....xx",
                    "    xx.....x",
                    "    x......x",
                    "    xxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxx",
                    "x......x",
                    "x......x",
                    "xxxx...x",
                    "   xxxxx"])
    zx.map_load_room(combo=[
                    "  xxxxxxx   ",
                    " xx.....x   ",
                    "xx......xx  ",
                    "x........xxx",
                    "x..........x",
                    "x.......x..x",
                    "xx.........x",
                    "xx....xx...x",
                    "x....xxxxx.x",
                    "x...xx   xxx",
                    "xxxxx     xx",
                    "          xx"])
    zx.map_load_room(combo=[
                    "xxx          ",
                    "x.xxxxxxx    ",
                    "x...xx..xx   ",
                    "x........xx  ",
                    "x.........xx ",
                    "x.......x..xx",
                    "x.xx....xx..x",
                    "x..x....xxx.x",
                    "x...x..xxxx.x",
                    "x........xx.x",
                    "x........xx.x",
                    "x........xx.x",
                    "x....xxx....x",
                    "x...xx x....x",
                    "x...x  x....x",
                    "xxxxx  xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxx         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....x         ",
                    "x.....xx        ",
                    "xxx....xxxx xxxx",
                    "  x.......xxx..x",
                    "  x...x........x",
                    "  x..xx...x....x",
                    "  x...x...xxx..x",
                    "  x.x.x...xx...x",
                    "  x.x.x......xxx",
                    "  x..........x  ",
                    "  x.......x..x  ",
                    "  xxxxxxxxxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "x....x....xx",
                    "x..........x",
                    "x..........x",
                    "x..........x",
                    "x..........x",
                    "x....xx....x",
                    "x...xxx....x",
                    "x....xx....x",
                    "x...xxx....x",
                    "x...x xx..xx",
                    "x...xx xxxx ",
                    "x....xx     ",
                    "x.....xx    ",
                    "x......x    ",
                    "xxxxxxxx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxx",
                    "x...xx.x",
                    "x..xxx.x",
                    "x...xx.x",
                    "x......x",
                    "x......x",
                    "x......x",
                    "x......x",
                    "x....xxx",
                    "x...xx  ",
                    "x..xx   ",
                    "x..x    ",
                    "x..x    ",
                    "x..x    ",
                    "x..x    ",
                    "xxxx    "])
    zx.map_load_room(combo=[
                    "   xxxxx  ",
                    "  xx...x  ",
                    " xx....x  ",
                    " x....xx  ",
                    " x....xxxx",
                    " x.....xxx",
                    "xx.......x",
                    "x...x....x",
                    "x........x",
                    "xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxx ",
                    "xx..x ",
                    "x...xx",
                    "x....x",
                    "x....x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "   xxx",
                    " xxx.x",
                    "xx...x",
                    "x....x",
                    "xx...x",
                    " xxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxx",
                    "x.......x",
                    "xx......x",
                    " xx..x..x",
                    "  x.....x",
                    "  x.....x",
                    "  xx....x",
                    "   xx..xx",
                    "    xxxx "])
    zx.map_load_room(combo=[
                    " xxx    ",
                    "xx.x    ",
                    "x..x    ",
                    "x..xx   ",
                    "x...x   ",
                    "x...xx  ",
                    "x.x..x  ",
                    "x....x  ",
                    "x....x  ",
                    "x....xx ",
                    "x.....xx",
                    "xx.....x",
                    " xx....x",
                    "  xx...x",
                    "   xxx.x",
                    "     xxx"])
    zx.map_load_room(combo=[
                    "  xxxxxxxx",
                    "  x..x...x",
                    " xx......x",
                    "xx...x.x.x",
                    "x........x",
                    "x........x",
                    "x....x...x",
                    "x......x.x",
                    "xxxxx....x",
                    "    xx...x",
                    "    xx...x",
                    "   xx..x.x",
                    " xxx.....x",
                    " x.......x",
                    " xxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxx ",
                    "x......xx",
                    "x.......x",
                    "x...xxxxx",
                    "x..xx    ",
                    "x..xx    ",
                    "x...xx   ",
                    "xx...xx  ",
                    "xxx...x  ",
                    "x....xx  ",
                    "x...xx   ",
                    "x...x    ",
                    "x.xxx    ",
                    "xxx      "])
    zx.map_load_room(combo=[
                    "   xxxxxxx",
                    "   x.....x",
                    "   x.....x",
                    "  xx.....x",
                    "xxx.....xx",
                    "x........x",
                    "x........x",
                    "x...xxxx.x",
                    "x..xx  xxx",
                    "xxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxx ",
                    "x.......xx",
                    "xxxxx....x",
                    "    xx...x",
                    "     xx..x",
                    "      x..x",
                    "      x..x",
                    "     xx..x",
                    "    xx...x",
                    "   xx....x",
                    " xxx.....x",
                    " x......xx",
                    " xxx...xx ",
                    "   xxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxx ",
                    "x...xx",
                    "x....x",
                    "x....x",
                    "x....x",
                    "x..xxx",
                    "x.xx  ",
                    "x.x   ",
                    "xxx   "])
    zx.map_load_room(combo=[
                    "  xxxxxxx",
                    "  x.....x",
                    " xx....xx",
                    "xx......x",
                    "x....x..x",
                    "x...xx..x",
                    "xxxxxx..x",
                    "    x...x",
                    "    x...x",
                    "    x...x",
                    "    xx..x",
                    "    xx..x",
                    "   xx...x",
                    "   x....x",
                    "   x...xx",
                    "   xxxxx "])
    zx.map_load_room(combo=[
                    "xxxxx   ",
                    "x...x   ",
                    "x..xx   ",
                    "x..xx   ",
                    "x...xxx ",
                    "x.....x ",
                    "x.x...x ",
                    "x.....x ",
                    "x....xx ",
                    "x....xx ",
                    "x.....xx",
                    "x......x",
                    "x.....xx",
                    "x.....x ",
                    "xxxxxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x........x",
                    "xx......xx",
                    " xx.....x ",
                    " xx.....x ",
                    " x......x ",
                    " x....xxx ",
                    " x...xx   ",
                    " x...x    ",
                    " x...x    ",
                    " x...x    ",
                    " xx..xx   ",
                    "  x...x   ",
                    "  x..xx   ",
                    "  x..x    ",
                    "  xxxx    "])
    zx.map_load_room(combo=[
                    " xxxxx     ",
                    " x...xx    ",
                    " xx...x    ",
                    " xx...x    ",
                    "xx....xx   ",
                    "x......xxx ",
                    "x........xx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x...xx....x",
                    "x....x...xx",
                    "x.....xx.x ",
                    "xxxxxxxxxx "])
    zx.map_load_room(combo=[
                    "         xxx",
                    "        xx.x",
                    "       xx..x",
                    "      xx...x",
                    "     xx....x",
                    "    xx.....x",
                    "    x......x",
                    "   xx......x",
                    "   x...xx..x",
                    "   x..xxxxxx",
                    "  xx..xx    ",
                    "xxx....xxxxx",
                    "x..........x",
                    "xxxxx...xxxx",
                    "    xxxxx   "])
    zx.map_load_room(combo=[
                    "xxxx  ",
                    "x..xx ",
                    "x...xx",
                    "x....x",
                    "x.xxxx",
                    "xxx   "])
    zx.map_load_room(combo=[
                    "    xxx",
                    "   xx.x",
                    "   x..x",
                    "   x..x",
                    "  xx..x",
                    "  x...x",
                    "  x...x",
                    " xx...x",
                    "xx...xx",
                    "x....x ",
                    "x.xxxx ",
                    "xxx    "])
    zx.map_load_room(combo=[
                    "   xxxx   ",
                    "  xx..xxx ",
                    " xx.....xx",
                    " x.......x",
                    "xx..x...xx",
                    "x...x...x ",
                    "xx......x ",
                    " xx.....x ",
                    "  xx...xx ",
                    "   xxxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxx ",
                    "x....x ",
                    "x....xx",
                    "xx....x",
                    " xx...x",
                    "  xx..x",
                    "   xxxx"])
    zx.map_load_room(combo=[
                    " xxx   ",
                    " x.xxx ",
                    "xx...xx",
                    "x.....x",
                    "xx....x",
                    " x..xxx",
                    " xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "x....x",
                    "x...xx",
                    "x.xxx ",
                    "xxx   "])
    zx.map_load_room(combo=[
                    "      xxxxx",
                    "    xxx...x",
                    "    x.....x",
                    "    x....xx",
                    "    xxx...x",
                    "   xx.....x",
                    "  xx......x",
                    "xxx.......x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxx      xx",
                    "x..xx xxxxxx",
                    "x...xxx.xx.x",
                    "x..........x",
                    "x.x........x",
                    "xxx........x",
                    "xx.........x",
                    "x..........x",
                    "x......x...x",
                    "x......xx..x",
                    "x.xx....xxxx",
                    "xxxxxxxxx xx"])
    zx.map_load_room(combo=[
                    "   xxx  xxx ",
                    "xxxx.xxxx.x ",
                    "x.........xx",
                    "x....x.....x",
                    "x....x....xx",
                    "x......xxxx ",
                    "xx....xx    ",
                    "x.....xx    ",
                    "x......xxxxx",
                    "x..........x",
                    "x..........x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx",
                    "x....xx...x",
                    "x.........x",
                    "x.........x",
                    "xx........x",
                    "xx........x",
                    "x.......x.x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxx xxx",
                    "x.....x x.x",
                    "x.....xxxxx",
                    "x......xxxx",
                    "xxxx....xxx",
                    "   xx.....x",
                    "    x.....x",
                    "   xx.....x",
                    "  xx......x",
                    "  x..x....x",
                    "  xxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxx ",
                    "x...x ",
                    "x...xx",
                    "x....x",
                    "x...xx",
                    "x..xx ",
                    "x..x  ",
                    "x..x  ",
                    "x.xx  ",
                    "x.x   ",
                    "xxx   "])
    zx.map_load_room(combo=[
                    "xxxxxx   ",
                    "x....xxxx",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "xx...x..x",
                    " x......x",
                    " xx.....x",
                    "  xxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxx",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x.xx",
                    "xxx "])
    zx.map_load_room(combo=[
                    "   xxx ",
                    " xxx.x ",
                    " x...xx",
                    "xx....x",
                    "x.....x",
                    "x.....x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxx ",
                    " xx.x ",
                    "xx..xx",
                    "x....x",
                    "x....x",
                    "x...xx",
                    "xxxxx "])
    zx.map_load_room(combo=[
                    "   xxxxx xxxxx",
                    "   x...xxx...x",
                    "   xx..xx....x",
                    "    x...xx...x",
                    "   xx..xxxx..x",
                    "  xx...x  x..x",
                    "  x....x  x..x",
                    "  x....xx x..x",
                    "  x.....xxx..x",
                    " xx......x...x",
                    " x..xx.....x.x",
                    "xx.........x.x",
                    "x..........xxx",
                    "x..........x  ",
                    "x........xxx  ",
                    "xxxxxxxxxx    "])
    zx.map_load_room(combo=[
                    "  xxxxxxxxxxxxxx",
                    " xx.......xx...x",
                    "xx....xx..x...xx",
                    "x....xxxx......x",
                    "x...xx  x......x",
                    "xx..x   x.xx...x",
                    "x...x   xxxxxxxx",
                    "x...x           ",
                    "x...x           ",
                    "xx..x           ",
                    "x..xx           ",
                    "x..x            ",
                    "x..xx           ",
                    "x...x           ",
                    "x..xx           ",
                    "xxxx            "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxxx",
                    "x..............x",
                    "x..............x",
                    "x.xxx..........x",
                    "xxx xxx........x",
                    "      xx.......x",
                    "       x...xxxxx",
                    "       x....xx  ",
                    "       x.....xx ",
                    "       x......xx",
                    "       xxx.....x",
                    "         xx....x",
                    "          x....x",
                    "         xx....x",
                    "         x....xx",
                    "         xxxxxx "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx    ",
                    "x........x    ",
                    "x........x    ",
                    "xxx...x..x    ",
                    "  x......x    ",
                    "  x......x    ",
                    "  x......xxx  ",
                    "  x.....x..x  ",
                    "  xxx......x  ",
                    "xxx x......x  ",
                    "x.x x......xxx",
                    "x.xxx.....xx.x",
                    "x..xxxxx.....x",
                    "x.....xx.....x",
                    "x............x",
                    "xxxxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxxxxxxxx   ",
                    " x......x..x   ",
                    " xxx.......x   ",
                    "   xxxxx...x   ",
                    "xxxxxx xxx.x   ",
                    "x....xx xx.xxxx",
                    "x.....xxx..xx.x",
                    "x.xx.......xx.x",
                    "x..........xx.x",
                    "x..........xx.x",
                    "x..xx......xx.x",
                    "x.xxxx.....xx.x",
                    "x.x  x.x...xx.x",
                    "x.x xx.....xx.x",
                    "x.x x...x.....x",
                    "xxx xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "x....x",
                    "x....x",
                    "x.x..x",
                    "x....x",
                    "x..x.x",
                    "x..x.x",
                    "x..xxx",
                    "x..x  ",
                    "x..x  ",
                    "xx.x  ",
                    " xxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx      ",
                    "x....xx..x      ",
                    "x........x      ",
                    "x.....xxxx      ",
                    "x....xx         ",
                    "x...xx          ",
                    "x...x           ",
                    "x...xx          ",
                    "x....xx         ",
                    "x.....xx        ",
                    "x......xxxxx    ",
                    "x.x........xxx  ",
                    "x.xx.........xx ",
                    "x.............xx",
                    "x.......xxx....x",
                    "xxxxxxxxx xxxxxx"])
    zx.map_load_room(combo=[
                    "   xxxxx  ",
                    "xxxx...xx ",
                    "x.......xx",
                    "x........x",
                    "x......x.x",
                    "xx.....x.x",
                    " xx......x",
                    "  x......x",
                    "  x.xxxxxx",
                    "  xxx     "])
    zx.map_load_room(combo=[
                    "xxx   ",
                    "x.xx  ",
                    "x..x  ",
                    "x..xx ",
                    "x...xx",
                    "xxx..x",
                    "  xx.x",
                    "   xxx"])
    zx.map_load_room(combo=[
                    " xxxxx",
                    " x...x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x.x..x",
                    "x....x",
                    "x....x",
                    "xxx..x",
                    "  x..x",
                    "  x..x",
                    "  x..x",
                    "  xxxx"])
    zx.map_load_room(combo=[
                    "   xxxx",
                    " xxx..x",
                    "xx....x",
                    "x.....x",
                    "x.....x",
                    "x.xxxxx",
                    "xxx  xx"])
    zx.map_load_room(combo=[
                    " xxx       ",
                    "xx.xx xxxxx",
                    "x...xxx...x",
                    "x.........x",
                    "xx........x",
                    " x........x",
                    " x........x",
                    " x...x....x",
                    " x........x",
                    " x........x",
                    " xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxx      ",
                    "xxx.x      ",
                    "x...xxxxxx ",
                    "xx...xx..xx",
                    " x........x",
                    " xxx......x",
                    "   xx.....x",
                    "    xx....x",
                    "     x....x",
                    "     xxxx.x",
                    "        xxx"])
    zx.map_load_room(combo=[
                    "xxx    ",
                    "x.x    ",
                    "x.xx   ",
                    "x..xxx ",
                    "x....xx",
                    "x.x...x",
                    "x.....x",
                    "x....xx",
                    "x..xxx ",
                    "xxxx   "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx",
                    "x..xx...x.x",
                    "x..x......x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "x......xxxx",
                    "x.....xx   ",
                    "x.....x    ",
                    "x.....xx   ",
                    "x......xx  ",
                    "x.......x  ",
                    "x.......x  ",
                    "xxxxxxx.x  ",
                    "      xxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx ",
                    "x.........x ",
                    "xx........x ",
                    " x...xx...x ",
                    " x....xx..x ",
                    " xx.......x ",
                    " xx.......x ",
                    " x....x...x ",
                    " x........x ",
                    " x........x ",
                    " x..x.....x ",
                    "xx........xx",
                    "x..........x",
                    "x.........xx",
                    "xxxxxxxx.xx ",
                    "       xxx  "])
    zx.map_load_room(combo=[
                    "xxxxx",
                    "x...x",
                    "xx..x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x...x",
                    "x..xx",
                    "x.xx ",
                    "x..xx",
                    "x...x",
                    "x...x",
                    "xx..x",
                    " xxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x........x",
                    "x........x",
                    "x......xxx",
                    "x.....xx  ",
                    "x.....xx  ",
                    "xxx....x  ",
                    "  xx...x  ",
                    "   x.xxx  ",
                    "   xxx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx xxx",
                    "x...xx...xxx.x",
                    "x............x",
                    "x............x",
                    "x..xx...xx...x",
                    "x..xx......xxx",
                    "x..xx.....xxxx",
                    "x..xx...x.x xx",
                    "x..xx.....x xx",
                    "x..xx....xx xx",
                    "x.xxx....x    ",
                    "xxx x....x    ",
                    "    xx...x    ",
                    "     xxxxx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxx",
                    "x...xx........x",
                    "x....xx.......x",
                    "x........xx...x",
                    "x.......xxxx..x",
                    "xxx....xx  xx.x",
                    "xx....xx    xxx",
                    "x.....x        ",
                    "x.....xx       ",
                    "x......xx      ",
                    "x...x...xx     ",
                    "x........x     ",
                    "x........x     ",
                    "x.......xx     ",
                    "xxxxxxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxx    ",
                    "x....x.....x    ",
                    "x....x.....xx   ",
                    "x.......x...x   ",
                    "x.....x.x...x   ",
                    "x.....x.x.xxx   ",
                    "x.......x..x    ",
                    "x....x..xx.x    ",
                    "x........x.x    ",
                    "x...xx.....x    ",
                    "x..........x    ",
                    "xxx....xx..x    ",
                    "  x...xxxxxx    ",
                    "  x...x         ",
                    "  xx..x         ",
                    "   xxxx         "])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "x..x.x",
                    "xx...x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x.xx.x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxx  ",
                    "x.......x  ",
                    "x......xx  ",
                    "x.x...xx   ",
                    "xxx...xx   ",
                    "x......xx  ",
                    "x.......xx ",
                    "x........x ",
                    "x........xx",
                    "x....x.x..x",
                    "x.........x",
                    "x.........x",
                    "x.....xx..x",
                    "x....xxxxxx",
                    "xxxxxx     "])
    zx.map_load_room(combo=[
                    " xxx",
                    " x.x",
                    "xx.x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "xx.x",
                    " xxx"])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "x.....x",
                    "x....xx",
                    "x...xx ",
                    "x...x  ",
                    "x...x  ",
                    "x...xx ",
                    "x....x ",
                    "x..xxx ",
                    "xxxx   "])
    zx.map_load_room(combo=[
                    "   xxx  ",
                    " xxx.x  ",
                    " x...x  ",
                    " x...x  ",
                    "xx..xxxx",
                    "x...xx.x",
                    "x...x..x",
                    "x......x",
                    "x......x",
                    "xxxx...x",
                    "   xxxxx"])
    zx.map_load_room(combo=[
                    " xxxx     ",
                    " x..xxxxxx",
                    "xx.......x",
                    "x........x",
                    "x........x",
                    "x........x",
                    "xxx...x..x",
                    "  xx.....x",
                    "   xx....x",
                    "    xxx.xx",
                    "      xxx "])
    zx.map_load_room(combo=[
                    "  xxx    ",
                    "xxx.xx   ",
                    "x....xxxx",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "x.......x",
                    "x......xx",
                    "xxxxxxxx "])
    zx.map_load_room(combo=[
                    "  xxx",
                    " xx.x",
                    " x..x",
                    " x..x",
                    " x..x",
                    "xx..x",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "  xxx   ",
                    "  x.xxxx",
                    " xx....x",
                    "xx.....x",
                    "x......x",
                    "x......x",
                    "xxx....x",
                    "  xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x.xx.x",
                    "x....x",
                    "x....x",
                    "xx...x",
                    " xxx.x",
                    "   xxx"])
    zx.map_load_room(combo=[
                    "       xxx  ",
                    "      xx.xx ",
                    "     xx...xx",
                    "    xx.....x",
                    "xxxxx......x",
                    "x..........x",
                    "x........xxx",
                    "x........xxx",
                    "x.x.......xx",
                    "x........xxx",
                    "x.......xx  ",
                    "xxxxxxxxx   "])
    zx.map_load_room(combo=[
                    "xxx  xxx    ",
                    "x.xxxx.xx   ",
                    "x.......xxxx",
                    "x........xxx",
                    "x.xx.......x",
                    "x.xx.......x",
                    "x..........x",
                    "x.....x....x",
                    "x....x.....x",
                    "xxx.......xx",
                    "  x........x",
                    "  xxxxxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxx",
                    "xx...x",
                    "x....x",
                    "xx..xx",
                    " xx.x ",
                    "  xxx "])
    zx.map_load_room(combo=[
                    "   xxxxx    ",
                    "  xx...xx xx",
                    "xxx.....xxxx",
                    "x..........x",
                    "x..........x",
                    "x...xx.....x",
                    "xxxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "   xxxxx   ",
                    " xxx...x   ",
                    "xx....xx   ",
                    "x.....x    ",
                    "x..x..xx   ",
                    "x......xx  ",
                    "x.......xxx",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxx    ",
                    "x.xx..x    ",
                    "x.....xx   ",
                    "x......xxxx",
                    "x.........x",
                    "x.........x",
                    "xx........x",
                    " xx....xxxx",
                    " xx...xx   ",
                    " x....x    ",
                    " xxxxxx    "])
    zx.map_load_room(combo=[
                    "     xxxxx ",
                    "    xx...xx",
                    "    x.....x",
                    "    xx....x",
                    "     x..x.x",
                    "xxx xx....x",
                    "x.xxx.....x",
                    "x........xx",
                    "x......xxx ",
                    "x.....xx   ",
                    "xxxxxxx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx  ",
                    "x........x  ",
                    "xx......xx  ",
                    " xxx....xx  ",
                    "   x.....xxx",
                    "  xx.......x",
                    " xx........x",
                    " x.........x",
                    " xx....xx..x",
                    "  xx...x...x",
                    "  xx......xx",
                    "  x........x",
                    "  x....x...x",
                    " xx....xx..x",
                    " x.........x",
                    " xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxx",
                    "x....x",
                    "xx...x",
                    " xxx.x",
                    "   xxx",
                    "    xx"])
    zx.map_load_room(combo=[
                    "xxxxxxxx",
                    "x......x",
                    "xx.....x",
                    " x.....x",
                    " x.....x",
                    " xx....x",
                    " xx....x",
                    " x.....x",
                    " x.xxxxx",
                    " xxx    "])
    zx.map_load_room(combo=[
                    "      xxxxxxxxx ",
                    "      x.......xx",
                    "      x...x....x",
                    "      x........x",
                    "      xxx...xx.x",
                    "        x..xxxxx",
                    "  xxxx xx..xx   ",
                    " xx..xxx....x   ",
                    "xx.........xx   ",
                    "x..........x    ",
                    "x.x........x    ",
                    "x..........x    ",
                    "x..........x    ",
                    "x.........xx    ",
                    "x........xx     ",
                    "xxxxxxxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx xxxx",
                    "x........xxx..x",
                    "x.............x",
                    "x...........x.x",
                    "x.....x.....x.x",
                    "x..........x..x",
                    "x......xxxx...x",
                    "x..xx..xxx....x",
                    "x..xx..xx.....x",
                    "x..xxxxxx...xxx",
                    "x..x    x.xxx  ",
                    "x..x    x.x    ",
                    "x..x    x.x    ",
                    "x.xx    x.x    ",
                    "xxx     x.x    ",
                    "        xxx    "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxx",
                    "x.xx......x",
                    "x.........x",
                    "x.........x",
                    "x.........x",
                    "xx...xxxx.x",
                    "x...xx  xxx",
                    "x...x    xx",
                    "x...x      ",
                    "x..xx      ",
                    "xxxx       "])
    zx.map_load_room(combo=[
                    "xxxxx",
                    "x...x",
                    "x...x",
                    "x..xx",
                    "xxxx "])
    zx.map_load_room(combo=[
                    " xxxxxxxxx ",
                    " x.......x ",
                    "xx..xx...x ",
                    "x........xx",
                    "x.........x",
                    "x....xx...x",
                    "x...xxxx..x",
                    "x...xxxx.xx",
                    "xx...xx..x ",
                    "x........x ",
                    "x........x ",
                    "x.x...x..x ",
                    "x....xx..x ",
                    "x........x ",
                    "x........x ",
                    "xxxxxxxxxx "])
    zx.map_load_room(combo=[
                    "       xxxx   ",
                    "      xx..xx  ",
                    "     xx....x  ",
                    " xxxxx.....xx ",
                    "xx.......x..xx",
                    "x........x...x",
                    "x............x",
                    "x............x",
                    "xx....x....xxx",
                    " xxx......xxxx",
                    "   xx.....xx  ",
                    "    x......xxx",
                    "    x.....xxxx",
                    "    xxxxxxx xx"])
    zx.map_load_room(combo=[
                    "   xxxx",
                    "   x..x",
                    "  xx..x",
                    "  x...x",
                    "  xx..x",
                    "   xx.x",
                    " xxxx.x",
                    "xx.x..x",
                    "x.....x",
                    "x.....x",
                    "x.x...x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxx      ",
                    "x...xx     ",
                    "x....x     ",
                    "x....xx    ",
                    "xx....xxxx ",
                    "x........xx",
                    "x.........x",
                    "x..x......x",
                    "x.........x",
                    "x....x....x",
                    "xxxxxxxxxxx"])
    zx.map_load_room(combo=[
                    "  xxx ",
                    "  x.xx",
                    "  x..x",
                    " xx..x",
                    " x...x",
                    " xx..x",
                    "  x..x",
                    " xx..x",
                    "xx...x",
                    "x..x.x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    " xxxx",
                    "xx..x",
                    "x...x",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "   xxxx",
                    "   x..x",
                    "  xx..x",
                    "xxx...x",
                    "x.....x",
                    "x.....x",
                    "xxxxxxx"])
    zx.map_load_room(combo=[
                    " xxxxx",
                    " x...x",
                    " x...x",
                    "xx...x",
                    "x....x",
                    "xxxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxx",
                    "x..........x",
                    "xx.........x",
                    " x.........x",
                    " x.........x",
                    " x.........x",
                    " xx.xx.....x",
                    "  xxxxx....x",
                    "      xx...x",
                    "       x..xx",
                    "      xx..xx",
                    "    xxx....x",
                    "   xx......x",
                    "   x.......x",
                    "   x...xxxxx",
                    "   xxxxx    "])
    zx.map_load_room(combo=[
                    " xxxxxxxxx",
                    " x.......x",
                    " xx......x",
                    "xx.......x",
                    "x........x",
                    "x......xxx",
                    "x.....xx  ",
                    "x....xx   ",
                    "xx..xx    ",
                    " xxxx     "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxx",
                    "x....x........x",
                    "x.............x",
                    "x...........x.x",
                    "x..xx.........x",
                    "x.xxxxxxx.....x",
                    "x.x     xx....x",
                    "x.x      xx..xx",
                    "x.x       x...x",
                    "x.x       x...x",
                    "x.x      xx...x",
                    "x.x     xx....x",
                    "x.x     x.....x",
                    "xxx     x....xx",
                    "        xxxxxx "])
    zx.map_load_room(combo=[
                    "xxx           ",
                    "x.x           ",
                    "x.x           ",
                    "x.x           ",
                    "x.xxxxx xxx   ",
                    "x.xx..xxx.xxxx",
                    "x............x",
                    "x............x",
                    "x......x..x..x",
                    "x........x...x",
                    "x............x",
                    "x..xx.......xx",
                    "x.......x...x ",
                    "x...........x ",
                    "xxxxxx......x ",
                    "     xxxxxxxx "])
    zx.map_load_room(combo=[
                    "  xxx",
                    "xxx.x",
                    "x...x",
                    "x...x",
                    "xxxxx"])
    zx.map_load_room(combo=[
                    "xxxxxxxxx   ",
                    "x.......x   ",
                    "x.......x   ",
                    "x.......xx  ",
                    "x........xx ",
                    "x.........xx",
                    "x..........x",
                    "x..........x",
                    "x..x.....xxx",
                    "x....x...x  ",
                    "x........x  ",
                    "xx.......x  ",
                    "xx......xx  ",
                    "x.....xxx   ",
                    "xx...xx     ",
                    " xxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxxxxxxx",
                    "x..xx.........x",
                    "x...x.........x",
                    "x.............x",
                    "x.....x...xxx.x",
                    "x.xx...xxxx xxx",
                    "x..x...x       ",
                    "x......x       ",
                    "x.....xx       ",
                    "x.x...x        ",
                    "x.....x        ",
                    "x..x..xx       ",
                    "x......xx      ",
                    "x.......x      ",
                    "xxxxxxxxx      "])
    zx.map_load_room(combo=[
                    "xxxxxxxxxx",
                    "x.....x..x",
                    "x.xx.....x",
                    "xxxxx....x",
                    "    xx...x",
                    "     x...x",
                    "     x...x",
                    "    xx...x",
                    " xxxx....x",
                    "xx.......x",
                    "x........x",
                    "x.....xx.x",
                    "x....xxxxx",
                    "x....x    ",
                    "xxx..x    ",
                    "  xxxx    "])
    zx.map_load_room(combo=[
                    "xxxx",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "x..x",
                    "xx.x",
                    " xxx"])
    zx.map_load_room(combo=[
                    "   xxx       ",
                    "  xx.xxxxxxxx",
                    " xx...xx....x",
                    "xx..........x",
                    "x.........x.x",
                    "x.xx......xxx",
                    "x....x.....xx",
                    "x....xx.....x",
                    "x....x......x",
                    "x.x.........x",
                    "x...........x",
                    "x..........xx",
                    "xxxxxxxxxxxx "])
    zx.map_load_room(combo=[
                    "   xxx",
                    "  xx.x",
                    "  x..x",
                    " xx..x",
                    "xx...x",
                    "x....x",
                    "x....x",
                    "x....x",
                    "xxx..x",
                    "  xx.x",
                    "   xxx"])
    zx.map_load_room(combo=[
                    "          ",
                    "       xxx",
                    "      xx.x",
                    "  xxxxx..x",
                    " xx......x",
                    "xx.......x",
                    "x........x",
                    "x........x",
                    "xx.xxxxxxx",
                    " xxx      "])
    zx.map_load_room(combo=[
                    " xxxxx",
                    " x...x",
                    "xx..xx",
                    "x...x ",
                    "x..xx ",
                    "x..x  ",
                    "xxxx  "])
    zx.map_load_room(combo=[
                    "xxxxxxx",
                    "x.....x",
                    "x.....x",
                    "xx....x",
                    " xxx..x",
                    "   xx.x",
                    "    xxx"])
map_data_init()
