import my

my.map_load_skill_tree(
    skill_data=[
        "d1", "skill_devoted_thrust1",
        "d2", "skill_devoted_thrust2",
        "d3", "skill_devoted_thrust3",
        "d4", "skill_devoted_thrust4",
        "d5", "skill_devoted_thrust5",
        "g1", "skill_gold_to_health1",
        "g2", "skill_gold_to_health2",
        "g3", "skill_gold_to_health3",
        "g4", "skill_gold_to_health4",
        "g5", "skill_gold_to_health5",
        "h1", "skill_healing1",
        "h2", "skill_healing2",
        "h3", "skill_healing3",
        "h4", "skill_healing4",
        "h5", "skill_healing5",
        "a1", "skill_double_strike1",
        "a2", "skill_double_strike2",
        "a3", "skill_double_strike3",
        "a4", "skill_double_strike4",
        "a5", "skill_double_strike5",
        "r1", "skill_artful_dodging1",
        "r2", "skill_artful_dodging2",
        "r3", "skill_artful_dodging3",
        "r4", "skill_artful_dodging4",
        "r5", "skill_artful_dodging5",
        "R1", "skill_primal_rage1",
        "R2", "skill_primal_rage2",
        "R3", "skill_primal_rage3",
        "R4", "skill_primal_rage4",
        "R5", "skill_primal_rage5",
        "[]", "",
    ],
    tree_data=[
        "a1->a2->a3->a4->a5  g5<-g4<-g3<-g2<-g1  ",
        "            ^           ^   v           ",
        "d1->d2->d3->d4->d5  h5<-h4<-h3<-h2<-h1  ",
        "        ^                               ",
        "        r4->r5                          ",
        "        ^                               ",
        "r1->r2->r3                              ",
        "        ^                               ",
        "R1->R1->R3->R4->R5                      ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ],
)
