import my

my.map_load_skill_tree(
    skill_data=[
        "d1", "skill_devoted_thrust1",
        "d2", "skill_devoted_thrust2",
        "d3", "skill_devoted_thrust3",
        "d4", "skill_devoted_thrust4",
        "d5", "skill_devoted_thrust5",
        "g1", "skill_gold_to_health1",
        "g2", "skill_gold_to_health2",
        "g3", "skill_gold_to_health3",
        "g4", "skill_gold_to_health4",
        "g5", "skill_gold_to_health5",
        "a1", "skill_secondary_attack1",
        "a2", "skill_secondary_attack2",
        "a3", "skill_secondary_attack3",
        "a4", "skill_secondary_attack4",
        "a5", "skill_secondary_attack5",
        "[]", "",
    ],
    tree_data=[
        "d1->d2->d3->d4->d5  g5<-g4<-g3<-g2<-g1  ",
        "                                        ",
        "a1->a2->a3->a4->a5                      ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ],
)
