import my

my.sound_load(volume=0.5, file="data/sounds/creatures/23733__tim-kahn__squeakyrat.wav", name="squeaky_toy",)
my.sound_load(volume=0.5, file="data/sounds/creatures/76962__michel88__deaths.wav", name="monst_death1",)
my.sound_load(volume=0.5, file="data/sounds/creatures/bones1.wav", name="bones1")
my.sound_load(volume=0.5, file="data/sounds/creatures/bones2.wav", name="bones2")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl10.wav", name="growl10")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl1.wav", name="growl1")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl2.wav", name="growl2")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl3.wav", name="growl3")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl4.wav", name="growl4")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl5.wav", name="growl5")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl6.wav", name="growl6")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl7.wav", name="growl7")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl8.wav", name="growl8")
my.sound_load(volume=0.5, file="data/sounds/creatures/growl9.wav", name="growl9")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss10.wav", name="hiss10")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss1.wav", name="hiss1")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss2.wav", name="hiss2")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss3.wav", name="hiss3")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss4.wav", name="hiss4")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss5.wav", name="hiss5")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss6.wav", name="hiss6")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss7.wav", name="hiss7")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss8.wav", name="hiss8")
my.sound_load(volume=0.5, file="data/sounds/creatures/hiss9.wav", name="hiss9")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime1.wav", name="slime1")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime2.wav", name="slime2")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime3.wav", name="slime3")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime4.wav", name="slime4")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime5.wav", name="slime5")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime6.wav", name="slime6")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime7.wav", name="slime7")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime8.wav", name="slime8")
my.sound_load(volume=0.5, file="data/sounds/creatures/slime9.wav", name="slime9")
my.sound_load(volume=0.5, file="data/sounds/impacts/257709__vmgraw__grunt-2.wav", name="player_hit5",)
my.sound_load(volume=0.5, file="data/sounds/impacts/268227__xxchr0nosxx__swing.wav", name="sword_swing2",)
my.sound_load(volume=0.5, file="data/sounds/impacts/404109__deathscyp__dmg-1.wav", name="player_hit2",)
my.sound_load(volume=0.5, file="data/sounds/impacts/434462__dersuperanton__getting-hit-hugh.wav", name="player_hit1",)
my.sound_load(volume=0.5, file="data/sounds/impacts/437650__dersuperanton__getting-hit-damage-scream.wav", name="player_hit4",)
my.sound_load(volume=0.5, file="data/sounds/impacts/437653__dersuperanton__moan-male-beat-punch.wav", name="player_punch")
my.sound_load(volume=0.5, file="data/sounds/impacts/442769__qubodup__sword-hit.wav", name="sword_impact1",)
my.sound_load(volume=0.5, file="data/sounds/impacts/443293__deathscyp__wood-break.wav", name="door_break",)
my.sound_load(volume=0.5, file="data/sounds/impacts/446016__slavicmagic__wpn-1-generic.wav", name="sword_impact2",)
my.sound_load(volume=0.5, file="data/sounds/impacts/446016__slavicmagic__wpn-1-generic.wav", name="sword_impact3",)
my.sound_load(volume=0.5, file="data/sounds/impacts/446016__slavicmagic__wpn-1-generic.wav", name="sword_impact4",)
my.sound_load(volume=0.5, file="data/sounds/impacts/554153__danielvj__door-open.wav", name="door_open",)
my.sound_load(volume=0.5, file="data/sounds/impacts/578808__nomiqbomi__fall-3.wav", name="fall",)
my.sound_load(volume=0.5, file="data/sounds/impacts/59992__qubodup__swosh-sword-swing.wav", name="sword_swing1",)
my.sound_load(volume=0.5, file="data/sounds/impacts/82388__robinhood76__01308_man_hit_9.wav", name="player_hit3",)
my.sound_load(volume=0.5, file="data/sounds/impacts/door_hit1.wav", name="door_hit1")
my.sound_load(volume=0.5, file="data/sounds/impacts/door_hit2.wav", name="door_hit2")
my.sound_load(volume=0.5, file="data/sounds/interface/181002__ueffects__s-key.wav", name="keypress",)
my.sound_load(volume=0.5, file="data/sounds/interface/click2.wav", name="click")
my.sound_load(volume=0.5, file="data/sounds/misc/drop.wav", name="drop")
my.sound_load(volume=1.0, file="data/sounds/abilities/lightning_a.wav", name="lightning_a")
my.sound_load(volume=1.0, file="data/sounds/abilities/lightning_b.wav", name="lightning_b")
my.sound_load(volume=1.0, file="data/sounds/abilities/teleport.wav", name="teleport")
my.sound_load(volume=1.0, file="data/sounds/creatures/148975__adam_n__squelch_1.wav", name="squelch",)
my.sound_load(volume=1.0, file="data/sounds/creatures/188384__wubitog__slime-attack-or-movement.wav", name="slime_attack",)
my.sound_load(volume=1.0, file="data/sounds/creatures/249686__cylon8472__cthulhu-growl.wav", name="monster_roar_epic",)
my.sound_load(volume=1.0, file="data/sounds/creatures/353250__zuzek06__slimejump.wav", name="slime_jump",)
my.sound_load(volume=1.0, file="data/sounds/creatures/487513__nicknamelarry__monster-roar.wav", name="monster_roar",)
my.sound_load(volume=1.0, file="data/sounds/creatures/56304__syna-max__monster-death-scream.wav", name="monst_death_epic",)
my.sound_load(volume=1.0, file="data/sounds/impacts/507466__danjocross__clean-fast-swoosh.wav", name="sword_swing3",)
my.sound_load(volume=1.0, file="data/sounds/impacts/explosion_a.wav", name="explosion_a")
my.sound_load(volume=1.0, file="data/sounds/impacts/explosion_b.wav", name="explosion_b")
my.sound_load(volume=1.0, file="data/sounds/impacts/explosion_c.wav", name="explosion_c")
my.sound_load(volume=1.0, file="data/sounds/impacts/explosion_d.wav", name="explosion_d")
my.sound_load(volume=1.0, file="data/sounds/impacts/explosion_e.wav", name="explosion_e")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash1.wav", name="splash1")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash2.wav", name="splash2")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash3.wav", name="splash3")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash4.wav", name="splash4")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash5.wav", name="splash5")
my.sound_load(volume=1.0, file="data/sounds/impacts/splash6.wav", name="splash6")
my.sound_load(volume=1.0, file="data/sounds/interface/coin.wav", name="coin")
my.sound_load(volume=1.0, file="data/sounds/misc/220173__gameaudio__spacey-1up-power-up.wav", name="powerup")
my.sound_load(volume=1.0, file="data/sounds/interface/1up_a.wav", name="potion")
my.sound_load(volume=1.0, file="data/sounds/misc/511385__mrthenoronha__power-up-8-bit.wav", name="skillup")
my.sound_load(volume=1.0, file="data/sounds/misc/512216__herkules92__coins.wav", name="gold")
my.sound_load(volume=1.0, file="data/sounds/misc/56264__q-k__sword-sheath.wav", name="sword_equip")
my.sound_load(volume=1.0, file="data/sounds/misc/630018__flem0527__singular-coin-dropping.wav", name="coindrop")
my.sound_load(volume=1.0, file="data/sounds/misc/clack.wav", name="bonk")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps1.wav", name="footsteps1")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps2.wav", name="footsteps2")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps3.wav", name="footsteps3")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps4.wav", name="footsteps4")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps5.wav", name="footsteps5")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps6.wav", name="footsteps6")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps7.wav", name="footsteps7")
my.sound_load(volume=1.0, file="data/sounds/misc/footsteps8.wav", name="footsteps8")
# my.sound_load(volume=1.0, file="data/sounds/misc/clack.wav",               name="clack")
# my.sound_load(volume=1.0, file="data/sounds/misc/step.wav",                name="step")
# my.sound_load(volume=1.0, file="data/sounds/misc/bay_door_close.wav",      name="bay_door_close")
# my.sound_load(volume=1.0, file="data/sounds/misc/fall.wav",                name="fall")
# my.sound_load(volume=1.0, file="data/sounds/misc/close_shut.wav",          name="close_shut")
# my.sound_load(volume=1.0, file="data/sounds/misc/swerve.wav",              name="swerve")
# my.sound_load(volume=1.0, file="data/sounds/misc/mushroom.wav",            name="mushroom")
# my.sound_load(volume=1.0, file="data/sounds/misc/rebound.wav",             name="rebound")
# my.sound_load(volume=1.0, file="data/sounds/misc/collect_a.wav",           name="collect_a")
# my.sound_load(volume=1.0, file="data/sounds/misc/bay_door_open.wav",       name="bay_door_open")
# my.sound_load(volume=1.0, file="data/sounds/misc/collect_b.wav",           name="collect_b")
# my.sound_load(volume=1.0, file="data/sounds/misc/shriek.wav",              name="shriek")
# my.sound_load(volume=1.0, file="data/sounds/misc/whistle.wav",             name="whistle")
# my.sound_load(volume=1.0, file="data/sounds/misc/zong.wav",                name="zong")
# my.sound_load(volume=1.0, file="data/sounds/misc/open.wav",                name="open")
# my.sound_load(volume=1.0, file="data/sounds/misc/scatter.wav",             name="scatter")
# my.sound_load(volume=1.0, file="data/sounds/misc/drip.wav",                name="drip")
# my.sound_load(volume=1.0, file="data/sounds/misc/unlock.wav",              name="unlock")
# my.sound_load(volume=1.0, file="data/sounds/misc/chime.wav",               name="chime")
# my.sound_load(volume=1.0, file="data/sounds/misc/transistor.wav",          name="transistor")
# my.sound_load(volume=1.0, file="data/sounds/misc/close.wav",               name="close")
# my.sound_load(volume=1.0, file="data/sounds/misc/resurrect.wav",           name="resurrect")
# my.sound_load(volume=1.0, file="data/sounds/misc/wave.wav",                name="wave")
# my.sound_load(volume=1.0, file="data/sounds/misc/wiggle_b.wav",            name="wiggle_b")
# my.sound_load(volume=1.0, file="data/sounds/misc/blurb.wav",               name="blurb")
# my.sound_load(volume=1.0, file="data/sounds/misc/wiggle_a.wav",            name="wiggle_a")
# my.sound_load(volume=1.0, file="data/sounds/misc/scramble.wav",            name="scramble")
# my.sound_load(volume=1.0, file="data/sounds/misc/twing.wav",               name="twing")
# my.sound_load(volume=1.0, file="data/sounds/misc/shut.wav",                name="shut")
# my.sound_load(volume=1.0, file="data/sounds/misc/rubberband.wav",          name="rubberband")
# my.sound_load(volume=1.0, file="data/sounds/misc/ping.wav",                name="ping")
# my.sound_load(volume=1.0, file="data/sounds/interface/select_b.wav",       name="select_b")
# my.sound_load(volume=1.0, file="data/sounds/interface/select_a.wav",       name="select_a")
# my.sound_load(volume=1.0, file="data/sounds/interface/end_turn.wav",       name="end_turn")
# my.sound_load(volume=1.0, file="data/sounds/interface/bonus.wav",          name="bonus")
# my.sound_load(volume=1.0, file="data/sounds/interface/paper.wav",          name="paper")
# my.sound_load(volume=1.0, file="data/sounds/interface/lose_a.wav",         name="lose_a")
# my.sound_load(volume=1.0, file="data/sounds/interface/lose_b.wav",         name="lose_b")
# my.sound_load(volume=1.0, file="data/sounds/interface/new_turn.wav",       name="new_turn")
# my.sound_load(volume=1.0, file="data/sounds/interface/gold.wav",           name="gold")
# my.sound_load(volume=1.0, file="data/sounds/interface/1up_a.wav",          name="1up_a")
# my.sound_load(volume=1.0, file="data/sounds/interface/blip.wav",           name="blip")
# my.sound_load(volume=1.0, file="data/sounds/interface/1up_b.wav",          name="1up_b")
# my.sound_load(volume=1.0, file="data/sounds/interface/error.wav",          name="error")
# my.sound_load(volume=1.0, file="data/sounds/interface/score.wav",          name="score")
# my.sound_load(volume=1.0, file="data/sounds/interface/dong.wav",           name="dong")
# my.sound_load(volume=1.0, file="data/sounds/interface/level_up.wav",       name="level_up")
# my.sound_load(volume=1.0, file="data/sounds/interface/ding.wav",           name="ding")
# my.sound_load(volume=1.0, file="data/sounds/impacts/boom_a.wav",           name="boom_a")
# my.sound_load(volume=1.0, file="data/sounds/impacts/boom_b.wav",           name="boom_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/impact_b.wav",         name="impact_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/impact_a.wav",         name="impact_a")
# my.sound_load(volume=1.0, file="data/sounds/impacts/explode_a.wav",        name="explode_a")
# my.sound_load(volume=1.0, file="data/sounds/impacts/pit_trap_fall.wav",    name="pit_trap_fall")
# my.sound_load(volume=1.0, file="data/sounds/impacts/sear.wav",             name="sear")
# my.sound_load(volume=1.0, file="data/sounds/impacts/explode_b.wav",        name="explode_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/explode_c.wav",        name="explode_c")
# my.sound_load(volume=1.0, file="data/sounds/impacts/magic_crumble.wav",    name="magic_crumble")
# my.sound_load(volume=1.0, file="data/sounds/impacts/area_effect_a.wav",    name="area_effect_a")
# my.sound_load(volume=1.0, file="data/sounds/impacts/area_effect_b.wav",    name="area_effect_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/pit_trap_dmg.wav",  name="pit_trap_dmg")
# my.sound_load(volume=1.0, file="data/sounds/impacts/spike_trap_a.wav",     name="spike_trap_a")
# my.sound_load(volume=1.0, file="data/sounds/impacts/hit.wav",              name="hit")
# my.sound_load(volume=1.0, file="data/sounds/impacts/spike_trap_b.wav",     name="spike_trap_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/magic_dust_b.wav",     name="magic_dust_b")
# my.sound_load(volume=1.0, file="data/sounds/impacts/magic_dust_a.wav",     name="magic_dust_a")
# my.sound_load(volume=1.0, file="data/sounds/status/curse.wav",             name="curse")
# my.sound_load(volume=1.0, file="data/sounds/status/freeze.wav",            name="freeze")
# my.sound_load(volume=1.0, file="data/sounds/status/mutation.wav",          name="mutation")
# my.sound_load(volume=1.0, file="data/sounds/status/confuse.wav",           name="confuse")
# my.sound_load(volume=1.0, file="data/sounds/status/disease.wav",           name="disease")
# my.sound_load(volume=1.0, file="data/sounds/status/burn.wav",              name="burn")
# my.sound_load(volume=1.0, file="data/sounds/status/charm.wav",             name="charm")
# my.sound_load(volume=1.0, file="data/sounds/status/poison.wav",            name="poison")
# my.sound_load(volume=1.0, file="data/sounds/abilities/jump_a.wav",         name="jump_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/disarm_single.wav",  name="disarm_single")
# my.sound_load(volume=1.0, file="data/sounds/abilities/jump_b.wav",         name="jump_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/disarm_multi_b.wav", name="disarm_multi_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/heal_b.wav",         name="heal_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/laser_a.wav",        name="laser_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/disarm_success.wav", name="disarm_success")
# my.sound_load(volume=1.0, file="data/sounds/abilities/sorcery.wav",        name="sorcery")
# my.sound_load(volume=1.0, file="data/sounds/abilities/disarm_multi_a.wav", name="disarm_multi_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/heal_a.wav",         name="heal_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/laser_b.wav",        name="laser_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/blaster.wav",        name="blaster")
# my.sound_load(volume=1.0, file="data/sounds/abilities/woosh_a.wav",        name="woosh_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/bazooka.wav",        name="bazooka")
# my.sound_load(volume=1.0, file="data/sounds/abilities/swing.wav",          name="swing")
# my.sound_load(volume=1.0, file="data/sounds/abilities/fire_a.wav",         name="fire_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/woosh_b.wav",        name="woosh_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/fire_b.wav",         name="fire_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/fire_c.wav",         name="fire_c")
# my.sound_load(volume=1.0, file="data/sounds/abilities/special_b.wav",      name="special_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/spell_a.wav",        name="spell_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/special_a.wav",      name="special_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/spell_b.wav",        name="spell_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/shoot_b.wav",        name="shoot_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/shoot_a.wav",        name="shoot_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/reload.wav",         name="reload")
# my.sound_load(volume=1.0, file="data/sounds/abilities/attack_a.wav",       name="attack_a")
# my.sound_load(volume=1.0, file="data/sounds/abilities/attack_b.wav",       name="attack_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/shotgun.wav",        name="shotgun")
# my.sound_load(volume=1.0, file="data/sounds/abilities/summon.wav",         name="summon")
# my.sound_load(volume=1.0, file="data/sounds/abilities/lightning_b.wav",    name="lightning_b")
# my.sound_load(volume=1.0, file="data/sounds/abilities/telepathy.wav",      name="telepathy")
# my.sound_load(volume=1.0, file="data/sounds/creatures/bird.wav",           name="bird")
# my.sound_load(volume=1.0, file="data/sounds/creatures/wings.wav",          name="wings")
# my.sound_load(volume=1.0, file="data/sounds/creatures/skeleton.wav",       name="skeleton")
# my.sound_load(volume=1.0, file="data/sounds/creatures/beetle.wav",         name="beetle")
# my.sound_load(volume=1.0, file="data/sounds/creatures/mystical.wav",       name="mystical")
# my.sound_load(volume=1.0, file="data/sounds/creatures/claw.wav",           name="claw")
# my.sound_load(volume=1.0, file="data/sounds/creatures/jelly.wav",          name="jelly")
# my.sound_load(volume=1.0, file="data/sounds/creatures/snake.wav",          name="snake")
# my.sound_load(volume=1.0, file="data/sounds/creatures/mouse.wav",          name="mouse")
# my.sound_load(volume=1.0, file="data/sounds/creatures/swarm.wav",          name="swarm")
# my.sound_load(volume=1.0, file="data/sounds/creatures/frog.wav",           name="frog")
