import my

my.map_load_spell_tree(
    spell_data=[
        "fd", "spell_summon_food",
        "rk", "spell_summon_rock",
        "mm", "spell_magic_missile",
        "sA", "spell_summon_monst1",
        "sB", "spell_summon_monst2",
        "sC", "spell_summon_monst3",
        "sD", "spell_summon_monst4",
        "sE", "spell_summon_monst5",
        "dA", "spell_dominate_monst1",
        "dB", "spell_dominate_monst2",
        "dC", "spell_dominate_monst3",
        "dD", "spell_dominate_monst4",
        "dE", "spell_dominate_monst5",
    ])

my.map_load_spell_tree(
    tree_name="combat",
    tree_data=[
        "mm                                      ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ],
)

my.map_load_spell_tree(
    tree_name="summoning",
    tree_data=[
        "fd                                      ",
        "                                        ",
        "rk                                      ",
        "                                        ",
        "sA->sB->sC->sD->sE                      ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ],
)

my.map_load_spell_tree(
    tree_name="psi",
    tree_data=[
        "dA->dB->dC->dD->dE                      ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ],
)
