//
// Copyright Neil McGill, goblinhack@gmail.com
//

#pragma once
#ifndef _MY_THING_TEMPLATE_H
#define _MY_THING_TEMPLATE_H

#include "my_dice.hpp"
#include "my_fwd.hpp"
#include "my_size.hpp"
#include "my_thing_defs.hpp"
#include "my_tile.hpp"
#include <map>
#include <set>
#include <vector>

using Tpidmap   = std::vector< class Tp   *>;
using Tpnamemap = std::map< std::string, class Tp * >;
using Allies    = std::set< class Tp    *>;

enum {
  THING_RARITY_COMMON,
  THING_RARITY_UNCOMMON,
  THING_RARITY_RARE,
  THING_RARITY_VERY_RARE,
  THING_RARITY_UNIQUE,
};

class Tp
{
public:
  uint8_t z_depth {};
  uint8_t z_prio {};

  TpId id {};

  Allies allies;

  Tilemap bl1_tiles;
  Tilemap bl2_tiles;
  Tilemap bot1_tiles;
  Tilemap bot2_tiles;
  Tilemap bot3_tiles;
  Tilemap br1_tiles;
  Tilemap br2_tiles;
  Tilemap left1_tiles;
  Tilemap left2_tiles;
  Tilemap right1_tiles;
  Tilemap right2_tiles;
  Tilemap tiles;
  Tilemap tl1_tiles;
  Tilemap tl2_tiles;
  Tilemap top1_tiles;
  Tilemap top2_tiles;
  Tilemap tr1_tiles;
  Tilemap tr2_tiles;

private:
  Dice _damage_acid_dice {};
  Dice _damage_cold_dice {};
  Dice _damage_crush_dice {};
  Dice _damage_digest_dice {};
  Dice _damage_draining_dice {};
  Dice _damage_energy_dice {};
  Dice _damage_fire_dice {};
  Dice _damage_future1_dice {};
  Dice _damage_bite_dice {};
  Dice _damage_claw_dice {};
  Dice _damage_lightning_dice {};
  Dice _damage_melee_dice {};
  Dice _damage_nat_att_dice {};
  Dice _damage_necrosis_dice {};
  Dice _damage_poison_dice {};
  Dice _damage_water_dice {};
  Dice _gold_value_dice {};
  Dice _health_initial_dice {};
  Dice _lifespan_dice {};
  Dice _nutrition_dice {};
  Dice _on_idle_tick_freq_dice {};
  Dice _resurrect_dice {};
  Dice _spawn_group_size_dice {};

  fsize _sz;

  std::vector< int > _damage_acid_chance_d1000 {};
  std::vector< int > _damage_water_chance_d1000 {};
  std::vector< int > _damage_cold_chance_d1000 {};
  std::vector< int > _damage_crush_chance_d1000 {};
  std::vector< int > _damage_digest_chance_d1000 {};
  std::vector< int > _damage_energy_chance_d1000 {};
  std::vector< int > _damage_fire_chance_d1000 {};
  std::vector< int > _damage_future1_chance_d1000 {};
  std::vector< int > _damage_bite_chance_d1000 {};
  std::vector< int > _damage_claw_chance_d1000 {};
  std::vector< int > _damage_lightning_chance_d1000 {};
  std::vector< int > _damage_melee_chance_d1000 {};
  std::vector< int > _damage_nat_att_chance_d1000 {};
  std::vector< int > _damage_necrosis_chance_d1000 {};
  std::vector< int > _damage_draining_chance_d1000 {};
  std::vector< int > _damage_poison_chance_d1000 {};

  int _aggression_pct {};
  int _ai_detect_secret_doors {};
  int _ai_obstacle {};
  int _ai_resent_count {};
  int _ai_shove_chance_d1000 {};
  int _ai_wanderer {};
  int _appearing_chance_d1000 {};
  int _attack_eater {};
  int _attack_engulf_chance_d1000 {};
  int _attack_humanoid {};
  int _attack_living {};
  int _attack_lunge {};
  int _attack_meat {};
  int _attack_no_msg {};
  int _attacks_per_round {};
  int _attack_undead {};
  int _blast_max_radius {};
  int _blast_min_radius {};
  int _blit_bot_off {};
  int _blit_left_off {};
  int _blit_off {};
  int _blit_right_off {};
  int _blit_top_off {};
  int _capacity_height {};
  int _capacity_width {};
  int _charge_count {};
  int _collateral_damage_pct {};
  int _collision_attack {};
  int _collision_check {};
  int _collision_hit_180 {};
  int _collision_hit_360 {};
  int _collision_hit_adj {};
  int _collision_hit_priority {};
  int _collision_hit_two_tiles_ahead {};
  int _crit_chance_d10000 {};
  int _damaged_chance_d10000 {};
  int _damage_received_doubled_from_acid {};
  int _damage_received_doubled_from_cold {};
  int _damage_received_doubled_from_fire {};
  int _damage_received_doubled_from_necrosis {};
  int _damage_received_doubled_from_poison {};
  int _damage_received_doubled_from_water {};
  int _distance_avoid {};
  int _distance_leader_max {};
  int _distance_minion_vision_shared {};
  int _distance_mob_max {};
  int _distance_recruitment_max {};
  int _distance_throw {};
  int _distance_vision {};
  int _is_eater_of_amulets {};
  int _is_eater_of_armor {};
  int _is_eater_of_boots {};
  int _is_eater_of_cloaks {};
  int _is_eater_of_gauntlets {};
  int _is_eater_of_helmets {};
  int _is_eater_of_rings {};
  int _is_eater_of_shields {};
  int _is_eater_of_staffs {};
  int _is_eater_of_wands {};
  int _is_eater_of_weapons {};
  int _enchant_level {};
  int _enchant_max {};
  int _environ_avoids_acid {};
  int _environ_avoids_cold {};
  int _environ_avoids_fire {};
  int _environ_avoids_necrosis {};
  int _environ_avoids_poison {};
  int _environ_avoids_water {};
  int _gfx_ascii_animated {};
  int _gfx_ascii_bg_color_spread_alpha {};
  int _gfx_ascii_bg_color_spread_blue {};
  int _gfx_ascii_bg_color_spread_green {};
  int _gfx_ascii_bg_color_spread_hue {};
  int _gfx_ascii_bg_color_spread_red {};
  int _gfx_ascii_color_is_animated {};
  int _gfx_ascii_fade_with_dist {};
  int _gfx_ascii_fg_color_spread_alpha {};
  int _gfx_ascii_fg_color_spread_blue {};
  int _gfx_ascii_fg_color_spread_green {};
  int _gfx_ascii_fg_color_spread_hue {};
  int _gfx_ascii_fg_color_spread_red {};
  int _gfx_ascii_shown {};
  int _gfx_ascii_shown_as_gray_in_shadow {};
  int _gfx_ascii_shown_in_bg {};
  int _gfx_glows {};
  int _gfx_on_fire_anim {};
  int _gfx_oversized_and_on_floor {};
  int _gfx_pixelart_animated {};
  int _gfx_pixelart_animated_can_hflip {};
  int _gfx_pixelart_animated_can_vflip {};
  int _gfx_pixelart_animated_no_dir {};
  int _gfx_pixelart_anim_synced_with_owner {};
  int _gfx_pixelart_attack_anim {};
  int _gfx_pixelart_bounce_always {};
  int _gfx_pixelart_bounce_on_move {};
  int _gfx_pixelart_equip_carry_anim {};
  int _gfx_pixelart_flickers {};
  int _gfx_pixelart_health_bar_autohide {};
  int _gfx_pixelart_health_bar_only_when_awake {};
  int _gfx_pixelart_health_bar_shown {};
  int _gfx_pixelart_shadow_long {};
  int _gfx_pixelart_shadow_short {};
  int _gfx_pixelart_shadow_solid {};
  int _gfx_pixelart_shadow_very_short {};
  int _gfx_pixelart_show_asleep_anim {};
  int _gfx_pixelart_shown_in_bg {};
  int _gfx_pixelart_show_outlined {};
  int _gfx_pixelart_wobbles_when_hit {};
  int _gfx_water {};
  int _has_temperature {};
  int _hunger_clock_tick_freq {};
  int _hunger_is_hunger_level_hungry_at_pct {};
  int _hunger_is_insatiable {};
  int _hunger_is_hunger_level_starving_at_pct {};
  int _internal_has_dir_anim {};
  int _internal_has_hp_anim {};
  int _is_able_to_attack_mobs {};
  int _is_able_to_attack_owner {};
  int _is_able_to_break_down_doors {};
  int _is_able_to_break_out_of_ice {};
  int _is_able_to_break_out_of_webs {};
  int _is_able_to_burn {};
  int _is_able_to_change_levels {};
  int _is_able_to_collect_keys {};
  int _is_able_to_enchant_items {};
  int _is_able_to_fall {};
  int _is_able_to_fire_at {};
  int _is_able_to_follow {};
  int _is_able_to_freeze {};
  int _is_able_to_jump {};
  int _is_able_to_jump_attack {};
  int _is_able_to_jump_attack_chance_d1000 {};
  int _is_able_to_jump_escape {};
  int _is_able_to_jump_on_low_hp_chance_d1000 {};
  int _is_able_to_jump_onto {};
  int _is_able_to_jump_onto_chance_d1000 {};
  int _is_able_to_jump_randomly_chance_d1000 {};
  int _is_able_to_jump_without_tiring {};
  int _is_able_to_learn_skills {};
  int _is_able_to_move_diagonally {};
  int _is_able_to_open_doors {};
  int _is_able_to_see_in_the_dark {};
  int _is_able_to_see_through_doors {};
  int _is_able_to_shove {};
  int _is_able_to_sleep {};
  int _is_able_to_swim {};
  int _is_able_to_teleport_attack {};
  int _is_able_to_teleport_attack_chance_d1000 {};
  int _is_able_to_teleport_escape {};
  int _is_able_to_teleport_without_tiring {};
  int _is_able_to_tire {};
  int _is_able_to_use_amulet {};
  int _is_able_to_use_armor {};
  int _is_able_to_use_boots {};
  int _is_able_to_use_cloak {};
  int _is_able_to_use_gauntlet {};
  int _is_able_to_use_helmet {};
  int _is_able_to_use_rings {};
  int _is_able_to_use_shield {};
  int _is_able_to_use_wands_or_staffs {};
  int _is_able_to_use_weapons {};
  int _is_able_to_walk_through_walls {};
  int _is_acid {};
  int _is_air_breathher {};
  int _is_alive_on_end_of_anim {};
  int _is_always_hit {};
  int _is_amulet {};
  int _is_aquatic {};
  int _is_armor {};
  int _is_ascend_dungeon {};
  int _is_ascend_sewer {};
  int _is_asleep_initially {};
  int _is_attackable_by_monst {};
  int _is_attackable_by_player {};
  int _is_auto_collect_item {};
  int _is_auto_equipped {};
  int _is_auto_throw {};
  int _is_auto_use {};
  int _is_bag {};
  int _is_bag_item {};
  int _is_bag_item_container {};
  int _is_bag_item_not_stackable {};
  int _is_barrel {};
  int _is_basalt {};
  int _is_biome_dungeon {};
  int _is_biome_swamp {};
  int _is_bleeder {};
  int _is_block_of_ice {};
  int _is_bones {};
  int _is_boots {};
  int _is_brazier {};
  int _is_bridge {};
  int _is_brittle {};
  int _is_buff {};
  int _is_carnivorous_plant {};
  int _is_carrier_of_treasure_class_a {};
  int _is_carrier_of_treasure_class_b {};
  int _is_carrier_of_treasure_class_c {};
  int _is_carrier_of_weapon_class_a {};
  int _is_carrier_of_weapon_class_b {};
  int _is_carrier_of_weapon_class_c {};
  int _is_chasm {};
  int _is_cloak {};
  int _is_cold {};
  int _is_collectable {};
  int _is_collected_as_gold {};
  int _is_collected_as_keys {};
  int _is_combustible {};
  int _is_corpse_on_death {};
  int _is_corpse_with_bones {};
  int _is_corridor {};
  int _is_cowardly {};
  int _is_critical_to_level {};
  int _is_crushable {};
  int _is_crystal {};
  int _is_cursor {};
  int _is_cursor_can_hover_over {};
  int _is_cursor_can_hover_over_x2_click {};
  int _is_cursor_path {};
  int _is_cursor_path_blocker {};
  int _is_cursor_path_hazard {};
  int _is_dagger {};
  int _is_dead_on_end_of_anim {};
  int _is_dead_on_falling {};
  int _is_dead_on_shove {};
  int _is_debuff {};
  int _is_debug_path {};
  int _is_debug_type {};
  int _is_deep_water {};
  int _is_descend_dungeon {};
  int _is_descend_sewer {};
  int _is_described_when_hovering_over {};
  int _is_destroyed_on_hit_or_miss {};
  int _is_destroyed_on_hitting {};
  int _is_dirt {};
  int _is_door {};
  int _is_droppable {};
  int _is_dry_grass {};
  int _is_dry_grass_trampled {};
  int _is_eater_of_food {};
  int _is_eater_of_green_blood {};
  int _is_eater_of_jelly {};
  int _is_eater_of_magical_items {};
  int _is_eater_of_meat {};
  int _is_eater_of_potions {};
  int _is_eater_of_red_blood {};
  int _is_eater_of_treasure {};
  int _is_enchantable {};
  int _is_enchantstone {};
  int _is_engulfer {};
  int _is_ethereal {};
  int _is_ethereal_mob {};
  int _is_exit_finder {};
  int _is_explorer {};
  int _is_explosion {};
  int _is_fearless {};
  int _is_fire {};
  int _is_flat {};
  int _is_floating {};
  int _is_floor {};
  int _is_floor_deco {};
  int _is_flying {};
  int _is_foilage {};
  int _is_food {};
  int _is_gas_blocker {};
  int _is_gauntlet {};
  int _is_gelatinous {};
  int _is_glass {};
  int _is_gold {};
  int _is_green_blood {};
  int _is_green_blooded {};
  int _is_green_splatter {};
  int _is_hard {};
  int _is_hazard {};
  int _is_health_booster {};
  int _is_heavy {};
  int _is_helmet {};
  int _is_hittable {};
  int _is_humanoid {};
  int _is_immune_to_acid {};
  int _is_immune_to_cold {};
  int _is_immune_to_draining {};
  int _is_immune_to_fire {};
  int _is_immune_to_necrosis {};
  int _is_immune_to_poison {};
  int _is_immune_to_spiderwebs {};
  int _is_immune_to_water {};
  int _is_intelligent {};
  int _is_interesting {}; // e.g. something edible or a monst or lava
  int _is_item {};
  int _is_item_carrier {};
  int _is_item_carrier0 {};
  int _is_item_collector {};
  int _is_item_organic {};
  int _is_item_targetted {};
  int _is_jelly {};
  int _is_jump_blocker {};
  int _is_key {};
  int _is_key_special {};
  int _is_laser {};
  int _is_lava {};
  int _is_lifeless {};
  int _is_light_blocker {};
  int _is_light_blocker_for_monst {};
  int _is_living {};
  int _is_loggable {};
  int _is_magical {};
  int _is_map_beast {};
  int _is_map_treasure {};
  int _is_meat {};
  int _is_meltable {};
  int _is_metal {};
  int _is_minion {};
  int _is_mob {};
  int _is_mob_challenge_class_a {};
  int _is_mob_challenge_class_b {};
  int _is_monst {};
  int _is_monst_class_a {};
  int _is_monst_class_b {};
  int _is_monst_class_c {};
  int _is_monst_class_d {};
  int _is_monst_class_e {};
  int _is_moveable {};
  int _is_msg {};
  int _is_necrotic_danger_level {};
  int _is_no_tile {};
  int _is_obs_destructable {};
  int _is_obstacle_when_dead {};
  int _is_obs_wall_or_door {};
  int _is_openable {};
  int _is_organic {};
  int _is_pack {};
  int _is_pillar {};
  int _is_plant {};
  int _is_player {};
  int _is_poisonous_danger_level {};
  int _is_potion {};
  int _is_projectile {};
  int _is_red_blood {};
  int _is_red_blooded {};
  int _is_red_splatter {};
  int _is_removeable_if_out_of_slots {};
  int _is_resurrectable {};
  int _is_ring {};
  int _is_ripple {};
  int _is_rock {};
  int _is_rusty {};
  int _is_secret_door {};
  int _is_sewer_wall {};
  int _is_shallow_water {};
  int _is_shield {};
  int _is_shovable {};
  int _is_shovable_and_sticky {};
  int _is_skill {};
  int _is_skillstone {};
  int _is_slippery {};
  int _is_smoke {};
  int _is_snake {};
  int _is_soft {};
  int _is_spawner {};
  int _is_spider {};
  int _is_spiderweb {};
  int _is_staff {};
  int _is_steal_item_chance_d1000 {};
  int _is_steam {};
  int _is_sticky {};
  int _is_stone {};
  int _is_sword {};
  int _is_target_radial {};
  int _is_target_select {};
  int _is_temperature_change_sensitive {};
  int _is_temperature_sensitive {};
  int _is_the_grid {};
  int _is_thief {};
  int _is_throwable {};
  int _is_throw_blocker {};
  int _is_tickable {}; // e.g. a monst or player or something moveable
  int _is_tireless {};
  int _is_tmp_thing {};
  int _is_torch {};
  int _is_treasure {};
  int _is_treasure_chest {};
  int _is_treasure_class_a {};
  int _is_treasure_class_b {};
  int _is_treasure_class_c {};
  int _is_treasure_type {};
  int _is_undead {};
  int _is_usable {};
  int _is_used_when_thrown {};
  int _is_very_combustible {};
  int _is_very_hard {};
  int _is_very_heavy {};
  int _is_wall {};
  int _is_wall_dungeon {};
  int _is_wand {};
  int _is_weapon {};
  int _is_weapon_class_a {};
  int _is_weapon_class_b {};
  int _is_weapon_class_c {};
  int _is_wet_grass {};
  int _is_wooden {};
  int _item_height {};
  int _item_width {};
  int _jump_distance {};
  int _jump_distance_mod {};
  int _light_dist {};
  int _melting_chance_d1000 {};
  int _minion_limit {};
  int _move_speed {};
  int _move_speed_mod {};
  int _noise_additional_on_jump_end {};
  int _noise_additional_on_teleporting {};
  int _noise_blocker {};
  int _noise_decibels_hearing {};
  int _noise_on_born {};
  int _noise_on_dropping {};
  int _noise_on_moving {};
  int _noise_on_open {};
  int _noise_on_you_are_hit_and_now_dead {};
  int _noise_on_you_are_hit_but_still_alive {};
  int _normal_placement_rules {};
  int _on_death_drop_all_items {};
  int _on_death_is_open {};
  int _range_max {};
  int _rarity {};
  int _shove_strength {};
  int _shove_strength_mod {};
  int _spawn_group_radius {};
  int _stamina {};
  int _stamina_drain_on_attacking {};
  int _stamina_drain_on_using {};
  int _stat_att {};
  int _stat_att_mod {};
  int _stat_att_penalty_when_idle {};
  int _stat_att_penalty_when_idle_max {};
  int _stat_att_penalty_when_in_deep_water {};
  int _stat_att_penalty_when_in_shallow_water {};
  int _stat_att_penalty_when_stuck {};
  int _stat_att_penalty_when_stuck_max {};
  int _stat_con {};
  int _stat_con_mod {};
  int _stat_def {};
  int _stat_def_mod {};
  int _stat_def_penalty_when_idle {};
  int _stat_def_penalty_when_idle_max {};
  int _stat_def_penalty_when_in_deep_water {};
  int _stat_def_penalty_when_in_shallow_water {};
  int _stat_def_penalty_when_stuck {};
  int _stat_def_penalty_when_stuck_max {};
  int _stat_dex {};
  int _stat_dex_mod {};
  int _stat_luck {};
  int _stat_luck_mod {};
  int _stats02 {};
  int _stats03 {};
  int _stats04 {};
  int _stats05 {};
  int _stats06 {};
  int _stats07 {};
  int _stats09 {};
  int _stat_str {};
  int _stat_str_mod {};
  int _teleport_distance {};
  int _temperature {TEMPERATURE_ROOM};
  int _thing_size {};
  int _tick_prio {};
  int _unused_chance1_d1000 {};
  int _unused_chance2_d1000 {};
  int _unused_chance3_d1000 {};
  int _unused_chance4_d1000 {};
  int _unused_chance5_d1000 {};
  int _unused_chance6_d1000 {};
  int _unused_flag1 {};
  int _unused_flag10 {};
  int _unused_flag103 {};
  int _unused_flag11 {};
  int _unused_flag12 {};
  int _unused_flag123 {};
  int _unused_flag13 {};
  int _unused_flag14 {};
  int _unused_flag15 {};
  int _unused_flag16 {};
  int _unused_flag17 {};
  int _unused_flag18 {};
  int _unused_flag19 {};
  int _unused_flag2 {};
  int _unused_flag20 {};
  int _unused_flag21 {};
  int _unused_flag22 {};
  int _unused_flag23 {};
  int _unused_flag24 {};
  int _unused_flag25 {};
  int _unused_flag26 {};
  int _unused_flag27 {};
  int _unused_flag28 {};
  int _unused_flag29 {};
  int _unused_flag3 {};
  int _unused_flag30 {};
  int _unused_flag31 {};
  int _unused_flag32 {};
  int _unused_flag33 {};
  int _unused_flag34 {};
  int _unused_flag35 {};
  int _unused_flag36 {};
  int _unused_flag37 {};
  int _unused_flag38 {};
  int _unused_flag39 {};
  int _unused_flag4 {};
  int _unused_flag40 {};
  int _unused_flag41 {};
  int _unused_flag42 {};
  int _unused_flag43 {};
  int _unused_flag44 {};
  int _unused_flag45 {};
  int _unused_flag46 {};
  int _unused_flag47 {};
  int _unused_flag48 {};
  int _unused_flag49 {};
  int _unused_flag5 {};
  int _unused_flag50 {};
  int _unused_flag51 {};
  int _unused_flag52 {};
  int _unused_flag53 {};
  int _unused_flag54 {};
  int _unused_flag55 {};
  int _unused_flag56 {};
  int _unused_flag57 {};
  int _unused_flag58 {};
  int _unused_flag59 {};
  int _unused_flag6 {};
  int _is_internal {};
  int _unused_flag7 {};
  int _unused_flag8 {};
  int _unused_flag87 {};
  int _unused_flag9 {};
  int _weapon_damage {};
  int _weapon_use_distance {};

  std::string _damage_acid_dice_str;
  std::string _damage_cold_dice_str;
  std::string _damage_crush_dice_str;
  std::string _damage_digest_dice_str;
  std::string _damage_draining_dice_str;
  std::string _damage_energy_dice_str;
  std::string _damage_fire_dice_str;
  std::string _damage_future1_dice_str;
  std::string _damage_bite_dice_str;
  std::string _damage_claw_dice_str;
  std::string _damage_lightning_dice_str;
  std::string _damage_melee_dice_str;
  std::string _damage_nat_att_dice_str;
  std::string _damage_nat_att_type;
  std::string _damage_necrosis_dice_str;
  std::string _damage_poison_dice_str;
  std::string _damage_water_dice_str;
  std::string _equip_carry_anim;
  std::string _gfx_anim_use;
  std::string _gold_value_dice_str;
  std::string _health_initial_dice_str;
  std::string _is_allied_with;
  std::string _lifespan_dice_str;
  std::string _light_color;
  std::string _name;
  std::string _nutrition_dice_str;
  std::string _on_attacking_dmg_acid_do;
  std::string _on_attacking_dmg_cold_do;
  std::string _on_attacking_dmg_crush_do;
  std::string _on_attacking_dmg_digest_do;
  std::string _on_attacking_dmg_draining_do;
  std::string _on_attacking_dmg_energy_do;
  std::string _on_attacking_dmg_fire_do;
  std::string _on_attacking_dmg_future1_do;
  std::string _on_attacking_dmg_bite_do;
  std::string _on_attacking_dmg_claw_do;
  std::string _on_attacking_dmg_lightning_do;
  std::string _on_attacking_dmg_melee_do;
  std::string _on_attacking_dmg_nat_att_do;
  std::string _on_attacking_dmg_necrosis_do;
  std::string _on_attacking_dmg_poison_do;
  std::string _on_attacking_dmg_stat_att_do;
  std::string _on_attacking_dmg_stat_con_do;
  std::string _on_attacking_dmg_stat_str_do;
  std::string _on_attacking_dmg_water_do;
  std::string _on_awake_do;
  std::string _on_born_do;
  std::string _on_death_do;
  std::string _on_death_of_a_follower_do;
  std::string _on_death_of_my_leader_do;
  std::string _on_dropped_do;
  std::string _on_enchant_do;
  std::string _on_equip_do;
  std::string _on_fall_do;
  std::string _on_final_use_do;
  std::string _on_firing_at_something_do;
  std::string _on_get_text_long_description_do;
  std::string _on_idle_tick_freq_dice_str;
  std::string _on_jump_do;
  std::string _on_lifespan_tick_do;
  std::string _on_move_do;
  std::string _on_open_do;
  std::string _on_owner_add_do;
  std::string _on_owner_attack_dmg_acid_do;
  std::string _on_owner_attack_dmg_cold_do;
  std::string _on_owner_attack_dmg_crush_do;
  std::string _on_owner_attack_dmg_digest_do;
  std::string _on_owner_attack_dmg_draining_do;
  std::string _on_owner_attack_dmg_energy_do;
  std::string _on_owner_attack_dmg_fire_do;
  std::string _on_owner_attack_dmg_future1_do;
  std::string _on_owner_attack_dmg_bite_do;
  std::string _on_owner_attack_dmg_claw_do;
  std::string _on_owner_attack_dmg_lightning_do;
  std::string _on_owner_attack_dmg_melee_do;
  std::string _on_owner_attack_dmg_nat_att_do;
  std::string _on_owner_attack_dmg_necrosis_do;
  std::string _on_owner_attack_dmg_poison_do;
  std::string _on_owner_attack_dmg_stat_att_do;
  std::string _on_owner_attack_dmg_stat_con_do;
  std::string _on_owner_attack_dmg_stat_str_do;
  std::string _on_owner_attack_dmg_water_do;
  std::string _on_owner_receive_dmg_acid_do;
  std::string _on_owner_receive_dmg_cold_do;
  std::string _on_owner_receive_dmg_crush_do;
  std::string _on_owner_receive_dmg_digest_do;
  std::string _on_owner_receive_dmg_draining_do;
  std::string _on_owner_receive_dmg_energy_do;
  std::string _on_owner_receive_dmg_fire_do;
  std::string _on_owner_receive_dmg_future1_do;
  std::string _on_owner_receive_dmg_bite_do;
  std::string _on_owner_receive_dmg_claw_do;
  std::string _on_owner_receive_dmg_lightning_do;
  std::string _on_owner_receive_dmg_melee_do;
  std::string _on_owner_receive_dmg_nat_att_do;
  std::string _on_owner_receive_dmg_necrosis_do;
  std::string _on_owner_receive_dmg_poison_do;
  std::string _on_owner_receive_dmg_stat_att_do;
  std::string _on_owner_receive_dmg_stat_con_do;
  std::string _on_owner_receive_dmg_stat_str_do;
  std::string _on_owner_receive_dmg_water_do;
  std::string _on_owner_remove_do;
  std::string _on_polymorphed_do;
  std::string _on_receiving_dmg_acid_do;
  std::string _on_receiving_dmg_cold_do;
  std::string _on_receiving_dmg_crush_do;
  std::string _on_receiving_dmg_digest_do;
  std::string _on_receiving_dmg_draining_do;
  std::string _on_receiving_dmg_energy_do;
  std::string _on_receiving_dmg_fire_do;
  std::string _on_receiving_dmg_future1_do;
  std::string _on_receiving_dmg_bite_do;
  std::string _on_receiving_dmg_claw_do;
  std::string _on_receiving_dmg_lightning_do;
  std::string _on_receiving_dmg_melee_do;
  std::string _on_receiving_dmg_nat_att_do;
  std::string _on_receiving_dmg_necrosis_do;
  std::string _on_receiving_dmg_poison_do;
  std::string _on_receiving_dmg_stat_att_do;
  std::string _on_receiving_dmg_stat_con_do;
  std::string _on_receiving_dmg_stat_str_do;
  std::string _on_receiving_dmg_water_do;
  std::string _on_resting_do;
  std::string _on_stuck_do;
  std::string _on_swing_do;
  std::string _on_teleport_do;
  std::string _on_thrown_do;
  std::string _on_tick_do;
  std::string _on_unequip_do;
  std::string _on_use_do;
  std::string _on_waiting_do;
  std::string _on_you_are_declared_a_follower_do;
  std::string _on_you_are_declared_leader_do;
  std::string _on_you_are_hit_and_now_dead_do;
  std::string _on_you_are_hit_but_dodge_it_do;
  std::string _on_you_are_hit_but_still_alive_do;
  std::string _on_you_are_on_fire_do;
  std::string _on_you_nat_att_do;
  std::string _resurrect_dice_str;
  std::string _spawn_group_size_dice_str;
  std::string _spawn_on_shoved;
  std::string _str1;
  std::string _str2;
  std::string _str4;
  std::string _target_name_laser;
  std::string _target_name_projectile;
  std::string _target_name_radial;
  std::string _text_a_or_an;
  std::string _text_debuff;
  std::string _text_enchant;
  std::string _text_hits;
  std::string _text_long_description;
  std::string _text_long_description2;
  std::string _text_long_description3;
  std::string _text_long_name;
  std::string _text_short_description;
  std::string _text_short_name;
  std::string _text_skill;
  std::string _text_title;
  std::string _text_unused;
  std::string _text_unused1;
  std::string _text_unused2;
  std::string _text_unused3;

public:
  Tp(void);
  ~Tp(void);

  bool is_disliked_by_me(class Level *, point p) const;
  bool is_hated_by_me(class Level *, point p) const;
  bool ai_obstacle(Thingp it);
  bool ai_obstacle_for_me(class Level *, point);
  bool can_eat(const Thingp itp);
  bool is_edible(const Thingp it);
  bool has_temperature(void);

  void dbg_(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void err(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void err_(const char *fmt, va_list args); // compile error without
  void log(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void log_(const char *fmt, va_list args); // compile error without
  void topcon(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void topcon_(const char *fmt, va_list args); // compile error without
  void die(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void die_(const char *fmt, va_list args); // compile error without
  void con(const char *fmt, ...) __attribute__((format(printf, 2, 3)));
  void con_(const char *fmt, va_list args); // compile error without

  const Dice &damage_acid_dice(void) const;
  const Dice &damage_water_dice(void) const;
  const Dice &damage_nat_att_dice(void) const;
  const Dice &damage_crush_dice(void) const;
  const Dice &damage_digest_dice(void) const;
  const Dice &damage_energy_dice(void) const;
  const Dice &damage_fire_dice(void) const;
  const Dice &damage_future1_dice(void) const;
  const Dice &damage_bite_dice(void) const;
  const Dice &damage_claw_dice(void) const;
  const Dice &damage_cold_dice(void) const;
  const Dice &damage_lightning_dice(void) const;
  const Dice &damage_melee_dice(void) const;
  const Dice &damage_necrosis_dice(void) const;
  const Dice &damage_draining_dice(void) const;
  const Dice &damage_poison_dice(void) const;
  const Dice &health_initial_dice(void) const;
  const Dice &gold_value_dice(void) const;
  const Dice &lifespan_dice(void) const;
  const Dice &nutrition_dice(void) const;
  const Dice &on_idle_tick_freq_dice(void) const;
  const Dice &resurrect_dice(void) const;
  const Dice &spawn_group_size_dice(void) const;

  const int cash(void) const;
  const int damage_acid(void) const;
  const int damage_water(void) const;
  const int damage_nat_att(void) const;
  const int damage_crush(void) const;
  const int damage_digest(void) const;
  const int damage_energy(void) const;
  const int damage_fire(void) const;
  const int damage_future1(void) const;
  const int damage_bite(void) const;
  const int damage_claw(void) const;
  const int damage_cold(void) const;
  const int damage_lightning(void) const;
  const int damage_melee(void) const;
  const int damage_necrosis(void) const;
  const int damage_draining(void) const;
  const int damage_poison(void) const;
  const int health_initial(void) const;
  const int health_initial_max_roll(void) const;
  const int on_idle_tick_freq(void) const;
  const int spawn_group_size(void) const;
  const int lifespan(void) const;
  const int nutrition(void) const;
  const int resurrect(void) const;

  const Tilemap *tp_bl1_tiles(void) const;
  const Tilemap *tp_bl2_tiles(void) const;
  const Tilemap *tp_bot1_tiles(void) const;
  const Tilemap *tp_bot2_tiles(void) const;
  const Tilemap *tp_bot3_tiles(void) const;
  const Tilemap *tp_br1_tiles(void) const;
  const Tilemap *tp_br2_tiles(void) const;
  const Tilemap *tp_horiz_tiles(void) const;
  const Tilemap *tp_l180_tiles(void) const;
  const Tilemap *tp_l270_tiles(void) const;
  const Tilemap *tp_l90_tiles(void) const;
  const Tilemap *tp_left1_tiles(void) const;
  const Tilemap *tp_left2_tiles(void) const;
  const Tilemap *tp_l_tiles(void) const;
  const Tilemap *tp_outline_tiles(void) const;
  const Tilemap *tp_right1_tiles(void) const;
  const Tilemap *tp_right2_tiles(void) const;
  const Tilemap *tp_t180_tiles(void) const;
  const Tilemap *tp_t270_tiles(void) const;
  const Tilemap *tp_t90_tiles(void) const;
  const Tilemap *tp_tiles(void) const;
  const Tilemap *tp_tl1_tiles(void) const;
  const Tilemap *tp_tl2_tiles(void) const;
  const Tilemap *tp_top1_tiles(void) const;
  const Tilemap *tp_top2_tiles(void) const;
  const Tilemap *tp_tr1_tiles(void) const;
  const Tilemap *tp_tr2_tiles(void) const;
  const Tilemap *tp_t_tiles(void) const;
  const Tilemap *tp_vert_tiles(void) const;
  const Tilemap *tp_x_tiles(void) const;

  void damage_acid_dice_set(const std::string &);
  void damage_water_dice_set(const std::string &);
  void damage_cold_dice_set(const std::string &);
  void damage_crush_dice_set(const std::string &);
  void damage_digest_dice_set(const std::string &);
  void damage_draining_dice_set(const std::string &);
  void damage_energy_dice_set(const std::string &);
  void damage_fire_dice_set(const std::string &);
  void damage_future1_dice_set(const std::string &);
  void damage_bite_dice_set(const std::string &);
  void damage_claw_dice_set(const std::string &);
  void damage_lightning_dice_set(const std::string &);
  void damage_melee_dice_set(const std::string &);
  void damage_nat_att_type_set(const std::string &);
  void damage_nat_att_dice_set(const std::string &);
  void damage_necrosis_dice_set(const std::string &);
  void damage_poison_dice_set(const std::string &);
  void gold_value_dice_set(const std::string &);
  void health_initial_dice_set(const std::string &);
  void lifespan_dice_set(const std::string &);
  void nutrition_dice_set(const std::string &);
  void on_idle_tick_freq_dice_set(const std::string &);
  void resurrect_dice_set(const std::string &);
  void spawn_group_size_dice_set(const std::string &);

  std::string text_short_capitalised(void) const;
  std::string text_a_or_an(void) const;
  std::string to_string(void);
  std::string to_short_string(void);

  const std::string &damage_acid_dice_str(void) const;
  const std::string &damage_water_dice_str(void) const;
  const std::string &damage_cold_dice_str(void) const;
  const std::string &damage_crush_dice_str(void) const;
  const std::string &damage_digest_dice_str(void) const;
  const std::string &damage_draining_dice_str(void) const;
  const std::string &damage_energy_dice_str(void) const;
  const std::string &damage_fire_dice_str(void) const;
  const std::string &damage_future1_dice_str(void) const;
  const std::string &damage_bite_dice_str(void) const;
  const std::string &damage_claw_dice_str(void) const;
  const std::string &damage_lightning_dice_str(void) const;
  const std::string &damage_melee_dice_str(void) const;
  const std::string &damage_nat_att_type(void) const;
  const std::string &damage_nat_att_dice_str(void) const;
  const std::string &damage_necrosis_dice_str(void) const;
  const std::string &damage_poison_dice_str(void) const;
  const std::string &equip_carry_anim(void) const;
  const std::string &gfx_anim_use(void) const;
  const std::string &gold_value_dice_str(void) const;
  const std::string &health_initial_dice_str(void) const;
  const std::string &is_allied_with(void) const;
  const std::string &lifespan_dice_str(void) const;
  const std::string &light_color(void) const;
  const std::string &name(void) const;
  const std::string &nutrition_dice_str(void) const;
  const std::string &on_attacking_dmg_acid_do(void) const;
  const std::string &on_attacking_dmg_water_do(void) const;
  const std::string &on_attacking_dmg_cold_do(void) const;
  const std::string &on_attacking_dmg_crush_do(void) const;
  const std::string &on_attacking_dmg_digest_do(void) const;
  const std::string &on_attacking_dmg_draining_do(void) const;
  const std::string &on_attacking_dmg_energy_do(void) const;
  const std::string &on_attacking_dmg_fire_do(void) const;
  const std::string &on_attacking_dmg_future1_do(void) const;
  const std::string &on_attacking_dmg_bite_do(void) const;
  const std::string &on_attacking_dmg_claw_do(void) const;
  const std::string &on_attacking_dmg_lightning_do(void) const;
  const std::string &on_attacking_dmg_melee_do(void) const;
  const std::string &on_attacking_dmg_nat_att_do(void) const;
  const std::string &on_attacking_dmg_necrosis_do(void) const;
  const std::string &on_attacking_dmg_poison_do(void) const;
  const std::string &on_attacking_dmg_stat_att_do(void) const;
  const std::string &on_attacking_dmg_stat_con_do(void) const;
  const std::string &on_attacking_dmg_stat_str_do(void) const;
  const std::string &on_awake_do(void) const;
  const std::string &on_born_do(void) const;
  const std::string &on_death_do(void) const;
  const std::string &on_death_of_a_follower_do(void) const;
  const std::string &on_death_of_my_leader_do(void) const;
  const std::string &on_enchant_do(void) const;
  const std::string &on_thrown_do(void) const;
  const std::string &on_dropped_do(void) const;
  const std::string &on_equip_do(void) const;
  const std::string &on_fall_do(void) const;
  const std::string &on_final_use_do(void) const;
  const std::string &on_firing_at_something_do(void) const;
  const std::string &on_get_text_long_description_do(void) const;
  const std::string &on_idle_tick_freq_dice_str(void) const;
  const std::string &on_jump_do(void) const;
  const std::string &on_lifespan_tick_do(void) const;
  const std::string &on_move_do(void) const;
  const std::string &on_open_do(void) const;
  const std::string &on_owner_add_do(void) const;
  const std::string &on_owner_attack_dmg_acid_do(void) const;
  const std::string &on_owner_attack_dmg_water_do(void) const;
  const std::string &on_owner_attack_dmg_cold_do(void) const;
  const std::string &on_owner_attack_dmg_crush_do(void) const;
  const std::string &on_owner_attack_dmg_digest_do(void) const;
  const std::string &on_owner_attack_dmg_draining_do(void) const;
  const std::string &on_owner_attack_dmg_energy_do(void) const;
  const std::string &on_owner_attack_dmg_fire_do(void) const;
  const std::string &on_owner_attack_dmg_future1_do(void) const;
  const std::string &on_owner_attack_dmg_bite_do(void) const;
  const std::string &on_owner_attack_dmg_claw_do(void) const;
  const std::string &on_owner_attack_dmg_lightning_do(void) const;
  const std::string &on_owner_attack_dmg_melee_do(void) const;
  const std::string &on_owner_attack_dmg_nat_att_do(void) const;
  const std::string &on_owner_attack_dmg_necrosis_do(void) const;
  const std::string &on_owner_attack_dmg_poison_do(void) const;
  const std::string &on_owner_attack_dmg_stat_att_do(void) const;
  const std::string &on_owner_attack_dmg_stat_con_do(void) const;
  const std::string &on_owner_attack_dmg_stat_str_do(void) const;
  const std::string &on_owner_receive_dmg_acid_do(void) const;
  const std::string &on_owner_receive_dmg_water_do(void) const;
  const std::string &on_owner_receive_dmg_cold_do(void) const;
  const std::string &on_owner_receive_dmg_crush_do(void) const;
  const std::string &on_owner_receive_dmg_digest_do(void) const;
  const std::string &on_owner_receive_dmg_draining_do(void) const;
  const std::string &on_owner_receive_dmg_energy_do(void) const;
  const std::string &on_owner_receive_dmg_fire_do(void) const;
  const std::string &on_owner_receive_dmg_future1_do(void) const;
  const std::string &on_owner_receive_dmg_bite_do(void) const;
  const std::string &on_owner_receive_dmg_claw_do(void) const;
  const std::string &on_owner_receive_dmg_lightning_do(void) const;
  const std::string &on_owner_receive_dmg_melee_do(void) const;
  const std::string &on_owner_receive_dmg_nat_att_do(void) const;
  const std::string &on_owner_receive_dmg_necrosis_do(void) const;
  const std::string &on_owner_receive_dmg_poison_do(void) const;
  const std::string &on_owner_receive_dmg_stat_att_do(void) const;
  const std::string &on_owner_receive_dmg_stat_con_do(void) const;
  const std::string &on_owner_receive_dmg_stat_str_do(void) const;
  const std::string &on_owner_remove_do(void) const;
  const std::string &on_polymorphed_do(void) const;
  const std::string &on_receiving_dmg_acid_do(void) const;
  const std::string &on_receiving_dmg_water_do(void) const;
  const std::string &on_receiving_dmg_cold_do(void) const;
  const std::string &on_receiving_dmg_crush_do(void) const;
  const std::string &on_receiving_dmg_digest_do(void) const;
  const std::string &on_receiving_dmg_draining_do(void) const;
  const std::string &on_receiving_dmg_energy_do(void) const;
  const std::string &on_receiving_dmg_fire_do(void) const;
  const std::string &on_receiving_dmg_future1_do(void) const;
  const std::string &on_receiving_dmg_bite_do(void) const;
  const std::string &on_receiving_dmg_claw_do(void) const;
  const std::string &on_receiving_dmg_lightning_do(void) const;
  const std::string &on_receiving_dmg_melee_do(void) const;
  const std::string &on_receiving_dmg_nat_att_do(void) const;
  const std::string &on_receiving_dmg_necrosis_do(void) const;
  const std::string &on_receiving_dmg_poison_do(void) const;
  const std::string &on_receiving_dmg_stat_att_do(void) const;
  const std::string &on_receiving_dmg_stat_con_do(void) const;
  const std::string &on_receiving_dmg_stat_str_do(void) const;
  const std::string &on_resting_do(void) const;
  const std::string &on_stuck_do(void) const;
  const std::string &on_swing_do(void) const;
  const std::string &on_teleport_do(void) const;
  const std::string &on_tick_do(void) const;
  const std::string &on_unequip_do(void) const;
  const std::string &on_use_do(void) const;
  const std::string &on_waiting_do(void) const;
  const std::string &on_you_are_declared_a_follower_do(void) const;
  const std::string &on_you_are_declared_leader_do(void) const;
  const std::string &on_you_are_hit_and_now_dead_do(void) const;
  const std::string &on_you_are_hit_but_dodge_it_do(void) const;
  const std::string &on_you_are_hit_but_still_alive_do(void) const;
  const std::string &on_you_are_on_fire_do(void) const;
  const std::string &on_you_nat_att_do(void) const;
  const std::string &resurrect_dice_str(void) const;
  const std::string &spawn_group_size_dice_str(void) const;
  const std::string &spawn_on_shoved(void) const;
  const std::string &str1(void) const;
  const std::string &str2(void) const;
  const std::string &str4(void) const;
  const std::string &target_name_laser(void) const;
  const std::string &target_name_projectile(void) const;
  const std::string &target_name_radial(void) const;
  const std::string &text_debuff(void) const;
  const std::string &text_enchant(void) const;
  const std::string &text_hits(void) const;
  const std::string &text_long_description2(void) const;
  const std::string &text_long_description3(void) const;
  const std::string &text_long_description(void) const;
  const std::string &text_long_name(void) const;
  const std::string &text_short_description(void) const;
  const std::string &text_short_name(void) const;
  const std::string &text_skill(void) const;
  const std::string &text_title(void) const;
  const std::string &text_unused1(void) const;
  const std::string &text_unused2(void) const;
  const std::string &text_unused3(void) const;
  const std::string &text_unused(void) const;

  int aggression_pct(void) const;
  int ai_detect_secret_doors(void) const;
  int ai_obstacle(void) const;
  int ai_resent_count(void) const;
  int ai_shove_chance_d1000(void) const;
  int ai_wanderer(void) const;
  int appearing_chance_d1000(void) const;
  int attack_eater(void) const;
  int attack_engulf_chance_d1000(void) const;
  int attack_humanoid(void) const;
  int attack_living(void) const;
  int attack_lunge(void) const;
  int attack_meat(void) const;
  int attack_no_msg(void) const;
  int attacks_per_round(void) const;
  int attack_undead(void) const;
  int blast_max_radius(void) const;
  int blast_min_radius(void) const;
  int blit_bot_off(void) const;
  int blit_left_off(void) const;
  int blit_right_off(void) const;
  int blit_top_off(void) const;
  int capacity_height(void) const;
  int capacity_width(void) const;
  int charge_count(void) const;
  int collateral_damage_pct(void) const;
  int collision_check(void) const;
  int collision_hit_180(void) const;
  int collision_hit_360(void) const;
  int collision_hit_adj(void) const;
  int collision_hit_priority(void) const;
  int collision_hit_two_tiles_ahead(void) const;
  int crit_chance_d10000(void) const;
  int damage_acid_chance_d1000(int index) const;
  int damage_cold_chance_d1000(int index) const;
  int damage_crush_chance_d1000(int index) const;
  int damaged_chance_d10000(void) const;
  int damage_digest_chance_d1000(int index) const;
  int damage_draining_chance_d1000(int index) const;
  int damage_energy_chance_d1000(int index) const;
  int damage_fire_chance_d1000(int index) const;
  int damage_future1_chance_d1000(int index) const;
  int damage_bite_chance_d1000(int index) const;
  int damage_claw_chance_d1000(int index) const;
  int damage_lightning_chance_d1000(int index) const;
  int damage_melee_chance_d1000(int index) const;
  int damage_nat_att_chance_d1000(int index) const;
  int damage_necrosis_chance_d1000(int index) const;
  int damage_poison_chance_d1000(int index) const;
  int damage_received_doubled_from_acid(void) const;
  int damage_received_doubled_from_cold(void) const;
  int damage_received_doubled_from_fire(void) const;
  int damage_received_doubled_from_necrosis(void) const;
  int damage_received_doubled_from_poison(void) const;
  int damage_received_doubled_from_water(void) const;
  int damage_water_chance_d1000(int index) const;
  int distance_avoid(void) const;
  int distance_leader_max(void) const;
  int distance_minion_vision_shared(void) const;
  int distance_mob_max(void) const;
  int distance_recruitment_max(void) const;
  int distance_throw(void) const;
  int distance_vision(void) const;
  int is_eater_of_amulets(void) const;
  int is_eater_of_armor(void) const;
  int is_eater_of_boots(void) const;
  int is_eater_of_cloaks(void) const;
  int is_eater_of_gauntlets(void) const;
  int is_eater_of_helmets(void) const;
  int is_eater_of_rings(void) const;
  int is_eater_of_shields(void) const;
  int is_eater_of_staffs(void) const;
  int is_eater_of_wands(void) const;
  int is_eater_of_weapons(void) const;
  int enchant_max(void) const;
  int environ_avoids_acid(void) const;
  int environ_avoids_cold(void) const;
  int environ_avoids_fire(void) const;
  int environ_avoids_necrosis(void) const;
  int environ_avoids_poison(void) const;
  int environ_avoids_water(void) const;
  int get_danger_level(void);
  int gfx_ascii_animated(void) const;
  int gfx_ascii_bg_color_spread_alpha(void) const;
  int gfx_ascii_bg_color_spread_blue(void) const;
  int gfx_ascii_bg_color_spread_green(void) const;
  int gfx_ascii_bg_color_spread_hue(void) const;
  int gfx_ascii_bg_color_spread_red(void) const;
  int gfx_ascii_color_is_animated(void) const;
  int gfx_ascii_fade_with_dist(void) const;
  int gfx_ascii_fg_color_spread_alpha(void) const;
  int gfx_ascii_fg_color_spread_blue(void) const;
  int gfx_ascii_fg_color_spread_green(void) const;
  int gfx_ascii_fg_color_spread_hue(void) const;
  int gfx_ascii_fg_color_spread_red(void) const;
  int gfx_ascii_shown_as_gray_in_shadow(void) const;
  int gfx_ascii_shown_in_bg(void) const;
  int gfx_ascii_shown(void) const;
  int gfx_glows(void) const;
  int gfx_on_fire_anim(void) const;
  int gfx_oversized_and_on_floor(void) const;
  int gfx_pixelart_animated_can_hflip(void) const;
  int gfx_pixelart_animated_can_vflip(void) const;
  int gfx_pixelart_animated_no_dir(void) const;
  int gfx_pixelart_anim_synced_with_owner(void) const;
  int gfx_pixelart_attack_anim(void) const;
  int gfx_pixelart_bounce_always(void) const;
  int gfx_pixelart_bounce_on_move(void) const;
  int gfx_pixelart_equip_carry_anim(void) const;
  int gfx_pixelart_flickers(void) const;
  int gfx_pixelart_health_bar_autohide(void) const;
  int gfx_pixelart_health_bar_only_when_awake(void) const;
  int gfx_pixelart_health_bar_shown(void) const;
  int gfx_pixelart_shadow_long(void) const;
  int gfx_pixelart_shadow_short(void) const;
  int gfx_pixelart_shadow_solid(void) const;
  int gfx_pixelart_shadow_very_short(void) const;
  int gfx_pixelart_show_asleep_anim(void) const;
  int gfx_pixelart_shown_in_bg(void) const;
  int gfx_pixelart_show_outlined(void) const;
  int gfx_pixelart_wobbles_when_hit(void) const;
  int gfx_water(void) const;
  int hunger_clock_tick_freq(void) const;
  int hunger_is_hunger_level_hungry_at_pct(void) const;
  int hunger_is_insatiable(void) const;
  int hunger_is_hunger_level_starving_at_pct(void) const;
  int internal_has_dir_anim(void) const;
  int internal_has_hp_anim(void) const;
  int is_able_to_attack_mobs(void) const;
  int is_able_to_attack_owner(void) const;
  int is_able_to_break_down_doors(void) const;
  int is_able_to_break_out_of_ice(void) const;
  int is_able_to_break_out_of_webs(void) const;
  int is_able_to_burn(void) const;
  int is_able_to_change_levels(void) const;
  int is_able_to_collect_keys(void) const;
  int is_able_to_enchant_items(void) const;
  int is_able_to_fall(void) const;
  int is_able_to_fire_at(void) const;
  int is_able_to_follow(void) const;
  int is_able_to_freeze(void) const;
  int is_able_to_jump_attack_chance_d1000(void) const;
  int is_able_to_jump_attack(void) const;
  int is_able_to_jump_escape(void) const;
  int is_able_to_jump_on_low_hp_chance_d1000(void) const;
  int is_able_to_jump_onto_chance_d1000(void) const;
  int is_able_to_jump_onto(void) const;
  int is_able_to_jump_randomly_chance_d1000(void) const;
  int is_able_to_jump(void) const;
  int is_able_to_jump_without_tiring(void) const;
  int is_able_to_learn_skills(void) const;
  int is_able_to_move_diagonally(void) const;
  int is_able_to_open_doors(void) const;
  int is_able_to_see_in_the_dark(void) const;
  int is_able_to_see_through_doors(void) const;
  int is_able_to_shove(void) const;
  int is_able_to_sleep(void) const;
  int is_able_to_swim(void) const;
  int is_able_to_teleport_attack_chance_d1000(void) const;
  int is_able_to_teleport_attack(void) const;
  int is_able_to_teleport_escape(void) const;
  int is_able_to_teleport_without_tiring(void) const;
  int is_able_to_tire(void) const;
  int is_able_to_use_amulet(void) const;
  int is_able_to_use_armor(void) const;
  int is_able_to_use_boots(void) const;
  int is_able_to_use_cloak(void) const;
  int is_able_to_use_gauntlet(void) const;
  int is_able_to_use_helmet(void) const;
  int is_able_to_use_rings(void) const;
  int is_able_to_use_shield(void) const;
  int is_able_to_use_wands_or_staffs(void) const;
  int is_able_to_use_weapons(void) const;
  int is_able_to_walk_through_walls(void) const;
  int is_acid(void) const;
  int is_air_breathher(void) const;
  int is_alive_on_end_of_anim(void) const;
  int is_always_hit(void) const;
  int is_amulet(void) const;
  int is_aquatic(void) const;
  int is_armor(void) const;
  int is_ascend_dungeon(void) const;
  int is_ascend_sewer(void) const;
  int is_asleep_initially(void) const;
  int is_attackable_by_monst(void) const;
  int is_attackable_by_player(void) const;
  int is_auto_collect_item(void) const;
  int is_auto_equipped(void) const;
  int is_auto_throw(void) const;
  int is_auto_use(void) const;
  int is_bag_item_container(void) const;
  int is_bag_item_not_stackable(void) const;
  int is_bag_item(void) const;
  int is_bag(void) const;
  int is_barrel(void) const;
  int is_basalt(void) const;
  int is_biome_dungeon(void) const;
  int is_biome_swamp(void) const;
  int is_bleeder(void) const;
  int is_block_of_ice(void) const;
  int is_bones(void) const;
  int is_boots(void) const;
  int is_brazier(void) const;
  int is_bridge(void) const;
  int is_brittle(void) const;
  int is_buff(void) const;
  int is_carnivorous_plant(void) const;
  int is_carrier_of_treasure_class_a(void) const;
  int is_carrier_of_treasure_class_b(void) const;
  int is_carrier_of_treasure_class_c(void) const;
  int is_carrier_of_weapon_class_a(void) const;
  int is_carrier_of_weapon_class_b(void) const;
  int is_carrier_of_weapon_class_c(void) const;
  int is_chasm(void) const;
  int is_cloak(void) const;
  int is_cold(void) const;
  int is_collectable(void) const;
  int is_collected_as_gold(void) const;
  int is_collected_as_keys(void) const;
  int is_combustible(void) const;
  int is_corpse_on_death(void) const;
  int is_corpse_with_bones(void) const;
  int is_corridor(void) const;
  int is_cowardly(void) const;
  int is_critical_to_level(void) const;
  int is_crushable(void) const;
  int is_crystal(void) const;
  int is_cursor_can_hover_over(void) const;
  int is_cursor_can_hover_over_x2_click(void) const;
  int is_cursor_path_blocker(void) const;
  int is_cursor_path_hazard(void) const;
  int is_cursor_path(void) const;
  int is_cursor(void) const;
  int is_dagger(void) const;
  int is_dead_on_end_of_anim(void) const;
  int is_dead_on_falling(void) const;
  int is_dead_on_shove(void) const;
  int is_debuff(void) const;
  int is_debug_path(void) const;
  int is_debug_type(void) const;
  int is_deep_water(void) const;
  int is_descend_dungeon(void) const;
  int is_descend_sewer(void) const;
  int is_described_when_hovering_over(void) const;
  int is_destroyed_on_hit_or_miss(void) const;
  int is_destroyed_on_hitting(void) const;
  int is_dirt(void) const;
  int is_door(void) const;
  int is_droppable(void) const;
  int is_dry_grass_trampled(void) const;
  int is_dry_grass(void) const;
  int is_eater_of_food(void) const;
  int is_eater_of_green_blood(void) const;
  int is_eater_of_jelly(void) const;
  int is_eater_of_magical_items(void) const;
  int is_eater_of_meat(void) const;
  int is_eater_of_potions(void) const;
  int is_eater_of_red_blood(void) const;
  int is_eater_of_treasure(void) const;
  int is_enchantable(void) const;
  int is_enchantstone(void) const;
  int is_engulfer(void) const;
  int is_ethereal_mob(void) const;
  int is_ethereal(void) const;
  int is_exit_finder(void) const;
  int is_explorer(void) const;
  int is_explosion(void) const;
  int is_fearless(void) const;
  int is_fire(void) const;
  int is_flat(void) const;
  int is_floating(void) const;
  int is_floor_deco(void) const;
  int is_floor(void) const;
  int is_flying(void) const;
  int is_foilage(void) const;
  int is_food(void) const;
  int is_gas_blocker(void) const;
  int is_gauntlet(void) const;
  int is_gelatinous(void) const;
  int is_glass(void) const;
  int is_gold(void) const;
  int is_green_blooded(void) const;
  int is_green_blood(void) const;
  int is_green_splatter(void) const;
  int is_hard(void) const;
  int is_hazard(void) const;
  int is_health_booster(void) const;
  int is_heavy(void) const;
  int is_helmet(void) const;
  int is_hittable(void) const;
  int is_humanoid(void) const;
  int is_immune_to_acid(void) const;
  int is_immune_to_cold(void) const;
  int is_immune_to_draining(void) const;
  int is_immune_to_fire(void) const;
  int is_immune_to_necrosis(void) const;
  int is_immune_to_poison(void) const;
  int is_immune_to_spiderwebs(void) const;
  int is_immune_to_water(void) const;
  int is_intelligent(void) const;
  int is_interesting(void) const;
  int is_item_carrier(void) const;
  int is_item_collector(void) const;
  int is_item_organic(void) const;
  int is_item_targetted(void) const;
  int is_item(void) const;
  int is_jelly(void) const;
  int is_jump_blocker(void) const;
  int is_key_special(void) const;
  int is_key(void) const;
  int is_laser(void) const;
  int is_lava(void) const;
  int is_lifeless(void) const;
  int is_light_blocker_for_monst(void) const;
  int is_light_blocker(void) const;
  int is_living(void) const;
  int is_loggable(void) const;
  int is_magical(void) const;
  int is_map_beast(void) const;
  int is_map_treasure(void) const;
  int is_meat(void) const;
  int is_meltable(void) const;
  int is_metal(void) const;
  int is_minion(void) const;
  int is_mob_challenge_class_a(void) const;
  int is_mob_challenge_class_b(void) const;
  int is_mob(void) const;
  int is_monst_class_a(void) const;
  int is_monst_class_b(void) const;
  int is_monst_class_c(void) const;
  int is_monst_class_d(void) const;
  int is_monst_class_e(void) const;
  int is_monst(void) const;
  int is_moveable(void) const;
  int is_msg(void) const;
  int is_necrotic_danger_level(void) const;
  int is_no_tile(void) const;
  int is_obs_destructable(void) const;
  int is_obstacle_when_dead(void) const;
  int is_obs_wall_or_door(void) const;
  int is_openable(void) const;
  int is_organic(void) const;
  int is_pack(void) const;
  int is_pillar(void) const;
  int is_plant(void) const;
  int is_player(void) const;
  int is_poisonous_danger_level(void) const;
  int is_potion(void) const;
  int is_projectile(void) const;
  int is_red_blooded(void) const;
  int is_red_blood(void) const;
  int is_red_splatter(void) const;
  int is_removeable_if_out_of_slots(void) const;
  int is_resurrectable(void) const;
  int is_ring(void) const;
  int is_ripple(void) const;
  int is_rock(void) const;
  int is_rusty(void) const;
  int is_secret_door(void) const;
  int is_sewer_wall(void) const;
  int is_shallow_water(void) const;
  int is_shield(void) const;
  int is_shovable_and_sticky(void) const;
  int is_shovable(void) const;
  int is_skillstone(void) const;
  int is_skill(void) const;
  int is_slippery(void) const;
  int is_smoke(void) const;
  int is_snake(void) const;
  int is_soft(void) const;
  int is_spawner(void) const;
  int is_spider(void) const;
  int is_spiderweb(void) const;
  int is_staff(void) const;
  int is_steal_item_chance_d1000(void) const;
  int is_steam(void) const;
  int is_sticky(void) const;
  int is_stone(void) const;
  int is_sword(void) const;
  int is_target_radial(void) const;
  int is_target_select(void) const;
  int is_temperature_change_sensitive(void) const;
  int is_temperature_sensitive(void) const;
  int is_the_grid(void) const;
  int is_thief(void) const;
  int is_throwable(void) const;
  int is_throw_blocker(void) const;
  int is_tickable(void) const;
  int is_tireless(void) const;
  int is_tmp_thing(void) const;
  int is_torch(void) const;
  int is_treasure_chest(void) const;
  int is_treasure_class_a(void) const;
  int is_treasure_class_b(void) const;
  int is_treasure_class_c(void) const;
  int is_treasure_type(void) const;
  int is_treasure(void) const;
  int is_undead(void) const;
  int is_usable(void) const;
  int is_used_when_thrown(void) const;
  int is_very_combustible(void) const;
  int is_very_hard(void) const;
  int is_very_heavy(void) const;
  int is_wall_dungeon(void) const;
  int is_wall(void) const;
  int is_wand_or_staff(void) const;
  int is_wand(void) const;
  int is_weapon_class_a(void) const;
  int is_weapon_class_b(void) const;
  int is_weapon_class_c(void) const;
  int is_weapon(void) const;
  int is_wet_grass(void) const;
  int is_wooden(void) const;
  int item_height(void) const;
  int item_width(void) const;
  int jump_distance_mod(void) const;
  int jump_distance(void) const;
  int light_dist(void) const;
  int melting_chance_d1000(void) const;
  int minion_limit(void) const;
  int move_speed_mod(void) const;
  int move_speed(void) const;
  int noise_additional_on_jump_end(void) const;
  int noise_additional_on_teleporting(void) const;
  int noise_blocker(void) const;
  int noise_decibels_hearing(void) const;
  int noise_on_born(void) const;
  int noise_on_dropping(void) const;
  int noise_on_moving(void) const;
  int noise_on_open(void) const;
  int noise_on_you_are_hit_and_now_dead(void) const;
  int noise_on_you_are_hit_but_still_alive(void) const;
  int normal_placement_rules(void) const;
  int on_death_drop_all_items(void) const;
  int on_death_is_open(void) const;
  int range_max(void) const;
  int rarity(void) const;
  int shove_strength_mod(void) const;
  int shove_strength(void) const;
  int spawn_group_radius(void) const;
  int stamina_drain_on_attacking(void) const;
  int stamina_drain_on_using(void) const;
  int stamina(void) const;
  int stat_att_mod(void) const;
  int stat_att_penalty_when_idle_max(void) const;
  int stat_att_penalty_when_idle(void) const;
  int stat_att_penalty_when_in_deep_water(void) const;
  int stat_att_penalty_when_in_shallow_water(void) const;
  int stat_att_penalty_when_stuck_max(void) const;
  int stat_att_penalty_when_stuck(void) const;
  int stat_att(void) const;
  int stat_con_mod(void) const;
  int stat_con(void) const;
  int stat_def_mod(void) const;
  int stat_def_penalty_when_idle_max(void) const;
  int stat_def_penalty_when_idle(void) const;
  int stat_def_penalty_when_in_deep_water(void) const;
  int stat_def_penalty_when_in_shallow_water(void) const;
  int stat_def_penalty_when_stuck_max(void) const;
  int stat_def_penalty_when_stuck(void) const;
  int stat_def(void) const;
  int stat_dex_mod(void) const;
  int stat_dex(void) const;
  int stat_luck_mod(void) const;
  int stat_luck(void) const;
  int stats02(void) const;
  int stats03(void) const;
  int stats04(void) const;
  int stats05(void) const;
  int stats06(void) const;
  int stats07(void) const;
  int stats09(void) const;
  int stat_str_mod(void) const;
  int stat_str(void) const;
  int teleport_distance(void) const;
  int temperature(void) const;
  int thing_size(void) const;
  int tick_prio(void) const;
  int unused_chance1_d1000(void) const;
  int unused_chance2_d1000(void) const;
  int unused_chance3_d1000(void) const;
  int unused_chance4_d1000(void) const;
  int unused_chance5_d1000(void) const;
  int unused_chance6_d1000(void) const;
  int unused_flag103(void) const;
  int unused_flag10(void) const;
  int unused_flag11(void) const;
  int unused_flag123(void) const;
  int unused_flag12(void) const;
  int unused_flag13(void) const;
  int unused_flag14(void) const;
  int unused_flag15(void) const;
  int unused_flag16(void) const;
  int unused_flag17(void) const;
  int unused_flag18(void) const;
  int unused_flag19(void) const;
  int unused_flag1(void) const;
  int unused_flag20(void) const;
  int unused_flag21(void) const;
  int unused_flag22(void) const;
  int unused_flag23(void) const;
  int unused_flag24(void) const;
  int unused_flag25(void) const;
  int unused_flag26(void) const;
  int unused_flag27(void) const;
  int unused_flag28(void) const;
  int unused_flag29(void) const;
  int unused_flag2(void) const;
  int unused_flag30(void) const;
  int unused_flag31(void) const;
  int unused_flag32(void) const;
  int unused_flag33(void) const;
  int unused_flag34(void) const;
  int unused_flag35(void) const;
  int unused_flag36(void) const;
  int unused_flag37(void) const;
  int unused_flag38(void) const;
  int unused_flag39(void) const;
  int unused_flag3(void) const;
  int unused_flag40(void) const;
  int unused_flag41(void) const;
  int unused_flag42(void) const;
  int unused_flag43(void) const;
  int unused_flag44(void) const;
  int unused_flag45(void) const;
  int unused_flag46(void) const;
  int unused_flag47(void) const;
  int unused_flag48(void) const;
  int unused_flag49(void) const;
  int unused_flag4(void) const;
  int unused_flag50(void) const;
  int unused_flag51(void) const;
  int unused_flag52(void) const;
  int unused_flag53(void) const;
  int unused_flag54(void) const;
  int unused_flag55(void) const;
  int unused_flag56(void) const;
  int unused_flag57(void) const;
  int unused_flag58(void) const;
  int unused_flag59(void) const;
  int unused_flag5(void) const;
  int is_internal(void) const;
  int unused_flag6(void) const;
  int unused_flag7(void) const;
  int unused_flag87(void) const;
  int unused_flag8(void) const;
  int unused_flag9(void) const;
  int weapon_damage(void) const;

  void aggression_pct_set(int v);
  void ai_detect_secret_doors_set(int v);
  void ai_obstacle_set(int v);
  void ai_resent_count_set(int v);
  void ai_shove_chance_d1000_set(int v);
  void ai_wanderer_set(int v);
  void appearing_chance_d1000_set(int v);
  void attack_eater_set(int v);
  void attack_engulf_chance_d1000_set(int v);
  void attack_humanoid_set(int v);
  void attack_living_set(int v);
  void attack_lunge_set(int v);
  void attack_meat_set(int v);
  void attack_no_msg_set(int v);
  void attacks_per_round_set(int v);
  void attack_undead_set(int v);
  void blast_max_radius_set(int v);
  void blast_min_radius_set(int v);
  void blit_bot_off_set(int v);
  void blit_left_off_set(int v);
  void blit_right_off_set(int v);
  void blit_top_off_set(int v);
  void capacity_height_set(int v);
  void capacity_width_set(int v);
  void charge_count_set(int v);
  void collateral_damage_pct_set(int v);
  void collision_attack_set(int v);
  void collision_check_set(int v);
  void collision_hit_180_set(int v);
  void collision_hit_360_set(int v);
  void collision_hit_adj_set(int v);
  void collision_hit_priority_set(int v);
  void collision_hit_two_tiles_ahead_set(int v);
  void crit_chance_d10000_set(int v);
  void damaged_chance_d10000_set(int v);
  void damage_received_doubled_from_acid_set(int v);
  void damage_received_doubled_from_cold_set(int v);
  void damage_received_doubled_from_fire_set(int v);
  void damage_received_doubled_from_necrosis_set(int v);
  void damage_received_doubled_from_poison_set(int v);
  void damage_received_doubled_from_water_set(int v);
  void distance_avoid_set(int v);
  void distance_leader_max_set(int v);
  void distance_minion_vision_shared_set(int v);
  void distance_mob_max_set(int v);
  void distance_recruitment_max_set(int v);
  void distance_throw_set(int v);
  void distance_vision_set(int v);
  void is_eater_of_amulets_set(int v);
  void is_eater_of_armor_set(int v);
  void is_eater_of_boots_set(int v);
  void is_eater_of_cloaks_set(int v);
  void is_eater_of_gauntlets_set(int v);
  void is_eater_of_helmets_set(int v);
  void is_eater_of_rings_set(int v);
  void is_eater_of_shields_set(int v);
  void is_eater_of_staffs_set(int v);
  void is_eater_of_wands_set(int v);
  void is_eater_of_weapons_set(int v);
  void enchant_level_set(int v);
  void enchant_max_set(int v);
  void environ_avoids_acid_set(int v);
  void environ_avoids_cold_set(int v);
  void environ_avoids_fire_set(int v);
  void environ_avoids_necrosis_set(int v);
  void environ_avoids_poison_set(int v);
  void environ_avoids_water_set(int v);
  void equip_carry_anim_set(const std::string &v);
  void gfx_anim_use_set(const std::string &v);
  void gfx_ascii_animated_set(int v);
  void gfx_ascii_bg_color_spread_alpha_set(int v);
  void gfx_ascii_bg_color_spread_blue_set(int v);
  void gfx_ascii_bg_color_spread_green_set(int v);
  void gfx_ascii_bg_color_spread_hue_set(int v);
  void gfx_ascii_bg_color_spread_red_set(int v);
  void gfx_ascii_color_is_animated_set(int v);
  void gfx_ascii_fade_with_dist_set(int v);
  void gfx_ascii_fg_color_spread_alpha_set(int v);
  void gfx_ascii_fg_color_spread_blue_set(int v);
  void gfx_ascii_fg_color_spread_green_set(int v);
  void gfx_ascii_fg_color_spread_hue_set(int v);
  void gfx_ascii_fg_color_spread_red_set(int v);
  void gfx_ascii_shown_as_gray_in_shadow_set(int v);
  void gfx_ascii_shown_in_bg_set(int v);
  void gfx_ascii_shown_set(int v);
  void gfx_glows_set(int v);
  void gfx_on_fire_anim_set(int v);
  void gfx_oversized_and_on_floor_set(int v);
  void gfx_pixelart_animated_can_hflip_set(int v);
  void gfx_pixelart_animated_can_vflip_set(int v);
  void gfx_pixelart_animated_no_dir_set(int v);
  void gfx_pixelart_animated_set(int v);
  void gfx_pixelart_anim_synced_with_owner_set(int v);
  void gfx_pixelart_attack_anim_set(int v);
  void gfx_pixelart_bounce_always_set(int v);
  void gfx_pixelart_bounce_on_move_set(int v);
  void gfx_pixelart_equip_carry_anim_set(int v);
  void gfx_pixelart_flickers_set(int v);
  void gfx_pixelart_health_bar_autohide_set(int v);
  void gfx_pixelart_health_bar_only_when_awake_set(int v);
  void gfx_pixelart_health_bar_shown_set(int v);
  void gfx_pixelart_shadow_long_set(int v);
  void gfx_pixelart_shadow_short_set(int v);
  void gfx_pixelart_shadow_solid_set(int v);
  void gfx_pixelart_shadow_very_short_set(int v);
  void gfx_pixelart_show_asleep_anim_set(int v);
  void gfx_pixelart_shown_in_bg_set(int v);
  void gfx_pixelart_show_outlined_set(int v);
  void gfx_pixelart_wobbles_when_hit_set(int v);
  void gfx_water_set(int v);
  void hunger_clock_tick_freq_set(int v);
  void hunger_is_hunger_level_hungry_at_pct_set(int v);
  void hunger_is_insatiable_set(int v);
  void hunger_is_hunger_level_starving_at_pct_set(int v);
  void internal_has_dir_anim_set(int v);
  void internal_has_hp_anim_set(int v);
  void is_able_to_attack_mobs_set(int v);
  void is_able_to_attack_owner_set(int v);
  void is_able_to_break_down_doors_set(int v);
  void is_able_to_break_out_of_ice_set(int v);
  void is_able_to_break_out_of_webs_set(int v);
  void is_able_to_burn_set(int v);
  void is_able_to_change_levels_set(int v);
  void is_able_to_collect_keys_set(int v);
  void is_able_to_enchant_items_set(int v);
  void is_able_to_fall_set(int v);
  void is_able_to_fire_at_set(int v);
  void is_able_to_follow_set(int v);
  void is_able_to_freeze_set(int v);
  void is_able_to_jump_attack_chance_d1000_set(int v);
  void is_able_to_jump_attack_set(int v);
  void is_able_to_jump_escape_set(int v);
  void is_able_to_jump_on_low_hp_chance_d1000_set(int v);
  void is_able_to_jump_onto_chance_d1000_set(int v);
  void is_able_to_jump_onto_set(int v);
  void is_able_to_jump_randomly_chance_d1000_set(int v);
  void is_able_to_jump_set(int v);
  void is_able_to_jump_without_tiring_set(int v);
  void is_able_to_learn_skills_set(int v);
  void is_able_to_move_diagonally_set(int v);
  void is_able_to_open_doors_set(int v);
  void is_able_to_see_in_the_dark_set(int v);
  void is_able_to_see_through_doors_set(int v);
  void is_able_to_shove_set(int v);
  void is_able_to_sleep_set(int v);
  void is_able_to_swim_set(int v);
  void is_able_to_teleport_attack_chance_d1000_set(int v);
  void is_able_to_teleport_attack_set(int v);
  void is_able_to_teleport_escape_set(int v);
  void is_able_to_teleport_without_tiring_set(int v);
  void is_able_to_tire_set(int v);
  void is_able_to_use_amulet_set(int v);
  void is_able_to_use_armor_set(int v);
  void is_able_to_use_boots_set(int v);
  void is_able_to_use_cloak_set(int v);
  void is_able_to_use_gauntlet_set(int v);
  void is_able_to_use_helmet_set(int v);
  void is_able_to_use_rings_set(int v);
  void is_able_to_use_shield_set(int v);
  void is_able_to_use_wands_or_staffs_set(int v);
  void is_able_to_use_weapons_set(int v);
  void is_able_to_walk_through_walls_set(int v);
  void is_acid_set(int v);
  void is_air_breathher_set(int v);
  void is_alive_on_end_of_anim_set(int v);
  void is_allied_with_set(const std::string &v);
  void is_always_hit_set(int v);
  void is_amulet_set(int v);
  void is_aquatic_set(int v);
  void is_armor_set(int v);
  void is_ascend_dungeon_set(int v);
  void is_ascend_sewer_set(int v);
  void is_asleep_initially_set(int v);
  void is_attackable_by_monst_set(int v);
  void is_attackable_by_player_set(int v);
  void is_auto_collect_item_set(int v);
  void is_auto_equipped_set(int v);
  void is_auto_throw_set(int v);
  void is_auto_use_set(int v);
  void is_bag_item_container_set(int v);
  void is_bag_item_not_stackable_set(int v);
  void is_bag_item_set(int v);
  void is_bag_set(int v);
  void is_barrel_set(int v);
  void is_basalt_set(int v);
  void is_biome_dungeon_set(int v);
  void is_biome_swamp_set(int v);
  void is_bleeder_set(int v);
  void is_block_of_ice_set(int v);
  void is_bones_set(int v);
  void is_boots_set(int v);
  void is_brazier_set(int v);
  void is_bridge_set(int v);
  void is_brittle_set(int v);
  void is_buff_set(int v);
  void is_carnivorous_plant_set(int v);
  void is_carrier_of_treasure_class_a_set(int v);
  void is_carrier_of_treasure_class_b_set(int v);
  void is_carrier_of_treasure_class_c_set(int v);
  void is_carrier_of_weapon_class_a_set(int v);
  void is_carrier_of_weapon_class_b_set(int v);
  void is_carrier_of_weapon_class_c_set(int v);
  void is_chasm_set(int v);
  void is_cloak_set(int v);
  void is_cold_set(int v);
  void is_collectable_set(int v);
  void is_collected_as_gold_set(int v);
  void is_collected_as_keys_set(int v);
  void is_combustible_set(int v);
  void is_corpse_on_death_set(int v);
  void is_corpse_with_bones_set(int v);
  void is_corridor_set(int v);
  void is_cowardly_set(int v);
  void is_critical_to_level_set(int v);
  void is_crushable_set(int v);
  void is_crystal_set(int v);
  void is_cursor_can_hover_over_set(int v);
  void is_cursor_can_hover_over_x2_click_set(int v);
  void is_cursor_path_blocker_set(int v);
  void is_cursor_path_hazard_set(int v);
  void is_cursor_path_set(int v);
  void is_cursor_set(int v);
  void is_dagger_set(int v);
  void is_dead_on_end_of_anim_set(int v);
  void is_dead_on_falling_set(int v);
  void is_dead_on_shove_set(int v);
  void is_debuff_set(int v);
  void is_debug_path_set(int v);
  void is_debug_type_set(int v);
  void is_deep_water_set(int v);
  void is_descend_dungeon_set(int v);
  void is_descend_sewer_set(int v);
  void is_described_when_hovering_over_set(int v);
  void is_destroyed_on_hit_or_miss_set(int v);
  void is_destroyed_on_hitting_set(int v);
  void is_dirt_set(int v);
  void is_door_set(int v);
  void is_droppable_set(int v);
  void is_dry_grass_set(int v);
  void is_dry_grass_trampled_set(int v);
  void is_eater_of_food_set(int v);
  void is_eater_of_green_blood_set(int v);
  void is_eater_of_jelly_set(int v);
  void is_eater_of_magical_items_set(int v);
  void is_eater_of_meat_set(int v);
  void is_eater_of_potions_set(int v);
  void is_eater_of_red_blood_set(int v);
  void is_eater_of_treasure_set(int v);
  void is_enchantable_set(int v);
  void is_enchantstone_set(int v);
  void is_engulfer_set(int v);
  void is_ethereal_mob_set(int v);
  void is_ethereal_set(int v);
  void is_exit_finder_set(int v);
  void is_explorer_set(int v);
  void is_explosion_set(int v);
  void is_fearless_set(int v);
  void is_fire_set(int v);
  void is_flat_set(int v);
  void is_floating_set(int v);
  void is_floor_deco_set(int v);
  void is_floor_set(int v);
  void is_flying_set(int v);
  void is_foilage_set(int v);
  void is_food_set(int v);
  void is_gas_blocker_set(int v);
  void is_gauntlet_set(int v);
  void is_gelatinous_set(int v);
  void is_glass_set(int v);
  void is_gold_set(int v);
  void is_green_blooded_set(int v);
  void is_green_blood_set(int v);
  void is_green_splatter_set(int v);
  void is_hard_set(int v);
  void is_hazard_set(int v);
  void is_health_booster_set(int v);
  void is_heavy_set(int v);
  void is_helmet_set(int v);
  void is_hittable_set(int v);
  void is_humanoid_set(int v);
  void is_immune_to_acid_set(int v);
  void is_immune_to_cold_set(int v);
  void is_immune_to_draining_set(int v);
  void is_immune_to_fire_set(int v);
  void is_immune_to_necrosis_set(int v);
  void is_immune_to_poison_set(int v);
  void is_immune_to_spiderwebs_set(int v);
  void is_immune_to_water_set(int v);
  void is_intelligent_set(int v);
  void is_interesting_set(int v);
  void is_item_carrier_set(int v);
  void is_item_collector_set(int v);
  void is_item_organic_set(int v);
  void is_item_set(int v);
  void is_item_targetted_set(int v);
  void is_jelly_set(int v);
  void is_jump_blocker_set(int v);
  void is_key_set(int v);
  void is_key_special_set(int v);
  void is_laser_set(int v);
  void is_lava_set(int v);
  void is_lifeless_set(int v);
  void is_light_blocker_for_monst_set(int v);
  void is_light_blocker_set(int v);
  void is_living_set(int v);
  void is_loggable_set(int v);
  void is_magical_set(int v);
  void is_map_beast_set(int v);
  void is_map_treasure_set(int v);
  void is_meat_set(int v);
  void is_meltable_set(int v);
  void is_metal_set(int v);
  void is_minion_set(int v);
  void is_mob_challenge_class_a_set(int v);
  void is_mob_challenge_class_b_set(int v);
  void is_mob_set(int v);
  void is_monst_class_a_set(int v);
  void is_monst_class_b_set(int v);
  void is_monst_class_c_set(int v);
  void is_monst_class_d_set(int v);
  void is_monst_class_e_set(int v);
  void is_monst_set(int v);
  void is_moveable_set(int v);
  void is_msg_set(int v);
  void is_necrotic_danger_level_set(int v);
  void is_no_tile_set(int v);
  void is_obs_destructable_set(int v);
  void is_obstacle_when_dead_set(int v);
  void is_obs_wall_or_door_set(int v);
  void is_openable_set(int v);
  void is_organic_set(int v);
  void is_pack_set(int v);
  void is_pillar_set(int v);
  void is_plant_set(int v);
  void is_player_set(int v);
  void is_poisonous_danger_level_set(int v);
  void is_potion_set(int v);
  void is_projectile_set(int v);
  void is_red_blooded_set(int v);
  void is_red_blood_set(int v);
  void is_red_splatter_set(int v);
  void is_removeable_if_out_of_slots_set(int v);
  void is_resurrectable_set(int v);
  void is_ring_set(int v);
  void is_ripple_set(int v);
  void is_rock_set(int v);
  void is_rusty_set(int v);
  void is_secret_door_set(int v);
  void is_sewer_wall_set(int v);
  void is_shallow_water_set(int v);
  void is_shield_set(int v);
  void is_shovable_and_sticky_set(int v);
  void is_shovable_set(int v);
  void is_skill_set(int v);
  void is_skillstone_set(int v);
  void is_slippery_set(int v);
  void is_smoke_set(int v);
  void is_snake_set(int v);
  void is_soft_set(int v);
  void is_spawner_set(int v);
  void is_spider_set(int v);
  void is_spiderweb_set(int v);
  void is_staff_set(int v);
  void is_steal_item_chance_d1000_set(int v);
  void is_steam_set(int v);
  void is_sticky_set(int v);
  void is_stone_set(int v);
  void is_sword_set(int v);
  void is_target_radial_set(int v);
  void is_target_select_set(int v);
  void is_temperature_change_sensitive_set(int v);
  void is_temperature_sensitive_set(int v);
  void is_the_grid_set(int v);
  void is_thief_set(int v);
  void is_throwable_set(int v);
  void is_throw_blocker_set(int v);
  void is_tickable_set(int v);
  void is_tireless_set(int v);
  void is_tmp_thing_set(int v);
  void is_torch_set(int v);
  void is_treasure_chest_set(int v);
  void is_treasure_class_a_set(int v);
  void is_treasure_class_b_set(int v);
  void is_treasure_class_c_set(int v);
  void is_treasure_set(int v);
  void is_treasure_type_set(int v);
  void is_undead_set(int v);
  void is_usable_set(int v);
  void is_used_when_thrown_set(int v);
  void is_very_combustible_set(int v);
  void is_very_hard_set(int v);
  void is_very_heavy_set(int v);
  void is_wall_dungeon_set(int v);
  void is_wall_set(int v);
  void is_wand_set(int v);
  void is_weapon_class_a_set(int v);
  void is_weapon_class_b_set(int v);
  void is_weapon_class_c_set(int v);
  void is_weapon_set(int v);
  void is_wet_grass_set(int v);
  void is_wooden_set(int v);
  void item_height_set(int v);
  void item_width_set(int v);
  void jump_distance_mod_set(int v);
  void jump_distance_set(int v);
  void light_color_set(const std::string &v);
  void light_dist_set(int v);
  void melting_chance_d1000_set(int v);
  void minion_limit_set(int v);
  void move_speed_mod_set(int v);
  void move_speed_set(int v);
  void name_set(const std::string &v);
  void noise_additional_on_jump_end_set(int v);
  void noise_additional_on_teleporting_set(int v);
  void noise_blocker_set(int v);
  void noise_decibels_hearing_set(int v);
  void noise_on_born_set(int v);
  void noise_on_dropping_set(int v);
  void noise_on_moving_set(int v);
  void noise_on_open_set(int v);
  void noise_on_you_are_hit_and_now_dead_set(int v);
  void noise_on_you_are_hit_but_still_alive_set(int v);
  void normal_placement_rules_set(int v);
  void on_attacking_dmg_acid_do_set(const std::string &v);
  void on_attacking_dmg_cold_do_set(const std::string &v);
  void on_attacking_dmg_crush_do_set(const std::string &v);
  void on_attacking_dmg_digest_do_set(const std::string &v);
  void on_attacking_dmg_draining_do_set(const std::string &v);
  void on_attacking_dmg_energy_do_set(const std::string &v);
  void on_attacking_dmg_fire_do_set(const std::string &v);
  void on_attacking_dmg_future1_do_set(const std::string &v);
  void on_attacking_dmg_bite_do_set(const std::string &v);
  void on_attacking_dmg_claw_do_set(const std::string &v);
  void on_attacking_dmg_lightning_do_set(const std::string &v);
  void on_attacking_dmg_melee_do_set(const std::string &v);
  void on_attacking_dmg_nat_att_do_set(const std::string &v);
  void on_attacking_dmg_necrosis_do_set(const std::string &v);
  void on_attacking_dmg_poison_do_set(const std::string &v);
  void on_attacking_dmg_stat_att_do_set(const std::string &v);
  void on_attacking_dmg_stat_con_do_set(const std::string &v);
  void on_attacking_dmg_stat_str_do_set(const std::string &v);
  void on_attacking_dmg_water_do_set(const std::string &v);
  void on_awake_do_set(const std::string &v);
  void on_born_do_set(const std::string &v);
  void on_death_do_set(const std::string &v);
  void on_death_drop_all_items_set(int v);
  void on_death_is_open_set(int v);
  void on_death_of_a_follower_do_set(const std::string &v);
  void on_death_of_my_leader_do_set(const std::string &v);
  void on_dropped_do_set(const std::string &v);
  void on_enchant_do_set(const std::string &v);
  void on_equip_do_set(const std::string &v);
  void on_fall_do_set(const std::string &v);
  void on_final_use_do_set(const std::string &v);
  void on_firing_at_something_do_set(const std::string &v);
  void on_get_text_long_description_do_set(const std::string &v);
  void on_jump_do_set(const std::string &v);
  void on_lifespan_tick_do_set(const std::string &v);
  void on_move_do_set(const std::string &v);
  void on_open_do_set(const std::string &v);
  void on_owner_add_do_set(const std::string &v);
  void on_owner_attack_dmg_acid_do_set(const std::string &v);
  void on_owner_attack_dmg_cold_do_set(const std::string &v);
  void on_owner_attack_dmg_crush_do_set(const std::string &v);
  void on_owner_attack_dmg_digest_do_set(const std::string &v);
  void on_owner_attack_dmg_draining_do_set(const std::string &v);
  void on_owner_attack_dmg_energy_do_set(const std::string &v);
  void on_owner_attack_dmg_fire_do_set(const std::string &v);
  void on_owner_attack_dmg_future1_do_set(const std::string &v);
  void on_owner_attack_dmg_bite_do_set(const std::string &v);
  void on_owner_attack_dmg_claw_do_set(const std::string &v);
  void on_owner_attack_dmg_lightning_do_set(const std::string &v);
  void on_owner_attack_dmg_melee_do_set(const std::string &v);
  void on_owner_attack_dmg_nat_att_do_set(const std::string &v);
  void on_owner_attack_dmg_necrosis_do_set(const std::string &v);
  void on_owner_attack_dmg_poison_do_set(const std::string &v);
  void on_owner_attack_dmg_stat_att_do_set(const std::string &v);
  void on_owner_attack_dmg_stat_con_do_set(const std::string &v);
  void on_owner_attack_dmg_stat_str_do_set(const std::string &v);
  void on_owner_attack_dmg_water_do_set(const std::string &v);
  void on_owner_receive_dmg_acid_do_set(const std::string &v);
  void on_owner_receive_dmg_cold_do_set(const std::string &v);
  void on_owner_receive_dmg_crush_do_set(const std::string &v);
  void on_owner_receive_dmg_digest_do_set(const std::string &v);
  void on_owner_receive_dmg_draining_do_set(const std::string &v);
  void on_owner_receive_dmg_energy_do_set(const std::string &v);
  void on_owner_receive_dmg_fire_do_set(const std::string &v);
  void on_owner_receive_dmg_future1_do_set(const std::string &v);
  void on_owner_receive_dmg_bite_do_set(const std::string &v);
  void on_owner_receive_dmg_claw_do_set(const std::string &v);
  void on_owner_receive_dmg_lightning_do_set(const std::string &v);
  void on_owner_receive_dmg_melee_do_set(const std::string &v);
  void on_owner_receive_dmg_nat_att_do_set(const std::string &v);
  void on_owner_receive_dmg_necrosis_do_set(const std::string &v);
  void on_owner_receive_dmg_poison_do_set(const std::string &v);
  void on_owner_receive_dmg_stat_att_do_set(const std::string &v);
  void on_owner_receive_dmg_stat_con_do_set(const std::string &v);
  void on_owner_receive_dmg_stat_str_do_set(const std::string &v);
  void on_owner_receive_dmg_water_do_set(const std::string &v);
  void on_owner_remove_do_set(const std::string &v);
  void on_polymorphed_do_set(const std::string &v);
  void on_receiving_dmg_acid_do_set(const std::string &v);
  void on_receiving_dmg_cold_do_set(const std::string &v);
  void on_receiving_dmg_crush_do_set(const std::string &v);
  void on_receiving_dmg_digest_do_set(const std::string &v);
  void on_receiving_dmg_draining_do_set(const std::string &v);
  void on_receiving_dmg_energy_do_set(const std::string &v);
  void on_receiving_dmg_fire_do_set(const std::string &v);
  void on_receiving_dmg_future1_do_set(const std::string &v);
  void on_receiving_dmg_bite_do_set(const std::string &v);
  void on_receiving_dmg_claw_do_set(const std::string &v);
  void on_receiving_dmg_lightning_do_set(const std::string &v);
  void on_receiving_dmg_melee_do_set(const std::string &v);
  void on_receiving_dmg_nat_att_do_set(const std::string &v);
  void on_receiving_dmg_necrosis_do_set(const std::string &v);
  void on_receiving_dmg_poison_do_set(const std::string &v);
  void on_receiving_dmg_stat_att_do_set(const std::string &v);
  void on_receiving_dmg_stat_con_do_set(const std::string &v);
  void on_receiving_dmg_stat_str_do_set(const std::string &v);
  void on_receiving_dmg_water_do_set(const std::string &v);
  void on_resting_do_set(const std::string &v);
  void on_stuck_do_set(const std::string &v);
  void on_swing_do_set(const std::string &v);
  void on_teleport_do_set(const std::string &v);
  void on_thrown_do_set(const std::string &v);
  void on_tick_do_set(const std::string &v);
  void on_unequip_do_set(const std::string &v);
  void on_use_do_set(const std::string &v);
  void on_waiting_do_set(const std::string &v);
  void on_you_are_declared_a_follower_do_set(const std::string &v);
  void on_you_are_declared_leader_do_set(const std::string &v);
  void on_you_are_hit_and_now_dead_do_set(const std::string &v);
  void on_you_are_hit_but_dodge_it_do_set(const std::string &v);
  void on_you_are_hit_but_still_alive_do_set(const std::string &v);
  void on_you_are_on_fire_do_set(const std::string &v);
  void on_you_nat_att_do_set(const std::string &v);
  void range_max_set(int v);
  void rarity_set(int v);
  void shove_strength_mod_set(int v);
  void shove_strength_set(int v);
  void spawn_group_radius_set(int v);
  void spawn_on_shoved_set(const std::string &v);
  void stamina_drain_on_attacking_set(int v);
  void stamina_drain_on_using_set(int v);
  void stamina_set(int v);
  void stat_att_mod_set(int v);
  void stat_att_penalty_when_idle_max_set(int v);
  void stat_att_penalty_when_idle_set(int v);
  void stat_att_penalty_when_in_deep_water_set(int v);
  void stat_att_penalty_when_in_shallow_water_set(int v);
  void stat_att_penalty_when_stuck_max_set(int v);
  void stat_att_penalty_when_stuck_set(int v);
  void stat_att_set(int v);
  void stat_con_mod_set(int v);
  void stat_con_set(int v);
  void stat_def_mod_set(int v);
  void stat_def_penalty_when_idle_max_set(int v);
  void stat_def_penalty_when_idle_set(int v);
  void stat_def_penalty_when_in_deep_water_set(int v);
  void stat_def_penalty_when_in_shallow_water_set(int v);
  void stat_def_penalty_when_stuck_max_set(int v);
  void stat_def_penalty_when_stuck_set(int v);
  void stat_def_set(int v);
  void stat_dex_mod_set(int v);
  void stat_dex_set(int v);
  void stat_luck_mod_set(int v);
  void stat_luck_set(int v);
  void stats02_set(int v);
  void stats03_set(int v);
  void stats04_set(int v);
  void stats05_set(int v);
  void stats06_set(int v);
  void stats07_set(int v);
  void stats09_set(int v);
  void stat_str_mod_set(int v);
  void stat_str_set(int v);
  void str1_set(const std::string &v);
  void str2_set(const std::string &v);
  void str4_set(const std::string &v);
  void target_name_laser_set(const std::string &v);
  void target_name_projectile_set(const std::string &v);
  void target_name_radial_set(const std::string &v);
  void teleport_distance_set(int v);
  void temperature_set(int v);
  void text_a_or_an_set(const std::string &v);
  void text_debuff_set(const std::string &v);
  void text_enchant_set(const std::string &v);
  void text_hits_set(const std::string &v);
  void text_long_description2_set(const std::string &v);
  void text_long_description3_set(const std::string &v);
  void text_long_description_set(const std::string &v);
  void text_long_name_set(const std::string &v);
  void text_short_description_set(const std::string &v);
  void text_short_name_set(const std::string &v);
  void text_skill_set(const std::string &v);
  void text_title_set(const std::string &v);
  void text_unused1_set(const std::string &v);
  void text_unused2_set(const std::string &v);
  void text_unused3_set(const std::string &v);
  void text_unused_set(const std::string &v);
  void thing_size_set(int v);
  void tick_prio_set(int v);
  void unused_chance1_d1000_set(int v);
  void unused_chance2_d1000_set(int v);
  void unused_chance3_d1000_set(int v);
  void unused_chance4_d1000_set(int v);
  void unused_chance5_d1000_set(int v);
  void unused_chance6_d1000_set(int v);
  void unused_flag103_set(int v);
  void unused_flag10_set(int v);
  void unused_flag11_set(int v);
  void unused_flag123_set(int v);
  void unused_flag12_set(int v);
  void unused_flag13_set(int v);
  void unused_flag14_set(int v);
  void unused_flag15_set(int v);
  void unused_flag16_set(int v);
  void unused_flag17_set(int v);
  void unused_flag18_set(int v);
  void unused_flag19_set(int v);
  void unused_flag1_set(int v);
  void unused_flag20_set(int v);
  void unused_flag21_set(int v);
  void unused_flag22_set(int v);
  void unused_flag23_set(int v);
  void unused_flag24_set(int v);
  void unused_flag25_set(int v);
  void unused_flag26_set(int v);
  void unused_flag27_set(int v);
  void unused_flag28_set(int v);
  void unused_flag29_set(int v);
  void unused_flag2_set(int v);
  void unused_flag30_set(int v);
  void unused_flag31_set(int v);
  void unused_flag32_set(int v);
  void unused_flag33_set(int v);
  void unused_flag34_set(int v);
  void unused_flag35_set(int v);
  void unused_flag36_set(int v);
  void unused_flag37_set(int v);
  void unused_flag38_set(int v);
  void unused_flag39_set(int v);
  void unused_flag3_set(int v);
  void unused_flag40_set(int v);
  void unused_flag41_set(int v);
  void unused_flag42_set(int v);
  void unused_flag43_set(int v);
  void unused_flag44_set(int v);
  void unused_flag45_set(int v);
  void unused_flag46_set(int v);
  void unused_flag47_set(int v);
  void unused_flag48_set(int v);
  void unused_flag49_set(int v);
  void unused_flag4_set(int v);
  void unused_flag50_set(int v);
  void unused_flag51_set(int v);
  void unused_flag52_set(int v);
  void unused_flag53_set(int v);
  void unused_flag54_set(int v);
  void unused_flag55_set(int v);
  void unused_flag56_set(int v);
  void unused_flag57_set(int v);
  void unused_flag58_set(int v);
  void unused_flag59_set(int v);
  void unused_flag5_set(int v);
  void is_internal_set(int v);
  void unused_flag6_set(int v);
  void unused_flag7_set(int v);
  void unused_flag87_set(int v);
  void unused_flag8_set(int v);
  void unused_flag9_set(int v);
  void weapon_damage_set(int v);
  void weapon_use_distance_set(int v);
  void z_depth_set(int v);
  void z_prio_set(int v);

  void damage_water_chance_d1000_set(int index, int v);
  void damage_acid_chance_d1000_set(int index, int v);
  void damage_cold_chance_d1000_set(int index, int v);
  void damage_crush_chance_d1000_set(int index, int v);
  void damage_digest_chance_d1000_set(int index, int v);
  void damage_energy_chance_d1000_set(int index, int v);
  void damage_fire_chance_d1000_set(int index, int v);
  void damage_future1_chance_d1000_set(int index, int v);
  void damage_bite_chance_d1000_set(int index, int v);
  void damage_claw_chance_d1000_set(int index, int v);
  void damage_lightning_chance_d1000_set(int index, int v);
  void damage_melee_chance_d1000_set(int index, int v);
  void damage_nat_att_chance_d1000_set(int index, int v);
  void damage_necrosis_chance_d1000_set(int index, int v);
  void damage_draining_chance_d1000_set(int index, int v);
  void damage_poison_chance_d1000_set(int index, int v);

  inline int gfx_pixelart_animated(void) const { return _gfx_pixelart_animated; }
};

Tilep tp_first_tile(class Tp *);

class Tp *string2tp(const char **s);
class Tp *string2tp(const std::string &s, int *len);
class Tp *string2tp(const std::wstring &s, int *len);
class Tp *tp_find(const std::string &name);
class Tp *tp_find(uint32_t id);
class Tp *tp_load(int id, const std::string &file, const std::string &text_long_name,
                  const std::string &text_short_name);
class Tp *tp_random_ascend_dungeon(void);
class Tp *tp_random_ascend_sewer(void);
class Tp *tp_random_barrel(void);
class Tp *tp_random_bones(void);
class Tp *tp_random_brazier(void);
class Tp *tp_random_deco(void);
class Tp *tp_random_descend_dungeon(void);
class Tp *tp_random_descend_sewer(void);
class Tp *tp_random_dirt(void);
class Tp *tp_random_door(void);
class Tp *tp_random_dry_grass(void);
class Tp *tp_random_enchantstone(void);
class Tp *tp_random_ethereal_mob(void);
class Tp *tp_random_floor(void);
class Tp *tp_random_foilage(void);
class Tp *tp_random_food(void);
class Tp *tp_random_gold(void);
class Tp *tp_random_green_blood(void);
class Tp *tp_random_green_splatter(void);
class Tp *tp_random_item_class_a(void);
class Tp *tp_random_item_class_b(void);
class Tp *tp_random_item_class_c(void);
class Tp *tp_random_item_not_a_container_class_a(void);
class Tp *tp_random_item_not_a_container_class_b(void);
class Tp *tp_random_item_not_a_container_class_c(void);
class Tp *tp_random_key(void);
class Tp *tp_random_mob_challenge_class_a(void);
class Tp *tp_random_mob_challenge_class_b(void);
class Tp *tp_random_mob(void);
class Tp *tp_random_monst_class_a(void);
class Tp *tp_random_monst_class_b(void);
class Tp *tp_random_monst_class_c(void);
class Tp *tp_random_monst_class_d(void);
class Tp *tp_random_monst_class_e(void);
class Tp *tp_random_monst(void);
class Tp *tp_random_potion(void);
class Tp *tp_random_red_blood(void);
class Tp *tp_random_red_splatter(void);
class Tp *tp_random_ring_class_a(void);
class Tp *tp_random_ring_class_b(void);
class Tp *tp_random_ring_class_c(void);
class Tp *tp_random_ring(void);
class Tp *tp_random_ripple(void);
class Tp *tp_random_rock(void);
class Tp *tp_random_secret_door(void);
class Tp *tp_random_sewer_wall(void);
class Tp *tp_random_skillstone(void);
class Tp *tp_random_spiderweb(void);
class Tp *tp_random_treasure_class_a(void);
class Tp *tp_random_treasure_class_b(void);
class Tp *tp_random_treasure_class_c(void);
class Tp *tp_random_treasure(void);
class Tp *tp_random_wall_dungeon(void);
class Tp *tp_random_wand_or_staff_class_a(void);
class Tp *tp_random_wand_or_staff_class_b(void);
class Tp *tp_random_wand_or_staff_class_c(void);
class Tp *tp_random_wand_or_staff(void);
class Tp *tp_random_weapon_class_a(void);
class Tp *tp_random_weapon_class_b(void);
class Tp *tp_random_weapon_class_c(void);
class Tp *tp_random_weapon(void);
class Tp *tp_random_wet_grass(void);

const Tpidmap &tp_get_skills(void);

uint8_t tp_init(void);

void tp_fini(void);
void tp_random_init(void);
void tp_fixup(void);
void tp_assign_allies(void);
void tp_get_id(const std::string &tp_name, int *id);

enum {
  THING_DIR_NONE,
  THING_DIR_DOWN,
  THING_DIR_UP,
  THING_DIR_LEFT,
  THING_DIR_RIGHT,
  THING_DIR_TL,
  THING_DIR_BL,
  THING_DIR_TR,
  THING_DIR_BR,
};

extern Tpidmap   tp_id_map;
extern Tpnamemap tp_name_map;

#endif // THING_TEMPLATE_H
