// Ramdisk data for files that due to licensing cannot be exposed

.globl data_ui_box0_tga_start_
data_ui_box0_tga_start_:
.incbin "../data/gfx/ui_box0.tga"
.globl data_ui_box0_tga_end_
data_ui_box0_tga_end_:

.globl data___tiles3_tga_start_
data___tiles3_tga_start_:
.incbin "../data/gfx/._tiles3.tga"
.globl data___tiles3_tga_end_
data___tiles3_tga_end_:

.globl data_ui_vert2_tga_start_
data_ui_vert2_tga_start_:
.incbin "../data/gfx/ui_vert2.tga"
.globl data_ui_vert2_tga_end_
data_ui_vert2_tga_end_:

.globl data_ui_credits_bg_tga_start_
data_ui_credits_bg_tga_start_:
.incbin "../data/gfx/ui_credits_bg.tga"
.globl data_ui_credits_bg_tga_end_
data_ui_credits_bg_tga_end_:

.globl data_tiles3_deep_water_tga_start_
data_tiles3_deep_water_tga_start_:
.incbin "../data/gfx/tiles3_deep_water.tga"
.globl data_tiles3_deep_water_tga_end_
data_tiles3_deep_water_tga_end_:

.globl data_blaster_wav_start_
data_blaster_wav_start_:
.incbin "../data/sounds/abilities/blaster.wav"
.globl data_blaster_wav_end_
data_blaster_wav_end_:

.globl data___disarm_multi_a_wav_start_
data___disarm_multi_a_wav_start_:
.incbin "../data/sounds/abilities/._disarm_multi_a.wav"
.globl data___disarm_multi_a_wav_end_
data___disarm_multi_a_wav_end_:

.globl data_disarm_single_wav_start_
data_disarm_single_wav_start_:
.incbin "../data/sounds/abilities/disarm_single.wav"
.globl data_disarm_single_wav_end_
data_disarm_single_wav_end_:

.globl data_woosh_b_wav_start_
data_woosh_b_wav_start_:
.incbin "../data/sounds/abilities/woosh_b.wav"
.globl data_woosh_b_wav_end_
data_woosh_b_wav_end_:

.globl data___bazooka_wav_start_
data___bazooka_wav_start_:
.incbin "../data/sounds/abilities/._bazooka.wav"
.globl data___bazooka_wav_end_
data___bazooka_wav_end_:

.globl data_reload_wav_start_
data_reload_wav_start_:
.incbin "../data/sounds/abilities/reload.wav"
.globl data_reload_wav_end_
data_reload_wav_end_:

.globl data___laser_a_wav_start_
data___laser_a_wav_start_:
.incbin "../data/sounds/abilities/._laser_a.wav"
.globl data___laser_a_wav_end_
data___laser_a_wav_end_:

.globl data_hiss7_wav_start_
data_hiss7_wav_start_:
.incbin "../data/sounds/creatures/hiss7.wav"
.globl data_hiss7_wav_end_
data_hiss7_wav_end_:

.globl data___wings_wav_start_
data___wings_wav_start_:
.incbin "../data/sounds/creatures/._wings.wav"
.globl data___wings_wav_end_
data___wings_wav_end_:

.globl data_wings_wav_start_
data_wings_wav_start_:
.incbin "../data/sounds/creatures/wings.wav"
.globl data_wings_wav_end_
data_wings_wav_end_:

.globl data___76962__michel88__deaths_wav_start_
data___76962__michel88__deaths_wav_start_:
.incbin "../data/sounds/creatures/._76962__michel88__deaths.wav"
.globl data___76962__michel88__deaths_wav_end_
data___76962__michel88__deaths_wav_end_:

.globl data_hiss2_wav_start_
data_hiss2_wav_start_:
.incbin "../data/sounds/creatures/hiss2.wav"
.globl data_hiss2_wav_end_
data_hiss2_wav_end_:

.globl data_slime5_wav_start_
data_slime5_wav_start_:
.incbin "../data/sounds/creatures/slime5.wav"
.globl data_slime5_wav_end_
data_slime5_wav_end_:

.globl data_magic_crumble_wav_start_
data_magic_crumble_wav_start_:
.incbin "../data/sounds/impacts/magic_crumble.wav"
.globl data_magic_crumble_wav_end_
data_magic_crumble_wav_end_:

.globl data___magic_dust_a_wav_start_
data___magic_dust_a_wav_start_:
.incbin "../data/sounds/impacts/._magic_dust_a.wav"
.globl data___magic_dust_a_wav_end_
data___magic_dust_a_wav_end_:

.globl data_splash2_wav_start_
data_splash2_wav_start_:
.incbin "../data/sounds/impacts/splash2.wav"
.globl data_splash2_wav_end_
data_splash2_wav_end_:

.globl data___434462__dersuperanton__getting_hit_hugh_wav_start_
data___434462__dersuperanton__getting_hit_hugh_wav_start_:
.incbin "../data/sounds/impacts/._434462__dersuperanton__getting-hit-hugh.wav"
.globl data___434462__dersuperanton__getting_hit_hugh_wav_end_
data___434462__dersuperanton__getting_hit_hugh_wav_end_:

.globl data___hit_wav_start_
data___hit_wav_start_:
.incbin "../data/sounds/impacts/._hit.wav"
.globl data___hit_wav_end_
data___hit_wav_end_:

.globl data___magic_dust_b_wav_start_
data___magic_dust_b_wav_start_:
.incbin "../data/sounds/impacts/._magic_dust_b.wav"
.globl data___magic_dust_b_wav_end_
data___magic_dust_b_wav_end_:

.globl data___score_wav_start_
data___score_wav_start_:
.incbin "../data/sounds/interface/._score.wav"
.globl data___score_wav_end_
data___score_wav_end_:

.globl data_gold_wav_start_
data_gold_wav_start_:
.incbin "../data/sounds/interface/gold.wav"
.globl data_gold_wav_end_
data_gold_wav_end_:

.globl data___level_up_wav_start_
data___level_up_wav_start_:
.incbin "../data/sounds/interface/._level_up.wav"
.globl data___level_up_wav_end_
data___level_up_wav_end_:

.globl data_click_wav_start_
data_click_wav_start_:
.incbin "../data/sounds/interface/click.wav"
.globl data_click_wav_end_
data_click_wav_end_:

.globl data___mushroom_wav_start_
data___mushroom_wav_start_:
.incbin "../data/sounds/misc/._mushroom.wav"
.globl data___mushroom_wav_end_
data___mushroom_wav_end_:

.globl data_twing_wav_start_
data_twing_wav_start_:
.incbin "../data/sounds/misc/twing.wav"
.globl data_twing_wav_end_
data_twing_wav_end_:

.globl data___open_wav_start_
data___open_wav_start_:
.incbin "../data/sounds/misc/._open.wav"
.globl data___open_wav_end_
data___open_wav_end_:

.globl data_footsteps8_wav_start_
data_footsteps8_wav_start_:
.incbin "../data/sounds/misc/footsteps8.wav"
.globl data_footsteps8_wav_end_
data_footsteps8_wav_end_:

.globl data_step_wav_start_
data_step_wav_start_:
.incbin "../data/sounds/misc/step.wav"
.globl data_step_wav_end_
data_step_wav_end_:

.globl data___wave_wav_start_
data___wave_wav_start_:
.incbin "../data/sounds/misc/._wave.wav"
.globl data___wave_wav_end_
data___wave_wav_end_:

.globl data___scramble_wav_start_
data___scramble_wav_start_:
.incbin "../data/sounds/misc/._scramble.wav"
.globl data___scramble_wav_end_
data___scramble_wav_end_:

.globl data_mutation_wav_start_
data_mutation_wav_start_:
.incbin "../data/sounds/status/mutation.wav"
.globl data_mutation_wav_end_
data_mutation_wav_end_:

.globl data___disease_wav_start_
data___disease_wav_start_:
.incbin "../data/sounds/status/._disease.wav"
.globl data___disease_wav_end_
data___disease_wav_end_:

