// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_fg4_tga_start_
data_title_fg4_tga_start_:
.incbin "../data/gfx/title_fg4.tga"
.globl data_title_fg4_tga_end_
data_title_fg4_tga_end_:

.globl data_title_splash_tga_start_
data_title_splash_tga_start_:
.incbin "../data/gfx/title_splash.tga"
.globl data_title_splash_tga_end_
data_title_splash_tga_end_:

.globl data_ui_vert2_tga_start_
data_ui_vert2_tga_start_:
.incbin "../data/gfx/ui_vert2.tga"
.globl data_ui_vert2_tga_end_
data_ui_vert2_tga_end_:

.globl data_tiles3_tga_start_
data_tiles3_tga_start_:
.incbin "../data/gfx/tiles3.tga"
.globl data_tiles3_tga_end_
data_tiles3_tga_end_:

.globl data_ui_status_bar_tga_start_
data_ui_status_bar_tga_start_:
.incbin "../data/gfx/ui_status_bar.tga"
.globl data_ui_status_bar_tga_end_
data_ui_status_bar_tga_end_:

.globl data_disarm_success_wav_start_
data_disarm_success_wav_start_:
.incbin "../data/sounds/abilities/disarm_success.wav"
.globl data_disarm_success_wav_end_
data_disarm_success_wav_end_:

.globl data_woosh_b_wav_start_
data_woosh_b_wav_start_:
.incbin "../data/sounds/abilities/woosh_b.wav"
.globl data_woosh_b_wav_end_
data_woosh_b_wav_end_:

.globl data_reload_wav_start_
data_reload_wav_start_:
.incbin "../data/sounds/abilities/reload.wav"
.globl data_reload_wav_end_
data_reload_wav_end_:

.globl data_growl5_wav_start_
data_growl5_wav_start_:
.incbin "../data/sounds/creatures/growl5.wav"
.globl data_growl5_wav_end_
data_growl5_wav_end_:

.globl data_hiss3_wav_start_
data_hiss3_wav_start_:
.incbin "../data/sounds/creatures/hiss3.wav"
.globl data_hiss3_wav_end_
data_hiss3_wav_end_:

.globl data_beetle_wav_start_
data_beetle_wav_start_:
.incbin "../data/sounds/creatures/beetle.wav"
.globl data_beetle_wav_end_
data_beetle_wav_end_:

.globl data_mouse_wav_start_
data_mouse_wav_start_:
.incbin "../data/sounds/creatures/mouse.wav"
.globl data_mouse_wav_end_
data_mouse_wav_end_:

.globl data_frog_wav_start_
data_frog_wav_start_:
.incbin "../data/sounds/creatures/frog.wav"
.globl data_frog_wav_end_
data_frog_wav_end_:

.globl data_257709__vmgraw__grunt_2_wav_start_
data_257709__vmgraw__grunt_2_wav_start_:
.incbin "../data/sounds/impacts/257709__vmgraw__grunt-2.wav"
.globl data_257709__vmgraw__grunt_2_wav_end_
data_257709__vmgraw__grunt_2_wav_end_:

.globl data_explosion_e_wav_start_
data_explosion_e_wav_start_:
.incbin "../data/sounds/impacts/explosion_e.wav"
.globl data_explosion_e_wav_end_
data_explosion_e_wav_end_:

.globl data_spike_trap_b_wav_start_
data_spike_trap_b_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_b.wav"
.globl data_spike_trap_b_wav_end_
data_spike_trap_b_wav_end_:

.globl data_lose_a_wav_start_
data_lose_a_wav_start_:
.incbin "../data/sounds/interface/lose_a.wav"
.globl data_lose_a_wav_end_
data_lose_a_wav_end_:

.globl data_error_wav_start_
data_error_wav_start_:
.incbin "../data/sounds/interface/error.wav"
.globl data_error_wav_end_
data_error_wav_end_:

.globl data_close_shut_wav_start_
data_close_shut_wav_start_:
.incbin "../data/sounds/misc/close_shut.wav"
.globl data_close_shut_wav_end_
data_close_shut_wav_end_:

.globl data_zong_wav_start_
data_zong_wav_start_:
.incbin "../data/sounds/misc/zong.wav"
.globl data_zong_wav_end_
data_zong_wav_end_:

.globl data_wave_wav_start_
data_wave_wav_start_:
.incbin "../data/sounds/misc/wave.wav"
.globl data_wave_wav_end_
data_wave_wav_end_:

.globl data_shut_wav_start_
data_shut_wav_start_:
.incbin "../data/sounds/misc/shut.wav"
.globl data_shut_wav_end_
data_shut_wav_end_:

.globl data_disease_wav_start_
data_disease_wav_start_:
.incbin "../data/sounds/status/disease.wav"
.globl data_disease_wav_end_
data_disease_wav_end_:

