// Ramdisk data for files that due to licensing cannot be exposed

.align 4
.globl data_ui_box5_tga_start_
data_ui_box5_tga_start_:
.incbin "../data/gfx/ui_box5.tga"
.align 4
.globl data_ui_box5_tga_end_
data_ui_box5_tga_end_:

.align 4
.globl data_laser_energy_tga_start_
data_laser_energy_tga_start_:
.incbin "../data/gfx/laser_energy.tga"
.align 4
.globl data_laser_energy_tga_end_
data_laser_energy_tga_end_:

.align 4
.globl data_ui_bag_highlighted_tga_start_
data_ui_bag_highlighted_tga_start_:
.incbin "../data/gfx/ui_bag_highlighted.tga"
.align 4
.globl data_ui_bag_highlighted_tga_end_
data_ui_bag_highlighted_tga_end_:

.align 4
.globl data_title_fg2_tga_start_
data_title_fg2_tga_start_:
.incbin "../data/gfx/title_fg2.tga"
.align 4
.globl data_title_fg2_tga_end_
data_title_fg2_tga_end_:

.align 4
.globl data_projectile_fire_tga_start_
data_projectile_fire_tga_start_:
.incbin "../data/gfx/projectile_fire.tga"
.align 4
.globl data_projectile_fire_tga_end_
data_projectile_fire_tga_end_:

.align 4
.globl data_bazooka_wav_start_
data_bazooka_wav_start_:
.incbin "../data/sounds/abilities/bazooka.wav"
.align 4
.globl data_bazooka_wav_end_
data_bazooka_wav_end_:

.align 4
.globl data_fire_c_wav_start_
data_fire_c_wav_start_:
.incbin "../data/sounds/abilities/fire_c.wav"
.align 4
.globl data_fire_c_wav_end_
data_fire_c_wav_end_:

.align 4
.globl data_disarm_single_wav_start_
data_disarm_single_wav_start_:
.incbin "../data/sounds/abilities/disarm_single.wav"
.align 4
.globl data_disarm_single_wav_end_
data_disarm_single_wav_end_:

.align 4
.globl data_laser_a_wav_start_
data_laser_a_wav_start_:
.incbin "../data/sounds/abilities/laser_a.wav"
.align 4
.globl data_laser_a_wav_end_
data_laser_a_wav_end_:

.align 4
.globl data_growl5_wav_start_
data_growl5_wav_start_:
.incbin "../data/sounds/creatures/growl5.wav"
.align 4
.globl data_growl5_wav_end_
data_growl5_wav_end_:

.align 4
.globl data_slime5_wav_start_
data_slime5_wav_start_:
.incbin "../data/sounds/creatures/slime5.wav"
.align 4
.globl data_slime5_wav_end_
data_slime5_wav_end_:

.align 4
.globl data_slime8_wav_start_
data_slime8_wav_start_:
.incbin "../data/sounds/creatures/slime8.wav"
.align 4
.globl data_slime8_wav_end_
data_slime8_wav_end_:

.align 4
.globl data_148975__adam_n__squelch_1_wav_start_
data_148975__adam_n__squelch_1_wav_start_:
.incbin "../data/sounds/creatures/148975__adam_n__squelch_1.wav"
.align 4
.globl data_148975__adam_n__squelch_1_wav_end_
data_148975__adam_n__squelch_1_wav_end_:

.align 4
.globl data_spike_trap_a_wav_start_
data_spike_trap_a_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_a.wav"
.align 4
.globl data_spike_trap_a_wav_end_
data_spike_trap_a_wav_end_:

.align 4
.globl data_impact_a_wav_start_
data_impact_a_wav_start_:
.incbin "../data/sounds/impacts/impact_a.wav"
.align 4
.globl data_impact_a_wav_end_
data_impact_a_wav_end_:

.align 4
.globl data_splash4_wav_start_
data_splash4_wav_start_:
.incbin "../data/sounds/impacts/splash4.wav"
.align 4
.globl data_splash4_wav_end_
data_splash4_wav_end_:

.align 4
.globl data_explosion_d_wav_start_
data_explosion_d_wav_start_:
.incbin "../data/sounds/impacts/explosion_d.wav"
.align 4
.globl data_explosion_d_wav_end_
data_explosion_d_wav_end_:

.align 4
.globl data_lose_b_wav_start_
data_lose_b_wav_start_:
.incbin "../data/sounds/interface/lose_b.wav"
.align 4
.globl data_lose_b_wav_end_
data_lose_b_wav_end_:

.align 4
.globl data_select_a_wav_start_
data_select_a_wav_start_:
.incbin "../data/sounds/interface/select_a.wav"
.align 4
.globl data_select_a_wav_end_
data_select_a_wav_end_:

.align 4
.globl data_bay_door_open_wav_start_
data_bay_door_open_wav_start_:
.incbin "../data/sounds/misc/bay_door_open.wav"
.align 4
.globl data_bay_door_open_wav_end_
data_bay_door_open_wav_end_:

.align 4
.globl data_scatter_wav_start_
data_scatter_wav_start_:
.incbin "../data/sounds/misc/scatter.wav"
.align 4
.globl data_scatter_wav_end_
data_scatter_wav_end_:

.align 4
.globl data_zong_wav_start_
data_zong_wav_start_:
.incbin "../data/sounds/misc/zong.wav"
.align 4
.globl data_zong_wav_end_
data_zong_wav_end_:

.align 4
.globl data_wiggle_a_wav_start_
data_wiggle_a_wav_start_:
.incbin "../data/sounds/misc/wiggle_a.wav"
.align 4
.globl data_wiggle_a_wav_end_
data_wiggle_a_wav_end_:

.align 4
.globl data_disease_wav_start_
data_disease_wav_start_:
.incbin "../data/sounds/status/disease.wav"
.align 4
.globl data_disease_wav_end_
data_disease_wav_end_:

