// Ramdisk data for files that due to licensing cannot be exposed

.globl data_tiles1_floors_tga_start_
data_tiles1_floors_tga_start_:
.incbin "../data/gfx/tiles1_floors.tga"
.globl data_tiles1_floors_tga_end_
data_tiles1_floors_tga_end_:

.globl data_ui_horiz1_tga_start_
data_ui_horiz1_tga_start_:
.incbin "../data/gfx/ui_horiz1.tga"
.globl data_ui_horiz1_tga_end_
data_ui_horiz1_tga_end_:

.globl data_background_tga_start_
data_background_tga_start_:
.incbin "../data/gfx/background.tga"
.globl data_background_tga_end_
data_background_tga_end_:

.globl data_ui_vert1_tga_start_
data_ui_vert1_tga_start_:
.incbin "../data/gfx/ui_vert1.tga"
.globl data_ui_vert1_tga_end_
data_ui_vert1_tga_end_:

.globl data_ui_box6_tga_start_
data_ui_box6_tga_start_:
.incbin "../data/gfx/ui_box6.tga"
.globl data_ui_box6_tga_end_
data_ui_box6_tga_end_:

.globl data_jump_b_wav_start_
data_jump_b_wav_start_:
.incbin "../data/sounds/abilities/jump_b.wav"
.globl data_jump_b_wav_end_
data_jump_b_wav_end_:

.globl data_woosh_a_wav_start_
data_woosh_a_wav_start_:
.incbin "../data/sounds/abilities/woosh_a.wav"
.globl data_woosh_a_wav_end_
data_woosh_a_wav_end_:

.globl data_special_a_wav_start_
data_special_a_wav_start_:
.incbin "../data/sounds/abilities/special_a.wav"
.globl data_special_a_wav_end_
data_special_a_wav_end_:

.globl data_lightning_b_wav_start_
data_lightning_b_wav_start_:
.incbin "../data/sounds/abilities/lightning_b.wav"
.globl data_lightning_b_wav_end_
data_lightning_b_wav_end_:

.globl data_growl2_wav_start_
data_growl2_wav_start_:
.incbin "../data/sounds/creatures/growl2.wav"
.globl data_growl2_wav_end_
data_growl2_wav_end_:

.globl data_hiss4_wav_start_
data_hiss4_wav_start_:
.incbin "../data/sounds/creatures/hiss4.wav"
.globl data_hiss4_wav_end_
data_hiss4_wav_end_:

.globl data_148975__adam_n__squelch_1_wav_start_
data_148975__adam_n__squelch_1_wav_start_:
.incbin "../data/sounds/creatures/148975__adam_n__squelch_1.wav"
.globl data_148975__adam_n__squelch_1_wav_end_
data_148975__adam_n__squelch_1_wav_end_:

.globl data_slime5_wav_start_
data_slime5_wav_start_:
.incbin "../data/sounds/creatures/slime5.wav"
.globl data_slime5_wav_end_
data_slime5_wav_end_:

.globl data_impact_b_wav_start_
data_impact_b_wav_start_:
.incbin "../data/sounds/impacts/impact_b.wav"
.globl data_impact_b_wav_end_
data_impact_b_wav_end_:

.globl data_explosion_b_wav_start_
data_explosion_b_wav_start_:
.incbin "../data/sounds/impacts/explosion_b.wav"
.globl data_explosion_b_wav_end_
data_explosion_b_wav_end_:

.globl data_area_effect_a_wav_start_
data_area_effect_a_wav_start_:
.incbin "../data/sounds/impacts/area_effect_a.wav"
.globl data_area_effect_a_wav_end_
data_area_effect_a_wav_end_:

.globl data_splash4_wav_start_
data_splash4_wav_start_:
.incbin "../data/sounds/impacts/splash4.wav"
.globl data_splash4_wav_end_
data_splash4_wav_end_:

.globl data_bonus_wav_start_
data_bonus_wav_start_:
.incbin "../data/sounds/interface/bonus.wav"
.globl data_bonus_wav_end_
data_bonus_wav_end_:

.globl data_coin_wav_start_
data_coin_wav_start_:
.incbin "../data/sounds/interface/coin.wav"
.globl data_coin_wav_end_
data_coin_wav_end_:

.globl data_bay_door_close_wav_start_
data_bay_door_close_wav_start_:
.incbin "../data/sounds/misc/bay_door_close.wav"
.globl data_bay_door_close_wav_end_
data_bay_door_close_wav_end_:

.globl data_shriek_wav_start_
data_shriek_wav_start_:
.incbin "../data/sounds/misc/shriek.wav"
.globl data_shriek_wav_end_
data_shriek_wav_end_:

.globl data_resurrect_wav_start_
data_resurrect_wav_start_:
.incbin "../data/sounds/misc/resurrect.wav"
.globl data_resurrect_wav_end_
data_resurrect_wav_end_:

.globl data_footsteps4_wav_start_
data_footsteps4_wav_start_:
.incbin "../data/sounds/misc/footsteps4.wav"
.globl data_footsteps4_wav_end_
data_footsteps4_wav_end_:

.globl data_mutation_wav_start_
data_mutation_wav_start_:
.incbin "../data/sounds/status/mutation.wav"
.globl data_mutation_wav_end_
data_mutation_wav_end_:

