// Ramdisk data for files that due to licensing cannot be exposed

.globl data_ui_tile_bg_tga_start_
data_ui_tile_bg_tga_start_:
.incbin "../data/gfx/ui_tile_bg.tga"
.globl data_ui_tile_bg_tga_end_
data_ui_tile_bg_tga_end_:

.globl data_ui_dead_tga_start_
data_ui_dead_tga_start_:
.incbin "../data/gfx/ui_dead.tga"
.globl data_ui_dead_tga_end_
data_ui_dead_tga_end_:

.globl data_light_tga_start_
data_light_tga_start_:
.incbin "../data/gfx/light.tga"
.globl data_light_tga_end_
data_light_tga_end_:

.globl data_ui_box1_tga_start_
data_ui_box1_tga_start_:
.incbin "../data/gfx/ui_box1.tga"
.globl data_ui_box1_tga_end_
data_ui_box1_tga_end_:

.globl data_explosion_tga_start_
data_explosion_tga_start_:
.incbin "../data/gfx/explosion.tga"
.globl data_explosion_tga_end_
data_explosion_tga_end_:

