// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_fg1_tga_start_
data_title_fg1_tga_start_:
.incbin "../data/gfx/title_fg1.tga"
.globl data_title_fg1_tga_end_
data_title_fg1_tga_end_:

.globl data_blood_tga_start_
data_blood_tga_start_:
.incbin "../data/gfx/blood.tga"
.globl data_blood_tga_end_
data_blood_tga_end_:

.globl data_tiles3_sewer_water_tga_start_
data_tiles3_sewer_water_tga_start_:
.incbin "../data/gfx/tiles3_sewer_water.tga"
.globl data_tiles3_sewer_water_tga_end_
data_tiles3_sewer_water_tga_end_:

.globl data_ui_box2_tga_start_
data_ui_box2_tga_start_:
.incbin "../data/gfx/ui_box2.tga"
.globl data_ui_box2_tga_end_
data_ui_box2_tga_end_:

