// Ramdisk data for files that due to licensing cannot be exposed

.globl data_ui_box5_tga_start_
data_ui_box5_tga_start_:
.incbin "../data/gfx/ui_box5.tga"
.globl data_ui_box5_tga_end_
data_ui_box5_tga_end_:

.globl data_ui_tile_bg_tga_start_
data_ui_tile_bg_tga_start_:
.incbin "../data/gfx/ui_tile_bg.tga"
.globl data_ui_tile_bg_tga_end_
data_ui_tile_bg_tga_end_:

.globl data_ui_vert1_tga_start_
data_ui_vert1_tga_start_:
.incbin "../data/gfx/ui_vert1.tga"
.globl data_ui_vert1_tga_end_
data_ui_vert1_tga_end_:

.globl data_ui_box2_tga_start_
data_ui_box2_tga_start_:
.incbin "../data/gfx/ui_box2.tga"
.globl data_ui_box2_tga_end_
data_ui_box2_tga_end_:

.globl data_tiles3_deep_water_tga_start_
data_tiles3_deep_water_tga_start_:
.incbin "../data/gfx/tiles3_deep_water.tga"
.globl data_tiles3_deep_water_tga_end_
data_tiles3_deep_water_tga_end_:

.globl data___lightning_b_wav_start_
data___lightning_b_wav_start_:
.incbin "../data/sounds/abilities/._lightning_b.wav"
.globl data___lightning_b_wav_end_
data___lightning_b_wav_end_:

.globl data___disarm_multi_a_wav_start_
data___disarm_multi_a_wav_start_:
.incbin "../data/sounds/abilities/._disarm_multi_a.wav"
.globl data___disarm_multi_a_wav_end_
data___disarm_multi_a_wav_end_:

.globl data_heal_b_wav_start_
data_heal_b_wav_start_:
.incbin "../data/sounds/abilities/heal_b.wav"
.globl data_heal_b_wav_end_
data_heal_b_wav_end_:

.globl data___spell_b_wav_start_
data___spell_b_wav_start_:
.incbin "../data/sounds/abilities/._spell_b.wav"
.globl data___spell_b_wav_end_
data___spell_b_wav_end_:

.globl data___woosh_b_wav_start_
data___woosh_b_wav_start_:
.incbin "../data/sounds/abilities/._woosh_b.wav"
.globl data___woosh_b_wav_end_
data___woosh_b_wav_end_:

.globl data_swing_wav_start_
data_swing_wav_start_:
.incbin "../data/sounds/abilities/swing.wav"
.globl data_swing_wav_end_
data_swing_wav_end_:

.globl data_telepathy_wav_start_
data_telepathy_wav_start_:
.incbin "../data/sounds/abilities/telepathy.wav"
.globl data_telepathy_wav_end_
data_telepathy_wav_end_:

.globl data_bird_wav_start_
data_bird_wav_start_:
.incbin "../data/sounds/creatures/bird.wav"
.globl data_bird_wav_end_
data_bird_wav_end_:

.globl data_slime7_wav_start_
data_slime7_wav_start_:
.incbin "../data/sounds/creatures/slime7.wav"
.globl data_slime7_wav_end_
data_slime7_wav_end_:

.globl data_growl4_wav_start_
data_growl4_wav_start_:
.incbin "../data/sounds/creatures/growl4.wav"
.globl data_growl4_wav_end_
data_growl4_wav_end_:

.globl data_growl2_wav_start_
data_growl2_wav_start_:
.incbin "../data/sounds/creatures/growl2.wav"
.globl data_growl2_wav_end_
data_growl2_wav_end_:

.globl data_growl8_wav_start_
data_growl8_wav_start_:
.incbin "../data/sounds/creatures/growl8.wav"
.globl data_growl8_wav_end_
data_growl8_wav_end_:

.globl data_hiss3_wav_start_
data_hiss3_wav_start_:
.incbin "../data/sounds/creatures/hiss3.wav"
.globl data_hiss3_wav_end_
data_hiss3_wav_end_:

.globl data_spike_trap_a_wav_start_
data_spike_trap_a_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_a.wav"
.globl data_spike_trap_a_wav_end_
data_spike_trap_a_wav_end_:

.globl data_pit_trap_damage_wav_start_
data_pit_trap_damage_wav_start_:
.incbin "../data/sounds/impacts/pit_trap_damage.wav"
.globl data_pit_trap_damage_wav_end_
data_pit_trap_damage_wav_end_:

.globl data_443293__deathscyp__wood_break_wav_start_
data_443293__deathscyp__wood_break_wav_start_:
.incbin "../data/sounds/impacts/443293__deathscyp__wood-break.wav"
.globl data_443293__deathscyp__wood_break_wav_end_
data_443293__deathscyp__wood_break_wav_end_:

.globl data_splash4_wav_start_
data_splash4_wav_start_:
.incbin "../data/sounds/impacts/splash4.wav"
.globl data_splash4_wav_end_
data_splash4_wav_end_:

.globl data___area_effect_b_wav_start_
data___area_effect_b_wav_start_:
.incbin "../data/sounds/impacts/._area_effect_b.wav"
.globl data___area_effect_b_wav_end_
data___area_effect_b_wav_end_:

.globl data___pit_trap_damage_wav_start_
data___pit_trap_damage_wav_start_:
.incbin "../data/sounds/impacts/._pit_trap_damage.wav"
.globl data___pit_trap_damage_wav_end_
data___pit_trap_damage_wav_end_:

.globl data_lose_b_wav_start_
data_lose_b_wav_start_:
.incbin "../data/sounds/interface/lose_b.wav"
.globl data_lose_b_wav_end_
data_lose_b_wav_end_:

.globl data_select_b_wav_start_
data_select_b_wav_start_:
.incbin "../data/sounds/interface/select_b.wav"
.globl data_select_b_wav_end_
data_select_b_wav_end_:

.globl data_new_turn_wav_start_
data_new_turn_wav_start_:
.incbin "../data/sounds/interface/new_turn.wav"
.globl data_new_turn_wav_end_
data_new_turn_wav_end_:

.globl data___end_turn_wav_start_
data___end_turn_wav_start_:
.incbin "../data/sounds/interface/._end_turn.wav"
.globl data___end_turn_wav_end_
data___end_turn_wav_end_:

.globl data___wave_wav_start_
data___wave_wav_start_:
.incbin "../data/sounds/misc/._wave.wav"
.globl data___wave_wav_end_
data___wave_wav_end_:

.globl data___collect_b_wav_start_
data___collect_b_wav_start_:
.incbin "../data/sounds/misc/._collect_b.wav"
.globl data___collect_b_wav_end_
data___collect_b_wav_end_:

.globl data_twing_wav_start_
data_twing_wav_start_:
.incbin "../data/sounds/misc/twing.wav"
.globl data_twing_wav_end_
data_twing_wav_end_:

.globl data_footsteps4_wav_start_
data_footsteps4_wav_start_:
.incbin "../data/sounds/misc/footsteps4.wav"
.globl data_footsteps4_wav_end_
data_footsteps4_wav_end_:

.globl data_chime_wav_start_
data_chime_wav_start_:
.incbin "../data/sounds/misc/chime.wav"
.globl data_chime_wav_end_
data_chime_wav_end_:

.globl data_drop_wav_start_
data_drop_wav_start_:
.incbin "../data/sounds/misc/drop.wav"
.globl data_drop_wav_end_
data_drop_wav_end_:

.globl data_collect_a_wav_start_
data_collect_a_wav_start_:
.incbin "../data/sounds/misc/collect_a.wav"
.globl data_collect_a_wav_end_
data_collect_a_wav_end_:

.globl data_mutation_wav_start_
data_mutation_wav_start_:
.incbin "../data/sounds/status/mutation.wav"
.globl data_mutation_wav_end_
data_mutation_wav_end_:

.globl data___freeze_wav_start_
data___freeze_wav_start_:
.incbin "../data/sounds/status/._freeze.wav"
.globl data___freeze_wav_end_
data___freeze_wav_end_:

