// Ramdisk data for files that due to licensing cannot be exposed

.globl data_tiles1_floors_tga_start_
data_tiles1_floors_tga_start_:
.incbin "../data/gfx/tiles1_floors.tga"
.globl data_tiles1_floors_tga_end_
data_tiles1_floors_tga_end_:

.globl data_tiles3_lava_tga_start_
data_tiles3_lava_tga_start_:
.incbin "../data/gfx/tiles3_lava.tga"
.globl data_tiles3_lava_tga_end_
data_tiles3_lava_tga_end_:

.globl data_tiles3_chasm_tga_start_
data_tiles3_chasm_tga_start_:
.incbin "../data/gfx/tiles3_chasm.tga"
.globl data_tiles3_chasm_tga_end_
data_tiles3_chasm_tga_end_:

.globl data_ui_box0_tga_start_
data_ui_box0_tga_start_:
.incbin "../data/gfx/ui_box0.tga"
.globl data_ui_box0_tga_end_
data_ui_box0_tga_end_:

.globl data_tiles3_deep_water_tga_start_
data_tiles3_deep_water_tga_start_:
.incbin "../data/gfx/tiles3_deep_water.tga"
.globl data_tiles3_deep_water_tga_end_
data_tiles3_deep_water_tga_end_:

.globl data_heal_b_wav_start_
data_heal_b_wav_start_:
.incbin "../data/sounds/abilities/heal_b.wav"
.globl data_heal_b_wav_end_
data_heal_b_wav_end_:

.globl data_swing_wav_start_
data_swing_wav_start_:
.incbin "../data/sounds/abilities/swing.wav"
.globl data_swing_wav_end_
data_swing_wav_end_:

.globl data_shoot_b_wav_start_
data_shoot_b_wav_start_:
.incbin "../data/sounds/abilities/shoot_b.wav"
.globl data_shoot_b_wav_end_
data_shoot_b_wav_end_:

.globl data_bird_wav_start_
data_bird_wav_start_:
.incbin "../data/sounds/creatures/bird.wav"
.globl data_bird_wav_end_
data_bird_wav_end_:

.globl data_frog_wav_start_
data_frog_wav_start_:
.incbin "../data/sounds/creatures/frog.wav"
.globl data_frog_wav_end_
data_frog_wav_end_:

.globl data_magic_crumble_wav_start_
data_magic_crumble_wav_start_:
.incbin "../data/sounds/impacts/magic_crumble.wav"
.globl data_magic_crumble_wav_end_
data_magic_crumble_wav_end_:

.globl data_select_a_wav_start_
data_select_a_wav_start_:
.incbin "../data/sounds/interface/select_a.wav"
.globl data_select_a_wav_end_
data_select_a_wav_end_:

.globl data_1up_b_wav_start_
data_1up_b_wav_start_:
.incbin "../data/sounds/interface/1up_b.wav"
.globl data_1up_b_wav_end_
data_1up_b_wav_end_:

.globl data_bay_door_close_wav_start_
data_bay_door_close_wav_start_:
.incbin "../data/sounds/misc/bay_door_close.wav"
.globl data_bay_door_close_wav_end_
data_bay_door_close_wav_end_:

.globl data_whistle_wav_start_
data_whistle_wav_start_:
.incbin "../data/sounds/misc/whistle.wav"
.globl data_whistle_wav_end_
data_whistle_wav_end_:

.globl data_wave_wav_start_
data_wave_wav_start_:
.incbin "../data/sounds/misc/wave.wav"
.globl data_wave_wav_end_
data_wave_wav_end_:

.globl data_freeze_wav_start_
data_freeze_wav_start_:
.incbin "../data/sounds/status/freeze.wav"
.globl data_freeze_wav_end_
data_freeze_wav_end_:

