// Ramdisk data for files that due to licensing cannot be exposed

.globl data_weapons_tga_start_
data_weapons_tga_start_:
.incbin "../data/gfx/weapons.tga"
.globl data_weapons_tga_end_
data_weapons_tga_end_:

.globl data_tiles3_lava_tga_start_
data_tiles3_lava_tga_start_:
.incbin "../data/gfx/tiles3_lava.tga"
.globl data_tiles3_lava_tga_end_
data_tiles3_lava_tga_end_:

.globl data_light_tga_start_
data_light_tga_start_:
.incbin "../data/gfx/light.tga"
.globl data_light_tga_end_
data_light_tga_end_:

.globl data_ui_box1_tga_start_
data_ui_box1_tga_start_:
.incbin "../data/gfx/ui_box1.tga"
.globl data_ui_box1_tga_end_
data_ui_box1_tga_end_:

.globl data_ui_status_bar_tga_start_
data_ui_status_bar_tga_start_:
.incbin "../data/gfx/ui_status_bar.tga"
.globl data_ui_status_bar_tga_end_
data_ui_status_bar_tga_end_:

