// Ramdisk data for files that due to licensing cannot be exposed

.globl data___explosion_tga_start_
data___explosion_tga_start_:
.incbin "../data/gfx/._explosion.tga"
.globl data___explosion_tga_end_
data___explosion_tga_end_:

.globl data_title_small_tga_start_
data_title_small_tga_start_:
.incbin "../data/gfx/title_small.tga"
.globl data_title_small_tga_end_
data_title_small_tga_end_:

.globl data_solid_tga_start_
data_solid_tga_start_:
.incbin "../data/gfx/solid.tga"
.globl data_solid_tga_end_
data_solid_tga_end_:

.globl data_laser_energy_tga_start_
data_laser_energy_tga_start_:
.incbin "../data/gfx/laser_energy.tga"
.globl data_laser_energy_tga_end_
data_laser_energy_tga_end_:

.globl data_blood_tga_start_
data_blood_tga_start_:
.incbin "../data/gfx/blood.tga"
.globl data_blood_tga_end_
data_blood_tga_end_:

.globl data_ui_circle_tga_start_
data_ui_circle_tga_start_:
.incbin "../data/gfx/ui_circle.tga"
.globl data_ui_circle_tga_end_
data_ui_circle_tga_end_:

.globl data___special_a_wav_start_
data___special_a_wav_start_:
.incbin "../data/sounds/abilities/._special_a.wav"
.globl data___special_a_wav_end_
data___special_a_wav_end_:

.globl data___woosh_b_wav_start_
data___woosh_b_wav_start_:
.incbin "../data/sounds/abilities/._woosh_b.wav"
.globl data___woosh_b_wav_end_
data___woosh_b_wav_end_:

.globl data___reload_wav_start_
data___reload_wav_start_:
.incbin "../data/sounds/abilities/._reload.wav"
.globl data___reload_wav_end_
data___reload_wav_end_:

.globl data___teleport_wav_start_
data___teleport_wav_start_:
.incbin "../data/sounds/abilities/._teleport.wav"
.globl data___teleport_wav_end_
data___teleport_wav_end_:

.globl data_special_a_wav_start_
data_special_a_wav_start_:
.incbin "../data/sounds/abilities/special_a.wav"
.globl data_special_a_wav_end_
data_special_a_wav_end_:

.globl data_laser_a_wav_start_
data_laser_a_wav_start_:
.incbin "../data/sounds/abilities/laser_a.wav"
.globl data_laser_a_wav_end_
data_laser_a_wav_end_:

.globl data_sorcery_wav_start_
data_sorcery_wav_start_:
.incbin "../data/sounds/abilities/sorcery.wav"
.globl data_sorcery_wav_end_
data_sorcery_wav_end_:

.globl data_frog_wav_start_
data_frog_wav_start_:
.incbin "../data/sounds/creatures/frog.wav"
.globl data_frog_wav_end_
data_frog_wav_end_:

.globl data_growl10_wav_start_
data_growl10_wav_start_:
.incbin "../data/sounds/creatures/growl10.wav"
.globl data_growl10_wav_end_
data_growl10_wav_end_:

.globl data_hiss5_wav_start_
data_hiss5_wav_start_:
.incbin "../data/sounds/creatures/hiss5.wav"
.globl data_hiss5_wav_end_
data_hiss5_wav_end_:

.globl data_hiss6_wav_start_
data_hiss6_wav_start_:
.incbin "../data/sounds/creatures/hiss6.wav"
.globl data_hiss6_wav_end_
data_hiss6_wav_end_:

.globl data_slime6_wav_start_
data_slime6_wav_start_:
.incbin "../data/sounds/creatures/slime6.wav"
.globl data_slime6_wav_end_
data_slime6_wav_end_:

.globl data_explosion_a_wav_start_
data_explosion_a_wav_start_:
.incbin "../data/sounds/impacts/explosion_a.wav"
.globl data_explosion_a_wav_end_
data_explosion_a_wav_end_:

.globl data_explosion_b_wav_start_
data_explosion_b_wav_start_:
.incbin "../data/sounds/impacts/explosion_b.wav"
.globl data_explosion_b_wav_end_
data_explosion_b_wav_end_:

.globl data___spike_trap_a_wav_start_
data___spike_trap_a_wav_start_:
.incbin "../data/sounds/impacts/._spike_trap_a.wav"
.globl data___spike_trap_a_wav_end_
data___spike_trap_a_wav_end_:

.globl data_boom_a_wav_start_
data_boom_a_wav_start_:
.incbin "../data/sounds/impacts/boom_a.wav"
.globl data_boom_a_wav_end_
data_boom_a_wav_end_:

.globl data_82388__robinhood76__01308_man_hit_9_wav_start_
data_82388__robinhood76__01308_man_hit_9_wav_start_:
.incbin "../data/sounds/impacts/82388__robinhood76__01308_man_hit_9.wav"
.globl data_82388__robinhood76__01308_man_hit_9_wav_end_
data_82388__robinhood76__01308_man_hit_9_wav_end_:

.globl data___boom_b_wav_start_
data___boom_b_wav_start_:
.incbin "../data/sounds/impacts/._boom_b.wav"
.globl data___boom_b_wav_end_
data___boom_b_wav_end_:

.globl data_bonus_wav_start_
data_bonus_wav_start_:
.incbin "../data/sounds/interface/bonus.wav"
.globl data_bonus_wav_end_
data_bonus_wav_end_:

.globl data___1up_b_wav_start_
data___1up_b_wav_start_:
.incbin "../data/sounds/interface/._1up_b.wav"
.globl data___1up_b_wav_end_
data___1up_b_wav_end_:

.globl data___ding_wav_start_
data___ding_wav_start_:
.incbin "../data/sounds/interface/._ding.wav"
.globl data___ding_wav_end_
data___ding_wav_end_:

.globl data_coin_wav_start_
data_coin_wav_start_:
.incbin "../data/sounds/interface/coin.wav"
.globl data_coin_wav_end_
data_coin_wav_end_:

.globl data___gold_wav_start_
data___gold_wav_start_:
.incbin "../data/sounds/interface/._gold.wav"
.globl data___gold_wav_end_
data___gold_wav_end_:

.globl data_chime_wav_start_
data_chime_wav_start_:
.incbin "../data/sounds/misc/chime.wav"
.globl data_chime_wav_end_
data_chime_wav_end_:

.globl data___drip_wav_start_
data___drip_wav_start_:
.incbin "../data/sounds/misc/._drip.wav"
.globl data___drip_wav_end_
data___drip_wav_end_:

.globl data_footsteps7_wav_start_
data_footsteps7_wav_start_:
.incbin "../data/sounds/misc/footsteps7.wav"
.globl data_footsteps7_wav_end_
data_footsteps7_wav_end_:

.globl data___zong_wav_start_
data___zong_wav_start_:
.incbin "../data/sounds/misc/._zong.wav"
.globl data___zong_wav_end_
data___zong_wav_end_:

.globl data_scramble_wav_start_
data_scramble_wav_start_:
.incbin "../data/sounds/misc/scramble.wav"
.globl data_scramble_wav_end_
data_scramble_wav_end_:

.globl data_drip_wav_start_
data_drip_wav_start_:
.incbin "../data/sounds/misc/drip.wav"
.globl data_drip_wav_end_
data_drip_wav_end_:

.globl data_bay_door_open_wav_start_
data_bay_door_open_wav_start_:
.incbin "../data/sounds/misc/bay_door_open.wav"
.globl data_bay_door_open_wav_end_
data_bay_door_open_wav_end_:

.globl data_poison_wav_start_
data_poison_wav_start_:
.incbin "../data/sounds/status/poison.wav"
.globl data_poison_wav_end_
data_poison_wav_end_:

