// Ramdisk data for files that due to licensing cannot be exposed

.align 4
.globl data_laser_descent_tga_start_
data_laser_descent_tga_start_:
.incbin "../data/gfx/laser_descent.tga"
.align 4
.globl data_laser_descent_tga_end_
data_laser_descent_tga_end_:

.align 4
.globl data_laser_green_tga_start_
data_laser_green_tga_start_:
.incbin "../data/gfx/laser_green.tga"
.align 4
.globl data_laser_green_tga_end_
data_laser_green_tga_end_:

.align 4
.globl data_title_fg3_tga_start_
data_title_fg3_tga_start_:
.incbin "../data/gfx/title_fg3.tga"
.align 4
.globl data_title_fg3_tga_end_
data_title_fg3_tga_end_:

.align 4
.globl data_title_fg4_tga_start_
data_title_fg4_tga_start_:
.incbin "../data/gfx/title_fg4.tga"
.align 4
.globl data_title_fg4_tga_end_
data_title_fg4_tga_end_:

.align 4
.globl data_title_small_tga_start_
data_title_small_tga_start_:
.incbin "../data/gfx/title_small.tga"
.align 4
.globl data_title_small_tga_end_
data_title_small_tga_end_:

.align 4
.globl data_background_tga_start_
data_background_tga_start_:
.incbin "../data/gfx/background.tga"
.align 4
.globl data_background_tga_end_
data_background_tga_end_:

.align 4
.globl data_fire_b_wav_start_
data_fire_b_wav_start_:
.incbin "../data/sounds/abilities/fire_b.wav"
.align 4
.globl data_fire_b_wav_end_
data_fire_b_wav_end_:

.align 4
.globl data_jump_b_wav_start_
data_jump_b_wav_start_:
.incbin "../data/sounds/abilities/jump_b.wav"
.align 4
.globl data_jump_b_wav_end_
data_jump_b_wav_end_:

.align 4
.globl data_special_a_wav_start_
data_special_a_wav_start_:
.incbin "../data/sounds/abilities/special_a.wav"
.align 4
.globl data_special_a_wav_end_
data_special_a_wav_end_:

.align 4
.globl data_bird_wav_start_
data_bird_wav_start_:
.incbin "../data/sounds/creatures/bird.wav"
.align 4
.globl data_bird_wav_end_
data_bird_wav_end_:

.align 4
.globl data_swarm_wav_start_
data_swarm_wav_start_:
.incbin "../data/sounds/creatures/swarm.wav"
.align 4
.globl data_swarm_wav_end_
data_swarm_wav_end_:

.align 4
.globl data_slime3_wav_start_
data_slime3_wav_start_:
.incbin "../data/sounds/creatures/slime3.wav"
.align 4
.globl data_slime3_wav_end_
data_slime3_wav_end_:

.align 4
.globl data_growl8_wav_start_
data_growl8_wav_start_:
.incbin "../data/sounds/creatures/growl8.wav"
.align 4
.globl data_growl8_wav_end_
data_growl8_wav_end_:

.align 4
.globl data_hiss3_wav_start_
data_hiss3_wav_start_:
.incbin "../data/sounds/creatures/hiss3.wav"
.align 4
.globl data_hiss3_wav_end_
data_hiss3_wav_end_:

.align 4
.globl data_magic_crumble_wav_start_
data_magic_crumble_wav_start_:
.incbin "../data/sounds/impacts/magic_crumble.wav"
.align 4
.globl data_magic_crumble_wav_end_
data_magic_crumble_wav_end_:

.align 4
.globl data_splash1_wav_start_
data_splash1_wav_start_:
.incbin "../data/sounds/impacts/splash1.wav"
.align 4
.globl data_splash1_wav_end_
data_splash1_wav_end_:

.align 4
.globl data_boom_b_wav_start_
data_boom_b_wav_start_:
.incbin "../data/sounds/impacts/boom_b.wav"
.align 4
.globl data_boom_b_wav_end_
data_boom_b_wav_end_:

.align 4
.globl data_bonus_wav_start_
data_bonus_wav_start_:
.incbin "../data/sounds/interface/bonus.wav"
.align 4
.globl data_bonus_wav_end_
data_bonus_wav_end_:

.align 4
.globl data_select_b_wav_start_
data_select_b_wav_start_:
.incbin "../data/sounds/interface/select_b.wav"
.align 4
.globl data_select_b_wav_end_
data_select_b_wav_end_:

.align 4
.globl data_click_wav_start_
data_click_wav_start_:
.incbin "../data/sounds/interface/click.wav"
.align 4
.globl data_click_wav_end_
data_click_wav_end_:

.align 4
.globl data_footsteps5_wav_start_
data_footsteps5_wav_start_:
.incbin "../data/sounds/misc/footsteps5.wav"
.align 4
.globl data_footsteps5_wav_end_
data_footsteps5_wav_end_:

.align 4
.globl data_wave_wav_start_
data_wave_wav_start_:
.incbin "../data/sounds/misc/wave.wav"
.align 4
.globl data_wave_wav_end_
data_wave_wav_end_:

.align 4
.globl data_transistor_wav_start_
data_transistor_wav_start_:
.incbin "../data/sounds/misc/transistor.wav"
.align 4
.globl data_transistor_wav_end_
data_transistor_wav_end_:

.align 4
.globl data_footsteps7_wav_start_
data_footsteps7_wav_start_:
.incbin "../data/sounds/misc/footsteps7.wav"
.align 4
.globl data_footsteps7_wav_end_
data_footsteps7_wav_end_:

