// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_small_tga_start_
data_title_small_tga_start_:
.incbin "../data/gfx/title_small.tga"
.globl data_title_small_tga_end_
data_title_small_tga_end_:

.globl data_title_fg3_tga_start_
data_title_fg3_tga_start_:
.incbin "../data/gfx/title_fg3.tga"
.globl data_title_fg3_tga_end_
data_title_fg3_tga_end_:

.globl data_background_tga_start_
data_background_tga_start_:
.incbin "../data/gfx/background.tga"
.globl data_background_tga_end_
data_background_tga_end_:

.globl data_ui_vert1_tga_start_
data_ui_vert1_tga_start_:
.incbin "../data/gfx/ui_vert1.tga"
.globl data_ui_vert1_tga_end_
data_ui_vert1_tga_end_:

.globl data_tiles1_walls_tga_start_
data_tiles1_walls_tga_start_:
.incbin "../data/gfx/tiles1_walls.tga"
.globl data_tiles1_walls_tga_end_
data_tiles1_walls_tga_end_:

