// Ramdisk data for files that due to licensing cannot be exposed

.globl data_tiles1_monsts_and_items_tga_start_
data_tiles1_monsts_and_items_tga_start_:
.incbin "../data/gfx/tiles1_monsts_and_items.tga"
.globl data_tiles1_monsts_and_items_tga_end_
data_tiles1_monsts_and_items_tga_end_:

.globl data_title_fg2_tga_start_
data_title_fg2_tga_start_:
.incbin "../data/gfx/title_fg2.tga"
.globl data_title_fg2_tga_end_
data_title_fg2_tga_end_:

.globl data_ui_bag_tga_start_
data_ui_bag_tga_start_:
.incbin "../data/gfx/ui_bag.tga"
.globl data_ui_bag_tga_end_
data_ui_bag_tga_end_:

.globl data_title_bg_tga_start_
data_title_bg_tga_start_:
.incbin "../data/gfx/title_bg.tga"
.globl data_title_bg_tga_end_
data_title_bg_tga_end_:

.globl data_ui_box7_tga_start_
data_ui_box7_tga_start_:
.incbin "../data/gfx/ui_box7.tga"
.globl data_ui_box7_tga_end_
data_ui_box7_tga_end_:

.globl data_disarm_multi_b_wav_start_
data_disarm_multi_b_wav_start_:
.incbin "../data/sounds/abilities/disarm_multi_b.wav"
.globl data_disarm_multi_b_wav_end_
data_disarm_multi_b_wav_end_:

.globl data_bazooka_wav_start_
data_bazooka_wav_start_:
.incbin "../data/sounds/abilities/bazooka.wav"
.globl data_bazooka_wav_end_
data_bazooka_wav_end_:

.globl data_spell_b_wav_start_
data_spell_b_wav_start_:
.incbin "../data/sounds/abilities/spell_b.wav"
.globl data_spell_b_wav_end_
data_spell_b_wav_end_:

.globl data_telepathy_wav_start_
data_telepathy_wav_start_:
.incbin "../data/sounds/abilities/telepathy.wav"
.globl data_telepathy_wav_end_
data_telepathy_wav_end_:

.globl data_swarm_wav_start_
data_swarm_wav_start_:
.incbin "../data/sounds/creatures/swarm.wav"
.globl data_swarm_wav_end_
data_swarm_wav_end_:

.globl data_sear_wav_start_
data_sear_wav_start_:
.incbin "../data/sounds/impacts/sear.wav"
.globl data_sear_wav_end_
data_sear_wav_end_:

.globl data_spike_trap_b_wav_start_
data_spike_trap_b_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_b.wav"
.globl data_spike_trap_b_wav_end_
data_spike_trap_b_wav_end_:

.globl data_lose_b_wav_start_
data_lose_b_wav_start_:
.incbin "../data/sounds/interface/lose_b.wav"
.globl data_lose_b_wav_end_
data_lose_b_wav_end_:

.globl data_dong_wav_start_
data_dong_wav_start_:
.incbin "../data/sounds/interface/dong.wav"
.globl data_dong_wav_end_
data_dong_wav_end_:

.globl data_rebound_wav_start_
data_rebound_wav_start_:
.incbin "../data/sounds/misc/rebound.wav"
.globl data_rebound_wav_end_
data_rebound_wav_end_:

.globl data_unlock_wav_start_
data_unlock_wav_start_:
.incbin "../data/sounds/misc/unlock.wav"
.globl data_unlock_wav_end_
data_unlock_wav_end_:

.globl data_twing_wav_start_
data_twing_wav_start_:
.incbin "../data/sounds/misc/twing.wav"
.globl data_twing_wav_end_
data_twing_wav_end_:

.globl data_charm_wav_start_
data_charm_wav_start_:
.incbin "../data/sounds/status/charm.wav"
.globl data_charm_wav_end_
data_charm_wav_end_:

