// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_small_tga_start_
data_title_small_tga_start_:
.incbin "../data/gfx/title_small.tga"
.globl data_title_small_tga_end_
data_title_small_tga_end_:

.globl data_title_fg3_tga_start_
data_title_fg3_tga_start_:
.incbin "../data/gfx/title_fg3.tga"
.globl data_title_fg3_tga_end_
data_title_fg3_tga_end_:

.globl data_glow_tga_start_
data_glow_tga_start_:
.incbin "../data/gfx/glow.tga"
.globl data_glow_tga_end_
data_glow_tga_end_:

.globl data_ui_circle_tga_start_
data_ui_circle_tga_start_:
.incbin "../data/gfx/ui_circle.tga"
.globl data_ui_circle_tga_end_
data_ui_circle_tga_end_:

.globl data_tiles1_walls_tga_start_
data_tiles1_walls_tga_start_:
.incbin "../data/gfx/tiles1_walls.tga"
.globl data_tiles1_walls_tga_end_
data_tiles1_walls_tga_end_:

.globl data_disarm_single_wav_start_
data_disarm_single_wav_start_:
.incbin "../data/sounds/abilities/disarm_single.wav"
.globl data_disarm_single_wav_end_
data_disarm_single_wav_end_:

.globl data_blaster_wav_start_
data_blaster_wav_start_:
.incbin "../data/sounds/abilities/blaster.wav"
.globl data_blaster_wav_end_
data_blaster_wav_end_:

.globl data_teleport_wav_start_
data_teleport_wav_start_:
.incbin "../data/sounds/abilities/teleport.wav"
.globl data_teleport_wav_end_
data_teleport_wav_end_:

.globl data_summon_wav_start_
data_summon_wav_start_:
.incbin "../data/sounds/abilities/summon.wav"
.globl data_summon_wav_end_
data_summon_wav_end_:

.globl data_snake_wav_start_
data_snake_wav_start_:
.incbin "../data/sounds/creatures/snake.wav"
.globl data_snake_wav_end_
data_snake_wav_end_:

.globl data_explode_a_wav_start_
data_explode_a_wav_start_:
.incbin "../data/sounds/impacts/explode_a.wav"
.globl data_explode_a_wav_end_
data_explode_a_wav_end_:

.globl data_spike_trap_a_wav_start_
data_spike_trap_a_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_a.wav"
.globl data_spike_trap_a_wav_end_
data_spike_trap_a_wav_end_:

.globl data_paper_wav_start_
data_paper_wav_start_:
.incbin "../data/sounds/interface/paper.wav"
.globl data_paper_wav_end_
data_paper_wav_end_:

.globl data_error_wav_start_
data_error_wav_start_:
.incbin "../data/sounds/interface/error.wav"
.globl data_error_wav_end_
data_error_wav_end_:

.globl data_swerve_wav_start_
data_swerve_wav_start_:
.incbin "../data/sounds/misc/swerve.wav"
.globl data_swerve_wav_end_
data_swerve_wav_end_:

.globl data_scatter_wav_start_
data_scatter_wav_start_:
.incbin "../data/sounds/misc/scatter.wav"
.globl data_scatter_wav_end_
data_scatter_wav_end_:

.globl data_wiggle_a_wav_start_
data_wiggle_a_wav_start_:
.incbin "../data/sounds/misc/wiggle_a.wav"
.globl data_wiggle_a_wav_end_
data_wiggle_a_wav_end_:

.globl data_disease_wav_start_
data_disease_wav_start_:
.incbin "../data/sounds/status/disease.wav"
.globl data_disease_wav_end_
data_disease_wav_end_:

