// Ramdisk data for files that due to licensing cannot be exposed

.align 16
.globl data_glow_tga_start_
data_glow_tga_start_:
.incbin "../data/gfx/glow.tga"
.globl data_glow_tga_end_
data_glow_tga_end_:

.align 16
.globl data_tiles1_walls_tga_start_
data_tiles1_walls_tga_start_:
.incbin "../data/gfx/tiles1_walls.tga"
.globl data_tiles1_walls_tga_end_
data_tiles1_walls_tga_end_:

.align 16
.globl data_ui_credits_fg_tga_start_
data_ui_credits_fg_tga_start_:
.incbin "../data/gfx/ui_credits_fg.tga"
.globl data_ui_credits_fg_tga_end_
data_ui_credits_fg_tga_end_:

.align 16
.globl data_ui_status_bar_tga_start_
data_ui_status_bar_tga_start_:
.incbin "../data/gfx/ui_status_bar.tga"
.globl data_ui_status_bar_tga_end_
data_ui_status_bar_tga_end_:

.align 16
.globl data_ui_box3_tga_start_
data_ui_box3_tga_start_:
.incbin "../data/gfx/ui_box3.tga"
.globl data_ui_box3_tga_end_
data_ui_box3_tga_end_:

.align 16
.globl data___heal_b_wav_start_
data___heal_b_wav_start_:
.incbin "../data/sounds/abilities/._heal_b.wav"
.globl data___heal_b_wav_end_
data___heal_b_wav_end_:

.align 16
.globl data_attack_b_wav_start_
data_attack_b_wav_start_:
.incbin "../data/sounds/abilities/attack_b.wav"
.globl data_attack_b_wav_end_
data_attack_b_wav_end_:

.align 16
.globl data_fire_c_wav_start_
data_fire_c_wav_start_:
.incbin "../data/sounds/abilities/fire_c.wav"
.globl data_fire_c_wav_end_
data_fire_c_wav_end_:

.align 16
.globl data_disarm_multi_a_wav_start_
data_disarm_multi_a_wav_start_:
.incbin "../data/sounds/abilities/disarm_multi_a.wav"
.globl data_disarm_multi_a_wav_end_
data_disarm_multi_a_wav_end_:

.align 16
.globl data_disarm_single_wav_start_
data_disarm_single_wav_start_:
.incbin "../data/sounds/abilities/disarm_single.wav"
.globl data_disarm_single_wav_end_
data_disarm_single_wav_end_:

.align 16
.globl data_special_a_wav_start_
data_special_a_wav_start_:
.incbin "../data/sounds/abilities/special_a.wav"
.globl data_special_a_wav_end_
data_special_a_wav_end_:

.align 16
.globl data_laser_a_wav_start_
data_laser_a_wav_start_:
.incbin "../data/sounds/abilities/laser_a.wav"
.globl data_laser_a_wav_end_
data_laser_a_wav_end_:

.align 16
.globl data_growl9_wav_start_
data_growl9_wav_start_:
.incbin "../data/sounds/creatures/growl9.wav"
.globl data_growl9_wav_end_
data_growl9_wav_end_:

.align 16
.globl data_swarm_wav_start_
data_swarm_wav_start_:
.incbin "../data/sounds/creatures/swarm.wav"
.globl data_swarm_wav_end_
data_swarm_wav_end_:

.align 16
.globl data_hiss1_wav_start_
data_hiss1_wav_start_:
.incbin "../data/sounds/creatures/hiss1.wav"
.globl data_hiss1_wav_end_
data_hiss1_wav_end_:

.align 16
.globl data___jelly_wav_start_
data___jelly_wav_start_:
.incbin "../data/sounds/creatures/._jelly.wav"
.globl data___jelly_wav_end_
data___jelly_wav_end_:

.align 16
.globl data_growl7_wav_start_
data_growl7_wav_start_:
.incbin "../data/sounds/creatures/growl7.wav"
.globl data_growl7_wav_end_
data_growl7_wav_end_:

.align 16
.globl data___spike_trap_b_wav_start_
data___spike_trap_b_wav_start_:
.incbin "../data/sounds/impacts/._spike_trap_b.wav"
.globl data___spike_trap_b_wav_end_
data___spike_trap_b_wav_end_:

.align 16
.globl data_257709__vmgraw__grunt_2_wav_start_
data_257709__vmgraw__grunt_2_wav_start_:
.incbin "../data/sounds/impacts/257709__vmgraw__grunt-2.wav"
.globl data_257709__vmgraw__grunt_2_wav_end_
data_257709__vmgraw__grunt_2_wav_end_:

.align 16
.globl data___magic_dust_a_wav_start_
data___magic_dust_a_wav_start_:
.incbin "../data/sounds/impacts/._magic_dust_a.wav"
.globl data___magic_dust_a_wav_end_
data___magic_dust_a_wav_end_:

.align 16
.globl data___magic_dust_b_wav_start_
data___magic_dust_b_wav_start_:
.incbin "../data/sounds/impacts/._magic_dust_b.wav"
.globl data___magic_dust_b_wav_end_
data___magic_dust_b_wav_end_:

.align 16
.globl data_hit_wav_start_
data_hit_wav_start_:
.incbin "../data/sounds/impacts/hit.wav"
.globl data_hit_wav_end_
data_hit_wav_end_:

.align 16
.globl data_554153__danielvj__door_open_wav_start_
data_554153__danielvj__door_open_wav_start_:
.incbin "../data/sounds/impacts/554153__danielvj__door-open.wav"
.globl data_554153__danielvj__door_open_wav_end_
data_554153__danielvj__door_open_wav_end_:

.align 16
.globl data___paper_wav_start_
data___paper_wav_start_:
.incbin "../data/sounds/interface/._paper.wav"
.globl data___paper_wav_end_
data___paper_wav_end_:

.align 16
.globl data_error_wav_start_
data_error_wav_start_:
.incbin "../data/sounds/interface/error.wav"
.globl data_error_wav_end_
data_error_wav_end_:

.align 16
.globl data_1up_b_wav_start_
data_1up_b_wav_start_:
.incbin "../data/sounds/interface/1up_b.wav"
.globl data_1up_b_wav_end_
data_1up_b_wav_end_:

.align 16
.globl data___click_long_wav_start_
data___click_long_wav_start_:
.incbin "../data/sounds/interface/._click_long.wav"
.globl data___click_long_wav_end_
data___click_long_wav_end_:

.align 16
.globl data_click_wav_start_
data_click_wav_start_:
.incbin "../data/sounds/interface/click.wav"
.globl data_click_wav_end_
data_click_wav_end_:

.align 16
.globl data_bay_door_open_wav_start_
data_bay_door_open_wav_start_:
.incbin "../data/sounds/misc/bay_door_open.wav"
.globl data_bay_door_open_wav_end_
data_bay_door_open_wav_end_:

.align 16
.globl data___ping_wav_start_
data___ping_wav_start_:
.incbin "../data/sounds/misc/._ping.wav"
.globl data___ping_wav_end_
data___ping_wav_end_:

.align 16
.globl data_scatter_wav_start_
data_scatter_wav_start_:
.incbin "../data/sounds/misc/scatter.wav"
.globl data_scatter_wav_end_
data_scatter_wav_end_:

.align 16
.globl data_shut_wav_start_
data_shut_wav_start_:
.incbin "../data/sounds/misc/shut.wav"
.globl data_shut_wav_end_
data_shut_wav_end_:

.align 16
.globl data_resurrect_wav_start_
data_resurrect_wav_start_:
.incbin "../data/sounds/misc/resurrect.wav"
.globl data_resurrect_wav_end_
data_resurrect_wav_end_:

.align 16
.globl data_wiggle_a_wav_start_
data_wiggle_a_wav_start_:
.incbin "../data/sounds/misc/wiggle_a.wav"
.globl data_wiggle_a_wav_end_
data_wiggle_a_wav_end_:

.align 16
.globl data_footsteps7_wav_start_
data_footsteps7_wav_start_:
.incbin "../data/sounds/misc/footsteps7.wav"
.globl data_footsteps7_wav_end_
data_footsteps7_wav_end_:

.align 16
.globl data_freeze_wav_start_
data_freeze_wav_start_:
.incbin "../data/sounds/status/freeze.wav"
.globl data_freeze_wav_end_
data_freeze_wav_end_:

