// Ramdisk data for files that due to licensing cannot be exposed

.globl data_solid_tga_start_
data_solid_tga_start_:
.incbin "../data/gfx/solid.tga"
.globl data_solid_tga_end_
data_solid_tga_end_:

.globl data_tiles3_lava_tga_start_
data_tiles3_lava_tga_start_:
.incbin "../data/gfx/tiles3_lava.tga"
.globl data_tiles3_lava_tga_end_
data_tiles3_lava_tga_end_:

.globl data_tiles3_chasm_tga_start_
data_tiles3_chasm_tga_start_:
.incbin "../data/gfx/tiles3_chasm.tga"
.globl data_tiles3_chasm_tga_end_
data_tiles3_chasm_tga_end_:

.globl data_ui_box0_tga_start_
data_ui_box0_tga_start_:
.incbin "../data/gfx/ui_box0.tga"
.globl data_ui_box0_tga_end_
data_ui_box0_tga_end_:

.globl data_tiles3_deep_water_tga_start_
data_tiles3_deep_water_tga_start_:
.incbin "../data/gfx/tiles3_deep_water.tga"
.globl data_tiles3_deep_water_tga_end_
data_tiles3_deep_water_tga_end_:

.globl data_heal_b_wav_start_
data_heal_b_wav_start_:
.incbin "../data/sounds/abilities/heal_b.wav"
.globl data_heal_b_wav_end_
data_heal_b_wav_end_:

.globl data_swing_wav_start_
data_swing_wav_start_:
.incbin "../data/sounds/abilities/swing.wav"
.globl data_swing_wav_end_
data_swing_wav_end_:

.globl data_shoot_b_wav_start_
data_shoot_b_wav_start_:
.incbin "../data/sounds/abilities/shoot_b.wav"
.globl data_shoot_b_wav_end_
data_shoot_b_wav_end_:

.globl data_bird_wav_start_
data_bird_wav_start_:
.incbin "../data/sounds/creatures/bird.wav"
.globl data_bird_wav_end_
data_bird_wav_end_:

.globl data_growl1_wav_start_
data_growl1_wav_start_:
.incbin "../data/sounds/creatures/growl1.wav"
.globl data_growl1_wav_end_
data_growl1_wav_end_:

.globl data_hiss9_wav_start_
data_hiss9_wav_start_:
.incbin "../data/sounds/creatures/hiss9.wav"
.globl data_hiss9_wav_end_
data_hiss9_wav_end_:

.globl data_slime3_wav_start_
data_slime3_wav_start_:
.incbin "../data/sounds/creatures/slime3.wav"
.globl data_slime3_wav_end_
data_slime3_wav_end_:

.globl data_slime6_wav_start_
data_slime6_wav_start_:
.incbin "../data/sounds/creatures/slime6.wav"
.globl data_slime6_wav_end_
data_slime6_wav_end_:

.globl data_impact_a_wav_start_
data_impact_a_wav_start_:
.incbin "../data/sounds/impacts/impact_a.wav"
.globl data_impact_a_wav_end_
data_impact_a_wav_end_:

.globl data_door_hit1_wav_start_
data_door_hit1_wav_start_:
.incbin "../data/sounds/impacts/door_hit1.wav"
.globl data_door_hit1_wav_end_
data_door_hit1_wav_end_:

.globl data_spike_trap_b_wav_start_
data_spike_trap_b_wav_start_:
.incbin "../data/sounds/impacts/spike_trap_b.wav"
.globl data_spike_trap_b_wav_end_
data_spike_trap_b_wav_end_:

.globl data_lose_a_wav_start_
data_lose_a_wav_start_:
.incbin "../data/sounds/interface/lose_a.wav"
.globl data_lose_a_wav_end_
data_lose_a_wav_end_:

.globl data_error_wav_start_
data_error_wav_start_:
.incbin "../data/sounds/interface/error.wav"
.globl data_error_wav_end_
data_error_wav_end_:

.globl data_close_shut_wav_start_
data_close_shut_wav_start_:
.incbin "../data/sounds/misc/close_shut.wav"
.globl data_close_shut_wav_end_
data_close_shut_wav_end_:

.globl data_zong_wav_start_
data_zong_wav_start_:
.incbin "../data/sounds/misc/zong.wav"
.globl data_zong_wav_end_
data_zong_wav_end_:

.globl data_wave_wav_start_
data_wave_wav_start_:
.incbin "../data/sounds/misc/wave.wav"
.globl data_wave_wav_end_
data_wave_wav_end_:

.globl data_shut_wav_start_
data_shut_wav_start_:
.incbin "../data/sounds/misc/shut.wav"
.globl data_shut_wav_end_
data_shut_wav_end_:

.globl data_disease_wav_start_
data_disease_wav_start_:
.incbin "../data/sounds/status/disease.wav"
.globl data_disease_wav_end_
data_disease_wav_end_:

