// Ramdisk data for files that due to licensing cannot be exposed

.globl data_laser_descent_tga_start_
data_laser_descent_tga_start_:
.incbin "../data/gfx/laser_descent.tga"
.globl data_laser_descent_tga_end_
data_laser_descent_tga_end_:

.globl data_tiles1_floors_tga_start_
data_tiles1_floors_tga_start_:
.incbin "../data/gfx/tiles1_floors.tga"
.globl data_tiles1_floors_tga_end_
data_tiles1_floors_tga_end_:

.globl data_tiles2_tga_start_
data_tiles2_tga_start_:
.incbin "../data/gfx/tiles2.tga"
.globl data_tiles2_tga_end_
data_tiles2_tga_end_:

.globl data_title_bg_tga_start_
data_title_bg_tga_start_:
.incbin "../data/gfx/title_bg.tga"
.globl data_title_bg_tga_end_
data_title_bg_tga_end_:

.globl data_attack_tga_start_
data_attack_tga_start_:
.incbin "../data/gfx/attack.tga"
.globl data_attack_tga_end_
data_attack_tga_end_:

.globl data_blood_tga_start_
data_blood_tga_start_:
.incbin "../data/gfx/blood.tga"
.globl data_blood_tga_end_
data_blood_tga_end_:

.globl data_bazooka_wav_start_
data_bazooka_wav_start_:
.incbin "../data/sounds/abilities/bazooka.wav"
.globl data_bazooka_wav_end_
data_bazooka_wav_end_:

.globl data_fire_b_wav_start_
data_fire_b_wav_start_:
.incbin "../data/sounds/abilities/fire_b.wav"
.globl data_fire_b_wav_end_
data_fire_b_wav_end_:

.globl data_woosh_a_wav_start_
data_woosh_a_wav_start_:
.incbin "../data/sounds/abilities/woosh_a.wav"
.globl data_woosh_a_wav_end_
data_woosh_a_wav_end_:

.globl data___attack_a_wav_start_
data___attack_a_wav_start_:
.incbin "../data/sounds/abilities/._attack_a.wav"
.globl data___attack_a_wav_end_
data___attack_a_wav_end_:

.globl data___fire_c_wav_start_
data___fire_c_wav_start_:
.incbin "../data/sounds/abilities/._fire_c.wav"
.globl data___fire_c_wav_end_
data___fire_c_wav_end_:

.globl data___shoot_b_wav_start_
data___shoot_b_wav_start_:
.incbin "../data/sounds/abilities/._shoot_b.wav"
.globl data___shoot_b_wav_end_
data___shoot_b_wav_end_:

.globl data_snake_wav_start_
data_snake_wav_start_:
.incbin "../data/sounds/creatures/snake.wav"
.globl data_snake_wav_end_
data_snake_wav_end_:

.globl data_growl5_wav_start_
data_growl5_wav_start_:
.incbin "../data/sounds/creatures/growl5.wav"
.globl data_growl5_wav_end_
data_growl5_wav_end_:

.globl data___claw_wav_start_
data___claw_wav_start_:
.incbin "../data/sounds/creatures/._claw.wav"
.globl data___claw_wav_end_
data___claw_wav_end_:

.globl data_slime3_wav_start_
data_slime3_wav_start_:
.incbin "../data/sounds/creatures/slime3.wav"
.globl data_slime3_wav_end_
data_slime3_wav_end_:

.globl data_hiss10_wav_start_
data_hiss10_wav_start_:
.incbin "../data/sounds/creatures/hiss10.wav"
.globl data_hiss10_wav_end_
data_hiss10_wav_end_:

.globl data_148975__adam_n__squelch_1_wav_start_
data_148975__adam_n__squelch_1_wav_start_:
.incbin "../data/sounds/creatures/148975__adam_n__squelch_1.wav"
.globl data_148975__adam_n__squelch_1_wav_end_
data_148975__adam_n__squelch_1_wav_end_:

.globl data_434462__dersuperanton__getting_hit_hugh_wav_start_
data_434462__dersuperanton__getting_hit_hugh_wav_start_:
.incbin "../data/sounds/impacts/434462__dersuperanton__getting-hit-hugh.wav"
.globl data_434462__dersuperanton__getting_hit_hugh_wav_end_
data_434462__dersuperanton__getting_hit_hugh_wav_end_:

.globl data_437653__dersuperanton__moan_male_beat_punch_wav_start_
data_437653__dersuperanton__moan_male_beat_punch_wav_start_:
.incbin "../data/sounds/impacts/437653__dersuperanton__moan-male-beat-punch.wav"
.globl data_437653__dersuperanton__moan_male_beat_punch_wav_end_
data_437653__dersuperanton__moan_male_beat_punch_wav_end_:

.globl data_splash6_wav_start_
data_splash6_wav_start_:
.incbin "../data/sounds/impacts/splash6.wav"
.globl data_splash6_wav_end_
data_splash6_wav_end_:

.globl data_268227__xxchr0nosxx__swing_wav_start_
data_268227__xxchr0nosxx__swing_wav_start_:
.incbin "../data/sounds/impacts/268227__xxchr0nosxx__swing.wav"
.globl data_268227__xxchr0nosxx__swing_wav_end_
data_268227__xxchr0nosxx__swing_wav_end_:

.globl data_door_hit2_wav_start_
data_door_hit2_wav_start_:
.incbin "../data/sounds/impacts/door_hit2.wav"
.globl data_door_hit2_wav_end_
data_door_hit2_wav_end_:

.globl data___404109__deathscyp__damage_1_wav_start_
data___404109__deathscyp__damage_1_wav_start_:
.incbin "../data/sounds/impacts/._404109__deathscyp__damage-1.wav"
.globl data___404109__deathscyp__damage_1_wav_end_
data___404109__deathscyp__damage_1_wav_end_:

.globl data_end_turn_wav_start_
data_end_turn_wav_start_:
.incbin "../data/sounds/interface/end_turn.wav"
.globl data_end_turn_wav_end_
data_end_turn_wav_end_:

.globl data_level_up_wav_start_
data_level_up_wav_start_:
.incbin "../data/sounds/interface/level_up.wav"
.globl data_level_up_wav_end_
data_level_up_wav_end_:

.globl data___select_a_wav_start_
data___select_a_wav_start_:
.incbin "../data/sounds/interface/._select_a.wav"
.globl data___select_a_wav_end_
data___select_a_wav_end_:

.globl data___dong_wav_start_
data___dong_wav_start_:
.incbin "../data/sounds/interface/._dong.wav"
.globl data___dong_wav_end_
data___dong_wav_end_:

.globl data___open_wav_start_
data___open_wav_start_:
.incbin "../data/sounds/misc/._open.wav"
.globl data___open_wav_end_
data___open_wav_end_:

.globl data___close_shut_wav_start_
data___close_shut_wav_start_:
.incbin "../data/sounds/misc/._close_shut.wav"
.globl data___close_shut_wav_end_
data___close_shut_wav_end_:

.globl data_footsteps5_wav_start_
data_footsteps5_wav_start_:
.incbin "../data/sounds/misc/footsteps5.wav"
.globl data_footsteps5_wav_end_
data_footsteps5_wav_end_:

.globl data___bay_door_open_wav_start_
data___bay_door_open_wav_start_:
.incbin "../data/sounds/misc/._bay_door_open.wav"
.globl data___bay_door_open_wav_end_
data___bay_door_open_wav_end_:

.globl data_clack_wav_start_
data_clack_wav_start_:
.incbin "../data/sounds/misc/clack.wav"
.globl data_clack_wav_end_
data_clack_wav_end_:

.globl data_transistor_wav_start_
data_transistor_wav_start_:
.incbin "../data/sounds/misc/transistor.wav"
.globl data_transistor_wav_end_
data_transistor_wav_end_:

.globl data___clack_wav_start_
data___clack_wav_start_:
.incbin "../data/sounds/misc/._clack.wav"
.globl data___clack_wav_end_
data___clack_wav_end_:

.globl data___curse_wav_start_
data___curse_wav_start_:
.incbin "../data/sounds/status/._curse.wav"
.globl data___curse_wav_end_
data___curse_wav_end_:

.globl data_confuse_wav_start_
data_confuse_wav_start_:
.incbin "../data/sounds/status/confuse.wav"
.globl data_confuse_wav_end_
data_confuse_wav_end_:

