// Ramdisk data for files that due to licensing cannot be exposed

.align 4
.globl data_weapons_tga_start_
data_weapons_tga_start_:
.incbin "../data/gfx/weapons.tga"
.align 4
.globl data_weapons_tga_end_
data_weapons_tga_end_:

.align 4
.globl data_glow_tga_start_
data_glow_tga_start_:
.incbin "../data/gfx/glow.tga"
.align 4
.globl data_glow_tga_end_
data_glow_tga_end_:

.align 4
.globl data_ui_bag_tga_start_
data_ui_bag_tga_start_:
.incbin "../data/gfx/ui_bag.tga"
.align 4
.globl data_ui_bag_tga_end_
data_ui_bag_tga_end_:

.align 4
.globl data_ui_box1_tga_start_
data_ui_box1_tga_start_:
.incbin "../data/gfx/ui_box1.tga"
.align 4
.globl data_ui_box1_tga_end_
data_ui_box1_tga_end_:

.align 4
.globl data_tiles3_lava_tga_start_
data_tiles3_lava_tga_start_:
.incbin "../data/gfx/tiles3_lava.tga"
.align 4
.globl data_tiles3_lava_tga_end_
data_tiles3_lava_tga_end_:

.align 4
.globl data_explosion_tga_start_
data_explosion_tga_start_:
.incbin "../data/gfx/explosion.tga"
.align 4
.globl data_explosion_tga_end_
data_explosion_tga_end_:

.align 4
.globl data_laser_b_wav_start_
data_laser_b_wav_start_:
.incbin "../data/sounds/abilities/laser_b.wav"
.align 4
.globl data_laser_b_wav_end_
data_laser_b_wav_end_:

.align 4
.globl data_woosh_a_wav_start_
data_woosh_a_wav_start_:
.incbin "../data/sounds/abilities/woosh_a.wav"
.align 4
.globl data_woosh_a_wav_end_
data_woosh_a_wav_end_:

.align 4
.globl data_shotgun_wav_start_
data_shotgun_wav_start_:
.incbin "../data/sounds/abilities/shotgun.wav"
.align 4
.globl data_shotgun_wav_end_
data_shotgun_wav_end_:

.align 4
.globl data_slime4_wav_start_
data_slime4_wav_start_:
.incbin "../data/sounds/creatures/slime4.wav"
.align 4
.globl data_slime4_wav_end_
data_slime4_wav_end_:

.align 4
.globl data_slime2_wav_start_
data_slime2_wav_start_:
.incbin "../data/sounds/creatures/slime2.wav"
.align 4
.globl data_slime2_wav_end_
data_slime2_wav_end_:

.align 4
.globl data_growl4_wav_start_
data_growl4_wav_start_:
.incbin "../data/sounds/creatures/growl4.wav"
.align 4
.globl data_growl4_wav_end_
data_growl4_wav_end_:

.align 4
.globl data_hiss9_wav_start_
data_hiss9_wav_start_:
.incbin "../data/sounds/creatures/hiss9.wav"
.align 4
.globl data_hiss9_wav_end_
data_hiss9_wav_end_:

.align 4
.globl data_slime6_wav_start_
data_slime6_wav_start_:
.incbin "../data/sounds/creatures/slime6.wav"
.align 4
.globl data_slime6_wav_end_
data_slime6_wav_end_:

.align 4
.globl data_257709__vmgraw__grunt_2_wav_start_
data_257709__vmgraw__grunt_2_wav_start_:
.incbin "../data/sounds/impacts/257709__vmgraw__grunt-2.wav"
.align 4
.globl data_257709__vmgraw__grunt_2_wav_end_
data_257709__vmgraw__grunt_2_wav_end_:

.align 4
.globl data_explosion_e_wav_start_
data_explosion_e_wav_start_:
.incbin "../data/sounds/impacts/explosion_e.wav"
.align 4
.globl data_explosion_e_wav_end_
data_explosion_e_wav_end_:

.align 4
.globl data_explosion_b_wav_start_
data_explosion_b_wav_start_:
.incbin "../data/sounds/impacts/explosion_b.wav"
.align 4
.globl data_explosion_b_wav_end_
data_explosion_b_wav_end_:

.align 4
.globl data_explosion_c_wav_start_
data_explosion_c_wav_start_:
.incbin "../data/sounds/impacts/explosion_c.wav"
.align 4
.globl data_explosion_c_wav_end_
data_explosion_c_wav_end_:

.align 4
.globl data_error_wav_start_
data_error_wav_start_:
.incbin "../data/sounds/interface/error.wav"
.align 4
.globl data_error_wav_end_
data_error_wav_end_:

.align 4
.globl data_coin_wav_start_
data_coin_wav_start_:
.incbin "../data/sounds/interface/coin.wav"
.align 4
.globl data_coin_wav_end_
data_coin_wav_end_:

.align 4
.globl data_fall_wav_start_
data_fall_wav_start_:
.incbin "../data/sounds/misc/fall.wav"
.align 4
.globl data_fall_wav_end_
data_fall_wav_end_:

.align 4
.globl data_step_wav_start_
data_step_wav_start_:
.incbin "../data/sounds/misc/step.wav"
.align 4
.globl data_step_wav_end_
data_step_wav_end_:

.align 4
.globl data_chime_wav_start_
data_chime_wav_start_:
.incbin "../data/sounds/misc/chime.wav"
.align 4
.globl data_chime_wav_end_
data_chime_wav_end_:

.align 4
.globl data_mushroom_wav_start_
data_mushroom_wav_start_:
.incbin "../data/sounds/misc/mushroom.wav"
.align 4
.globl data_mushroom_wav_end_
data_mushroom_wav_end_:

.align 4
.globl data_freeze_wav_start_
data_freeze_wav_start_:
.incbin "../data/sounds/status/freeze.wav"
.align 4
.globl data_freeze_wav_end_
data_freeze_wav_end_:

