// Ramdisk data for files that due to licensing cannot be exposed

.globl data_laser_energy_tga_start_
data_laser_energy_tga_start_:
.incbin "../data/gfx/laser_energy.tga"
.globl data_laser_energy_tga_end_
data_laser_energy_tga_end_:

.globl data_title_fg1_tga_start_
data_title_fg1_tga_start_:
.incbin "../data/gfx/title_fg1.tga"
.globl data_title_fg1_tga_end_
data_title_fg1_tga_end_:

.globl data_ui_credits_fg_tga_start_
data_ui_credits_fg_tga_start_:
.incbin "../data/gfx/ui_credits_fg.tga"
.globl data_ui_credits_fg_tga_end_
data_ui_credits_fg_tga_end_:

.globl data_attack_tga_start_
data_attack_tga_start_:
.incbin "../data/gfx/attack.tga"
.globl data_attack_tga_end_
data_attack_tga_end_:

.globl data_ui_box2_tga_start_
data_ui_box2_tga_start_:
.incbin "../data/gfx/ui_box2.tga"
.globl data_ui_box2_tga_end_
data_ui_box2_tga_end_:

.globl data_ui_box4_tga_start_
data_ui_box4_tga_start_:
.incbin "../data/gfx/ui_box4.tga"
.globl data_ui_box4_tga_end_
data_ui_box4_tga_end_:

.globl data_heal_a_wav_start_
data_heal_a_wav_start_:
.incbin "../data/sounds/abilities/heal_a.wav"
.globl data_heal_a_wav_end_
data_heal_a_wav_end_:

.globl data_special_b_wav_start_
data_special_b_wav_start_:
.incbin "../data/sounds/abilities/special_b.wav"
.globl data_special_b_wav_end_
data_special_b_wav_end_:

.globl data_shotgun_wav_start_
data_shotgun_wav_start_:
.incbin "../data/sounds/abilities/shotgun.wav"
.globl data_shotgun_wav_end_
data_shotgun_wav_end_:

.globl data_growl7_wav_start_
data_growl7_wav_start_:
.incbin "../data/sounds/creatures/growl7.wav"
.globl data_growl7_wav_end_
data_growl7_wav_end_:

.globl data_hiss7_wav_start_
data_hiss7_wav_start_:
.incbin "../data/sounds/creatures/hiss7.wav"
.globl data_hiss7_wav_end_
data_hiss7_wav_end_:

.globl data_jelly_wav_start_
data_jelly_wav_start_:
.incbin "../data/sounds/creatures/jelly.wav"
.globl data_jelly_wav_end_
data_jelly_wav_end_:

.globl data_swarm_wav_start_
data_swarm_wav_start_:
.incbin "../data/sounds/creatures/swarm.wav"
.globl data_swarm_wav_end_
data_swarm_wav_end_:

.globl data_59992__qubodup__swosh_sword_swing_wav_start_
data_59992__qubodup__swosh_sword_swing_wav_start_:
.incbin "../data/sounds/impacts/59992__qubodup__swosh-sword-swing.wav"
.globl data_59992__qubodup__swosh_sword_swing_wav_end_
data_59992__qubodup__swosh_sword_swing_wav_end_:

.globl data_sear_wav_start_
data_sear_wav_start_:
.incbin "../data/sounds/impacts/sear.wav"
.globl data_sear_wav_end_
data_sear_wav_end_:

.globl data_268227__xxchr0nosxx__swing_wav_start_
data_268227__xxchr0nosxx__swing_wav_start_:
.incbin "../data/sounds/impacts/268227__xxchr0nosxx__swing.wav"
.globl data_268227__xxchr0nosxx__swing_wav_end_
data_268227__xxchr0nosxx__swing_wav_end_:

.globl data_magic_dust_a_wav_start_
data_magic_dust_a_wav_start_:
.incbin "../data/sounds/impacts/magic_dust_a.wav"
.globl data_magic_dust_a_wav_end_
data_magic_dust_a_wav_end_:

.globl data_gold_wav_start_
data_gold_wav_start_:
.incbin "../data/sounds/interface/gold.wav"
.globl data_gold_wav_end_
data_gold_wav_end_:

.globl data_181002__ueffects__s_key_wav_start_
data_181002__ueffects__s_key_wav_start_:
.incbin "../data/sounds/interface/181002__ueffects__s-key.wav"
.globl data_181002__ueffects__s_key_wav_end_
data_181002__ueffects__s_key_wav_end_:

.globl data_mushroom_wav_start_
data_mushroom_wav_start_:
.incbin "../data/sounds/misc/mushroom.wav"
.globl data_mushroom_wav_end_
data_mushroom_wav_end_:

.globl data_drip_wav_start_
data_drip_wav_start_:
.incbin "../data/sounds/misc/drip.wav"
.globl data_drip_wav_end_
data_drip_wav_end_:

.globl data_footsteps7_wav_start_
data_footsteps7_wav_start_:
.incbin "../data/sounds/misc/footsteps7.wav"
.globl data_footsteps7_wav_end_
data_footsteps7_wav_end_:

.globl data_rubberband_wav_start_
data_rubberband_wav_start_:
.incbin "../data/sounds/misc/rubberband.wav"
.globl data_rubberband_wav_end_
data_rubberband_wav_end_:

.globl data_poison_wav_start_
data_poison_wav_start_:
.incbin "../data/sounds/status/poison.wav"
.globl data_poison_wav_end_
data_poison_wav_end_:

