// Ramdisk data for files that due to licensing cannot be exposed

.globl data_ui_tile_bg_tga_start_
data_ui_tile_bg_tga_start_:
.incbin "../data/gfx/ui_tile_bg.tga"
.globl data_ui_tile_bg_tga_end_
data_ui_tile_bg_tga_end_:

.globl data_title_fg2_tga_start_
data_title_fg2_tga_start_:
.incbin "../data/gfx/title_fg2.tga"
.globl data_title_fg2_tga_end_
data_title_fg2_tga_end_:

.globl data_ui_bag_tga_start_
data_ui_bag_tga_start_:
.incbin "../data/gfx/ui_bag.tga"
.globl data_ui_bag_tga_end_
data_ui_bag_tga_end_:

.globl data_title_bg_tga_start_
data_title_bg_tga_start_:
.incbin "../data/gfx/title_bg.tga"
.globl data_title_bg_tga_end_
data_title_bg_tga_end_:

.globl data_ui_box7_tga_start_
data_ui_box7_tga_start_:
.incbin "../data/gfx/ui_box7.tga"
.globl data_ui_box7_tga_end_
data_ui_box7_tga_end_:

.globl data_disarm_multi_b_wav_start_
data_disarm_multi_b_wav_start_:
.incbin "../data/sounds/abilities/disarm_multi_b.wav"
.globl data_disarm_multi_b_wav_end_
data_disarm_multi_b_wav_end_:

.globl data_bazooka_wav_start_
data_bazooka_wav_start_:
.incbin "../data/sounds/abilities/bazooka.wav"
.globl data_bazooka_wav_end_
data_bazooka_wav_end_:

.globl data_spell_b_wav_start_
data_spell_b_wav_start_:
.incbin "../data/sounds/abilities/spell_b.wav"
.globl data_spell_b_wav_end_
data_spell_b_wav_end_:

.globl data_telepathy_wav_start_
data_telepathy_wav_start_:
.incbin "../data/sounds/abilities/telepathy.wav"
.globl data_telepathy_wav_end_
data_telepathy_wav_end_:

.globl data_growl3_wav_start_
data_growl3_wav_start_:
.incbin "../data/sounds/creatures/growl3.wav"
.globl data_growl3_wav_end_
data_growl3_wav_end_:

.globl data_skeleton_wav_start_
data_skeleton_wav_start_:
.incbin "../data/sounds/creatures/skeleton.wav"
.globl data_skeleton_wav_end_
data_skeleton_wav_end_:

.globl data_snake_wav_start_
data_snake_wav_start_:
.incbin "../data/sounds/creatures/snake.wav"
.globl data_snake_wav_end_
data_snake_wav_end_:

.globl data_slime7_wav_start_
data_slime7_wav_start_:
.incbin "../data/sounds/creatures/slime7.wav"
.globl data_slime7_wav_end_
data_slime7_wav_end_:

.globl data_437653__dersuperanton__moan_male_beat_punch_wav_start_
data_437653__dersuperanton__moan_male_beat_punch_wav_start_:
.incbin "../data/sounds/impacts/437653__dersuperanton__moan-male-beat-punch.wav"
.globl data_437653__dersuperanton__moan_male_beat_punch_wav_end_
data_437653__dersuperanton__moan_male_beat_punch_wav_end_:

.globl data_explosion_c_wav_start_
data_explosion_c_wav_start_:
.incbin "../data/sounds/impacts/explosion_c.wav"
.globl data_explosion_c_wav_end_
data_explosion_c_wav_end_:

.globl data_area_effect_b_wav_start_
data_area_effect_b_wav_start_:
.incbin "../data/sounds/impacts/area_effect_b.wav"
.globl data_area_effect_b_wav_end_
data_area_effect_b_wav_end_:

.globl data_magic_dust_b_wav_start_
data_magic_dust_b_wav_start_:
.incbin "../data/sounds/impacts/magic_dust_b.wav"
.globl data_magic_dust_b_wav_end_
data_magic_dust_b_wav_end_:

.globl data_paper_wav_start_
data_paper_wav_start_:
.incbin "../data/sounds/interface/paper.wav"
.globl data_paper_wav_end_
data_paper_wav_end_:

.globl data_click_wav_start_
data_click_wav_start_:
.incbin "../data/sounds/interface/click.wav"
.globl data_click_wav_end_
data_click_wav_end_:

.globl data_fall_wav_start_
data_fall_wav_start_:
.incbin "../data/sounds/misc/fall.wav"
.globl data_fall_wav_end_
data_fall_wav_end_:

.globl data_whistle_wav_start_
data_whistle_wav_start_:
.incbin "../data/sounds/misc/whistle.wav"
.globl data_whistle_wav_end_
data_whistle_wav_end_:

.globl data_footsteps6_wav_start_
data_footsteps6_wav_start_:
.incbin "../data/sounds/misc/footsteps6.wav"
.globl data_footsteps6_wav_end_
data_footsteps6_wav_end_:

.globl data_twing_wav_start_
data_twing_wav_start_:
.incbin "../data/sounds/misc/twing.wav"
.globl data_twing_wav_end_
data_twing_wav_end_:

.globl data_confuse_wav_start_
data_confuse_wav_start_:
.incbin "../data/sounds/status/confuse.wav"
.globl data_confuse_wav_end_
data_confuse_wav_end_:

