// Ramdisk data for files that due to licensing cannot be exposed

.globl ui_horiz1_tga_start_
ui_horiz1_tga_start_:
.incbin "../data/gfx/ui_horiz1.tga"
.globl ui_horiz1_tga_end_
ui_horiz1_tga_end_:

.globl ui_bag_tga_start_
ui_bag_tga_start_:
.incbin "../data/gfx/ui_bag.tga"
.globl ui_bag_tga_end_
ui_bag_tga_end_:

.globl title_bg_tga_start_
title_bg_tga_start_:
.incbin "../data/gfx/title_bg.tga"
.globl title_bg_tga_end_
title_bg_tga_end_:

.globl ui_box7_tga_start_
ui_box7_tga_start_:
.incbin "../data/gfx/ui_box7.tga"
.globl ui_box7_tga_end_
ui_box7_tga_end_:

