// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_fg4_tga_start_
data_title_fg4_tga_start_:
.incbin "../data/gfx/title_fg4.tga"
.globl data_title_fg4_tga_end_
data_title_fg4_tga_end_:

.globl data_ui_health_bar_tga_start_
data_ui_health_bar_tga_start_:
.incbin "../data/gfx/ui_health_bar.tga"
.globl data_ui_health_bar_tga_end_
data_ui_health_bar_tga_end_:

.globl data_chasm_tga_start_
data_chasm_tga_start_:
.incbin "../data/gfx/chasm.tga"
.globl data_chasm_tga_end_
data_chasm_tga_end_:

.globl data_ui_box3_tga_start_
data_ui_box3_tga_start_:
.incbin "../data/gfx/ui_box3.tga"
.globl data_ui_box3_tga_end_
data_ui_box3_tga_end_:

.globl data_ui_box4_tga_start_
data_ui_box4_tga_start_:
.incbin "../data/gfx/ui_box4.tga"
.globl data_ui_box4_tga_end_
data_ui_box4_tga_end_:

