// Ramdisk data for files that due to licensing cannot be exposed

.globl data_chasm2_tga_start_
data_chasm2_tga_start_:
.incbin "../data/gfx/chasm2.tga"
.globl data_chasm2_tga_end_
data_chasm2_tga_end_:

.globl data_blood_tga_start_
data_blood_tga_start_:
.incbin "../data/gfx/blood.tga"
.globl data_blood_tga_end_
data_blood_tga_end_:

.globl data_tiles3_sewer_water_tga_start_
data_tiles3_sewer_water_tga_start_:
.incbin "../data/gfx/tiles3_sewer_water.tga"
.globl data_tiles3_sewer_water_tga_end_
data_tiles3_sewer_water_tga_end_:

.globl data_tiles2_tga_start_
data_tiles2_tga_start_:
.incbin "../data/gfx/tiles2.tga"
.globl data_tiles2_tga_end_
data_tiles2_tga_end_:

.globl data_jump_a_wav_start_
data_jump_a_wav_start_:
.incbin "../data/sounds/abilities/jump_a.wav"
.globl data_jump_a_wav_end_
data_jump_a_wav_end_:

.globl data_laser_b_wav_start_
data_laser_b_wav_start_:
.incbin "../data/sounds/abilities/laser_b.wav"
.globl data_laser_b_wav_end_
data_laser_b_wav_end_:

.globl data_spell_a_wav_start_
data_spell_a_wav_start_:
.incbin "../data/sounds/abilities/spell_a.wav"
.globl data_spell_a_wav_end_
data_spell_a_wav_end_:

.globl data_lightning_a_wav_start_
data_lightning_a_wav_start_:
.incbin "../data/sounds/abilities/lightning_a.wav"
.globl data_lightning_a_wav_end_
data_lightning_a_wav_end_:

.globl data_jelly_wav_start_
data_jelly_wav_start_:
.incbin "../data/sounds/creatures/jelly.wav"
.globl data_jelly_wav_end_
data_jelly_wav_end_:

.globl data_impact_a_wav_start_
data_impact_a_wav_start_:
.incbin "../data/sounds/impacts/impact_a.wav"
.globl data_impact_a_wav_end_
data_impact_a_wav_end_:

.globl data_pit_trap_damage_wav_start_
data_pit_trap_damage_wav_start_:
.incbin "../data/sounds/impacts/pit_trap_damage.wav"
.globl data_pit_trap_damage_wav_end_
data_pit_trap_damage_wav_end_:

.globl data_bonus_wav_start_
data_bonus_wav_start_:
.incbin "../data/sounds/interface/bonus.wav"
.globl data_bonus_wav_end_
data_bonus_wav_end_:

.globl data_click_wav_start_
data_click_wav_start_:
.incbin "../data/sounds/interface/click.wav"
.globl data_click_wav_end_
data_click_wav_end_:

.globl data_close_shut_wav_start_
data_close_shut_wav_start_:
.incbin "../data/sounds/misc/close_shut.wav"
.globl data_close_shut_wav_end_
data_close_shut_wav_end_:

.globl data_open_wav_start_
data_open_wav_start_:
.incbin "../data/sounds/misc/open.wav"
.globl data_open_wav_end_
data_open_wav_end_:

.globl data_blurb_wav_start_
data_blurb_wav_start_:
.incbin "../data/sounds/misc/blurb.wav"
.globl data_blurb_wav_end_
data_blurb_wav_end_:

.globl data_confuse_wav_start_
data_confuse_wav_start_:
.incbin "../data/sounds/status/confuse.wav"
.globl data_confuse_wav_end_
data_confuse_wav_end_:

