// Ramdisk data for files that due to licensing cannot be exposed

.globl data_solid_tga_start_
data_solid_tga_start_:
.incbin "../data/gfx/solid.tga"
.globl data_solid_tga_end_
data_solid_tga_end_:

.globl data_title_splash_tga_start_
data_title_splash_tga_start_:
.incbin "../data/gfx/title_splash.tga"
.globl data_title_splash_tga_end_
data_title_splash_tga_end_:

.globl data_ui_vert2_tga_start_
data_ui_vert2_tga_start_:
.incbin "../data/gfx/ui_vert2.tga"
.globl data_ui_vert2_tga_end_
data_ui_vert2_tga_end_:

.globl data_tiles3_tga_start_
data_tiles3_tga_start_:
.incbin "../data/gfx/tiles3.tga"
.globl data_tiles3_tga_end_
data_tiles3_tga_end_:

.globl data_ui_credits_bg_tga_start_
data_ui_credits_bg_tga_start_:
.incbin "../data/gfx/ui_credits_bg.tga"
.globl data_ui_credits_bg_tga_end_
data_ui_credits_bg_tga_end_:

