// Ramdisk data for files that due to licensing cannot be exposed

.globl ui_horiz2_tga_start_
ui_horiz2_tga_start_:
.incbin "../data/gfx/ui_horiz2.tga"
.globl ui_horiz2_tga_end_
ui_horiz2_tga_end_:

.globl ui_credits_fg_tga_start_
ui_credits_fg_tga_start_:
.incbin "../data/gfx/ui_credits_fg.tga"
.globl ui_credits_fg_tga_end_
ui_credits_fg_tga_end_:

.globl attack_tga_start_
attack_tga_start_:
.incbin "../data/gfx/attack.tga"
.globl attack_tga_end_
attack_tga_end_:

.globl ui_box3_tga_start_
ui_box3_tga_start_:
.incbin "../data/gfx/ui_box3.tga"
.globl ui_box3_tga_end_
ui_box3_tga_end_:

