// Ramdisk data for files that due to licensing cannot be exposed

.globl data_laser_descent_tga_start_
data_laser_descent_tga_start_:
.incbin "../data/gfx/laser_descent.tga"
.globl data_laser_descent_tga_end_
data_laser_descent_tga_end_:

.globl data_ui_dead_tga_start_
data_ui_dead_tga_start_:
.incbin "../data/gfx/ui_dead.tga"
.globl data_ui_dead_tga_end_
data_ui_dead_tga_end_:

.globl data_light_tga_start_
data_light_tga_start_:
.incbin "../data/gfx/light.tga"
.globl data_light_tga_end_
data_light_tga_end_:

.globl data_ui_box1_tga_start_
data_ui_box1_tga_start_:
.incbin "../data/gfx/ui_box1.tga"
.globl data_ui_box1_tga_end_
data_ui_box1_tga_end_:

.globl data_explosion_tga_start_
data_explosion_tga_start_:
.incbin "../data/gfx/explosion.tga"
.globl data_explosion_tga_end_
data_explosion_tga_end_:

.globl data_laser_a_wav_start_
data_laser_a_wav_start_:
.incbin "../data/sounds/abilities/laser_a.wav"
.globl data_laser_a_wav_end_
data_laser_a_wav_end_:

.globl data_fire_a_wav_start_
data_fire_a_wav_start_:
.incbin "../data/sounds/abilities/fire_a.wav"
.globl data_fire_a_wav_end_
data_fire_a_wav_end_:

.globl data_shoot_a_wav_start_
data_shoot_a_wav_start_:
.incbin "../data/sounds/abilities/shoot_a.wav"
.globl data_shoot_a_wav_end_
data_shoot_a_wav_end_:

.globl data_growl4_wav_start_
data_growl4_wav_start_:
.incbin "../data/sounds/creatures/growl4.wav"
.globl data_growl4_wav_end_
data_growl4_wav_end_:

.globl data_hiss1_wav_start_
data_hiss1_wav_start_:
.incbin "../data/sounds/creatures/hiss1.wav"
.globl data_hiss1_wav_end_
data_hiss1_wav_end_:

.globl data_hiss8_wav_start_
data_hiss8_wav_start_:
.incbin "../data/sounds/creatures/hiss8.wav"
.globl data_hiss8_wav_end_
data_hiss8_wav_end_:

.globl data_slime1_wav_start_
data_slime1_wav_start_:
.incbin "../data/sounds/creatures/slime1.wav"
.globl data_slime1_wav_end_
data_slime1_wav_end_:

.globl data_23733__tim_kahn__squeakyrat_wav_start_
data_23733__tim_kahn__squeakyrat_wav_start_:
.incbin "../data/sounds/creatures/23733__tim-kahn__squeakyrat.wav"
.globl data_23733__tim_kahn__squeakyrat_wav_end_
data_23733__tim_kahn__squeakyrat_wav_end_:

.globl data_507466__danjocross__clean_fast_swoosh_wav_start_
data_507466__danjocross__clean_fast_swoosh_wav_start_:
.incbin "../data/sounds/impacts/507466__danjocross__clean-fast-swoosh.wav"
.globl data_507466__danjocross__clean_fast_swoosh_wav_end_
data_507466__danjocross__clean_fast_swoosh_wav_end_:

.globl data_magic_crumble_wav_start_
data_magic_crumble_wav_start_:
.incbin "../data/sounds/impacts/magic_crumble.wav"
.globl data_magic_crumble_wav_end_
data_magic_crumble_wav_end_:

.globl data_magic_dust_b_wav_start_
data_magic_dust_b_wav_start_:
.incbin "../data/sounds/impacts/magic_dust_b.wav"
.globl data_magic_dust_b_wav_end_
data_magic_dust_b_wav_end_:

.globl data_lose_b_wav_start_
data_lose_b_wav_start_:
.incbin "../data/sounds/interface/lose_b.wav"
.globl data_lose_b_wav_end_
data_lose_b_wav_end_:

.globl data_score_wav_start_
data_score_wav_start_:
.incbin "../data/sounds/interface/score.wav"
.globl data_score_wav_end_
data_score_wav_end_:

.globl data_swerve_wav_start_
data_swerve_wav_start_:
.incbin "../data/sounds/misc/swerve.wav"
.globl data_swerve_wav_end_
data_swerve_wav_end_:

.globl data_open_wav_start_
data_open_wav_start_:
.incbin "../data/sounds/misc/open.wav"
.globl data_open_wav_end_
data_open_wav_end_:

.globl data_wiggle_b_wav_start_
data_wiggle_b_wav_start_:
.incbin "../data/sounds/misc/wiggle_b.wav"
.globl data_wiggle_b_wav_end_
data_wiggle_b_wav_end_:

.globl data_footsteps1_wav_start_
data_footsteps1_wav_start_:
.incbin "../data/sounds/misc/footsteps1.wav"
.globl data_footsteps1_wav_end_
data_footsteps1_wav_end_:

.globl data_burn_wav_start_
data_burn_wav_start_:
.incbin "../data/sounds/status/burn.wav"
.globl data_burn_wav_end_
data_burn_wav_end_:

