// Ramdisk data for files that due to licensing cannot be exposed

.globl data_title_small_tga_start_
data_title_small_tga_start_:
.incbin "../data/gfx/title_small.tga"
.globl data_title_small_tga_end_
data_title_small_tga_end_:

.globl data_laser_lightning_tga_start_
data_laser_lightning_tga_start_:
.incbin "../data/gfx/laser_lightning.tga"
.globl data_laser_lightning_tga_end_
data_laser_lightning_tga_end_:

.globl data_laser_green_tga_start_
data_laser_green_tga_start_:
.incbin "../data/gfx/laser_green.tga"
.globl data_laser_green_tga_end_
data_laser_green_tga_end_:

.globl data_chasm_tga_start_
data_chasm_tga_start_:
.incbin "../data/gfx/chasm.tga"
.globl data_chasm_tga_end_
data_chasm_tga_end_:

.globl data_ui_box3_tga_start_
data_ui_box3_tga_start_:
.incbin "../data/gfx/ui_box3.tga"
.globl data_ui_box3_tga_end_
data_ui_box3_tga_end_:

.globl data_ui_credits_bg_tga_start_
data_ui_credits_bg_tga_start_:
.incbin "../data/gfx/ui_credits_bg.tga"
.globl data_ui_credits_bg_tga_end_
data_ui_credits_bg_tga_end_:

.globl data_disarm_multi_a_wav_start_
data_disarm_multi_a_wav_start_:
.incbin "../data/sounds/abilities/disarm_multi_a.wav"
.globl data_disarm_multi_a_wav_end_
data_disarm_multi_a_wav_end_:

.globl data_fire_c_wav_start_
data_fire_c_wav_start_:
.incbin "../data/sounds/abilities/fire_c.wav"
.globl data_fire_c_wav_end_
data_fire_c_wav_end_:

.globl data_attack_b_wav_start_
data_attack_b_wav_start_:
.incbin "../data/sounds/abilities/attack_b.wav"
.globl data_attack_b_wav_end_
data_attack_b_wav_end_:

.globl data_slime8_wav_start_
data_slime8_wav_start_:
.incbin "../data/sounds/creatures/slime8.wav"
.globl data_slime8_wav_end_
data_slime8_wav_end_:

.globl data_hiss6_wav_start_
data_hiss6_wav_start_:
.incbin "../data/sounds/creatures/hiss6.wav"
.globl data_hiss6_wav_end_
data_hiss6_wav_end_:

.globl data_bones2_wav_start_
data_bones2_wav_start_:
.incbin "../data/sounds/creatures/bones2.wav"
.globl data_bones2_wav_end_
data_bones2_wav_end_:

.globl data_mouse_wav_start_
data_mouse_wav_start_:
.incbin "../data/sounds/creatures/mouse.wav"
.globl data_mouse_wav_end_
data_mouse_wav_end_:

.globl data_frog_wav_start_
data_frog_wav_start_:
.incbin "../data/sounds/creatures/frog.wav"
.globl data_frog_wav_end_
data_frog_wav_end_:

.globl data_257709__vmgraw__grunt_2_wav_start_
data_257709__vmgraw__grunt_2_wav_start_:
.incbin "../data/sounds/impacts/257709__vmgraw__grunt-2.wav"
.globl data_257709__vmgraw__grunt_2_wav_end_
data_257709__vmgraw__grunt_2_wav_end_:

.globl data_explosion_e_wav_start_
data_explosion_e_wav_start_:
.incbin "../data/sounds/impacts/explosion_e.wav"
.globl data_explosion_e_wav_end_
data_explosion_e_wav_end_:

.globl data_hit_wav_start_
data_hit_wav_start_:
.incbin "../data/sounds/impacts/hit.wav"
.globl data_hit_wav_end_
data_hit_wav_end_:

.globl data_select_b_wav_start_
data_select_b_wav_start_:
.incbin "../data/sounds/interface/select_b.wav"
.globl data_select_b_wav_end_
data_select_b_wav_end_:

.globl data_1up_a_wav_start_
data_1up_a_wav_start_:
.incbin "../data/sounds/interface/1up_a.wav"
.globl data_1up_a_wav_end_
data_1up_a_wav_end_:

.globl data_level_up_wav_start_
data_level_up_wav_start_:
.incbin "../data/sounds/interface/level_up.wav"
.globl data_level_up_wav_end_
data_level_up_wav_end_:

.globl data_rebound_wav_start_
data_rebound_wav_start_:
.incbin "../data/sounds/misc/rebound.wav"
.globl data_rebound_wav_end_
data_rebound_wav_end_:

.globl data_unlock_wav_start_
data_unlock_wav_start_:
.incbin "../data/sounds/misc/unlock.wav"
.globl data_unlock_wav_end_
data_unlock_wav_end_:

.globl data_footsteps5_wav_start_
data_footsteps5_wav_start_:
.incbin "../data/sounds/misc/footsteps5.wav"
.globl data_footsteps5_wav_end_
data_footsteps5_wav_end_:

.globl data_ping_wav_start_
data_ping_wav_start_:
.incbin "../data/sounds/misc/ping.wav"
.globl data_ping_wav_end_
data_ping_wav_end_:

