// Ramdisk data for files that due to licensing cannot be exposed

.align 16
.globl data_tiles3_water_tga_start_
data_tiles3_water_tga_start_:
.incbin "../data/gfx/tiles3_water.tga"
.globl data_tiles3_water_tga_end_
data_tiles3_water_tga_end_:

.align 16
.globl data_ui_box0_tga_start_
data_ui_box0_tga_start_:
.incbin "../data/gfx/ui_box0.tga"
.globl data_ui_box0_tga_end_
data_ui_box0_tga_end_:

.align 16
.globl data_solid_tga_start_
data_solid_tga_start_:
.incbin "../data/gfx/solid.tga"
.globl data_solid_tga_end_
data_solid_tga_end_:

.align 16
.globl data_ui_dead_tga_start_
data_ui_dead_tga_start_:
.incbin "../data/gfx/ui_dead.tga"
.globl data_ui_dead_tga_end_
data_ui_dead_tga_end_:

.align 16
.globl data_ui_box7_tga_start_
data_ui_box7_tga_start_:
.incbin "../data/gfx/ui_box7.tga"
.globl data_ui_box7_tga_end_
data_ui_box7_tga_end_:

.align 16
.globl data___shoot_a_wav_start_
data___shoot_a_wav_start_:
.incbin "../data/sounds/abilities/._shoot_a.wav"
.globl data___shoot_a_wav_end_
data___shoot_a_wav_end_:

.align 16
.globl data___spell_a_wav_start_
data___spell_a_wav_start_:
.incbin "../data/sounds/abilities/._spell_a.wav"
.globl data___spell_a_wav_end_
data___spell_a_wav_end_:

.align 16
.globl data_special_b_wav_start_
data_special_b_wav_start_:
.incbin "../data/sounds/abilities/special_b.wav"
.globl data_special_b_wav_end_
data_special_b_wav_end_:

.align 16
.globl data___woosh_a_wav_start_
data___woosh_a_wav_start_:
.incbin "../data/sounds/abilities/._woosh_a.wav"
.globl data___woosh_a_wav_end_
data___woosh_a_wav_end_:

.align 16
.globl data___fire_b_wav_start_
data___fire_b_wav_start_:
.incbin "../data/sounds/abilities/._fire_b.wav"
.globl data___fire_b_wav_end_
data___fire_b_wav_end_:

.align 16
.globl data___special_a_wav_start_
data___special_a_wav_start_:
.incbin "../data/sounds/abilities/._special_a.wav"
.globl data___special_a_wav_end_
data___special_a_wav_end_:

.align 16
.globl data_summon_wav_start_
data_summon_wav_start_:
.incbin "../data/sounds/abilities/summon.wav"
.globl data_summon_wav_end_
data_summon_wav_end_:

.align 16
.globl data___mouse_wav_start_
data___mouse_wav_start_:
.incbin "../data/sounds/creatures/._mouse.wav"
.globl data___mouse_wav_end_
data___mouse_wav_end_:

.align 16
.globl data_slime2_wav_start_
data_slime2_wav_start_:
.incbin "../data/sounds/creatures/slime2.wav"
.globl data_slime2_wav_end_
data_slime2_wav_end_:

.align 16
.globl data_76962__michel88__deaths_wav_start_
data_76962__michel88__deaths_wav_start_:
.incbin "../data/sounds/creatures/76962__michel88__deaths.wav"
.globl data_76962__michel88__deaths_wav_end_
data_76962__michel88__deaths_wav_end_:

.align 16
.globl data_23733__tim_kahn__squeakyrat_wav_start_
data_23733__tim_kahn__squeakyrat_wav_start_:
.incbin "../data/sounds/creatures/23733__tim-kahn__squeakyrat.wav"
.globl data_23733__tim_kahn__squeakyrat_wav_end_
data_23733__tim_kahn__squeakyrat_wav_end_:

.align 16
.globl data_frog_wav_start_
data_frog_wav_start_:
.incbin "../data/sounds/creatures/frog.wav"
.globl data_frog_wav_end_
data_frog_wav_end_:

.align 16
.globl data_slime6_wav_start_
data_slime6_wav_start_:
.incbin "../data/sounds/creatures/slime6.wav"
.globl data_slime6_wav_end_
data_slime6_wav_end_:

.align 16
.globl data___hit_wav_start_
data___hit_wav_start_:
.incbin "../data/sounds/impacts/._hit.wav"
.globl data___hit_wav_end_
data___hit_wav_end_:

.align 16
.globl data___434462__dersuperanton__getting_hit_hugh_wav_start_
data___434462__dersuperanton__getting_hit_hugh_wav_start_:
.incbin "../data/sounds/impacts/._434462__dersuperanton__getting-hit-hugh.wav"
.globl data___434462__dersuperanton__getting_hit_hugh_wav_end_
data___434462__dersuperanton__getting_hit_hugh_wav_end_:

.align 16
.globl data_explosion_a_wav_start_
data_explosion_a_wav_start_:
.incbin "../data/sounds/impacts/explosion_a.wav"
.globl data_explosion_a_wav_end_
data_explosion_a_wav_end_:

.align 16
.globl data_59992__qubodup__swosh_sword_swing_wav_start_
data_59992__qubodup__swosh_sword_swing_wav_start_:
.incbin "../data/sounds/impacts/59992__qubodup__swosh-sword-swing.wav"
.globl data_59992__qubodup__swosh_sword_swing_wav_end_
data_59992__qubodup__swosh_sword_swing_wav_end_:

.align 16
.globl data___sear_wav_start_
data___sear_wav_start_:
.incbin "../data/sounds/impacts/._sear.wav"
.globl data___sear_wav_end_
data___sear_wav_end_:

.align 16
.globl data_explosion_d_wav_start_
data_explosion_d_wav_start_:
.incbin "../data/sounds/impacts/explosion_d.wav"
.globl data_explosion_d_wav_end_
data_explosion_d_wav_end_:

.align 16
.globl data___ding_wav_start_
data___ding_wav_start_:
.incbin "../data/sounds/interface/._ding.wav"
.globl data___ding_wav_end_
data___ding_wav_end_:

.align 16
.globl data___score_wav_start_
data___score_wav_start_:
.incbin "../data/sounds/interface/._score.wav"
.globl data___score_wav_end_
data___score_wav_end_:

.align 16
.globl data___click_wav_start_
data___click_wav_start_:
.incbin "../data/sounds/interface/._click.wav"
.globl data___click_wav_end_
data___click_wav_end_:

.align 16
.globl data_gold_wav_start_
data_gold_wav_start_:
.incbin "../data/sounds/interface/gold.wav"
.globl data_gold_wav_end_
data_gold_wav_end_:

.align 16
.globl data___rebound_wav_start_
data___rebound_wav_start_:
.incbin "../data/sounds/misc/._rebound.wav"
.globl data___rebound_wav_end_
data___rebound_wav_end_:

.align 16
.globl data_swerve_wav_start_
data_swerve_wav_start_:
.incbin "../data/sounds/misc/swerve.wav"
.globl data_swerve_wav_end_
data_swerve_wav_end_:

.align 16
.globl data_footsteps2_wav_start_
data_footsteps2_wav_start_:
.incbin "../data/sounds/misc/footsteps2.wav"
.globl data_footsteps2_wav_end_
data_footsteps2_wav_end_:

.align 16
.globl data_ping_wav_start_
data_ping_wav_start_:
.incbin "../data/sounds/misc/ping.wav"
.globl data_ping_wav_end_
data_ping_wav_end_:

.align 16
.globl data___chime_wav_start_
data___chime_wav_start_:
.incbin "../data/sounds/misc/._chime.wav"
.globl data___chime_wav_end_
data___chime_wav_end_:

.align 16
.globl data_blurb_wav_start_
data_blurb_wav_start_:
.incbin "../data/sounds/misc/blurb.wav"
.globl data_blurb_wav_end_
data_blurb_wav_end_:

.align 16
.globl data___mushroom_wav_start_
data___mushroom_wav_start_:
.incbin "../data/sounds/misc/._mushroom.wav"
.globl data___mushroom_wav_end_
data___mushroom_wav_end_:

.align 16
.globl data_charm_wav_start_
data_charm_wav_start_:
.incbin "../data/sounds/status/charm.wav"
.globl data_charm_wav_end_
data_charm_wav_end_:

.align 16
.globl data_burn_wav_start_
data_burn_wav_start_:
.incbin "../data/sounds/status/burn.wav"
.globl data_burn_wav_end_
data_burn_wav_end_:

