name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential g++ libegl1 libfishsound1-dev libflac-dev libfluidsynth-dev libfreetype6-dev libgl1 libglvnd0 libglx0 libmikmod-dev liboggz2-dev libsdl2-2.0-0 libsdl2-dev libsdl2-mixer-2.0-0 libsdl2-mixer-dev libsmpeg-dev libx11-6 libxext6 python3 python3-dev
        version: 1.0
    - name: configure
      run: ./RUNME

