name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git make mingw-w64-ucrt-x86_64-gcc \
              mingw-w64-ucrt-x86_64-SDL2 \
              mingw-w64-ucrt-x86_64-SDL2_mixer
							mingw-w64-ucrt-x86_64-clang \
							mingw-w64-ucrt-x86_64-clang-tools-extra
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./RUNME
