name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git make mingw-w64-ucrt-x86_64-gcc
          install: mingw-w64-ucrt-x86_64-SDL
          install: mingw-w64-ucrt-x86_64-SDL2
          install: mingw-w64-ucrt-x86_64-SDL2_gfx
          install: mingw-w64-ucrt-x86_64-SDL2_image
          install: mingw-w64-ucrt-x86_64-SDL2_mixer
          install: mingw-w64-ucrt-x86_64-SDL2_net
          install: mingw-w64-ucrt-x86_64-SDL2_ttf
          install: mingw-w64-ucrt-x86_64-binutils
          install: mingw-w64-ucrt-x86_64-bzip2
          install: mingw-w64-ucrt-x86_64-clang
          install: mingw-w64-ucrt-x86_64-clang-tools-extra
          install: mingw-w64-ucrt-x86_64-crt-git
          install: mingw-w64-ucrt-x86_64-expat
          install: mingw-w64-ucrt-x86_64-flac
          install: mingw-w64-ucrt-x86_64-fluidsynth
          install: mingw-w64-ucrt-x86_64-gcc
          install: mingw-w64-ucrt-x86_64-gcc-libs
          install: mingw-w64-ucrt-x86_64-gdb
          install: mingw-w64-ucrt-x86_64-gdbm
          install: mingw-w64-ucrt-x86_64-gettext
          install: mingw-w64-ucrt-x86_64-giflib
          install: mingw-w64-ucrt-x86_64-glib2
          install: mingw-w64-ucrt-x86_64-gmp
          install: mingw-w64-ucrt-x86_64-headers-git
          install: mingw-w64-ucrt-x86_64-isl
          install: mingw-w64-ucrt-x86_64-libffi
          install: mingw-w64-ucrt-x86_64-libiconv
          install: mingw-w64-ucrt-x86_64-libjpeg-turbo
          install: mingw-w64-ucrt-x86_64-libmad
          install: mingw-w64-ucrt-x86_64-libmodplug
          install: mingw-w64-ucrt-x86_64-libogg
          install: mingw-w64-ucrt-x86_64-libpng
          install: mingw-w64-ucrt-x86_64-libsndfile
          install: mingw-w64-ucrt-x86_64-libsystre
          install: mingw-w64-ucrt-x86_64-libtiff
          install: mingw-w64-ucrt-x86_64-libtre-git
          install: mingw-w64-ucrt-x86_64-libvorbis
          install: mingw-w64-ucrt-x86_64-libwebp
          install: mingw-w64-ucrt-x86_64-libwinpthread-git
          install: mingw-w64-ucrt-x86_64-mpc
          install: mingw-w64-ucrt-x86_64-mpfr
          install: mingw-w64-ucrt-x86_64-ncurses
          install: mingw-w64-ucrt-x86_64-openssl
          install: mingw-w64-ucrt-x86_64-portaudio
          install: mingw-w64-ucrt-x86_64-python3
          install: mingw-w64-ucrt-x86_64-python3-pip
          install: mingw-w64-ucrt-x86_64-python3-py
          install: mingw-w64-ucrt-x86_64-readline
          install: mingw-w64-ucrt-x86_64-smpeg2
          install: mingw-w64-ucrt-x86_64-speex
          install: mingw-w64-ucrt-x86_64-speexdsp
          install: mingw-w64-ucrt-x86_64-termcap
          install: mingw-w64-ucrt-x86_64-windows-default-manifest
          install: mingw-w64-ucrt-x86_64-winpthreads-git
          install: mingw-w64-ucrt-x86_64-xz
          install: mingw-w64-ucrt-x86_64-zl
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./RUNME
